### ISSUE TITLE
Season matching with custom names

### ISSUE THREAD

**Issue by Brian-Graham** [ZeroQI/Hama.bundle#11]
I label my shows with season titles or series titles, and this seems to upset the scanner and it throws it all into Season 1.

Some examples:
Dragon Ball\Z
Dragon Ball\GT
Bleach\Season 01 (The Substitute)
Bleach\Season 02 (The Entry)
Bleach\Season 14 - Sub
Bleach\Season 15 (Sub)
Bleach\Season 16 (Subbed)
Zero No Tsukaima\Season 1 (The Familiar of Zero)
Zero No Tsukaima\Season 2 (Futatsuki no Kishi)
Zero No Tsukaima\Season 3 (Princess no Rondo)
Zero No Tsukaima\Season 4 (The Familiar of Zero F)

The Dragon Ball series are thrown into one folder just for organizational purposes but are two different series. One would assume the folder includes the parent in its folder name if it does not match a season.

As you can see with Bleach, the season is labelled properly but has additional information just for the readier which doesn't need to be checked. Whether I have the title of the season/series, or if they are subbed and not dubbed.

As you can see with Zero, in shows that have different seasons, but their series titles are different I had originally stored them in the original name but with their real name beside Season #.

Could support for this be added? I understand that with just Plex, it's not exactly required but the ability to label the folders this way is good for reading purposes (especially shows like Zero).

**Comment by ZeroQI** [comment]
Are you using my scanner?
Dragon Ball/Dragon Ball Z. Can't group series with different names otherwise so you need to have the last folder labelled properly.
Bleach and zero: you are using seasons so thetvdb.com data should be used which the agent already support if there is a more than one season folder. What actually happens? Please include the scanner logs that only my scanner generates. You might have to enter a direct path in the scanner source.  In case of conflict between the folder and the filename, the filename is used.

**Comment by Brian-Graham** [comment]
Here is an example when it tries to match Zero (and fails): https://i.netcoding.net/6840140f.png and here is a picture within the season, where it has matched the 4 seasons as overlapping sources: https://i.netcoding.net/c4d719b5.png

Here is a paste of the log using HamaTV where it fails to locate Zero: https://paste.netcoding.net/kekocubu.pl

**Comment by ZeroQI** [comment]
The scanner decides the season the episode is in, not the agent. I do include a scanner in my release  [https://forums.plex.tv/index.php/topic/77636-release-http-anidb-metadata-agent-hama/page-13]

The scanner gets the right episode number from the file, and knows there is no show name in front but doesn't associate the season number, so it puts all in the same serie with default season (1)...
(on my synology box the scanner logs are in homes/plex/custom. It might require to edit the agent source. My scanner is the only one gererating its own log)

You use seasons hence tvdb mode of my agent/scanner. I changed the code in the Absolute series scanner (used in non-absolute mode for the record, but it just manage all and better :p) and it now works for what you want it to do... 

Replace season_re_match table in  with that one:

season_re_match               = [                                                                        ### Season folder ### 
  '.*?(SEASON|Season|season)[ -_]?(?P<season>0?[0-9]+).*',                                               # season
  '.*?(SAISON|Saison|saison)[ -_]?(?P<season>[0-9]+).*',                                                 # saison
  '(?P<season>[0-9]{1,2})a? Stagione+.*'                                                                 # Xa Stagiona
]

To fix it i replaced "$" meaning end of string by ".*". Thanks for the feedback, it makes it much better

**Comment by ZeroQI** [comment]
tried latest release on plex forums ? It should handle season folders ok. if not, give me the scanner logs and the exact path so I can reproduce
naming must match the anidb title (in any language or one of the synonyms...) putting two titles side by side will make it pass below the automated recognition rate (70 or 80% similarity). double the folder name length and it will only match 50%... it does check all synonyms and title in all languages though...
