### ISSUE TITLE
Episode log not catching all missing episodes

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#113]
This is related to #112, but I wanted to keep them as separate tickets.

I've done several full refreshes in the past few days, intentionally not adding Fuuka S01E03 and now 04.  Neither show up in my missing log.

This leads me to believe there might be something that isn't catching everything.  When I added Fuuka, I had to manually match it.  If we manually match (whether to TVDB or Hama) does that prevent it from getting caught in the logs?

In theory, when I do a full refresh the scanner should scan every folder, even if there are no changes, right?  Then new metadata should come down and Hama checks every show?

**Comment by ZeroQI** [comment]
scanner tends to not run for the folder if nothing changed, which makes scanner dev really annoying.
Once we have force ids there is too many use cases and i loose track to be fair

Is hte in progress code impacted ?
https://github.com/ZeroQI/Hama.bundle/releases/tag/Beta

**Comment by sven-7** [comment]
I was hoping since this was a folder I was adding things to, the scanner would call.  Does the scanner not call on old folders when a force refresh is applied?  It'd be nice to be able to scan everything without having to add/remove/change names for all of them.

Yes, the new code is still affected.  If I remove an episode, it does not get placed into the missing log.

**Comment by ZeroQI** [comment]
yes, was not programmed that way but new beta code seem to have solved that.
Reopen if not
