### ISSUE TITLE
NO custom poster for Seasons

### ISSUE THREAD

**Issue by bycominixo** [ZeroQI/Hama.bundle#117]
PMS v1.3.4.3285 running on CentOS7
Up to date ASS & HAMA

I've used this agent / ASS scanner for a year, and the Season posters were working; a few days ago my RAID failed (KMS pls) and i had no backup of my VMs, so had to setup PMS again.
All is working great, metadata, poster, bg... but now with the up to date versions of ASS & HAMA the Season poster doesn't work anymore. Not sure if you removed the feature, or there is something wrong with my setup.

Already checked all folders / permissions. I will send logs asap.

And btw, i checked the TVDB/seasons folder and i found there the posters. So HAMA it's downloading them but they dont appear as season posters.

**Comment by sven-7** [comment]
This issue was noted in #98. This was a Plex issue that was patched in the latest 1.4 release.

**Comment by ZeroQI** [comment]
already a ticket for this issue: https://github.com/ZeroQI/Hama.bundle/issues/98
closing that one
