### ISSUE TITLE
Matching Issue

### ISSUE THREAD

**Issue by SilverSix311** [ZeroQI/Hama.bundle#119]
Why does my Plex keep matching these shows like this:
http://i.imgur.com/Fdlk5aO.png

**Comment by SilverSix311** [comment]
Nevermind, looks like it resolved itself.

**Comment by SilverSix311** [comment]
Looks like its happening again. Any ideas what generally causes this?

**Comment by ZeroQI** [comment]
It look like the search works but the update crash
Please follow the read-me troubleshooting steps. i need logs to solve it

**Comment by ZeroQI** [comment]
No update in 22 days, closing
It shows search worked but crashed during update, hama log mandatory to solve...
