### ISSUE TITLE
Ending/Openings with non-numbers.

### ISSUE THREAD

**Issue by SwissKid** [ZeroQI/Hama.bundle#12]
So for Tokyo Ghoul (at least) they called them "Ending 1a" and such, which breaks the process.

I fixed it (sorta, just to throw out the info) by modifying the treatment of Endings/Openings as follows:
            if epNumType=="3":
              testdig = ep_title[7:]
              if testdig.isdigit():
                if ep_title.startswith("Ending"):  epNumVal = str( 150 + int(ep_title[7:]) ) #int(epNum.text[1:] gives 103 for ed2 with 2 op before that
                else:                              op_nb   +=1
              else:
                epNumVal = str(150+10) #Will this make it error out?
              Log.Debug("AniDB specials title - Season: '%s', epNum.text: '%s', epNumVal: '%s', ep_title: '%s'" % (season, epNum.text, epNumVal, ep_title) )

**Comment by SwissKid** [comment]
And FYI - this will break processing for the whole show if it's not fixed, when you try to throw stuff like "1a" to an int.

**Comment by ZeroQI** [comment]
Thanks a  lot for the information. i actually just redid this morning the scanner episode translation part for opening and ending with "OP1a" type of names, good timing :D
I am finishing up the scanner to make sure it is stable enough for a release and will update back the agent.

**Comment by ZeroQI** [comment]
scanner handles this properly.
