### ISSUE TITLE
Question on AniDB/TVDB mode

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#120]
Question - in TVDB 2/3 (made 4 too), does HAMA grab metadata from AniDB as well?

For instance, with My Hero Academia, does it take the TVDB id and grab metadata from both related AniDB series?

 ```
 <anime anidbid="11739" tvdbid="305074" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Boku no Hero Academia</name>
  </anime>
```

```
  <anime anidbid="12233" tvdbid="305074" defaulttvdbseason="2" episodeoffset="" tmdbid="" imdbid="">
    <name>Boku no Hero Academia (2017)</name>
  </anime>
```

**Comment by ZeroQI** [comment]
Yes from the tvdbid it can find one anidbid, AnimeLists.py page 82
`if AniDB_id and AniDBid == AniDB_id or TVDB_id and TVDB_id == TVDBid and (not mappingList['defaulttvdbseason'] or mappingList['defaulttvdbseason'] in ('1', 'a')):`

related series are used for collections t supplement the movie collection db

**Comment by sven-7** [comment]
Ah, great. Thanks!
