### ISSUE TITLE
OMDB now requires a personal API Key

### ISSUE THREAD

**Issue by btadeus** [ZeroQI/Hama.bundle#123]
Would you mind adding a text field in the settings that will apply the key to the API request URL? Should be pretty easy. I did the same with the OMDB agent already.

**Comment by ZeroQI** [comment]
Sorry for long delay.
https://github.com/ZeroQI/Hama.bundle/releases/download/Beta/Hama.bundle.2017-08-18.04h24.zip
Code currently only loads OMDb if flagged hentai in ScudLee's XML mapping files, using imdbid to download metadata...
Please test

**Comment by ZeroQI** [comment]
Got updated on beta branch: https://github.com/ZeroQI/Hama.bundle/tree/Beta-Agent

**Comment by ZeroQI** [comment]
Please reopen if api key does not work
