### ISSUE TITLE
Absolute Series scanner fails to pick up folder

### ISSUE THREAD

**Issue by Baine** [ZeroQI/Hama.bundle#125]
I've got a show with a very short name:
MM! (https://anidb.net/perl-bin/animedb.pl?show=anime&aid=7622)

the folder is named "MM" files are named like "MM! - 01 - My Free-Fall First Love.mkv"

this folder does not show up in plex after scanning.

(renaming the folder to MM! made it show up in plex after a scan though, so that's not really an issue, more like an enhancement^^)

**Comment by ZeroQI** [comment]
Why created a bug report on the agent for a scanner issue?

2017-06-30 00:21:25,420 (-bfee4c0) :  CRITICAL (caching:271) - Error trimming cache (most recent call last):
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-313f93718/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/caching.py", line 264, in trim
    del self._info[key]
KeyError: 'http://image.tmdb.org/t/p/original/lCZ6wZzyzMb8dmI4lmji92Unv2Z.jpg'

wish i knew how to remove the above error...

gets loaded first time for me: MM/MM! - 01 - My Free-Fall First Love.mkv

**Comment by Baine** [comment]
sorry for posting it in the wrong place, assumed that this would be the more logical place to post it since it's part of this pack

will retry once i get around to it, since I lost data due to a hdd crashand have to redo a lot :/

**Comment by ZeroQI** [comment]
should work, need logs...
Works for me.
Closing but please reopen if you experience again
