### ISSUE TITLE
Error downloading two mathes: Drifters

### ISSUE THREAD

**Issue by koalix** [ZeroQI/Hama.bundle#128]
I am rebuilding my server from scratch and while I am creating my animes libraries I found an issue with two specific titles while using HAMA (already imported a lot of others, no other occurrences).

- Drifters (11164)
- Drifters: Special Edition (12038)

I paste the log excerpt (com.plexapp.agents.hama.log) containing the error. Don't know if it is a bug or not.
[https://pastebin.com/SrnGZGWS](https://pastebin.com/SrnGZGWS)

It changes the name of the first one to Drifters [anidb-11164] and the second one to Drifters: Special Edition [anidb-12038] and stops.

Thanks in Advance.

**Comment by ZeroQI** [comment]
the xml is corrupted, can't see if anidb or tvdb but have seen it twice with thetvdb already
https://github.com/ZeroQI/Hama.bundle/releases/download/Beta/Hama.bundle.2017-06-30.00h11.zip should handle bettter

**Comment by koalix** [comment]
Worked perfectly. I had to unmatch and do it again to capture the info, but worked perfectly in the end.

Thanks a lot for your help and hard work!
