### ISSUE TITLE
No episode titles & summaries?

### ISSUE THREAD

**Issue by puyt** [ZeroQI/Hama.bundle#130]
Could someone help me find out why I have no episode names & summary when forcing the id with tvdb3 or tvdb4?

[Link to full Hama log](https://drive.google.com/open?id=0B45Bc66q8uyqZDU1OHdfQm9RYkk)

I think the Absolute Serie Scanner is working as it should, My folder is named **"One Piece [tvdb3-81797]"** and my files look like this:

![screenshot](https://lh3.googleusercontent.com/sjKg2-AY6UKz0xDBmbMwIEfeCeWj7IjAo6Gqo9MoLbePvUcSVOSCTkIrzEbjXBojnHnpHjyC=w2806-h1562-rw)

No title or summary in plex
![screenshot plex](https://lh3.googleusercontent.com/t5WrXEuyPSPg_7HIT5oOAx3OCmY8ODVT6f01E0hp8q24muIGyZwb0ZPpaltw_79RO7ecxcxosB4Gndw=w2806-h1562-rw)
![screenshot plex 2](https://lh5.googleusercontent.com/ZwggPzLR4fn6QtOh2M8CHE4AfMobMTrgM60dDGuR_PjJuHLPZ92vXJyw20TS8CwSAhwU2csWoAiSoCA=w2806-h1562-rw)

**Comment by ZeroQI** [comment]
Please check latest beta https://github.com/ZeroQI/Hama.bundle/releases/download/Beta/Hama.bundle.2017-06-30.00h11.zip
can't see pics

**Comment by puyt** [comment]
It works with the beta, Thanks! 

-- 
@ZeroQI one more little question..

On my previous setup I had to create a `tvdb.id` file with just the ID in it but now I want to use the guid_type and i'm not a fan of renaming the folder.

The following sentence in the readme is a bit confusing for me:

> You can specify the guid to use the following way:
> - In guid_type.id inside serie folder with the id in it (ex: tvdb.id file with tvdbid "114801" without double quotes in it)

Does this mean I can use `tvdb.id` with `[tvdb4-81797]` or do I have to create a file `guid_type.id` with `[tvdb4-81797]`

**Comment by ZeroQI** [comment]
tvdb4.id with 81797 inside.

**Comment by puyt** [comment]
Thanks @ZeroQI
