### ISSUE TITLE
Agent not appearing

### ISSUE THREAD

**Issue by pepe291** [ZeroQI/Hama.bundle#131]
After I installed the agent,it's not appearing in the Plex agents section

**Comment by ZeroQI** [comment]
Either right issue or installed at wrong place or wrongly
Please follow the read-me, which outlines few issues including one on linux/osx due to missing folders and logs to include

**Comment by pepe291** [comment]
I use Win7, and downloaded the agent and putted in the Plugin folder

**Comment by ZeroQI** [comment]
do the folders look like Plex Media Server\Plug-ins\Hama.bundle\Contents\Code ?
did you decompress the zip?
need com.plexapp.system.log...

**Comment by ZeroQI** [comment]
No answer, work for me, assume it is resolved
