### ISSUE TITLE
anidb2 series not combining with Fix Match

### ISSUE THREAD

**Issue by mweber03** [ZeroQI/Hama.bundle#133]
All of my anime were originally scanned as 'anidb'. I'd like to change some of them to 'anidb2' via Plex (to not affect the date added). So I go to the series, click the 3 dots then "Fix Match..." then "Search Options" then type: "Anime Name [anidb2-xxxx]". When I do this, I expected the related anime would combine into one series like thetvdb has, but this is not the case.

The series I was testing with is: Black Lagoon
Black Lagoon [anidb-3395] -> Black Lagoon [anidb2-3395]
Black Lagoon The Second Barrage [anidb-4597] -> Black Lagoon The Second Barrage [anidb2-4597]
Black Lagoon Roberta's Blood Trail [anidb-6645] -> Black Lagoon Roberta's Blood Trail [anidb2-6645]

After doing a Fix Match to anidb2, they stay as 3 separate series.

I am using Hama/Scanner version: Hama.bundle.2017-06-30.00h11.zip

**Comment by ZeroQI** [comment]
The series will be grouped if the guid is the same, but the ep numbering won't change if not processed by the scanner.......
in other words anidb2 is processed by the scanner to pass a common tvdb-xxxx equivalent to the agent after shifting the episode numbering at scanner level...

**Comment by mweber03** [comment]
It looks like Fix Match is using the scanner. And they should all have the same tvdb ID. What more information can I get you?

**Comment by ZeroQI** [comment]
No. it assign a new metadata id to the serie at agent level. scanner not called...
