### ISSUE TITLE
Beta:  Missing Episodes log 

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#135]
Hi @ZeroQI -- the missing episodes log is currently listing every episode as missing.  I wanted to see if you had any beta updates to test.  I had some hard drive issues recently and think I'm probably missing a few episodes here and there from down time, so it would be helpful to check against.  Here is a copy of my latest, which I delete regularly:

[Missing Episodes.zip](https://github.com/ZeroQI/Hama.bundle/files/1214836/Missing.Episodes.zip)

**Comment by ZeroQI** [comment]
added db super w/ 77-83 missing:
TVDBid: 295068 | Title: 'Dragon Ball Super' | Missing Episodes: ['78', '79', '80', '81', '82', '83', '84']
It's off by 1
moved abs number increment down, now solved.
TVDBid: 295068 | Title: 'Dragon Ball Super' | Missing Episodes: ['77', '78', '79', '80', '81', '82', '83']

Scan library files doesn't update missing eps, refresh metadata does
tvdb4 works but tvdb3 does show all missing, maybe other modes impacted...
Coding now...

**Comment by sven-7** [comment]
Thank you.  

I will test this today and report back.

**Comment by sven-7** [comment]
It's still refreshing, but it looks like anything set to TVDB 2/3/4 is showing up in the missing logs still. AniDB entries seem to be correct.

**Comment by ZeroQI** [comment]
i had issues where the file didn't refresh, i saw it from the timestamp. i deleted it to be sure...
tvdb4 worked for me, and fixed tvdb3 for dragon ball super...
Can you paste the serie master log (agent data folder > _logs/Series) after ensuring you have the scanner part AND agent part in it, and tell me what you think of the format. it has filelist, scanner and agent log in the same file! Troubleshooting Easy !!

**Comment by sven-7** [comment]
Wow, brilliant work! I think having them both in one for each series is very clever. Easy to troubleshoot by each show.

I've attached a log for Food Wars! Shokugeki no Soma, which is TVDB2.  It looks like I misspoke earlier, like you said, I had to refresh.  Only TVDB2 shows are showing up as missing. I do not see any TVDB3 or TVDB4, but I have included a log for each of those as well. 

[Archive.zip](https://github.com/ZeroQI/Hama.bundle/files/1235158/Archive.zip)

**Comment by ZeroQI** [comment]
Solved tvdb2
https://github.com/ZeroQI/Hama.bundle/releases/download/Beta/Hama.bundle.2017-08-19.00h55.zip

**Comment by sven-7** [comment]
Yes, looks like the TVDB2 ones have been fixed.  I did get an error in one of the logs:

```
TheTVDB.GetMetadata() - TVDBid: '78960', IMDbid: ''
common.LoadFile() - Filename: '78960.xml', Directory: 'TheTVDB\xml' does not exists in cache
Requesting 'http://thetvdb.plexapp.com/api/A27AD9BE0DA63333/series/78960/all/en.xml'
Exception in I/O handler for fd 1104
Traceback (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-c789b3fbb\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\ioloop.py", line 256, in start
    self._handlers[fd](fd, events)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-c789b3fbb\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\stack_context.py", line 128, in wrapped
    callback(*args, **kwargs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-c789b3fbb\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\httpserver.py", line 219, in _handle_events
    connection, address = self._socket.accept()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 10035] A non-blocking socket operation could not be completed immediately
Handling request GET /:/plugins/com.plexapp.agents.hama/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNgoxNTMwNjlzNApkYmlkaTAKczcKdmVyc2lvbm5zMTAKcGFyZW50R1VJRG5zOApwYXJlbnRJRHM3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZXM0Ngpjb20ucGxleGFwcC5hZ2VudHMuaGFtYTovL3R2ZGIyLTI0ODAzNT9sYW5nPWVuczQKZ3VpZHMxMgp0dmRiMi0yNDgwMzVzMgppZHIwCg__
Received packed state data (1528 bytes)
Found route matching /:/plugins/com.plexapp.agents.hama/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNgoxNTMwNjlzNApkYmlkaTAKczcKdmVyc2lvbm5zMTAKcGFyZW50R1VJRG5zOApwYXJlbnRJRHM3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZXM0Ngpjb20ucGxleGFwcC5hZ2VudHMuaGFtYTovL3R2ZGIyLTI0ODAzNT9sYW5nPWVuczQKZ3VpZHMxMgp0dmRiMi0yNDgwMzVzMgppZHIwCg__
Loading model with GUID com.plexapp.agents.hama://tvdb2-248035?lang=en
Deserializing from C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Metadata\TV Shows\9\3579f7744b8211a23c3d87fdaac1d87fbb7b6ae.bundle\Contents\com.plexapp.agents.hama\Info.xml
AniDB.get_metadata() - Duration: 9175, numEpisodes: 366, average duration: 25
AniDB.get_metadata() - ANNid: '6197', MALid: '834', xml loaded: 'True'
-----------------------------------------------------------------------
```

Daily Lives of High School Boys (TVDB4) is showing up as the first season missing.  I've included a all the shows that are showing up as missing, but in reality are not. A few in there are legitimately missing.

[Missing Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/1236385/Missing.Logs.zip)

**Comment by ZeroQI** [comment]
the anidb/tvdb xml need to be loaded to refresh the missing ep status so since the tvdb xml fails to load, that explain the missing ep file not changing, the missing ep code is actually not at fault...
I didn't get that error so you might require the plex dance to correct corruption
Improved logging and regroupe root folder loggin to agent data folder, was in 2 places before
https://github.com/ZeroQI/Hama.bundle/releases/download/Beta/Hama.bundle.2017-08-19.18h05.zip
please re-send me the same logs with this firmware

**Comment by sven-7** [comment]
Same results, without doing any kind of Plex dance.  Logs are attached.  Will do a Plex dance next.

[logs v2.zip](https://github.com/ZeroQI/Hama.bundle/files/1237082/logs.v2.zip)

**Comment by ZeroQI** [comment]
there is the filelist and scanner but no agent log...
so refresh library then all meta to have agent logs
still practical to have all logs in a single file

**Comment by sven-7** [comment]
After a Plex Dance, all except Bleach resolved themselves. 

Here are the logs for all of them:

[logs.zip](https://github.com/ZeroQI/Hama.bundle/files/1237151/logs.zip)

**Comment by ZeroQI** [comment]
there was a corruption most likely, that is why i asked for the Plex dance
need to find why it shows ep1 missing for bleach

**Comment by sven-7** [comment]
Yes, that definitely worked.

Within Plex, ep1 is showing up as expected within Bleach. So it's still registering as ep1.  I looked on TVDB to see if there were any issues, but absolute numbering seems correct.

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Hama.bundle/blob/Beta-Agent/Contents/Code/TheTVDB.py
Line 88 corrected, was using a loop across all seasons folders  and reused season variable, changing its value and messing few things up...
Please update this file and check

**Comment by sven-7** [comment]
So far, so good. Bleach is not showing up in the missing episodes file anymore.

I did, however, see something else.  Please let me know if you want me to create an additional ticket.  Within the Bleach log, I began seeing logs for a different show, Blood Blockade Battlefront.

[Bleach.zip](https://github.com/ZeroQI/Hama.bundle/files/1241990/Bleach.zip)

**Comment by ZeroQI** [comment]
Please do create a ticket per issue, am i trying to keep track of problems separately
i believe there is 2 threads concurrently and that run after the log redirection...
so either a proper lock mechanish or 1 thread only... not sure how to do that....
