### ISSUE TITLE
Episode Titles are missing

### ISSUE THREAD

**Issue by cokebar** [ZeroQI/Hama.bundle#138]
These things are OK:
- Subtitles
- Background
- Serie poster
- Serie Season poster
- Theme song

But Episodes Titles are missing
When using TVDB, episodes titiles are normal.

I've test on three bangumi, “地獄少女”, "中二病でも恋がしたい!" and "中華一番".
"中華一番"'s episode titles are OK. It is put in a single season.
“地獄少女”, "中二病でも恋がしたい!" are not good. Episode titiles are missing. These two have multiple seasons.
Screenshot:
![image 2](https://user-images.githubusercontent.com/9136591/29742474-8d019092-8ab2-11e7-956a-5943957d7030.png)

Logs:
[Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/1253757/Logs.zip)

**Comment by ZeroQI** [comment]
Please use beta branch as it already have a second source for theme songs and is the next version to come, i will not code fixes on the standard branch as beta has the fixes to come... Just need to sort a logging glitch before replacing main branch with beta one's code

**Comment by cokebar** [comment]
@ZeroQI I made a mistake before. Theme song is OK for the master branch.
I'll try beta branch to see if episodes subtiles are OK or not.

**Comment by ZeroQI** [comment]
@cokebar Plex scanners don't manage subtitles, "local media assets" agent from Plex does, and you said subs were ok. Episodes titles should be fixed. make sure to go in the Hama agent options, a lot has changed

**Comment by cokebar** [comment]
@ZeroQI sorry miss spelling. I mean episodes titles.

**Comment by cokebar** [comment]
beta branch works fine. thanks

**Comment by ZeroQI** [comment]
And you can select the metadata source order per field. Once i fix a remaining logging issue it will replace normal code.

**Comment by cokebar** [comment]
@ZeroQI Can I select metadata source order for "episode title"? I didn't see the option for episode title.

**Comment by ZeroQI** [comment]
You select the source for all titles so both series and episodes
You can select the language priority for series and episode titles separately
I had to group the options or i would have too many fields. Do you have a reason to want serie title and episode titles with a different source priority? If it makes sense to me i could add an option for ep title priority

**Comment by cokebar** [comment]
There's a problem ablout Chinese Simplified (zh-Hans) / Chinese Traditional(zh-Hant).
ANIDB's serie title is very good, many contains both zh-Hans and zh-Hant, but episode titles are not(usually no Chinese). If I use anidb, serie title is good, but episode title are usually jp or en(I want Chinese)
TVDB's Chinese support is better, many episode title has Chinese language, but TVDB doesn't distinguish zh-Hans and zh-Hant. TVDB only have "zh". If I use TVDB, many serie title will be zh-Hant, but I want zh-Hans.

So, I want serie title use anidb(to get zh-Hans title), and episode tiles use TVDB(at least it's Chinese, not jp or en).

**Comment by cokebar** [comment]
Faced another problem:
<Ore no Imouto ga Konnani Kawaii Wake ga Nai> Season 2, the episode titles are wrong (Air Date appears instead of title).
![image 6](https://user-images.githubusercontent.com/9136591/29749193-f34b3442-8b58-11e7-9ba5-b0133b41aae2.png)

[com.plexapp.agents.hama.zip](https://github.com/ZeroQI/Hama.bundle/files/1254324/com.plexapp.agents.hama.zip)

**Comment by ZeroQI** [comment]
the metadata id for the serie is: anidb2-7525. You most likely searched manually, which doesn't work for scanner assisted translation. anidb2 maps separate anidb numbered series (seasons) in the same serie in plex.
The scanner translate anidb2 ids on anidb2.id file or serie folders to tvdbids ([tvdb-194961] in this case).

Please search for "我的妹妹哪有这么可爱 [tvdb-194961]". It make no sense to assign anidb2 mode to an already tvdb numbered serie, even less at agent level only.

**Comment by cokebar** [comment]
I delete the serie from the library, then re-add it. Then search for "我的妹妹哪有这么可爱 [tvdb-194961]". But still got the same result.

**Comment by ZeroQI** [comment]
I can't see any title in chinese for episodes in thetvdb xml file: http://thetvdb.com/api/A27AD9BE0DA63333/series/194961/all/zh.xml

logs show ep 1 to 12 have episode titles comes from anidb...
Season 2 logs show:

> [#] title                          Type: NoneType              Source: 'AniDB, TheMovieDb', Field present in this sources: '['TheTVDB']'
> [#] title                          Type: NoneType              Source: 'AniDB, TheMovieDb', Field present in this sources: '['TheTVDB']'

If you want titles from TheTVDB, why title priority  'AniDB, TheMovieDb' ??? Try 'AniDB, TheMovieDb, TheTVDB'...
i have re-produced the serie with ep 1 and 2 of season 2 and get english titles

**Comment by cokebar** [comment]
I delete TVDB from the title source by a mistake. sorry. Know I can get english episode title.
But my language priority is : zh-Hans, zh, zh-Hant, ja, jp, main, en.
Season 1 I got Japanese episode title. It should also be Japanese for season 2. But season 2 I got English.

**Comment by ZeroQI** [comment]
It is because the agent need to download multiple anidb xml files, which it currently doesn't support.
Need to allow download of multiple anidb xml files and the source selection separate for serie title and episode title to make this work, will take time coding...

**Comment by ZeroQI** [comment]
Can you attach new logs not showing anidb2-xxxx guid?
currently anidb eps gets mapped to tvdb eps but tvdb series to the first season only and need to change the code quite a bit...

**Comment by ZeroQI** [comment]
@cokebar 
- update to latest beta
- modify title agent settings to "AniDB, TheTVDB | TheTVDB, AniDB"
- attach new logs not showing anidb2-xxxx guid
- confirm you can get serie title in chinese from anidb and episode titles from TheTVDB as it should work

**Comment by cokebar** [comment]
@ZeroQI Thanks very much! I'll try it this weekend.

**Comment by ZeroQI** [comment]
@cokebar did you had time to check?

**Comment by cokebar** [comment]
@ZeroQI It works with single season serie if TVDB has Chinese episode titles. 
But It has the following problem.
- AniDB have Japanese an English episode titles.
- TVDB has English, no Chinese and Japanese.
- My language priority is : zh-Hans, zh, zh-Hant, ja, jp, main, en. 
- Result should be Japanse from AniDB, but in fact it is English.

For serie with multiple seasons, I'll do the test later.

**Comment by ZeroQI** [comment]
The way it works currently is that the source is taken first, in the order of languages then the other source in the order of languages. It make sense to have languages first, but would need a complete re-design.
to have only chinese you temporarily would have to switch to "zh-Hans, zh, zh-Hant" only...

I will think of a simple enough way to make this work, but i need to stack All languages fields in the language order (title/review for serie/episode) then skip it in the current source order loop then another loop with language order with just these two fields (or use first loop iteration to get the deed done)....

Will take some time but will implement it.
Have to sort logging with scanner and agent first though...

**Comment by ZeroQI** [comment]
Hi, sorry for the delay. I haven't forgotten.
I am trying to implement few things:
- language selection Before metadata source
- multiple anidb xml downloads for multiple seasons series IF 1 concerned file present in Plex
- scanner hybrid mode to have automated grouping folders AND normal caching otherwise

Starting with the language selection, will take few days it's a big change
Will involve series and episode titles

**Comment by ZeroQI** [comment]
You were SO right, episode titles for AniDB was so broken i can't believe i missed it... Was getting all from thetvdb... This fix episode titles from anidb:
https://github.com/ZeroQI/Hama.bundle/commit/7aef95f581fa7bb7816fac6bb2f255da6c2a0858

have added a variable to the metadata list 'language_rank' for series and episodes
If rank is not 0, system will loop over the metadata source until a lower rank is found and the title replaced. added the variable to aniDB for now and prevented its reporting as unrecognised field in logs

Left to add the variable to tvdb and add the exceptions to the loop for titles and we will have Metadata source independant functioning language selection so you will get language priority really working in a few days.

**Comment by ZeroQI** [comment]
re-uploaded a new beta branche code, please test chinese titles with it. there should be episode titles and should take chinese one from tvdb if not on anidb but anidb must be first in the agent title priority: AniDB, TheTVDB | AniDB, TheTVDB

**Comment by ZeroQI** [comment]
Please reply/reopen if issue not solved
