### ISSUE TITLE
No Posters or Backgrounds

### ISSUE THREAD

**Issue by mweber03** [ZeroQI/Hama.bundle#14]
When I use the Hama agent I get no Posters or Backgrounds or anything. I've tried with only AniDB posters checked, and only TheTVDB posters checked, both checked, and other variations to no avail.

**Comment by ZeroQI** [comment]
closing this case as no exemple nor hama log provided and you open 2...
tested code and i have no issue,
Either you did wrong and didn't follow the readme (saved source as html) or it only impact some series but you didn't specify which, but it for sure works for 07-ghost that i just tried
