### ISSUE TITLE
Cover Art Not downloading

### ISSUE THREAD

**Issue by Reflectin88** [ZeroQI/Hama.bundle#142]
Cover art will not download. Running everything off of a synology nas, The metadata seems to download(names and seasons) art work does not

**Comment by sven-7** [comment]
Try hitting “Refresh Metadata” one more time in the show. Even if HAMA tends gets it, it tends to not load the artwork on its first go around.

**Comment by Reflectin88** [comment]
Just under more then refresh?

**Comment by sven-7** [comment]
Yes. Is it just a single show that isn’t showing up? If so, go into that show and select refresh metadata for that show specifically.

**Comment by Reflectin88** [comment]
Its all the anime

**Comment by Reflectin88** [comment]
![example](https://user-images.githubusercontent.com/5627328/30779711-331c51bc-a13b-11e7-8957-3036ba5087ff.PNG)
This is what the anime section currently looks like. So it adds the anidb tag but and episode titles but thats it

**Comment by ZeroQI** [comment]
Readme mention a case when poster doesn't download. Agent folders are missing. Bera agent would fix it as it create them automatically

**Comment by Reflectin88** [comment]
![not correct](https://user-images.githubusercontent.com/5627328/30782196-766d907c-a170-11e7-9973-c2014c464123.PNG)

Is this not the correct structure?

**Comment by ZeroQI** [comment]
2017-09-24 14:30:59,110 - com.plexapp.agents.hama (73a59460) : ERROR (__init__/anidbTvdbMapping:790) - anidbid '6239' not found in file
Please try beta branch i believe this issue to be resolved already

**Comment by ZeroQI** [comment]
Closing due to no answer for 2 weeks
