### ISSUE TITLE
Metadata fields appear to no match reliably

### ISSUE THREAD

**Issue by thuringia** [ZeroQI/Hama.bundle#144]
Hi everyone,

when pulling metadata from AniDB, some field use strings with whitespace as "key" (notably `Animation Work`), these seem to not match reliably on my PMS (running on OS X - 10.12.6 to be exact) though. For example, any of the "Monogatari" Series has the value _Shaft_ for `creators > name[type="Animation Work"]` - but the field `studio` in the PMS remains entry.
This also happens for other shows but I can't tell you which since I did not manage to query my PMS for all shows _without_ a value in either `studio` or `network`.

My best guess is that the string literal in the source code and the string in the XML file are not equivalent, like an encoding issue. I'm not very experienced with Python though, so this is not even an educated guess.

Thanks for the great work everyone, I really appreciate it!

**Comment by ZeroQI** [comment]
Does it happens in beta branch? you can select the metadata source order there per field.
All are stores in agent data folders and if studio is empty in plex, will use anidb, tvdb or scudlee's in some order
In the beta branch, the order is "AnimeLists, AniDB, TheTVDB, TheMovieDb" by default

**Comment by thuringia** [comment]
Sorry, I was on vacation.
This happens in `beta` as well as `master` unfortunately. I also checked the diff but the relevant code did not change other than moving.
I created a new library that only uses AniDB for the `studio` field but the issue persists.

**Comment by ZeroQI** [comment]
Can i please have hama beta branch logs for an impacted series like "Monogatari"?
This look like a genuine bug but do not know yet where to start

**Comment by ZeroQI** [comment]
Can i please have hama logs?

**Comment by thuringia** [comment]
@ZeroQI sorry for not posting any updates, I didn’t have access to my server due to international travel. I will be back on Wednesday with full access to everything. I’ll upload logs then.

**Comment by thuringia** [comment]
@ZeroQI I created a completely new library containing just the Monogatari series and only allowing AniDB for the `studio`field:
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/1497355/com.plexapp.agents.hama.log)

The first entry "Bakemonogatari" does not have a studio in PMS:
<img width="1134" alt="screen shot 2017-11-22 at 21 05 42" src="https://user-images.githubusercontent.com/752104/33147838-b68b9852-cfc9-11e7-9568-2ad41246b32f.png">
but the AniDB data is fine:
<img width="523" alt="screen shot 2017-11-22 at 21 11 10" src="https://user-images.githubusercontent.com/752104/33147857-c2f6c8aa-cfc9-11e7-8f91-23af6c836c1b.png">

**Comment by ZeroQI** [comment]
Thanks for the detailed answer, thanks to that I have reproduced the issue.
It seems the studio was gotten from TheTVDB ok but never worked in Beta from AniDB
Fixed that but the producer writers, directors (not by episode on AniDB like it is on TheTVDB) so trying to fix that
will have to download multiple anidb series xml for multiple seasons series

**Comment by ZeroQI** [comment]
Please reply if issue not solved
