### ISSUE TITLE
Beta: Missing Eps Log Incorrect

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#145]
I have Mr. Osomatsu on tvdb2 and season 1 is showing up as missing currently. 

[com.plexapp.agents.hama.zip](https://github.com/ZeroQI/Hama.bundle/files/1357052/com.plexapp.agents.hama.zip)

**Comment by ZeroQI** [comment]
DEBUG (logkit:13) - common.write_logs() - Missing Specials           : ["TVDBid: <a href='http://thetvdb.com/?tab=series&id=300989' target='_blank'>300989</a> | Title: 'Mr. Osomatsu' | Missing Specials: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']"]
DEBUG (logkit:13) - common.write_logs() - Missing Episodes           : ["TVDBid: <a href='http://thetvdb.com/?tab=series&id=300989' target='_blank'>300989</a> | Title: 'Mr. Osomatsu' | Missing Episodes: ['s1e1', 's1e2', 's1e3', 's1e4', 's1e5', 's1e6', 's1e7', 's1e8', 's1e9', 's1e10', 's1e11', 's1e12', 's1e13', 's1e14', 's1e15', 's1e16', 's1e17', 's1e18', 's1e19', 's1e20', 's1e21', 's1e22', 's1e23', 's1e24', 's1e25']"]
2017-10-04 14:59:42,801 (d2c4) :  INFO (logkit:16) - id: anidb-11347, title: Mr. Osomatsu, lang: en, force: True, movie: False
**not on tvdb2**

**Comment by sven-7** [comment]
Right, I’m not quite sure why it’s not showing up on tvdb2. I’ll try a Plex Dance, but tvdb2 is present within the file structure and the metadata is showing up correctly. It’s just the log that’s odd. Once I Plex Dance, I’ll let you know how it goes.

**Comment by sven-7** [comment]
Here is what I think happened, as it just happened with a second show.  Before Mr. Osomatsu had a second season announced, I had it on the standard AniDB/HAMA defaults.  Once the second season started, I added the tvdb2.id to the folder.  While it split up right via the scanner, something about the missing eps ended up not translating over.  The metadata showed up correctly and the scanner did things properly.  I had this happen to a second show as well.  

Once I Plex danced them and they came into HAMA fresh, it worked as intended.  It seems to be a bug (maybe not) when switching from AniDB to a TVDB mode when the series is already in the library. 

See the logs for Himouto! Umaru attached.  
[com.plexapp.agents.hama.log.zip](https://github.com/ZeroQI/Hama.bundle/files/1369454/com.plexapp.agents.hama.log.zip)

Because the Plex dance fixed it, I would consider this closed for me unless you want to track down if this is or is not really a bug.

**Comment by ZeroQI** [comment]
You can't do that unfortunately
The guid is assigned at creation...
When adding the guid the series guid isn't updated. You have to re-match the series

**Comment by ZeroQI** [comment]
The guid is assigned at creation...
When adding the guid file the series guid isn't updated. You have to re-match the series so the plex dance solved that.

**Comment by sven-7** [comment]
Good to know.  Perhaps an update to the readme then? Thanks.

**Comment by ZeroQI** [comment]
updated scanner readme in beta branch
