### ISSUE TITLE
Series getting stuck as anidb-xxx/ Now unable to locate files.

### ISSUE THREAD

**Issue by diksm8** [ZeroQI/Hama.bundle#149]
Some entries are getting stuck as just their anidb after manually matching them.
![Image of error](https://i.imgur.com/GUPEvWT.png)
Some are not downloading all of the meta-data, only some parts
![Image two](https://i.imgur.com/CCSSJZ8.png)
![Image three](https://i.imgur.com/4PRc4Vj.jpg)
Most of my entries work fine, but as shown above, some get stuck.

**Comment by ZeroQI** [comment]
Agent probably crashed.  i need agent logs
Are you using beta branch ? I am only working on Beta branch code and it will replace main branch soon.

**Comment by diksm8** [comment]
Tried pulling it from the repo directly, same thing.
What logs do you need?

**Comment by ZeroQI** [comment]
Agent log ìn agent data folder if using beta branch

**Comment by diksm8** [comment]
After updating plex can no-longer detect any files if using the scanner/agent combo

**Comment by ZeroQI** [comment]
Try going back in scanner versions and give the link of working one if any...

**Comment by diksm8** [comment]
First time I tried this plugin was after the latest release of the scanner.

**Comment by JohnAlzagatiti** [comment]
I get this same error, did you ever figure out a solution?

**Comment by ZeroQI** [comment]
Logs...

**Comment by JohnAlzagatiti** [comment]
Sure, which ones do you want? I'll have them asap.

**Comment by diksm8** [comment]
I found a way to get the Hama agent to detect my files. I first have to scan the directory with TheTVDB agent and then I have to change it to Hama. Sadly if TheTVDB doesn't detect the series neither will Hama.

**Comment by ZeroQI** [comment]
Plex scanners detect files, not agents. which scanner is configured for the library?
If none showing, ASS is not installed properly

**Comment by ZeroQI** [comment]
Please create ticket with either scanner log in the scanner github page or with the agent in HAMA agent github page like here. Clearly your agent crash and doesn't update the title here, and solved a lot a bugs recently so should be resolved.
