### ISSUE TITLE
Im getting wrong episode names

### ISSUE THREAD

**Issue by YamiFrankc** [ZeroQI/Hama.bundle#151]
Hello, I am getting episodes names wrong in a weird way.
For example, for Nisemonogatari, Plex tags it correctly as Nisemonogatari and actually gives the correct season description for it, but it has the episode names of the first season.
The same happens with Digimon 02, correct show name and description, but episode names from fist season. 
Something weird is that Nisemonogatari used to be alright, but I had to rebuild the database and now its wrong. I did not change the file names or structure in the slightest. So im wondering whats wrong.

I do have the [anidb-xxx] tag for every folder and show.

**Comment by ZeroQI** [comment]
i cannot tell the guid used by Plex, which could be wrong if you modified the serie folder name after an initial scan...
I cannot tell with your wording if the forced id is on the serie folder name
I cannot tell if you are using the beta branch...

I need scanner and agent logs as per the troubleshooting section of each readme

**Comment by YamiFrankc** [comment]
Sorry, Been very busy lately.
I did not modify any names or folder structure. I did have the folder named "Nisemonogatari [anidb-8658]"
since I first added it to my library folder, and no beta branch.
Anyway, i fiddled more with it and now it is working mostly alright. Thanks for your time.
