### ISSUE TITLE
Entries getting stuck as their anidb id or not showing images

### ISSUE THREAD

**Issue by diksm8** [ZeroQI/Hama.bundle#155]
![Image of anidb](https://i.imgur.com/uFCOgHQ.png)
![Image of no images](https://i.imgur.com/QIi2acu.png)
[logs.zip](https://github.com/ZeroQI/Hama.bundle/files/1544612/logs.zip)

**Comment by diksm8** [comment]
Also would it be possible to include films in a series library? Some movies are already showing up even though they are not supposed to.

**Comment by ZeroQI** [comment]
No poster for items showing is an agent issue, so you created a bug report on the agent part, so far so good.
I can tell you the agent crash and could tell more had you included agent logs, as per the agent read-me
https://github.com/ZeroQI/Hama.bundle/blob/master/README.md
Troubleshooting section:

> [...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.hama.log (Agent logs)

What do you mean "even though they are not supposed to." ? The scanner read-me says it is supported:

https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/README.md
file section:

> Movie files in Series libraries (since this is a Series Scanner) are supported if:
> 
> Files are in a folder with the same name or with a single file inside it
> Files are numbered (01|ep 01|s01e01)
> Filename contain " - Complete Movie"

Everything between brackets ie '[' and ']' is skipped. that is a scanner issue.
Your naming is so atrocious that you would have to actually go out of your way to create it: [2012 OVA][Ai no Kusabi][BDRIP][1080P][1-4FIn+SP]

Please read the read-me on scanner and agents.
If some parts are wrong or unclear you can submit changes or let me know
Please use the beta branch agent as i am pretty sure i solved that already, and i am not goint to have to concurrent versions of agents to maintain, so i work exclusively on the Beta and it will replace soon the main branch

**Comment by diksm8** [comment]
Nothing has been renamed, everything is just as how I got it from Animebytes.

As for the movies the movie "[Ganbarou] Ajin Movie Part 1 - Shoudou [BD 1080p].mkv" shows up but "Hells [BD.1080p.Hi10p] [Iznjie Biznjie] [4E5BF17B].mkv" and "Kimi.no.Na.wa.2016.1080p.Remux.AVC.FLAC.5.1-SUCC.mkv" doesn't. Thought that was an error.

And I don't have a folder name "PMS Plugin Logs" and when I download the logs via plex they are not included.

**Comment by diksm8** [comment]
This issue does not occur with the beta branch.
And the beta branch creates the PMS Plugin Logs folder.
