### ISSUE TITLE
Incorrect image matching

### ISSUE THREAD

**Issue by WulfTek** [ZeroQI/Hama.bundle#156]
When downloading the metadata for the movie Dragonball Z: Battle of Gods, the information is all correct, but the cover art, background and banners are all incorrect, as they're all from the tv series Dragonball Z. 

![capture1](https://user-images.githubusercontent.com/34924422/34423485-39f50816-ec14-11e7-8a95-f873f5cf423f.PNG)
![capture2](https://user-images.githubusercontent.com/34924422/34423484-39d412dc-ec14-11e7-9511-951e4aaa7001.PNG)

I've looked over the [FanartTV](https://fanart.tv/movie/126963/dragon-ball-z-battle-of-gods/) and [TMDB](https://www.themoviedb.org/movie/126963-z/images/posters) images for Battle of Gods and none of those images are picked up. Also for some reason the movie's description and thumbnail are pulled from the One Piece/Dragonball crossover.

Also Dragonball Z: Resurrection F only seems to grab the anidb poster and nothing else.

![capture3](https://user-images.githubusercontent.com/34924422/34423760-39284ee6-ec16-11e7-9cab-4bf5533443c2.PNG)

**Comment by ZeroQI** [comment]
if tvdb shows the episode as a special, posters wouldn't be wrong per say but the movie pictures should be prefered.
Could you please paste hama beta branch logs so i could see the scudlee mappings and if the tbdb id is generated and the xml links used?

**Comment by WulfTek** [comment]
Apologies, I'm quite new to this, where would the log be located?

**Comment by WulfTek** [comment]
I'm an idiot, should have checked the readme first :P

[Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/1592380/Logs.zip)

**Comment by ZeroQI** [comment]
Thanks for reading the read-me. I will have to rewrite it to avoid that after i finish the beta branch code.

It is an agent issue so i need the agent logs [com.plexapp.agents.hama] showing the serie/movie concerned. Agent logs provided contain only "Magi: Sinbad no Bouken (2016)" http://anidb.net/perl-bin/animedb.pl?show=anime&aid=11672
Since you are using Beta Branch in agent data folders you will haven a Logs folder with a log per serie/movie.

**Comment by WulfTek** [comment]
Here ya go

[Dragon Ball Z Battle of Gods.agent.log](https://github.com/ZeroQI/Hama.bundle/files/1593164/Dragon.Ball.Z.Battle.of.Gods.agent.log)
[Dragon Ball Z Resurrection F.agent.log](https://github.com/ZeroQI/Hama.bundle/files/1593165/Dragon.Ball.Z.Resurrection.F.agent.log)

**Comment by ZeroQI** [comment]
Thanks.
For Dragon Ball Z Battle of Gods, you forced the anidb id and mapping file gave the tvdbid
tvdb gave the imdb id tt0214341 however themoviedb used the tvdb id, and returned tmdb id for series which i call tsdbid. I should prefer movie id there when present...
The other logs have too many bits missing, but not your fault.
Will need to release new code with better logging favouring movie ids compare to series it to gain in accuracy.
Logs will be spitted per series (even if in grouping folder) in upda and search, and scanner and filelist.
i keep you posted

**Comment by ZeroQI** [comment]
I just upgraded the code for logging, which solve a movie library crash.
This issue is tricky for me...
The movie is linked to the tvdb series on a special, so i need to detect it is a movie and discount series poster fanarts rank or not link them at all... need to  favor movies for every data source without impacting too much other series with movies...

**Comment by ZeroQI** [comment]
added a field in AniDB metadata to say when it is a movie. left is to access and discount rank when it is a movie. will try to code soon

**Comment by ZeroQI** [comment]
so latest code check if an AniDB movie then tells tvdb to increase rank which lower priorities for anidb movies.
Need agent logs with new library if possible and see if pic ranks for movie correct and especially which poster should be taken in this case, any proposition ? AniDB posters are generally atrocious... 
Which source had the movie poster correct?

**Comment by ZeroQI** [comment]
Can you test with latest release and attach logs if still failling?

**Comment by ZeroQI** [comment]
Can you test with latest release and attach logs if still failling?
it may not update the rank so if you can put the serie in a new library for tests, that would be great

**Comment by ZeroQI** [comment]
@WulfTek please test and report if not fixed. closing as nothing posted since the 29 December
