### ISSUE TITLE
Artwork isn't generating.

### ISSUE THREAD

**Issue by soupyy** [ZeroQI/Hama.bundle#158]
The artwork for the shows is not generating, I believe this is because files are missing but unfortunately I cannot seem to find the files. Any help would be greatly appreciated. 
![capture](https://user-images.githubusercontent.com/30208354/34698878-afada96a-f497-11e7-81cc-93e6bdb5b436.PNG)

**Comment by ZeroQI** [comment]
folders missing. No posters are mentionned in read-me...
please use beta branch it will create them for you

**Comment by soupyy** [comment]
I'm very sorry, I don't know what that means. I am very new to this and I must have missed a step or something because everything is being sorted correctly, There just isn't any artwork.

**Comment by ZeroQI** [comment]
Follow installation steps in the readme. Did you do the below or not understand it?

`MANDATORY: Go into the agent data folder ("Plug-In Support/Data/com.plexapp.agents.hama/DataItems") and make sure the following folders are all created: (folders are included in Zip archive in release tab and nammed "Plug-in.Support.zip", i recently added "TVDB/episodes" and "FanartTV" folder for TVDB screenshots).
"AniDB"
"Plex"
"OMDB"
"TMDB"
"TVDB"
"TVDB/blank
"TVDB/_cache/fanart/original"
"TVDB/episodes"
"TVDB/fanart/original"
"TVDB/fanart/vignette"
"TVDB/graphical"
"TVDB/posters"
"TVDB/seasons"
"TVDB/seasonswide"
"TVDB/text"
"FanartTV"
`

If you use the files from beta branch [https://github.com/ZeroQI/Hama.bundle/tree/Beta-Agent] it will create the folders automatically

**Comment by soupyy** [comment]
Wow I am dumb. I must have totally skipped that part, it's working now. Thanks so much for the help!!
