### ISSUE TITLE
Where do you Place TVDB4 ?

### ISSUE THREAD

**Issue by Comfubar** [ZeroQI/Hama.bundle#159]
I am new to Hama and ASS and have added a lot to the TVDB4 file for myself

I there like a larger collective one to add to hama and all or where should i place mine so plex can update correctly

**Comment by ZeroQI** [comment]
If you set tvdb4 mode on series folder using [tvdb4-xxxxx] or in tvdb4 id file in series folder, can place absolute numbered episodes in seasons folder with any arrangement, or use a tvdb4.mapping file in series folder to split into sagas seasons for you or let the common file anime-list-corrections.xml located https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/anime-list-corrections.xml
If there is clear sagas you have defined that are not in that file please submit a commit. You have another file for posters for the sagas seasons defined 
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/tvdb4.posters.xml

**Comment by ZeroQI** [comment]
I will close for now as it is the most complete technical answer i could write but please reply or reopen if you still have queries
