### ISSUE TITLE
Incorrect Episode Title Names

### ISSUE THREAD

**Issue by Sn0wCrack** [ZeroQI/Hama.bundle#160]
Certain shows such as Darling in the FranXX and The Junji Ito Collection appear to be displaying their air date's as their episode titles for some reason

![image](https://user-images.githubusercontent.com/442287/34913418-e329b14a-f950-11e7-80b1-7216a0ef85fe.png)

**Comment by ZeroQI** [comment]
Need agent logs.
Use beta branch so logs are precise and readable

**Comment by Sn0wCrack** [comment]
This appears to be the segment relating to Darling in the Franxx
https://pastebin.com/raw/2SqgxqDy

**Comment by ZeroQI** [comment]
Damn i am meant to have a line per field and title isn't there and i know it is in anidb...
Need to fix this first and list sources even if the field is present in the metadata source order, this is important to troubleshoot easily in the future and will fix this title issue in the process

**Comment by ZeroQI** [comment]
Thank you, spotted a very bad bug, if tvdb was first and didn't have a fiekd, would skip that field for all other metadata sources
was a bad tabulation that caused it...
Please try latest beta and feedback any issue encountered and will fix

**Comment by Sn0wCrack** [comment]
Yup, everything appears to be functioning properly again!
