### ISSUE TITLE
Refresh All doesn't seem to actually refresh all

### ISSUE THREAD

**Issue by mweber03** [ZeroQI/Hama.bundle#164]
Doing a "Refresh All" seems to work differently than if I do a "Refresh Metadata" on each individual serie. For example, doing it on the series will update posters but the All will not. Shouldn't the All, just run each refresh as if one did it manually to each?

**Comment by ZeroQI** [comment]
Looking at the source there is a "force" variable making that distinction, displayed, but not used, my code behave the same for both situation so a plex issue possibly...
Would need the series agent log for both situations to try fixing.

**Comment by ZeroQI** [comment]
Did you do the plex dance to solve any possible corrupted database ?
