### ISSUE TITLE
Compatibility with Plex Trakt scrobbler

### ISSUE THREAD

**Issue by Arno500** [ZeroQI/Hama.bundle#17]
Can it be possible to add Trakt Plex Scrobbler compatibility ?
Because Trakt is so useful, but the TPS isn't compatible with HAMA and on the issues tracker of TPS, the issue is stagnating...
Please !
Thank you,
Arno

**Comment by ZeroQI** [comment]
can't see in https://github.com/trakt/Plex-Trakt-Scrobbler what is uses
my metadata id is not normal (anidb-xxxx) but even if it was i believe it would use the tvdb.id, or does it non use the metadata id at all ???

**Comment by Arno500** [comment]
Hi,
In the issue, I think Trakt is searching for a TVDB ID,
https://github.com/trakt/Plex-Trakt-Scrobbler/issues/190 . From what I
understand, the TPS gather TVDB ID from file agent (in this case hama) and
send it to Trakt to associate collection, views...
But like you said in the readme, HAMA is already trying to bind TVDB API
format, but TPS doesn't even try, because of the detected agent "hama" (to
prevent incompatibilities).
As I said in the first post, HAMA must send TVDB API seasons/episodes
structure.
Thank you for your fast response.
Arno

**Comment by ZeroQI** [comment]
Hama does uses tvdb seasons and eps if present and Absolute series scanner let it pass to, but the guid will be tvdb-xxxxx and code would need to be edited to allow for the direct tvdbid to be used. this is an anidb agent to allow for movies and series to be in the same library, with heavy cross reference with tvdb and does allow tvdbid to be selected but that is not the default. if you want it to work use a tvdb agent (abs or season numbering, both exists).
