### ISSUE TITLE
Seasons only have banners from season 1

### ISSUE THREAD

**Issue by mweber03** [ZeroQI/Hama.bundle#172]
I'm using the anidb2 guid, so the episodes are split into their respective seasons. It looks like most of the season data is fine, but the banners for season 2+ only have the season 1 banners. I am using the beta agent.

**Comment by ZeroQI** [comment]
I believe i corrected that two days ago.
https://github.com/ZeroQI/Hama.bundle/commit/a3c246f4cdec2cb71d2d790173b5930f5284302e
Please confirm you are using latest beta branch code and update if not.
If issue is présent on latest code please attach 1 impacted series update log.

**Comment by mweber03** [comment]
Should they be updated with a Refresh Metadata?

**Comment by ZeroQI** [comment]
Which version of the agent are you running ? Did you update in the last 2 days? 
if not please update it as it is already resolved

**Comment by mweber03** [comment]
It looks like most pulled the new banners when I updated the files and did a "Refresh Metadata". One that seems to have not worked was: `anidb2-11203`.

**Comment by mweber03** [comment]
Actually I just tried a Refresh All and it seemed to work. Thanks.
