### ISSUE TITLE
[Feature Request] Custom movie set list

### ISSUE THREAD

**Issue by hthuong09** [ZeroQI/Hama.bundle#173]
So, from what I see, you are currently hard code this part [here](https://github.com/ZeroQI/Hama.bundle/blob/Beta-Agent/Contents/Code/AnimeLists.py#L35-L39)
I wonder if we should make it a config slot for people how want to build their own set list.
For me, I put anime seasons into separate shows so I want to make collections to connect those shows.

What do you think?

**Comment by ifonefox** [comment]
If I'm understanding you correctly, you want to be able to make your own collections? You can already do that without this plugin. https://support.plex.tv/articles/201273953-collections/

**Comment by ZeroQI** [comment]
I actually managed that in the AniDB part, and is done through the init code belwo
https://github.com/ZeroQI/Hama.bundle/blob/Beta-Agent/Contents/Code/__init__.py

```
### Variables ###
AniDBMovieSets = AnimeLists.GetAniDBMovieSets()
dict_AnimeLists, AniDBid, TVDBid, TMDbid, IMDbid, mappingList =  AnimeLists.GetMetadata(media, movie, error_log, metadata.id,                   AniDBMovieSets) #, AniDBTVDBMap
  dict_AniDB, ANNid, MALid                                      =       AniDB.GetMetadata(media, movie, error_log,       source, AniDBid, TVDBid, AniDBMovieSets, mappingList)
```
I do load the movie collection from ScudLee which i complement with AniDB related anime which include series and put the string in the "Collection field" under the AniDB metadata source.
XBMC and scudlee file are not for tv series collection. We could have a TV series collection xml file modeled on the same format but that is not a very popular query...

If you do not want it populated, put "None" in the agent config "collection" field. to be honest the default should be "AniDB" only, by default it list sources that will never update it...

**If you do want to add to that manually and lock it you are not prevented, just put the same string in multiple anime in collection field**

**Comment by hthuong09** [comment]
@ifonefox @ZeroQI Yes, I knew I could put collection name in Collection field but I don't want to do it manually. Since I some of my TV Series being grouped (Add to Collection), I thought it was done by Hama (Still unsure why they were being grouped). So, I think it would be great if I can configure a list and push to github.

**Comment by ZeroQI** [comment]
HAMA loads the collection two ways (wrote these parts ages ago):
- AniDB source from movie collection xml from ScudLee [https://github.com/ScudLee/anime-lists/blob/master/anime-movieset-list.xml] which only contain movies. it then add to this all anidbids listed in anidb "related anime" in the anidb anime xml file, and put the collection title string in the "Collection field" for AniDB metadata source.
 -  TheMovieDb source:
`    if Dict(json, 'belongs_to_collection', 'name'):  SaveDict( [ Dict(json, 'belongs_to_collection', 'name').replace(' Collection','')], dict_TheMovieDb, 'collections')`
- TheTVDB i could add  support for anidb numbered series, since ScudLee maps anidb to thetvdb, i could make everything matching the same tvdbid the same collection...

Please give an example of series that do not get a collection
Tte metadata collection agent setting you have configured is by default: "AnimeLists, AniDB, TheTVDB, MyAnimeList, TheMovieDb, OMDb". Did you try "TheMovieDb, AniDB" for example?



https://www.reddit.com/r/PleX/comments/5ntgxd/psa_automatic_movie_collection_tags/

**Comment by ZeroQI** [comment]
Please give an example of series/movies that do not get a collection so i can see if i can make it more automatic but there is something already in place so i need to ensure it is working...

i can make it so it uses all collections fields from scudlee movie collection+anidb related anime and TheMovieDB, right not it use the first available
i could load locally a movie collection or host it online like for tvdb4 mode, but the format use only anidbids so i prefer something fully automated.

```
  <set>
    <anime anidbid="11">Initial D Battle Stage</anime>
    <anime anidbid="625">Initial D Third Stage</anime>
    <anime anidbid="5298">Initial D Battle Stage 2</anime>
    <anime anidbid="6129">Initial D Extra Stage 2</anime>
    <titles>
      <title type="main" xml:lang="x-jat">Initial D Collection</title>
    </titles>
  </set>
```

**Comment by hthuong09** [comment]
> Please give an example of series/movies that do not get a collection
Series with only one season or original movie like Your name. doesn't need to get a collection.

**Comment by ZeroQI** [comment]
I should have been more explicit...
What series or movies should have been assigned a collection tag logically by HAMA and wasn't in your experience? I will then check how to make it happen

**Comment by ZeroQI** [comment]
"Local" source in beta branch agent for collection field use grouping folder if present and works for me.

Am working in multiple anidb xml fully working and once done will woork on anidb related anime based collection but grouping folders is simple: you group on the disk, it groups in Plex...

**Comment by ZeroQI** [comment]
Recent changes in beta agent:
- If you use a grouping folder, and set 'Local' in collection field in agent setting as source, it will be in a collection
- If you use 'AnimeLists' as metadata source in collection field, it will group any anidb entry mapped to the same tvdb id, using the name of the entry mapped as season 1 of the tvdb series

Please try 'Local, AnimeLists, TheMovieDb' in collection field agent setting and feedback any comment

**Comment by ZeroQI** [comment]
Did you try the grouping folders and "Local" metadata source for collection field ?

**Comment by ZeroQI** [comment]
no update in 45 days, closing. Please comment if any information
