### ISSUE TITLE
Beta - mapping to wrong anidb series when tvdbid matches

### ISSUE THREAD

**Issue by mweber03** [ZeroQI/Hama.bundle#175]
I am using the Beta-Agent merged on Mar 19. I have series: `Chain Chronicle [anidb2-10971]` that scans ok, but Hama pulls the metadata for its sister series `10747`. Both series map to TVDB `314031`. (one to season 0 and one to season 1) 

It seems like when using `anidb2`, the `AnimeLists.GetMetadata()` and `AniDB.GetMetadata()` only have access to the TVDBid and try to guess at or uses the first ID in the dict as the AniDB, and in this case unsuccessfully.

Below is the filelist log, scanner log, and agent-update log where you can it using the wrong anidbid. Let me know if you need anymore information. Thanks.

**.filelist.log:**

```
Library: 'no valid X-Plex-Token.id', root: '/volume1/User.Video/Anime', path: 'Chain Chronicle [anidb2-10971]', files: '12', dirs: '0', Plex scan date: 2018-03-20 01:37:14
=============================================================================================================================================================
/volume1/User.Video/Anime/Chain Chronicle [anidb2-10971]/Chain Chronicle - 01 - Light And Darkness.mkv
/volume1/User.Video/Anime/Chain Chronicle [anidb2-10971]/Chain Chronicle - 02 - To Be With Others.mkv
/volume1/User.Video/Anime/Chain Chronicle [anidb2-10971]/Chain Chronicle - 03 - Symbol of Loyalty.mkv
/volume1/User.Video/Anime/Chain Chronicle [anidb2-10971]/Chain Chronicle - 04 - The Expanding Darkness.mkv
/volume1/User.Video/Anime/Chain Chronicle [anidb2-10971]/Chain Chronicle - 05 - Snowy Mountain Screams.mkv
/volume1/User.Video/Anime/Chain Chronicle [anidb2-10971]/Chain Chronicle - 06 - The Nadir of Anguish.mkv
/volume1/User.Video/Anime/Chain Chronicle [anidb2-10971]/Chain Chronicle - 07 - Torn Apart.mkv
/volume1/User.Video/Anime/Chain Chronicle [anidb2-10971]/Chain Chronicle - 08 - Unyielding Will.mkv
/volume1/User.Video/Anime/Chain Chronicle [anidb2-10971]/Chain Chronicle - 09 - The Flower In The Desert.mkv
/volume1/User.Video/Anime/Chain Chronicle [anidb2-10971]/Chain Chronicle - 10 - The Sword That Rends Darkness.mkv
/volume1/User.Video/Anime/Chain Chronicle [anidb2-10971]/Chain Chronicle - 11 - Live By The Sword, Die By The Sword.mkv
/volume1/User.Video/Anime/Chain Chronicle [anidb2-10971]/Chain Chronicle - 12 - The Light of Haecceitas.mkv
```

**.scanner.log:**

```
Library: 'no valid X-Plex-Token.id', root: '/volume1/User.Video/Anime', path: 'Chain Chronicle [anidb2-10971]', files: '12', dirs: '0', Plex scan date: 2018-03-20 01:37:14
=============================================================================================================================================================
Use existing: '/volume1/Plex/tmp_transcoding/anime-list-corrections.xml'
anidbTvdbMapping() - No valid tvbdbid: found for anidbid '10971'
Use existing: '/volume1/Plex/tmp_transcoding/ASS-tmp-anime-list-master.xml'
anidbTvdbMapping() - anidb: '10971', tvbdid: '314031', defaulttvdbseason: '1', name: 'Chain Chronicle: Haecceitas no Hikari', mappingList: '{'episodeoffset': ''}'
-------------------------------------------------------------------------------------------------------------------------------------------------------------
"Chain Chronicle [tvdb-314031]" s0001e001 "Light And Darkness"
"Chain Chronicle [tvdb-314031]" s0001e002 "To Be With Others"
"Chain Chronicle [tvdb-314031]" s0001e003 "Symbol Of Loyalty"
"Chain Chronicle [tvdb-314031]" s0001e004 "The Expanding Darkness"
"Chain Chronicle [tvdb-314031]" s0001e005 "Snowy Mountain Screams"
"Chain Chronicle [tvdb-314031]" s0001e006 "The Nadir Of Anguish"
"Chain Chronicle [tvdb-314031]" s0001e007 "Torn Apart"
"Chain Chronicle [tvdb-314031]" s0001e008 "Unyielding Will"
"Chain Chronicle [tvdb-314031]" s0001e009 "The Flower In The Desert"
"Chain Chronicle [tvdb-314031]" s0001e010 "The Sword That Rends Darkness"
"Chain Chronicle [tvdb-314031]" s0001e011 "Live By The Sword, Die By The Sword"
"Chain Chronicle [tvdb-314031]" s0001e012 "The Light Of Haecceitas"
```

**.agent-update.log:**

```
=== Update ==================================================================================================================================================
id: tvdb-314031, title: None, lang: en, force: True, movie: False
-------------------------------------------------------------------------------------------------------------------------------------------------------------
AnimeLists.GetMetadata() - source: tvdb, id: 314031, AniDB_id: , TVDB_id: 314031
AnimeLists.GetMetadata() - Loading local custom mapping - url: /volume1/Plex/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/anime-list-corrections.xml
MergeMaps() - AniDBids concerned: ['9227', '10008', '10009']
[!] AniDBid: 10747, TVDBid: 314031, mappingList['defaulttvdbseason']: 0
AnimeLists.GetMetadata() - AniDBid is not part of any collection
AnimeLists.GetMetadata() - anidb: '10747', tvbdid: '314031', tmdbid: '', imbdid: '', defaulttvdbseason: '0', name: 'Chain Chronicle: Short Animation'
mappingList: {'poster_id_array': {'314031': {'10747': ('0', '')}}, 'defaulttvdbseason': '0', 'name': 'Chain Chronicle: Short Animation', 'episodeoffset': ''}
-------------------------------------------------------------------------------------------------------------------------------------------------------------
AniDB.GetMetadata() - AniDBid: '10747'
AniDB.GetMetadata() - AniDB_array:  '{'10747': ('0', '')}', AniDB_array2: '['10747']'
common.LoadFile() - Filename: '10747.xml', Directory: 'AniDB/xml', url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10747' does not exists in cache
Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10747'
LoadFile() - url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10747' loaded
common.SaveFile() - CachePath: '/volume1/Plex/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems', file: 'AniDB/xml/10747.xml', directory present
AniDB.GetMetadata() - 'title': Chain Chronicle: Short Animation, 'title_sort': Chain Chronicle: Short Animation, original_title: Chain Chronicle: Short Animation
AniDB.GetMetadata() - 'originally_available_at': '2014-09-06'
AniDB.GetMetadata() - 'summary' empty: 'False'
AniDB.GetMetadata() - 'rating': '2.87'
AniDB.GetMetadata() - 'genre' (5/19 above 200 weight): ['Magic', 'Swordplay', 'Fairies', 'Action', 'Fantasy']
AniDB.GetMetadata() - collections
AniDBid is not part of any collection, related_anime_list: '{'10747': ('0', ''), '10971': (0, '')}'
AniDB.GetMetadata() - Roles:
AniDB.GetMetadata() - creators tag: {'directors': ['Mori Takeshi', 'Katou Hiromi']}
AniDB.get_metadata() - Duration: 40, numEpisodes: 8, average duration: 5
AniDB.get_metadata() - ANNid: '16638', MALid: '25431', xml loaded: 'True'
```

**Comment by ZeroQI** [comment]
Hi, here is the mapping xml i use to map anidb eps to tvdb eps https://raw.githubusercontent.com/ScudLee/anime-lists/master/anime-list-master.xml showing  anidbid="10971"
```
  <anime anidbid="10971" tvdbid="314031" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Chain Chronicle: Haecceitas no Hikari</name>
  </anime>
```
There should be a defaulttvdbseason of '0' and an offset of 8 since your serie is tvdb 314031 s00e09-20 (12 eps) which is absent from the mapping list, and instead map it to tvdb season 1...

I believe the agent work as designed.

You can use [tvdb-314031-s00e09] in the meantime which the scanner would have added to the serie title in tvdb2 mode had the offset been present and the defaulttvdbseason had been '0'

Please submit a pull request to ScudLee's AnimeList anime-list-master.xml file https://github.com/ScudLee/anime-lists/blob/master/anime-list-master.xml with the following changes:
```
  <anime anidbid="10971" tvdbid="314031" defaulttvdbseason="0" episodeoffset="8" tmdbid="69237" imdbid="">
    <name>Chain Chronicle: Haecceitas no Hikari</name>
  </anime>
```

**Comment by mweber03** [comment]
I disagree, the Scudlee mapping is correct because the series lines up perfectly with season 1 on TVDB.

https://www.thetvdb.com/?seasonid=673044&seriesid=314031&tab=season

The real problem is that the series folder specifies `anidb2-10971` but Hama is mapping it to `10747`.

**Comment by sven-7** [comment]
FYI - It seems that there are three mappings to TVDBID 314031 in ScudLee's file. 

```
  <anime anidbid="12291" tvdbid="314031" defaulttvdbseason="0" episodeoffset="8" tmdbid="415282,428294,428297" imdbid="">
    <name>Chain Chronicle (2016)</name>
  </anime>
```

```
 <anime anidbid="10747" tvdbid="314031" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Chain Chronicle: Short Animation</name>
  </anime>
```

```
  <anime anidbid="10971" tvdbid="314031" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Chain Chronicle: Haecceitas no Hikari</name>
  </anime>
```

**Comment by mweber03** [comment]
Correct, there are 3 different series that map to one TVDB id, which is the case for many series in the Scudlee list.

The Hama code looks to me like it tries to translate the TVDB id back into the AniDb id? IF this is the case, i think that is a bad idea because there are so many series in the Scudlee file that map to the same TVDB id.

Also, Hama was mapping my `10971` series correctly to season 1 a few weeks ago.

**Comment by ZeroQI** [comment]
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=10747 Anime: Chain Chronicle: Short Animation 8 episodes tvdb s00e01-08
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=12291 Anime: Chain Chronicle (2016)/Chain Chronicle: The Light of Haecceitas tvdbs00e09-20
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=10971 Anime:Chain Chronicle: Haecceitas no Hikari tvdb s01e01-12

To show a single series grouped with TVDB numbering in Plex the series need to have the same guid assigned which will be "tvdb-314031" in this case. anidb 10971 is mapped to guid [tvdb-314031], and back to anidbid 10747 for season 1 and it should load all 2 or 3 xmls, my bad...
- Will code so if tvdb used or anidb2 used or multiple seasons used we need to load multiple anidbids in a table with the mappings both ways and i need to check if eps are presents. That will be a pain to code

**Comment by mweber03** [comment]
For this specific case

**Comment by mweber03** [comment]
Yeah I tried to come up with a good way to translate TVDB ids back into AniDB ids once, but there are a lot of weird edge cases that arise.

**Comment by ZeroQI** [comment]
In AnimeLists.py got 2 functions but it's mainly one anidbid concerned and used defaulttvdbseason for multiple seasons but doesn't really work 100% as you saw:
- def anidb_ep(mappingList, season, episode):
- def tvdb_ep(mappingList, season, episode):

Notes:
- converted GetAniDBTVDBMap to load local 'anime-list-corrections.xml' from agent data folders only to avoid checking locally for every series. code simpler, less variables already
- Never considered reverse tvdb to anidb mapping with multiple anidbids more accurately but have to now that i have a good series example to test against, thanks for that...  

It is easier to build a proper dict while iterating so i can:
- convert tvdb ep numbering to anidb across multiple anidbids that work with the engine
- Load the anidb xml if at least one of the concerned episodes is loaded in Plex
- maybe reduce the variables used

**Comment by ZeroQI** [comment]
simplified AnimeLists.py already, on this morning release, will try to modify mapping so the engine to update in common.py still works

**Comment by ZeroQI** [comment]
weird, i reproduced the folder naming, and it loads already the right anidbid albeit a single anidbid for season 1 on my current code so any other anidb season would not load so still need to implement the fix. so fat building the new array seem good, but need to use it everywhere the old MappingList was used...

**Comment by ZeroQI** [comment]
Updates:
- animelists.py tvdb to anidb numbering function now returns the anidbid, collection support for all series sharing the same tvdbid (if tvdbid or multiple seasons)
- anidb.py build a list of xmls to download by checking which anidbids the files present belong to
Remaining:
- anidb.py update AniDB_dict so it uses tvdb numbering (if tvdbid or multiple seasons)
- common.py do not translate anidb numbering to tvdb numbering, done at source level
Unsure:
- common.py do not translate tvdb numbering to anidb numbering, done at source level
- tvdb.py need to translate to anidb numbering not in the engine like currently done
-

**Comment by ZeroQI** [comment]
Please test and check episode mappings are as they should, report ANY errors as i change little code but changed completely how it use to behave so could have missed something...

**Comment by mweber03** [comment]
Tested with the `Chain Chronicle: Haecceitas no Hikari [anidb-10971]` which seems to be mapping correctly now.

**Comment by ZeroQI** [comment]
Excellent. If you see other issues please let me know
