### ISSUE TITLE
Can't download posters of any anime

### ISSUE THREAD

**Issue by Issam2204** [ZeroQI/Hama.bundle#18]
Hello! Thank you for the hard work!

I've an issue with the bundle: I can't download the posters or any images of any anime:

![plex no posters hama](https://cloud.githubusercontent.com/assets/8282518/10262214/2a623be2-69be-11e5-9f27-ec6187688304.png)

I've read the README and installed the bundle where it should, and checked if all folders are present. I'm using the latest version of Plex on Ubuntu Server 14.04.3 x64.

These are my settings in the Library:

![plex](https://cloud.githubusercontent.com/assets/8282518/10262182/f2be7e9a-69bc-11e5-8582-7f93f8a02acf.png)

![screenshot from 2015-10-03 10 52 49](https://cloud.githubusercontent.com/assets/8282518/10262185/046f397c-69bd-11e5-985a-4e817c8a3c76.png)

Also, I followed this guide to install everything bacause the readme wasn't very clear to me: https://forums.freenas.org/index.php?threads/tutorial-plex-plugin-http-anidb-metadata-agent-hama-installation-instructions.36469/

Finally, this is the agent log (/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.hama.log): http://justpaste.it/o49m

If you need any other log please let me know.

Thank you again!

**Comment by ZeroQI** [comment]
I would rather you say what was unclear in the readme....
Agent log contain no matching attempt so useless
You most likelly are missing folders in agent data folders

**Comment by Issam2204** [comment]
Thank you for your answer ZeroQI!

I deleted the files and remade the procedure. Unfortunately, this time I can't even see the HamaTV agent. I'm gonna show you how I did:

1. Go here and download the latest version of the bundle: https://forums.plex.tv/discussion/77636/release-http-anidb-metadata-agent-hama/p1

2. Download the latest versions of the following components: 
https://github.com/ZeroQI/Absolute-Series-Scanner
https://github.com/ZeroQI/Hama.bundle

3. Extract everything.

4. Substitute the two component downloaded from GitHub with the ones downloaded from Plex.

5. Be careful to create the folder "episodes" (as it is missing) in com.plexapp.agents.hama/DataItems/TVDB/

6. Go to the server and copy each element in the correct Plex folder. For this I use rsync:

    sudo rsync -av com.plexapp.agents.hama /var/lib/plexmediaserver/Library/Application\     Support/Plex\ Media\ Server/Plug-in\ Support/Data/

    sudo rsync -av Absolute\ Series\ Scanner.py /var/lib/plexmediaserver/Library/Application\     Support/Plex\ Media\ Server/Scanners/Series/

    sudo rsync -av Hama.bundle /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\     Server/Plug-ins/

7. Restart the server with:

    sudo service plexmediaserver restart

What do I do wrong?

Thank you!

**Comment by ZeroQI** [comment]
Can't see the agent so agent folder wrong, possibly added folders since
data folder issue would cause no posters

**Comment by Issam2204** [comment]
I've repeated the procedure 4 times. I still can't see the Hama agent. This is very weird.

Please, take a look at the folders' location. This should be correct, right?

![hama bundle folders](https://cloud.githubusercontent.com/assets/8282518/10283422/d72c50c0-6b7f-11e5-9b35-640f9c5610cc.png)

Thank you!

**Comment by ZeroQI** [comment]
What is in Hama.bundle?
On 5 Oct 2015 15:41, "Issam Chajii" <notifications@github.com> wrote:
>
> I've repeated the procedure 4 times. I still can't see the Hama agent.
This is very weird.
>
> Please, take a look at the folders' location. This should be correct,
right?

**Comment by Issam2204** [comment]
Thank you for the answer!

Yes, it is very weird.

Here is the content of Hama.bundle:

![hama bundle content](https://cloud.githubusercontent.com/assets/8282518/10288156/6a023db2-6b97-11e5-9bd2-42415e01b5d4.png)

**Comment by ZeroQI** [comment]
Folder location ok so must be rights issue. Data folders missing would not
make agent not start or not being detected...

**Comment by Issam2204** [comment]
I gave:

    sudo chmod 777 Hama.bundle

I also did it to all the others. Still not present:

![plex missing hama agent](https://cloud.githubusercontent.com/assets/8282518/10288452/4553a6a2-6b99-11e5-82a4-293f035e65b2.png)

**Comment by ZeroQI** [comment]
Please tey adding another agent as i believe it is not an agent issue but a
plex or os issue

**Comment by Issam2204** [comment]
I think you are right. It doesn't make sense that it works once and then it doesn't. 

Thank you for your help. I'll try to figure it out and see what it's wrong with it.

**Comment by 9a3eedi** [comment]
Hi, I'm having EXACTLY the same issues described here. My posters weren't appearing, so I thought the data folders weren't installed correctly, so I recopied everything, and now the agent doesn't show up!

I was just wondering if someone managed to figure this out by now. I'm running Plex on a Synology server if it makes a difference.

**Comment by 9a3eedi** [comment]
Ok I fixed it. I performed a chown -R plex:users and a  chmod -R 700 and that fixed everything. This is strictly speaking a Synology-specific fix. I don't think normal systems use these kinds of permissions.

**Comment by ZeroQI** [comment]
thanks for precising the commands used, added back to the agent readme resolutions. Using synology box as well

**Comment by supermonteiro** [comment]
Im having the same problem on windows 10, any ideas?

**Comment by ZeroQI** [comment]
agent data folders missing.
use https://github.com/ZeroQI/Hama.bundle/releases/download/Beta/Hama.bundle.2017-06-30.00h11.zip

**Comment by supermonteiro** [comment]
ty, it works now!
