### ISSUE TITLE
Beta - Wotaku ni Koi wa Muzukashii [tvdb-341425] - Metadata Issues

### ISSUE THREAD

**Issue by DJScias** [ZeroQI/Hama.bundle#183]
Hello there,

Seem to be having issues in gathering the second episode's metadata, even though it does exist on TVDB. It's just called "Episode 2" without summary:
![image](https://user-images.githubusercontent.com/439655/39078751-39fd4fb4-450e-11e8-929c-601e0b5ea583.png)

The link to it in TVDB: https://www.thetvdb.com/?tab=episode&seriesid=341425&seasonid=747812&id=6644095&lid=7

`Wotaku ni Koi wa Muzukashii [tvdb-341425].agent-update` is here: https://pastebin.com/VvLTtHB9

Nothing too pressing, but since it's an issue I figured I'd report it just to figure out where the cause is located.

**Comment by ZeroQI** [comment]
This is weird
```
AnimeLists.GetMetadata() - source 'tvdb', id: '341425' not found in file
anidbTvdbMapping() - mappingList: {}
```
Looking at mapping file there is a match...
Please open "Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/AnimeLists/anime-list-master.xml" and search for '341425', check the file last modification/creation date too.
```
  <anime anidbid="13293" tvdbid="341425" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Otaku ni Koi wa Muzukashii</name>
```

Sould still work...
TheTVDB meta indicate summary for ep 2 missing
```
common.LoadFile() - CacheTime: 'Thu Apr 19 04:46:26 2018', Limit: 'Fri Apr 27 02:42:26 2018', url: 'http://thetvdb.plexapp.com/api/A27AD9BE0DA63333/series/341425/all/en.xml', Filename: 'TheTVDB\xml\341425.xml' loaded from cache
TheTVDB.GetMetadata() - TVDB - Episodes without Summary: ['s1e2', 's1e3', 's1e4', 's1e5', 's1e6', 's1e7', 's1e8', 's1e9', 's1e10', 's1e11']
```
Please open "Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/TheTVDB\xml\341425.xml" to check if ep 2 indeed has summary and file creation/modification date

Trying to reproduce but have to fix my current code as am workign on TheTVDB API v2 (json)

**Comment by DJScias** [comment]
Hello,

In regards to:
`
Looking at mapping file there is a match...
Please open "Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/AnimeLists/anime-list-master.xml" and search for '341425', check the file last modification/creation date too.
`
Looking for `341425` nets me zero results:
![image](https://user-images.githubusercontent.com/439655/39098336-80824726-4669-11e8-813f-6abd470b507f.png)

`"Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/TheTVDB\xml\341425.xml"` has the following: https://pastebin.com/WrtMZLN6

At an early glance it seems episode 2 has nothing specific in there.
![image](https://user-images.githubusercontent.com/439655/39098362-fbd05dfa-4669-11e8-9a8e-690b37331ef2.png)

**Comment by ZeroQI** [comment]
It looks to me you have the metadata present in your cached files which are both not up to date since you should see the tvdbid and the ep 2 metadata in the files...
Which date were they created at both at file system level? need to check they are updating every 2 weeks as it was reported in the past some cache issue and i thought it was resolved...

**Comment by sven-7** [comment]
I’ve found the AnimeLists cache to be a little long. When new seasons start, the ScudLee updates a few times per week.

**Comment by ZeroQI** [comment]
so should i change the cache to once a week instead or should i lower that?

**Comment by ZeroQI** [comment]
6 days sounds reasonable

**Comment by DJScias** [comment]
So the issue is honestly just that for running/airing animes, the metadata will not always load as there's a weekly check and it may or may not fall within the same day, or days thereafter, as it releases.

Perhaps a disclaimer somewhere (it may already exists, haven't explicitly looked in all files) that states that currently running/airing anime may take up to x days before the latest episode metadata is taken in by the agent?

It's up to you how to spin it, of course. But I wouldn't have made the issue if I knew it was because the check is done every so many days. Regardless, you can consider the 'issue' fixed!

Thank you for the help. :)

**Comment by ZeroQI** [comment]
switched to 6 days caching, should avoid issues
