### ISSUE TITLE
tvdb3 season cover issue.

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#190]
Using Bleach [tvdb3-74796] folder without any subfolders inside (just episodes). 

I expected to see each season using their season cover that tvdb provides. Instead I just see the main cover repeated on every season like this:

![image](https://user-images.githubusercontent.com/14930057/39674031-d5d27726-513d-11e8-8e84-2aa555dc723b.png)

The first two seasons are the result of my attempt of trying to choose a cover downloaded by hama, for example season 2 I tried to choose the only cover downloaded by hama, but after selecting it the cover disappears:

![image](https://user-images.githubusercontent.com/14930057/39674059-366c4a1c-513e-11e8-82fa-f2b9e0bc8010.png)

Last point every episode doesn't have their names on. So it seems tvdb3 mode isn't working for the most part.

**Comment by ZeroQI** [comment]
Will edit this post soon
- season posters broken, found fix
- ep in tvdb3 mode no info: found fix
- only 100 eps info downloaded: when will it stop!!!

**Comment by KurtzPT** [comment]
The fix worked!

![image](https://user-images.githubusercontent.com/14930057/39678755-2c92d2bc-518a-11e8-93b8-35da133c18f7.png)

**Comment by ZeroQI** [comment]
I should hope so, passed the whole afternoon until the evening :p
Thanks for responding quickly and reporting, solved so many bugs, and now it even only loads tvdb info for eps when file presents, so thanks too

**Comment by KurtzPT** [comment]
Using the latest version, the season 1 cover is repeated for all seasons now:

![image](https://user-images.githubusercontent.com/14930057/40279887-761f0802-5c42-11e8-8a81-0eca4fea7f97.png)

instead of:

https://user-images.githubusercontent.com/14930057/39678755-2c92d2bc-518a-11e8-93b8-35da133c18f7.png

**Comment by ZeroQI** [comment]
Normally fixed but the poster may not change back, might need to remove the serie, scan the library, then put it back
Please test and close if resolved

**Comment by KurtzPT** [comment]
Seems fixed.
