### ISSUE TITLE
Beta - Question

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#193]
Hi @ZeroQI -- I noticed that under /DataItems/ several new folders have appeared for:

```
/fanart
/posters
/seasons
```

Is that right?  Here is a screenshot:

<img width="209" alt="screen shot 2018-05-08 at 4 34 59 pm" src="https://user-images.githubusercontent.com/18091557/39781638-c654bb5a-52dd-11e8-9ace-92a6d446cef7.png">

**Comment by ZeroQI** [comment]
Not normal, move them to TheTVDB folder after updating to the next version to come

Changes pending included in next version
- fixed TheTVDB not putting images in TheTVDB subfolder
- fixed animetitles.xml.tgz download at every plex restart leading to ban with anidb.net not responding
- fixing SSLV3_ALERT_HANDSHAKE_FAILURE for linux/OSX with centralised function (ssl and urllib2 for now)

Bugs remaining
- tvdb4 season posters not falling back to standard posters
- AniDB season mapped to season >1 get TheTVDB metadata season 1
