### ISSUE TITLE
Beta - Ep title formatting issue

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#198]
Seeing episode titles having capitalized letters after there is an apostrophe in a title. 

<img width="296" alt="screen shot 2018-05-14 at 8 14 13 am" src="https://user-images.githubusercontent.com/18091557/39997033-768c3bae-574f-11e8-854f-f4813be19f89.png">

Doesn't seem to be very much info in the logs either. I haven't followed the changes/issues over the last few days. I will take a look at the changes.

[Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/2000597/Logs.zip)

**Comment by ZeroQI** [comment]
Super weird
Probably because TheTVDB is unavailable, then other titles seep through
I don't have the end summary in the agent logs though...
Once TheTVDB work back, will be trickier to get logs as it will probably work...

**Comment by ZeroQI** [comment]
Saiki Kusuo no Sainan (2018) [anidb-12691]/s02e17.mp4
`[1] title                          Sources: (TheTVDB), AniDB                                              Inside: '['TheTVDB']'  Value: 'He's Back! The Brother's Five Directives + Let's Go to the Zoo! + The Disastrous..'`
works for me

**Comment by sven-7** [comment]
That one fixed on a refresh.  One Piece has not.

**Comment by ZeroQI** [comment]
I couldn't see the issue, but one piece doesn't load ep metadata passed a certain point. have to solve that issue first. I keep you posted

**Comment by ZeroQI** [comment]
Please test latest beta branch code should be solved
