### ISSUE TITLE
[BETA] Weird episode images. #197 - Reopen

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#200]
Since I can't reopen issues closed by other users, I'll create a new one. Hama updated to last version.

Anime Folder: **Young Black Jack [anidb-11226]**

All episodes have the exact same type or bugged image like issue #197 

**Logs:**

[logs.zip](https://github.com/ZeroQI/Hama.bundle/files/2001756/logs.zip)

**NOTES:**

This anime doesn't have episode images on TVDB, here it is the TVDB URL:
https://www.thetvdb.com/series/young-black-jack/seasons/1

**Comment by ZeroQI** [comment]
Please create 1 ticket per bug like you did, this way:
-  you can close and reopen as you like
- i can put the link when uploading fix to have a link to it in the bug report

I am not assigning any thumbnail.
It seem like either:
- it generate it from the video but wrongly
- it generate it from the poster wrongly
I am sorry but i cannot solve as the agent never gave a screenshot in the first place.
Latest PMS seem to have updated quite few things, may have resolved or introduced new issues...

**Comment by KurtzPT** [comment]
Well, I would use the old ticket, but since you closed #197, I can't reopen myself. 

I'll try to test some more stuff and see what's happening.

**Comment by ZeroQI** [comment]
Please. Also see if changing the series poster changes something, i get the feeling it might.

**Comment by KurtzPT** [comment]
Well I can safely say it's not a problem with hama, I changed the agent to TheTVDB from plex and the same thing happens. Using a total different episode from a random show it generates the thumbnail correctly.

So either it's a problem with plex or the files I have. Closing this.
