### ISSUE TITLE
Beta - Title Sort Issue

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#209]
Not sure if this is related to #208, but I'm having a lot of shows mis-sorted now. 

Example:  The Ambition of Oda Nobuna is being sorted correctly, but the display title is Oda Nobuna's Ambition. 

<img width="720" alt="screen shot 2018-05-29 at 12 09 35 pm" src="https://user-images.githubusercontent.com/18091557/40671284-73680e4e-6339-11e8-9788-de94a5b24231.png">

Logs: [Oda Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/2049162/Oda.Logs.zip)

```
-------------------------------------------------------------------------------------------------------------------------------------------------------------
AniDB.GetMetadata() - AniDBid: 8869, AniDBids present on disk: ['8869'], AniDBids list: ['8869']
Fetching 'https://api.thetvdb.com/episodes/5000363' from the HTTP cache
common.SaveFile() - CachePath: 'C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems', file: 'TheTVDB/json/280330\episode_5000363_en.json', directory present
Requesting 'https://api.thetvdb.com/episodes/5943798'
Fetching 'https://api.thetvdb.com/episodes/5943798' from the HTTP cache
common.SaveFile() - CachePath: 'C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems', file: 'TheTVDB/json/308030\episode_5943798_en.json', directory present
Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=8869'
common.SaveFile() - CachePath: 'C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems', file: 'AniDB\xml\8869.xml', directory present
AniDBid: 8869, url: http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=8869----------------------------------------------
'title': The Ambition of Oda Nobuna, 'title_sort': Ambition of Oda Nobuna, original_title: Oda Nobuna no Yabou
'originally_available_at': '2012-07-09'
'summary' empty: 'False'
'rating': '5.78'
Requesting 'https://api.thetvdb.com/episodes/5000364'
'genre' (10/54 above 400 weight): ['Swordplay', 'Past', 'Alternative past', 'Japan', 'Sengoku period', 'Action', 'Comedy', 'Romance', 'Harem', 'War']
'collection' AniDBid is not part of any collection, related_anime_list: '{}'
Roles (creators tag): {'producers': ['Suzuki Masashi'], 'directors': ['Kumazawa Yuuji', 'Miyamae Shin`ichi', 'Yoshikawa Shin`ichi', 'Takashina Yuka'], 'writers': ['Kasuga Mikage']}
Season: 0 Episodes: ['1', '2', '101', '151', '152', '153', '154', '201', '202', '203', '204', '205', '206', '207', '208', '209'] not on disk
Season: 1 Episodes: [] not on disk
AniDB.get_metadata() - Duration: 300, numEpisodes: 12, average duration: 25
AniDB.get_metadata() - ANNid: '13761', MALid: '11933', xml loaded: 'True'
-------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by ZeroQI** [comment]
title: (TheTVDB), AniDB           Inside: '['MyAnimeList', 'TheTVDB', 'AniDB']'  Value: 'Amagi Brilliant Park'
title_sort: TheTVDB, (AniDB)   Inside: '['AniDB']'                                             Value: 'Amagi Brilliant Park'
AniDB: 'title': The Ambition of Oda Nobuna, 'title_sort': Ambition of Oda Nobuna, original_title: Oda Nobuna no Yabou
```
	<anime aid="10399">
		<title type="main" xml:lang="x-jat">Amagi Brilliant Park</title>
		<title type="official" xml:lang="en">Amagi Brilliant Park</title>
		<title type="official" xml:lang="ja">甘城ブリリアントパーク</title>
		<title type="official" xml:lang="ko">아마기 브릴리언트 파크</title>
		<title type="official" xml:lang="pl">Cudowny Park Amagi</title>
		<title type="official" xml:lang="zh-Hans">甘城光辉游乐园</title>
		<title type="short" xml:lang="ja">甘ブリ</title>
		<title type="short" xml:lang="ko">아마기</title>
		<title type="short" xml:lang="x-jat">amaburi</title>
	</anime>
```
TheTVDB give no sort title and searched en titles only...
http://thetvdb.com/api/A27AD9BE0DA63333/series/280330/all/en.xml
`<SeriesName>Amagi Brilliant Park</SeriesName>`

What should title_sort equates to? AniDB main title?
Selected main title without "the", "a", "an"?

**Comment by sven-7** [comment]
Hmm. I tend to sort my titles by TheTVDB because they are more consistent than AniDB when it comes to main title. Does theTVDB have no title sort?

This is the show I was referring to:  http://thetvdb.com/api/A27AD9BE0DA63333/series/259643/all/en.xml

I think the important thing for me is to have it sort by the same title it's displaying, with the exception of 'a', 'an', and 'the'. 

DIdn't HAMA have an option to sort with or without 'the', 'a', and 'an' up until recently?  I don't see it anymore in the preferences. I believe this was in the preferences: ` <SortTitlePrefixRemoval>true</SortTitlePrefixRemoval>`

**Comment by ZeroQI** [comment]
It used to be in the xml version BUT the title was selected per source and in each source per language
`SaveDict( common.SortTitle(GetXml(xml, 'Series/SeriesName'), "en" if lang ==Locale.Language.English else lang), TheTVDB_dict, 'title_sort')`
    
Now that it's per language first as logic dictates (otherwise primary languuage titles in secondary source skipped in favor of lowest priority language in primary source )

Therefore the engine needs changing, since the source doesn't know its sort title because while it takes sourced sequentially it use the language index to decide as a trick and process all sources...
The same priority in title and title sort would end up with different sources

Need something like the below on title update, and 'title_sort' evaluated after 'title' but then the language isn't known...
`MetaSources[source]['title_sort'] =  common.SortTitle(title)`

Should have it fixed this evening

**Comment by ZeroQI** [comment]
Was tricky but solved language not indicated in AniDB thanks to you.
Please test and report and close if resolved

**Comment by sven-7** [comment]
I also have TheTVDB has the first priority for title and sort title.

**Comment by ZeroQI** [comment]
So series and language priority 'en' and title and title_sort: 'TheTVDB, AniDB'
used that and reproduced the issue
```
source: TheTVDB, title: The Seven Deadly Sins, title_sort: Seven Deadly Sins, languages: ['en'], language_rank: 0, language: en
source: AniDB, title: The Seven Deadly Sins, title_sort: Seven Deadly Sins, languages: ['en'], language_rank: 0, language: en
[=] title                          Sources: TheTVDB, (AniDB)                                              Inside: '['MyAnimeList', 'TheTVDB', 'AniDB']'  Value: 'The Seven Deadly Sins'
[=] title_sort                     Sources: (TheTVDB), AniDB                                              Inside: '['TheTVDB']'  Value: 'Seven Deadly Sins'

```

**Comment by ZeroQI** [comment]
the title_sort is added during title check so if title_sort sources match title sources all good, if not sort_title not populated
Fixed at last, seems the last source from the loop was used to add metadata resulting in wrong title

Should work as expected now, and removed useless variables by making rank the index or unknown language index (len of languages) or unassigned (len of languages+1)

Please test and report and close if resolved
