### ISSUE TITLE
AttributeError: 'str' object has no attribute 'xpath'

### ISSUE THREAD

**Issue by xrsxj** [ZeroQI/Hama.bundle#210]
Been getting this for a couple of newly added series and it's refusing to pull any metadata.

```
 id: tvdb-344222, title: None, lang: en, force: True, movie: False
-------------------------------------------------------------------------------------------------------------------------------------------------------------
AnimeLists.GetMetadata() - tvdb_numbering: True
[+] AniDBid: 13426, TVDBid: 344222, defaulttvdbseason:  1, offset:   0, name: Uchuu Senkan Tiramisu
             -----          ------
             13426          344222
-------------------------------------------------------------------------------------------------------------------------------------------------------------
AniDB.GetMetadata() - AniDBid: 13426, AniDBids present on disk: ['13426'], AniDBids list: []
Fetching 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=13426' from the HTTP cache
Error decoding with simplejson, using demjson instead (this will cause a performance hit) - Expecting value: line 1 column 1 (char 0)
LoadFile() - returning string
Exception in the update function of agent named 'HamaTV', called with guid 'com.plexapp.agents.hama://tvdb-344222?lang=en' (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-4898d7d96/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 130, in update
    def update (self, metadata, media, lang, force ):  Update (metadata, media, lang, force,  False)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 108, in Update
    dict_AniDB, ANNid, MALid                                      =       AniDB.GetMetadata(media, movie, error_log,       source, AniDBid, TVDBid, AniDBMovieSets, mappingList)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/AniDB.py", line 266, in GetMetadata
    else:    missing_eps.append(numbering)
AttributeError: 'str' object has no attribute 'xpath'

Serializing to /config/Library/Application Support/Plex Media Server/Metadata/TV Shows/1/5ab74bedbbb98a83c7dd350a27a600f9dc3d87d.bundle/Contents/com.plexapp.agents.hama/Info.xml
Sending packed state data (104 bytes)
Response: [200] str, 16 bytes
Stopping plug-in
```

The Series are:
Uchuu Senkan Tiramisu
Tada-kun wa Koi o Shinai
Tachina-kan to Lie Angle
Steins Gate 0
Rokuhoudou Yotsuiro Biyori
Akkun to Kanojo
Beatless
Dorei-ku The Animation
Golden Kamuy
Gundam Build Divers
Isekai Izakaya: koto Aitheria no Izakaya Nobu
last Period: Owarinaki Rasen no Monogatari
Mahou Shoujo Site

Using anidb2.id file as my matching setting.

**Comment by xrsxj** [comment]
Actually that file doesn't exist, and i keep the plugin git synced with the beta branch every hour.  I recently did a fresh setup of Plex but copied the database only, as in deleted all the metadata and plug-in data.  Would that have caused this?

**Comment by ZeroQI** [comment]
AniDB banned since you pulled all meta possibly. That's one of the reason the cache is there...

**Comment by xrsxj** [comment]
That's what i thought too but it's been a week and other shows, brand new shows to my collection pull fine.  Just manually created the 13426.xml from the api link and it went through... no clue why didn't create it on it's own.  Any other possibilities then an API ban?

**Comment by ZeroQI** [comment]
It downloaded fine for me and other series download fine for you so you are not banned. 
it says it's a string so AniDB returned something which couldn't convert to xml
if no file saved bad cache saved by Plex or rare plex bug or AniDB message in received file just for you...

Only way to troubleshoot is to display the string before xpath and crash again.
printed too small files by default now so please update agent to beta branch latest and reproduce
If you cannot reproduce close the ticket next time there will be one more line before crash with the string received instead of the xml

**Comment by xrsxj** [comment]
2018-06-03 12:36:16,215 (7fd9f97fa700) :  INFO (common:338) - [!] File received too small (<64 bytes), file: "<error code="500">banned</error>"

I shouldn't second guess you, it looks like i was banned not sure how or why, i'll double check it tomorrow evening and see if it's still reporting the same but i'll close regardless, sorry man, much appreciated.

**Comment by ZeroQI** [comment]
So the series working were only because the cache was there....
Mu ha ha ha ha ha (evil laugh)

Well your feedback added much needed display of errors so is useful
I did add a fallback, not saving errors and load back from cache if issues so that cover most cases as you now know

And you can always do a donation as i am starting building a passive house and would prefer to use less of my money and more of yours ;)
Have a good week end

**Comment by xrsxj** [comment]
You gotta post your donation or patreon link then!

**Comment by ZeroQI** [comment]
I did put it in the scanner and agent beta branch read-me and Plex forum signature , and now in the agent master branch read-me. 

I think it's by far the most complex Plex agent but the best (apart from the occasional bug) anime agent, with excusive feature like anidb2 tvdb3 modes, and grouping folders which Plex own scanner doesn't support...

Donation link: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=S8CUKCX4CWBBG&lc=IE&item_name=ZeroQI&item_number=Absolute%20Series%20Scanner%20%2b%20Http%20AniDB%20Metadata%20Agent&currency_code=EUR&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted
