### ISSUE TITLE
Not in Plex but threshold exceded or thumbs/themes agent setting not selected

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#221]
Using last update, while adding new anime ( https://www.thetvdb.com/series/school-babysitters ), one of the ja posters did not get added/downloaded (  https://www.thetvdb.com/banners/posters/335235-2.jpg )

I have the "single poster" option unchecked, poster language setting is the following: "en, ja". Checking the log I see the following message: "Not in Plex but threshold exceded or thumbs/themes agent setting not selected". Why is that?

[Gakuen Babysitters [anidb-13023].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/2123007/Gakuen.Babysitters.anidb-13023.agent-update.log)

**Comment by ZeroQI** [comment]
removed option 'GetSingleOne' across the board as had too many posts about people leaving it ticked
Please update to latest and close if resolved

**Comment by KurtzPT** [comment]
Tried again and this time it downloaded every single poster on tvdb that matched my preferences.
