### ISSUE TITLE
Pull summary from forced database

### ISSUE THREAD

**Issue by rcdailey** [ZeroQI/Hama.bundle#223]
When I force a season folder to a specific database, such as anidb:

    Kizumonogatari [anidb-8357]

I expect the 'summary' field to be populated from that same forced database. I want the default priority configuration for 'summary' to be ignored when forcing happens. Instead, the description is pulled from TheTVDB (because 'summary' for me is set to `TheTVDB, AniDB` in the priority configuration).

**Comment by ZeroQI** [comment]
All series are AniDB matched unless a season 2 or more is present
That's behave exactly as expected and the way you want would require a rewrite, checking series forder name for force id or content, an agent setting to allow that optionnaly, then TheTVDB series with forced ID will not have AniDB titles so series like  'Asobi ni Iku yo!' will become ''Bombshells from the sky' if no other foreign language present...
would be easier to do another anidbx and tvdbx mode to diregards the other metadata provider

This is a feature request, It will wait as i have quite few changes in ASS and YouTube-Agent at the moment.

**Comment by rcdailey** [comment]
To be clear, this request is specifically for *summary* and only that field. Title would continue to work today, so the "Bombshells from the sky" concern is moot here. As to "require a rewrite", I find that difficult to believe but I have not looked at the code so you know better than I do at this point.

In theory my request is simple: If series is forced to anidb, then force 'anidb' to be top priority for "summary" field only. No other fields would be affected.

You could of course do extra work to make this more generic. Adding options, as you indicated, would probably be necessary. And you might be able to generalize this by having a new edit field called "Force override top priority: ", where you give a list of existing fields that will have their #1 priority overridden by the forced database.

I know you have a full plate, so no pressure. Just throwing something I think that would be useful into your backlog. I appreciate you considering it!!

**Comment by ZeroQI** [comment]
only one field is doable i thought it applied to all values.
Queuing that
