### ISSUE TITLE
Ajin 2 (2016) [anidb-12111] Wrong thumbs and missing most episode information.

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#227]
**Folder Name:** Ajin 2 (2016) [anidb-12111]
**TVDB Link:** https://www.thetvdb.com/series/ajin/seasons/2

**Problem:** Hama doesn't download the correct thumbs from TVDB and doesn't show any information from the episodes.
![image](https://user-images.githubusercontent.com/14930057/41971599-ee179176-7a06-11e8-93e0-3de9457996f0.png)

**What it should appear on episode one:**
![image](https://user-images.githubusercontent.com/14930057/41971875-df5f8a70-7a07-11e8-9fc5-b11cb00fd7a3.png)
**What it appears using last Hama version:**
![image](https://user-images.githubusercontent.com/14930057/41971907-fafbdcb6-7a07-11e8-927a-a6fc4193841c.png)

**Logs:** (Notice that logs are all messed up again after I redid a full new library scan)
[Ajin 2 (2016) [anidb-12111].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/2141012/Ajin.2.2016.anidb-12111.agent-update.log)

I'm not sure about this one, All thumbs are wrong, all episodes are missing their description too.

**Comment by ZeroQI** [comment]
No metadata at all came from TheTVDB for episodes according to your logs latest output at the bottom,, no overview, no thumbs. Latest line is
`common.LoadFile() - file cached - CacheTime: 'Tue Jun 26 14:10:13 2018', Limit: 'Thu Jun 28 03:59:17 2018', url: 'https://api.thetvdb.com/series/300835/episodes?page=1', Filename: 'TheTVDB/json/300835/episodes_page1_en.json' file_valid: 'True'`
yeah, normally you refresh the metadata manually, as when you run a full metadata update, you have 2 concurrent threads and it messes up logs quite a bit...

Will reproduce and see if TheTVDB does generate episodes metadata.

**Comment by ZeroQI** [comment]
Each time i publish a fix quoting a bug report it closes it
Thnaks for the report, it did not map tvdb back to anidb so no metadat for eps at all
This is resolved now normally thanks you, Please confirm and close

**Comment by KurtzPT** [comment]
Confirmed, it's fixed.
