### ISSUE TITLE
Error Multiple Versions of Anime 

### ISSUE THREAD

**Issue by ZapGitHub** [ZeroQI/Hama.bundle#228]
Hi, when I have two versions of an anime (e.g. different resolutions etc.) and I "match" them as the same anime with Hama it correctly matches them then groups under one poster on Plex. Then each episode of the anime will show two different versions pointing to the two different files; perfect. But when I try to play any of the episodes I receive the following error: 

Playback Error: 
Please check that the file exists and the necessary drive is mounted.

When viewing "Get Info" for the episodes it shows that the files are "Unavailable" 
This only happens when using the Absolute Series Scanner and "matching" as the same anime.

Couldn't find anything about this searching here. Any help would be much appreciated…Thanks.

**Comment by ZeroQI** [comment]
@ZapGitHub does the work until you match to the same series?
Does getinfo show the fullpath or just the filename?
I need both folders scanner logs located in agent data folders (see readme) so I reproduce your setup exactly as it may be OS related

**Comment by ZeroQI** [comment]
If files are unavailable, most likely added wrong by the Absolute Series Scanner...
Closing this, as scanner related and no reply. Please reply back if issue persists after updating ASS scanner and re-scan
