### ISSUE TITLE
Nvidia shield TV (oreo -> external hdd as internal disk space)

### ISSUE THREAD

**Issue by whinette** [ZeroQI/Hama.bundle#230]
Hello,

With the release of Oreo Nvidia shield tv is finally able to expose com.plexapp.mediaserver.smb without being root.
I gave it a new chance.

ASS works perfectly (or so it seems) but Hama has some rights issues. TvDB agent does not have any problems.

Here are the logs (lib name is `test`) with the same structure / settings I use on my other plexserver.
Started server -> created library -> waited for scan and metadata matching to finish -> retried to automatch with hama -> tried to automatch with tvdb (success).

Thanks!

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/2156786/com.plexapp.agents.hama.log)
[com.plexapp.system.log](https://github.com/ZeroQI/Hama.bundle/files/2156789/com.plexapp.system.log)
[Ano Hi Mita Hana no Namae o Bokutachi wa Mada Shiranai.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/2156794/Ano.Hi.Mita.Hana.no.Namae.o.Bokutachi.wa.Mada.Shiranai.filelist.log)
[Ano Hi Mita Hana no Namae o Bokutachi wa Mada Shiranai.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/2156795/Ano.Hi.Mita.Hana.no.Namae.o.Bokutachi.wa.Mada.Shiranai.scanner.log)

There are no files for agent-search.log and agent-update.log

**Comment by longhim** [comment]
I can confirm this - though I'm trying ASS+Hama for the first time so I spent all weekend thinking it was my set-up. Also using Nvidia Shield TV on Oreo; when moved to adopted storage, Plex Media Server files are located at:

- /storage/emulated/0/Android/data/com.plexapp.mediaserver.smb/Plex Media Server **(Plug-ins, Scanners, Plug-in Support folders etc.)**
- /sdcard/Plex Media Server/Logs **(Logs - X-Plex-Token.id file with token inside was placed here, but isn't read for whatever reason. Maybe I have the format wrong)**
- "/data/data/com.plexapp.mediaserver.smb/ **(Original, non-user writable location - Resources folder still seems to be referenced here)**

To elaborate, ASS seems to work, but Hama is unable to match at all. All manual attempts return "No Matches Found". Switching to TvDB agent works.

Here's a second set of logs. Library name is 

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/2156951/com.plexapp.agents.hama.log)
[com.plexapp.system.log](https://github.com/ZeroQI/Hama.bundle/files/2156950/com.plexapp.system.log)
[_root_.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/2156948/_root_.filelist.log)
[_root_.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/2156949/_root_.scanner.log)
[Acchi Kocchi.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/2156946/Acchi.Kocchi.filelist.log)
[Acchi Kocchi.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/2156947/Acchi.Kocchi.scanner.log)

Ditto on agent-search.log and agent-update.log. Thank you for any light you can shed on this!

**Comment by ZeroQI** [comment]
I cannot reproduce but you are the second person with that error.
Wraped in a try box and specified encoding. Please test and report by attaching new com.plexapp.agents.hama.log

**Comment by longhim** [comment]
Confirming updated common.py works - match successful. You are magic, sir

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/2157027/com.plexapp.agents.hama.log)

Also solved the token issue - I was indeed placing the X-Plex-Token.id file in Plex Media Server/Logs and not in the parent directory itself.

**Comment by ZeroQI** [comment]
When it cannot read the library file it tries getting the root folder from the scanner log, an error popped up but now contained
Also error in validateprefs but contained so prob OS related:
`Error :bad argument type for built-in operation, filename: /storage/emulated/0/Android/data/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Hama.bundle/Contents/DefaultPrefs.json`

@whinette Ravi que ma correction marches pour toi.
@longhim Please confirm it is solved for you as well.
