### ISSUE TITLE
FutureWarning: The behavior of this method will change in future versions

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#231]
Just noticed these warnings on Plex running service:

> Jul 06 15:54:50 sh[19837]: AnimeLists:27: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
Jul 06 15:54:50 sh[19837]: AnimeLists:14: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
Jul 06 15:54:50 sh[19837]: AnimeLists:16: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
Jul 06 15:54:50 sh[19837]: AnimeLists:17: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
Jul 06 15:54:51 sh[19837]: AniDB:307: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
Jul 06 15:54:51 sh[19837]: AnimeLists:41: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.

**Comment by ZeroQI** [comment]
if obj is not None test whether the object is not None.
if obj tests whether bool(obj) is True. 
- There are many objects which are not None but for which bool(obj) is False: for instance, an empty list, an empty dict, an empty set, an empty string. . .

Thats just a warning. It shouldn't affect anything. too many corrections needed as well to fix that.
Will do when broken
