### ISSUE TITLE
tvdb4 crash

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#234]
Refreshing metadata of One Piece [tvdb4-81797]

> [=] original_title                 Sources: (AniDB),TheTVDB                                               Inside: '['TheTVDB', 'AniDB']'  Value: 'One Piece'
metadata.seasons[ 1]--------------------------------------------------------------------------------------------------------------------------------------
[!] field: "summary" not in meta_root, source: "AniDB"
Exception in the update function of agent named 'HamaTV', called with guid 'com.plexapp.agents.hama://tvdb4-81797?lang=en' (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-20455f518/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 132, in update
    def update (self, metadata, media, lang, force ):  Update (metadata, media, lang, force,  False)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 124, in Update
    'TheMovieDb': dict_TheMovieDb, 'TVTunes': dict_TVTunes, 'tvdb4': dict_tvdb4, 'OMDb': dict_OMDb, 'FanartTV': dict_FanartTV}, mappingList)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/common.py", line 690, in UpdateMeta
    elif not Dict(count, field) and Prefs[field]!="None" and source_list:  Log.Info("[#] {field:<29}  Sources: {sources:<60}  Inside: {source_list}".format(field=field, sources=Prefs[field], source_list=source_list))
AttributeError: 'str' object has no attribute 'keys'

Also by some reason cannot download tvdb4.posters (even if the link seems working):

> common.GetMetadata() - tvdb4 mode
common.GetMetadata() - No 'tvdb4.posters.xml' file detected locally
Requesting 'http://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml'
Error opening URL 'http://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml'
common.LoadFile() - issue loading url: 'http://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml', filename: 'tvdb4.posters.xml', Exception: 'HTTP Error 404: Not Found'
LoadFile() - not xml nor json: None

**Comment by ZeroQI** [comment]
@KurtzPT Thanks for the precise bug report.
- didn't provide Dict(...) with default={}
- was using thetvdb headers to download xml resulting in 404 which shouldn't have...
Reproduced and fixed bith. please confirm and close if resolved
