### ISSUE TITLE
Missing Episodes Log not generating

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#237]
Hi there. 

I had not seen the missing episode log pop up in a while, so I ran a test with a series I didn't have before.  Nothing generated while running it (but I do see in the logs that it notes several were missing).  Here are the logs.

[Persona4 Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/2195665/Persona4.Logs.zip)

**Comment by ZeroQI** [comment]
@sven-7 I think you are the only one using this function...

There was the old and new missing episode list cohabiting in the AniDB.py file. This series use AniDB numbering
- Season: 0 Episodes: ['101', '102', '103', '151', '152', '153', '201'] not on disk
- Season: 1 Episodes: ['7', '8', '9', '10', '11', '12'] not on disk

Please test fix and report

According to you, shall i add scrobbler support (Trakt) ?
Currently, Trakt support only TheTVDB IDs and i could make it work for AniDB series? 
Are loads of people are using it according to you?

**Comment by sven-7** [comment]
[_Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/2197162/_Logs.zip)

It is such a useful log! I find myself missing things and this helps point them out. The log generated this time, but a few odd things happened. 

- Some of the TVDB mode shows like Fairy Tail or Bleach are in this. 
- Many are showing up even though there are no missing. 
- Black Clover, Baki, and Banana Fish (as an example) are showing up as missing, but they have mot aired yet. I believe in the previous HAMA anything on toddy's date or after for “aired date” was ignored.


I do not use trakt or know anyone directly that does. I am vaguely familiar with it, but do not use it. I can take a look at it.

By the way — congrats on France winning the cup yesterday!

**Comment by ZeroQI** [comment]
So the numbering is either TheTVDB or AniDB and the respective function in  AniDB.py and TheTVDBv2.py will manage missing episodes, so you do not have missing episodes for season 2 when the AniDB numbered serie is season 1, etc...
- Both AniDB and TVDB missing eps will be in the file, that is expected
- I need examples of ep showing up even though they are not missing (after deleting the log file to be sure)
- for TheTVDB to be aired eps were ignored. Never did for AniDB but it make sense, will add it.

Thanks but i wanted Croatia to Win, i prefer their president...

**Comment by sven-7** [comment]
Exactly regarding each managing it depending on which is selected. 

Sorry, to clarify on the second point. I mean the shows were showing up in the log even tho there were no missing logs.  I don't mind it, but I think in the previous version, only shows that had something missing generated a line in the log.

Example:

```
AniDBid: 24 | Title: '.hack//SIGN' | Missing Episodes: []
AniDBid: 6239 | Title: '07-Ghost' | Missing Episodes: []
AniDBid: 12014 | Title: '91 Days' | Missing Episodes: []
AniDBid: 5975 | Title: 'A Certain Magical Index' | Missing Episodes: []
AniDBid: 6460 | Title: 'A Certain Scientific Railgun' | Missing Episodes: []
AniDBid: 8229 | Title: 'A Dark Rabbit has Seven Lives' | Missing Episodes: []
AniDBid: 9387 | Title: 'A Lull in the Sea' | Missing Episodes: []
AniDBid: 13257 | Title: 'A Place Further Than the Universe' | Missing Episodes: []
AniDBid: 13346 | Title: 'A.I.C.O. Incarnation' | Missing Episodes: []
AniDBid: 12136 | Title: 'ACCA: 13-Territory Inspection Dept.' | Missing Episodes: []
AniDBid: 8691 | Title: 'Accel World' | Missing Episodes: []
```

Hah! I think a lot of people wanted Croatia to win.

**Comment by ZeroQI** [comment]
Will correct tonight
I like how these logs are unique, pretty happy about this, nonody else does it...
And a lot of people wanted england to lose :)

**Comment by sven-7** [comment]
I ran a test over night. Looks like all the blank shows on AniDB went away as expected. It still looked like all TheTVDB mode ones were showing up as missing with an aniDB tag. Will get you logs later today.

**Comment by ZeroQI** [comment]
Uploaded new version, logging greatly improved
- was reusing source variable in list comprehension... that caused the tvdb numbering detection to always be AniDB
- Displayed all eps with [X] if present and [ ] if not.
- missing eps should be missing tvdb 
- missing tvdb series missing ep logging i think

**Comment by sven-7** [comment]
Very nice! Looks to be working perfectly now.  I'll do some extra tests, but everything as worked so far! 

Closing #237.
