### ISSUE TITLE
Metadata split of seasons for long running series

### ISSUE THREAD

**Issue by dargon007** [ZeroQI/Hama.bundle#24]
Hi,

For a most AniDB Anime series, seasons are not stored into a single anime.
```
    Toaru Majutsu no Index (a5975) = https://anidb.net/perl-bin/animedb.pl?show=anime&aid=5975
    Toaru Majutsu no Index II (a7599) = https://anidb.net/perl-bin/animedb.pl?show=anime&aid=7599
```
Your Hama agent works just fine for these animes. As the ScudLee Anime Master list helps in recognizing where AnimeDB has two listings and TheTVDB has only one based on the 'defaulttvdbseason' entry.
```
<anime anidbid="5975" tvdbid="83322" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
<name>Toaru Majutsu no Index</name>
</anime>
<anime anidbid="7599" tvdbid="83322" defaulttvdbseason="2" episodeoffset="" tmdbid="" imdbid="">
<name>Toaru Majutsu no Index II</name>
</anime>
```
The problem I have is when we have multi season AniDB entry. Like the animes Ranma 1/2, Bleach, Naruto, One Piece, ... If we leave in a single 'Season 1' the agent recognizes it fine but then we can then have a 100+ episodes in a single season. This causes issues when trying to scroll through the episode listings when viewing in any client other than web (due to the amount of data the client tried to load when opening a season).

If I try to separate out the episodes into separate season folders, that comes to another issue in where we would now need to renumber every single 100+ episodes. It also means that it will get forced into "TVDB numbering mode" as there is multiple seasons instead of the wanted "AniDB mode".

It is possible to have the agent recognize a single season folder with 'anidb-' in the name. And from that, to use the season number provided by thetvdb be used to override it from being a 'Season 1' episode to a 'Season X' episode? This way, the AniDB episode numbers can still be used to pull in all metadata (title/summary/...) and we don't have to spend the hours to renumber every episode we have for these multi-season AniDB animes. (Bleach=366, One Piece=746+, Naruto=220, Naruto Shippuuden=444+, ...)

The season number is already available in thetvdb xml created that can easily be imported into the 'tvdb_table' item for data reference in the "### TVDB - Build 'tvdb_table' ###" section.
```
"83322.xml":
<Episode>
  <id>3449781</id>
  <Combined_episodenumber>24</Combined_episodenumber>
  <Combined_season>2</Combined_season>
```

This should also be dooable to be just added into the existing 'Update' function after the ' elif metadata.id.startswith("anidb-"): ' line to change the season number.

As you can guess, I have tried to get this working hence I know your code and files somewhat =). I just could not find out how to get the season changed. Once it is set by the scanner it is not possible to change it through the metadata?

Regards

**Comment by ZeroQI** [comment]
Hi, very nice descriptive post.
The episode number and season is chossen by the scanner, period. The issue is that the serie id isn't know then but you can force it and check if seasons folders are present but i try to avoid dowloading files there...
So in short you want absolute numbering but displaying in seasons? Try adding ' [tvdb-83322]' to the serie name. It should display a long tunning series in absolute mode using seasons but will use tbdb numbering for display.

Does that work out for you?

**Comment by ZeroQI** [comment]
Use the long running serie tvdb id obviously.
I think supporting anidb and tvdb numbering and anidbd as tvdb numbering alredy catters for all needs and is complex enough in the code. Your opinion?

**Comment by ZeroQI** [comment]
You can put tvdb id in tvdb.id file as well in serie or serie extra folder.
Try using the alpha scanner in gits and feedback
https://gist.github.com/ZeroQI/26d26f91af04c876b1a0

**Comment by dargon007** [comment]
Closing issue and raising new issue in the scanner as no issue here in the Hama.bundle.
