### ISSUE TITLE
Powershell Update script does not update itself

### ISSUE THREAD

**Issue by Xalaxis** [ZeroQI/Hama.bundle#240]
Currently the PowerShell update script does not update itself.  This led to me thinking that I was running the latest version of the plugin despite not having received the new additional files (thus leading to crashes).

Could potentially the script update itself to allow for the addition of future files/directories to be updated?

**Comment by ZeroQI** [comment]
Need to go over these few links to know if possible:
- https://stackoverflow.com/questions/5637362/self-updating-powershell-script
- https://curi0usjack.blogspot.com/2017/08/creating-self-updating-powershell.html
- https://gist.github.com/MarkTiedemann/c0adc1701f3f5c215fc2c2d5b1d5efd3

**Comment by ZeroQI** [comment]
Re-wrote the Powershell script to download the repository zip instead so it can't happen anymore.
Please consider donating (link in readme)
