### ISSUE TITLE
Not working with most of my library

### ISSUE THREAD

**Issue by YamiFrankc** [ZeroQI/Hama.bundle#242]
Hello, Hama is not working, leaving most of my library with titles as "X [anidb-x]" without any metadata or posters, however, about 5 of my series where correctly recognized and one was matched incorrectly.
I rebuilt the server and this is a new install of Plex and Hama, and with the previous install it worked correctly.
Thanks

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/2238558/com.plexapp.agents.hama.log)
[com.plexapp.system.log](https://github.com/ZeroQI/Hama.bundle/files/2238559/com.plexapp.system.log)
[_root_.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/2238560/_root_.agent-search.log)
[_root_.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/2238561/_root_.agent-update.log)
[_root_.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/2238562/_root_.filelist.log)
[_root_.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/2238563/_root_.scanner.log)

**Comment by ZeroQI** [comment]
Thanks for reporting, it impacted all users with 'ja' for posters language 
Please update the agent and run full metadata update

**Comment by ZeroQI** [comment]
Excellent, thanks for reporting. Please consider a donation, loads of hours went into coding and as you can see in the source it it way more complex than the average Plex agent due to multiple data sources and xml referencing between them...
