### ISSUE TITLE
Hanamonogatari and Tsukimonogatari metadata matching error

### ISSUE THREAD

**Issue by NextFire** [ZeroQI/Hama.bundle#244]
├── Hanamonogatari Suruga Devil [anidb-10046]
│   └── Hanamonogatari Suruga Devil - 01 - TV Special (1920x1080 8-bit x264 AAC).mp4
├── Tsukimonogatari Yotsugi Doll [anidb-10891]
│   └── Tsukimonogatari Yotsugi Doll - 01 - TV Special (1920x1080 8-bit x264 AAC).mp4

![image](https://user-images.githubusercontent.com/20094890/44202908-a3f38780-a14d-11e8-9185-2bb8aa229263.png)
![image](https://user-images.githubusercontent.com/20094890/44202926-ae158600-a14d-11e8-990e-b2e1b0769758.png)

Hello, 
I'm using latest version of ASS & HAMA. When adding Hanamonogatari and Tsukimonogatari the scanner is working fine but metadata fetching is quite wrong as you can see: all is ok except episodes titles and thumbnails.

Log : [com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/2293313/com.plexapp.agents.hama.log)

**Comment by NextFire** [comment]
Uhh pressed "enter button" too fast

**Comment by ZeroQI** [comment]
Go in desktop mode in your browser  and edit your post and delete the second post will edit this post as a result

**Comment by ZeroQI** [comment]
if 2 anidb eps are mapped to the same tvdb episode, keepingthe first episode for now
Please test and report

**Comment by NextFire** [comment]
Ok so:
![image](https://user-images.githubusercontent.com/20094890/44334615-58edb300-a472-11e8-9502-5946f5487c1f.png)
![image](https://user-images.githubusercontent.com/20094890/44334629-6145ee00-a472-11e8-89ae-e8ebd062d076.png)

It seems good now episode names and thumbnails are corrects, but I'm still going to rename these two episodes becauses they are the TV specials containing all parts of each arc, not only "Parts 1".
These two eps are listed in anidb but not in tvdb: if I'm not wrong HAMA agent takes episodes names from tvdb so now it's not the agent's fault but tvdb's...

Anyway, thanks for your work!

**Comment by ZeroQI** [comment]
Since both anidb and tvdb EPs are mapped
Hama takes titles according to the agent settings.
The 'title' field carry both series and episode titles.
If priority differs between series and episodes by splitting it with a pipe '|'

**Comment by NextFire** [comment]
> The 'title' field carry both series and episode titles.
> If priority differs between series and episodes by splitting it with a pipe '|'

Oh, I didn't know that...

**Comment by ZeroQI** [comment]
For example for title field "AniDB, TheTVDB | TheTVDB, AniDB" would use the first part (AniDB, TheTVDB ) for series and the second for episodes (TheTVDB, AniDB)

Can i close this ticket or is it not resolved?

**Comment by NextFire** [comment]
Yes you can close it now thanks for your help!
