### ISSUE TITLE
AniDB Series Poster Priority/Ranking Issue

### ISSUE THREAD

**Issue by purposelycryptic** [ZeroQI/Hama.bundle#245]
The issue I am having is that, no matter what I do, I can not get HAMA to assign the AniDB poster for a series as its main poster when fetching metadata - it is always placed somewhere near or at the end of the list, with TVDB posters taking priority, and will only use the AniDB poster if manually assigned, regardless of HAMA settings.

Since I have all my media organized according to AniDB, and TVDB uses a single series to encompass multiple AniDB series, I end up with many, many shows with duplicate posters, and/or posters with terrible English names like "Cat Planet Cuties" on them.

I am not sure how complicated an issue this is (The poster rank code looked surprisingly complicated), but if there is any way to have HAMA place AniDB posters at highest priority (Either by just having it in the highest position in the 'Poster' order as I do now, or through some sort of toggle to have it bypass the poster ranking system), I would be extremely grateful.

Thank you for taking the time to consider my issue.

**Comment by ZeroQI** [comment]
Poster source priority?
Title source ans language priorities?
Need Hama agent logs for 1 impacted series at least.

**Comment by purposelycryptic** [comment]
I've tried all sorts of configurations, but atm, I think it's:
Poster Source Priority: AniDB, FanArt.tv, TheTVDB, TheMovieDB?
Title Source Priority: AniDB
Title Language Priority: Main, X-Jat, En, Ja

I'll up a log when I'm back home tomorrow (and double check my current settings).

I thought this was a known issue, I've never been able to get HAMA to set an AniDB poster as default for a series unless the series either wasn't matched yet in the matching XML, or I set AniDB as the sole source (basically when the only available poster was from AniDB). Might have gotten mixed up with something posted in the issue tracker for Shoko Metadata, which also has issues with AniDB posters (among other things).

**Comment by purposelycryptic** [comment]
Sorry for the delay - these are my current HAMA preference settings:
```xml
<?xml version='1.0' encoding='utf-8'?>
<PluginPreferences>
  <rating>AniDB, TheTVDB, TheMovieDb, OMDb</rating>
  <content_rating>AniDB,TheTVDB</content_rating>
  <art>AniDB, TheTVDB, FanartTV, TheMovieDb</art>
  <EpisodeLanguagePriority>main, en, x-jat, ja</EpisodeLanguagePriority>
  <SerieLanguagePriority>main, x-jat, en, ja</SerieLanguagePriority>
  <themes>Plex, TVTunes</themes>
  <quotes>TheMovieDb, OMDb</quotes>
  <thumbs>TheTVDB</thumbs>
  <year>AniDB</year>
  <duration>TheTVDB, AniDB, TheMovieDb, OMDb</duration>
  <rating_count>None</rating_count>
  <genres>AniDB, TheTVDB, TheMovieDb, OMDb</genres>
  <title>AniDB, TheTVDB</title>
  <MinimumWeight>5</MinimumWeight>
  <content_rating_age>None</content_rating_age>
  <writers>AniDB, TheTVDB</writers>
  <collections>TheMovieDb, AniDB, AnimeLists</collections>
  <absolute_index>TheTVDB</absolute_index>
  <trivia>TheMovieDb, OMDb</trivia>
  <tags>None</tags>
  <audience_rating_image>None</audience_rating_image>
  <rating_image>None</rating_image>
  <producers>AniDB,TheTVDB</producers>
  <audience_rating>None</audience_rating>
  <studio>AnimeLists, AniDB, TheTVDB, TheMovieDb</studio>
  <adult>false</adult>
  <posters>AniDB, TheTVDB, AnimeLists, tvdb4, FanartTV, TheMovieDb</posters>
  <originally_available_at>AniDB,TheTVDB</originally_available_at>
  <roles>AniDB, TheTVDB</roles>
  <countries>TheMovieDb</countries>
  <title_sort>AniDB,TheTVDB</title_sort>
  <original_title>AniDB,TheTVDB</original_title>
  <OMDbApiKey>XXXXXXXX</OMDbApiKey>
  <summary>AniDB, TheTVDB</summary>
  <reviews>None</reviews>
  <guest_stars>None</guest_stars>
  <directors>AniDB,TheTVDB</directors>
  <extras>None</extras>
  <tagline>TheMovieDb</tagline>
  <banners>TheTVDB</banners>
  <similar>AniDB</similar>
  <PosterLanguagePriority>ja,en,fr,zh,sv,no,da,fi,nl,de,it,es,pl,hu,el,tr,ru,he,pt,cs,ko,sl,hr</PosterLanguagePriority>
</PluginPreferences>
```
The many languages in _PosterLanguagePriority_, aside from the first two, are only there because a lot of TVDB users will flag a poster in their native language when uploading, regardless of what language, if any, is featured on the poster itself.

To get relatively clean logs, and avoid any issues due to old metadata, I created a new library with a random sample of 15 series. Since ASS is also currently undergoing changes, for reference, I used the version with today's fixes (commit 306101e58727e3b542a96876fa506b0b55615cc1).

The Library folder contained the following series folders:
 - Accel World [FFF] [BD, 720p]
 - Amagami SS [UTW] [BD, 720p]
 - Bakemonogatari [Coalgirls] [BD, 1080p]
 - Darker Than Black Kuro no Keiyakusha [THORA] [BD, 720p]
 - Fate Stay Night [Doki] [BD, 1080p]
 - Ginga Eiyuu Densetsu [CA] [DVD, 480p]
 - Kaichou wa Maid-sama! [Coalgirls] [BD, 720p]
 - Kobato. [YuS] [HDTV, 720p]
 - Moyashimon [BSS] [BD, 720p]
 - Ore no Imouto ga Konna ni Kawaii Wake ga Nai [Coalgirls] [BD, 720p]
 - Owarimonogatari (2017) [Dmon] [BD, 720p]
 - Plastic Memories [HorribleSubs] [www, 720p]
 - RD Sennou Chousashitsu [Ureshii_Saizen] [HDTV, 720p]
 - Re Zero kara Hajimeru Isekai Seikatsu [Nep_Blanc] [BD, 1080p]
 - Shingeki no Kyojin [Coalgirls] [BD, 1080p]

Out of those, only the following series actually appeared in Plex, I am assuming due to an issue with the changes to ASS, but sufficient as a sample:

 - Darker Than Black: Kuro no Keiyakusha
 - Ginga Eiyuu Densetsu
 - Kobato.
 - Owarimonogatari (2017)
 - Plastic Memories
 - RD Sennou Chousashitsu
 - Re: Zero kara Hajimeru Isekai Seikatsu
 - Shingeki no Kyojin

Which appeared in Plex like this:

![HamaPosters](https://i.imgur.com/v7d1QEX.jpg)

As a note, "Shingeki no Kyojin" was misidentified as "Shingeki no Kyojin Season 2", due to the latter's synonym, "Shingeki no Kyojin (2017)" receiving the same weight score as the actual name and appearing above it on the list.

Out of the sample, "Shingeki no Kyojin Season 2" and "Plastic Memories" appeared to use the AniDB series poster (although I cannot be certain regarding the latter, as the same poster appeared in the poster list twice, once in the top position, and once toward the bottom where AniDB posters appear in the list for other series), while the rest all used posters from other sources.

As a reference, here are the AniDB posters for the other series:

![AniDBPosters](https://i.imgur.com/sbZ8X9v.jpg)

I have uploaded all of the logs to a Google Drive folder [here](https://drive.google.com/open?id=1tkirrjt1vtqWCjm_-4Dbr66XLa7ZrIW_), and am attaching the HAMA log from Library creation until metadata completion to this post as well.

All the best - since it has gotten to be quite late here, I'll be calling it a night.

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/2300978/com.plexapp.agents.hama.log)

**Comment by ZeroQI** [comment]
ASS issue resolved this morning due to bad code trying to fix OP/ED, also resolved
```
  <EpisodeLanguagePriority>main, en, x-jat, ja</EpisodeLanguagePriority>
  <SerieLanguagePriority>main, x-jat, en, ja</SerieLanguagePriority>
```
I would remove 'main' as it always equate to 'x-jat'

[=] posters                  ( 1)  Sources: (AniDB), TheTVDB, AnimeLists, tvdb4, FanartTV, TheMovieDb     Inside: '['FanartTV', 'MyAnimeList', 'TheTVDB', 'AniDB', 'TheMovieDb']'  Value: '{'http://img7.anidb.net/pics/anime/180443.jpg': (u'AniDB\\poster\\180443.jpg', **1,** 'http://img7.anidb.net/pics/anime/thumbs/150/180443.jpg-thumb.jpg')}'

seem like AniDB poster ID is 1...  Look good to me...
it's possible the posters added with a wrong id (i used to set AniDB to 99) would not possibly be updated. a new library should solve that possibly...

**Comment by purposelycryptic** [comment]
Surprisingly, 'main' and 'x-jat' are actually not always the same (granted, in my collection of 1,600+ series, that is only true for a handful of cases, but...).

I created a new library specifically for these logs (and during each step of testing for the OP/ED issue), which never seemed to affect the posters used.

If all else fails, I suppose I could always go into the code and just hard-code AniDB posters as '1', and add 1 to all other poster sources...

**Comment by ZeroQI** [comment]
Good to know... Never encountered a series for which it differed, if you have it will be  much appreciated...
I will code a fix but if logs it as Id 1 not sure what I can do... The I'd is the second variable in the touple. If you spot a series with anidb poster and higher I'd than 1 paste the logs and I will start coding

**Comment by purposelycryptic** [comment]
There aren't a ton (there used to be a lot more, often in X-Jat but separate from the default X-Jat title, when there were disputes about the main title due to the anime changing from the name of the LN/VN/Manga source and such, but that calmed down over the past 5 years or so), these days it's mainly things like Chinese productions and Manhwa/Manhua adaptations. AniDB has roughly 14,130 series, of which 486 have a non-X-Jat main title, or about 3.44%. 

But using 'X-Jat' rather than 'Main' often results in the dreaded _Terrible English Anime Name_ for affected series (which usually don't haven an X-Jat version) - as a recent example, [Quanzhi Fashi](http://anidb.net/a13171) and [Quanzhi Fashi 2](http://anidb.net/a13469) ended up as "Full-Time Magister" and "Full-Time Magister Season 2".


Anyway, I'll check my logs and see what I can find regarding AniDB Posters with priority above '1'.

Btw, if you're curious, here's the list of AniDB series with main titles in non-X-Jat languages (taken from ScudLee's anime-titles.xml):

Series Name | Main Title Language
---------------------------------------- | ---------------------
15 Sonyeon Uju Pyoryugi | x-kot
2020 Nyeon Ujuui Wonder Kiddy | x-kot
77 Danui Bimil | x-kot
84 Taekwon V | x-kot
9 Satra | x-tht
A Tang Qiyu | x-zht
Aachi wa Ssipak | x-kot
Agigongryong Dooly | x-kot
Agigongryong Dooly (1988) | x-kot
Agigongryong Dooly: Aeouleumbyul`daemohum | x-kot
Aishen Qiaokeli-ing... | x-zht
Aishen Qiaokeli-ing... II | x-zht
A-Jang.com | x-kot
Alarm | x-kot
Annyeong Jaduya | x-kot
Annyeong Jaduya 2 | x-kot
Annyeong Jaduya 3 Special | x-kot
Annyeong Totobi | x-kot
Annyeong, Tirano | x-kot
AOTU Shijie | x-zht
AOTU Shijie Di Er Ji | x-zht
Bab Mook Ja | x-kot
Backkom | x-kot
Bai Bian Zhu Zhu Xia | x-zht
Bai Dao | x-zht
Baiye Linglong | x-zht
Balala Xiaomoxian: Caihong Xinshi | x-zht
Balala Xiaomoxian: Feiyue Cai Ling Bao 1 Jingling Li Li | x-zht
Balala Xiaomoxian: Feiyue Cai Ling Bao 2 Choi Li Gongzhu | x-zht
Balala Xiaomoxian: Menghuan Xuanlu | x-zht
Balala Xiaomoxian: Qiji Wubu | x-zht
Balgwanghaneun Hyeondaesa | x-kot
Bandoe Sareoriratda | x-kot
Bao Lian Deng | x-zht
Barnacle Lou | x-kot
Beautiful World | en
Beongae Atom | x-kot
Birthday Boy | x-kot
Blue Seagull | x-kot
Bogeul Bogeul Bomulseon | x-kot
Bola Kampung | my
Booleung! Booleung! Beuloomijeu: Seupideoeui Moheom Ilgi | x-kot
Bulg-eunmae | x-kot
Bulsajo roboteu Pinikseu-King | x-kot
Bumper King Zapper | x-kot
Byeolnala Samchongsa | x-kot
Byulbyul Iyagi | x-kot
Byulbyul Iyagi 2 | x-kot
Card Wang Mix Master | x-kot
Card Wang Mix Master (2010) | x-kot
Chang | x-kot
Chao You Bing | x-zht
Chao Zhi Neng Zu Qiu | x-zht
Chengyu Donghua Lang | x-zht
Cheorin 007 | x-kot
Cheorin Samchongsa | x-kot
Cheung Gong 7 hou: Oi dei kau | x-zht
Chi Jian Chuan Qi | x-zht
Chonnyonyeouu Yeouubi | x-kot
Chu Feng: Bee | x-zht
Chuldong! Super Wings | x-kot
Circle | en
Cirque le coeur | fr
Closers: Side Blacklambs | x-kot
CMFU Xueyuan: Shenshi Ji Jijian Dongman | x-zht
CMFU Xueyuan: Wangzi Peng Peng Qiu | x-zht
Computer Haekjeonham Pokpadaejakjeon | x-kot
Congming de Yixiu Zhi Fan Dou Gongzhu | x-zht
Contact | x-kot
Cubix | x-kot
Da Nao Tian Gong | x-zht
Da Wei Bei Ken Zhi Dao Mei Te Gong Xiong | x-zht
Da Yu Hai Tang | x-zht
Dabing Jinbao | x-zht
Dahufa | x-zht
Dalam-iwa Goseumdochi | x-kot
Dalbitkungkwol | x-kot
Dallyeora Maxinger X | x-kot
David Gwa Goliath | x-kot
Di Ling Qu | x-zht
Di Tou Ren Sheng | x-zht
Di Wang Gong Lue | x-zht
DinoZone: TV Series | en
Dokkaebi Bangmangi | x-kot
Dokkaebi Gamtu | x-kot
Dongguo Xiaojie | x-zht
Dooly-ui Baenang`yeohaeng | x-kot
Dou Hun Wei Zhi Xuan Yue Qi Yuan | x-zht
Dou Po Cang Qiong Di Er Ji | x-zht
Douluo Dalu | en
Duan Nao | x-zht
Duan Nao (2017) | x-zht
Dwaejiui Wang | x-kot
Elsword: El-ui Yeoin | x-kot
Eunhahamdae Jiguho | x-kot
Eunhajeonseol Tera | x-kot
Eun-sil-i | x-kot
Fei Ren Zai | x-zht
Fen Qing | x-zht
Feng Ling Yu Xiu | x-zht
Feng Shen Bang | x-zht
Feng Wei Ying Xiong | x-zht
Fengyun Jue: Storm Rider - Clash of Evils | x-zht
Flowering Heart | x-kot
Fojiao Donghua: Dashi Zhi Pusa Nianfo Yuantong Zhang | x-zht
Fuwa Aoyun Manyou Ji | x-zht
Geugjangpan Annyeong Jaduya | x-kot
Geugjangpan Turning Mecard W: Black Mirror ui Buhwal | x-kot
Ghost Messenger | x-kot
Ghost Messenger Geugjangpan | x-kot
Giga Tribe (2008) | x-kot
Gogulyeoui Jeolm-eun Musadeul | x-kot
Gonglyong Mecard | x-kot
Gongnyong Baengmannyeon Ttori | x-kot
Grami`s Circus Show | x-kot
Greek Roman Sinhwa Olympus Guardian | x-kot
Gu Huo Xiang Jia Tou | x-zht
Guan Hai Ce | x-zht
Gui Bao Zhi Bao Xiao Chuang Yu Zhou | x-zht
Guomin Laogong Dai Huijia | x-zht
Gwahakmasuldan | x-kot
Haedori Daemoheom | x-kot
Haejeotamheomdae Marin X | x-kot
Hanguksa Siganyeohaeng | x-kot
Happy Day | x-kot
Harry &amp; Bunnie | en
Hayan ma-eum Baekgu | x-kot
Hei Mao Jing Zhang | x-zht
Heibai Wushang | x-zht
Heonggeuri Beseuteu 5 | x-kot
Heungbujeon | x-kot
Heungbuwa Nolbu | x-kot
Heungnyongwanggwa Bihodongja | x-kot
Hey Yo Yorang | x-kot
Ho Dong Wangjawa Rang Nang Gongju | x-kot
Hokseong Robot Sseondeo A | x-kot
Hong Gildong Janggun | x-kot
Hong Hai`er: Juezhan Huoyanshan | x-zht
Hong Ling Jin Xia | x-zht
Hong Mao Lan Tu A Muxing | x-zht
Hong Mao Lan Tu Ao You Guo Lixian Ji | x-zht
Hong Mao Lan Tu Chuang Taikong | x-zht
Hong Mao Lan Tu Guangming Jian | x-zht
Hong Mao Lan Tu Haidi Lixian Ji | x-zht
Hong Mao Lan Tu Huo Fenghuang | x-zht
Hong Mao Lan Tu Kaixin Yike | x-zht
Hong Mao Lan Tu Kuaile Shizi | x-zht
Hong Mao Lan Tu Le Fantian | x-zht
Hong Mao Lan Tu Maoyan Kan Yuzhou | x-zht
Hong Mao Lan Tu Meng Zhi Guo Lixian Ji | x-zht
Hong Mao Lan Tu Ni Wen Wo Da | x-zht
Hong Mao Lan Tu Qi Xia Chuan | x-zht
Hong Mao Lan Tu Qi Xia Waizhuan | x-zht
Hong Mao Lan Tu Shuimo Donghua | x-zht
Hong Mao Lan Tu Xiao Youmo | x-zht
Hong Mao Lan Tu Zhang Jian Zou Tianya | x-zht
Hong Mao Lan Tu Zhi Yongzhe Guilai | x-zht
Hopiwa Chadol Bawi | x-kot
Houzi Lao Yue | x-zht
Hu wang gui lai | x-zht
Hu Yao Xiao Hong Niang | x-zht
Hua Jianghu Zhi Bei Mo Ting | x-zht
Hua Jianghu Zhi Buliang Ren | x-zht
Hua Jianghu Zhi Buliang Ren Di Er Ji | x-zht
Hua Jianghu Zhi Ling Zhu | x-zht
Huan Jie Wang | x-zht
Huan Jing Nuo De Lin | x-zht
Hudie Meng - Liang Shanbo yu Zhu Yingtai | x-zht
Hulu Xiao Jin Gang | x-zht
Hulu Xiongdi | x-zht
Hwang Geumnalgae 1.2.3. | x-kot
Hwanggeum Cheolin | x-kot
Hwanggeumnyeonpilgwa Gaegujangi Oegyesonyeon | x-kot
Hwanggeumui Pal | x-kot
I-Cheng | x-zht
Indie Anibox: Selma Danbaekjil Coffee | x-kot
Iron Kid | x-kot
Jang Geum Ieui Kkum | x-kot
Jang Geum Ieui Kkum 2 | x-kot
Jebulchalssi Iyagi | x-kot
Jeonjaingan 337 | x-kot
Jian Wangchao | x-zht
Jian Wangchao (2017) | x-zht
Jianzhen Da he shang | x-zht
Jiaoao de Jiangjun | x-zht
Jie Mo Ren | x-zht
Jin Hou Xiang Yao | x-zht
Jin Sheng Yuan | x-zht
Jinxiu Shenzhou Zhi Qi You Ji | x-zht
Jiu Se Lu | x-zht
Joleobban | x-kot
Jue Ji | x-zht
Jungle Hero | x-kot
Kai Feng Qitan: Zhege Baogong Bu Taixing | x-zht
Kai: Geoul Hosuui Jeonseol | x-kot
Kao An | x-zht
Kkachi ae Nalgae | x-kot
Kkoma Bus Tayo | x-kot
Kkoma Bus Tayo 2 | x-kot
Kkoma Bus Tayo 3 | x-kot
Kkoma Bus Tayo 4 | x-kot
Kkoma Bus Tayoui Ace Guchuljakjeon | x-kot
Kkureogi Balmyeongwang | x-kot
Ku Pao Ying Xiong | x-zht
Kuiba | x-zht
Kuiba II: Dazhan Yuan Yang Jie | x-zht
Kuiba III | x-zht
Kung Fu Cooking Girls | x-zht
Lan Mo De Hua | x-zht
Lao Fu Zi Fan Dou Zhen Tan | x-zht
Lao Fu Zi Shui Hu Chuan | x-zht
Lao Fu Zi Zhi Xiao Shui Hu Chuan Qi | x-zht
Larva | x-kot
Larva 2nd Season | x-kot
Lei Su Deng Shandian Chong Xian | x-zht
Ling Yu | en
Ling Yu 2nd Season | en
Little Big War | x-zht
Lost Forest | en
Lu Shidai | x-zht
Lu Shidai (2014) | x-zht
Ma La Xiao Yuan Jia | x-zht
Ma Ma Mi Ya | x-zht
Madangeul Naon Amtak | x-kot
Mai Zhu | x-zht
Mailroui Daemoheom | x-kot
Mak Dau BoloYao WongZi | x-zht
Mak Dau Dang Dang Ban wo Xin | x-zht
Mak Dau Faan Bou Gei Bing | x-zht
Mak Dau Goo Si | x-zht
Mak Dau wo He wo Mama | x-zht
Mak Dau Xiang Dang Dang | x-zht
Mandamgangho | x-kot
Mari Iyagi | x-kot
Mask Masters | x-kot
Meng Hui Jinsha Cheng | x-zht
Meng Yue Jingling | x-zht
Meoteoldosa | x-kot
Meoteoldosawa 108 Yogoe | x-kot
Meoteoldosawa Ttomae | x-kot
MetaJets | x-kot
Mi Yu Xingzhe | x-zht
Mianhada, Saranghanda | x-kot
Micro Teukgongdae Diatron 5 | x-kot
Miraesonyeon Kunta Bermuda 5000 Nyeon | x-kot
Mo Fa A Ma | x-zht
Mo Mo | x-zht
Modao Zushi | x-zht
Moheomwang Jangbogo | x-kot
Mori Shuguang | x-zht
Mu Di | x-zht
Mu Wang Zhi Wang: Han Tie Dou | x-zht
Mu Wang Zhi Wang: Qi Lin Jue | x-zht
Mu Wang Zhi Wang: Xuan Guan Si | x-zht
Mujeokcheorin Lamboteu | x-kot
Munyeodo | x-kot
Murim Ilgeomui Sasaenghwal | x-kot
My Last Day | en
Naengjanggo Nara Cocomong | x-kot
Naengjanggo Nara Cocomong (2011) | x-kot
Naengjanggo Nara Cocomong (2015) | x-kot
Nancy`s Morning | x-zht
Nanocore | en
Nanocore 2nd Season | en
Narara Superboard | x-kot
Narara Superboard (1998) | x-kot
Narara Superboard (2001) | x-kot
Narara Wondergongju | x-kot
Narara! Ujujeonham Geobukseon | x-kot
Nezha Nao Hai | x-zht
Noblesse: Pamyeol-ui Sijak | x-kot
Nu Sheng Su She Ri Chang | x-zht
Nu Sheng Su She Ri Chang Di 2 Ji | x-zht
Nuwa Chengzhang Riji | x-zht
O-di-syeon | x-kot
Olympus Guardian | x-kot
Orchestra | en
Oscar`s Oasis | x-kot
Oseam | x-kot
Padak Padak | x-kot
Pororo Daemoheom | ko
Pororo Hanguk-e Wass-eoyo | ko
Ppaekkom-ui Mug-jan Yeohaeng | x-kot
Pucca | x-kot
Pucca (2006) | x-kot
Pung Dengidengi | x-kot
Qi Cai Lao Fu Zi | x-zht
Qi Che Ren Zong Dong Yuan | x-zht
Qiang Niang | x-zht
Qiang Shen Ji | zh-Hans
Qin Shi Mingyue 3D: Dianying Longteng Wanli | x-zht
Qin Shi Mingyue Si: Wanli Changcheng | x-zht
Qin Shi Mingyue Tebie Pian: Dizi Jiang Xi | zh
Qin Shi Mingyue Tebie Pian: Kongshan Niao Yu | x-zht
Qin Shi Mingyue: Bai Bu Fei Jian | x-zht
Qin Shi Mingyue: Junlin Tianxia | x-zht
Qin Shi Mingyue: Luo Shengtang Xia | x-zht
Qin Shi Mingyue: Ye Jin Tianming | x-zht
Qin Shi Mingyue: Yi Zhe Ru Shi | zh
Qin Shi Mingyue: Zhu Zi Bai Jia | x-zht
Qing Wa Wang Guo | x-zht
Qingcong: Youth | x-zht
Quanzhi Fashi | x-zht
Quanzhi Fashi 2 | x-zht
Quanzhi Gaoshou | x-zht
Quanzhi Gaoshou: Tebie Pian | x-zht
Rakshasa Street | x-zht
Rang Wo Men Shao Ba!!! | x-zht
Re Boot | en
Renshenguo | x-zht
Robot King | x-kot
Robot Taekwon V | x-kot
Robot Taekwon V Jae2tan: Wooju-jakjeon | x-kot
Robot Taekwon V Jae3tan! - Sujuung Teukgongdae | x-kot
Robot Taekwon V wa Hwanggeum Nalgae ue Daegyul | x-kot
Robot Trains | x-kot
Roboteugundangwa Meka3 | x-kot
Robotex | x-kot
Romangeun Eobsda | x-kot
Ru Guo Wo Shi Ying Xiong | x-zht
Saibi | x-kot
Salaoreum: Cheonnyeonui Donghaeng | x-kot
Samchongsa: Time Machine 001 | x-kot
San Ge Heshang | x-zht
San Mao Liu Lang Ji (2006) | x-zht
Scan2Go | x-kot
Scandal Anime | en
Seoulyeok | x-kot
Seupideuwang Beongae | x-kot
Shan T Lao Fu Zi | x-zht
Shanchiiou | x-zht
Shanshan de Hongxing | x-zht
Shanshui Qing | x-zht
Shao Nian Jin Yi Wei | x-zht
Shen Diao Xia Lu II: Xiang Yang Feng Yun | x-zht
Shen Diao Xia Lu III: Xiangyue Shiliu Nian | x-zht
Shen Po | x-zht
Sheng Shi Zhuang Niang | x-zht
Sheng Xiao Chuan Qi | x-zht
Shengshi Chuanshuo | x-zht
Shi Wan Ge Leng Xiaohua | x-zht
Shi Wan Ge Leng Xiaohua 2 | x-zht
Shi Xiong | x-zht
Shin Agigongryong Dooly | x-kot
Shou Hu Zhe Sen Lin | x-zht
Shuang Yue Zhi Cheng | x-zht
Shuangsheng Lingtan | x-zht
Si Juki the Movie | id
Si Ling Bianma: Zhi Shijie Caozong Zhe | x-zht
Sinbi Apartment 444 Ho | x-kot
Siu Sin | x-zht
Sojunghan Nal-ui Kkum | x-kot
Sonyeon 007 Eunhateukgongdae | x-kot
Sonyeon 007 Jihajeguj | x-kot
Spheres | x-kot
Starship Troopers: Traitor of Mars | en
Sun Wukong Qiyu Xiaodingding | x-zht
Sun Wukong: Dazhan Huoyanshan | x-zht
Sun Wukong: Yusanjian Baobei | x-zht
Super Child | x-kot
Super Samchongsa | x-kot
Super Taekwon V | x-kot
Super Teukgeup Mazinger 7 | x-kot
Super Titan 15 | x-kot
Taikong Lixianji | x-zht
Tang Lang Bu Chan | x-zht
Tao Hua Yuan Ji | x-zht
Te Ke Dong Ji Pian | x-zht
Teo the Magic Planet | en
Teugbyeolpan Turning Mecard W: Bandain ui Bimil | x-kot
The Tibetan Dog | x-zht
Tian Xin Ge Ge | x-zht
Tian Xin Ge Ge 2nd Season | x-zht
Tie Shan Gongzhu | x-zht
Tonghua Wangguo Lixian Ji | x-zht
Tteodori Kkachi | x-kot
Ttokttokbaksa Eddy | x-kot
Ttori wa Zeta Robot | x-kot
Tu Xia Chuanqi | x-zht
Tu Xia: Qing Li Chuanshuo | x-zht
Turning Mecard | x-kot
Turning Mecard R | x-kot
Turning Mecard W | x-kot
Turning Mecard W Season 2 | x-kot
Turning Mecard W: Bandainui Bimil | x-kot
Uju Heukgisa | x-kot
Uribyeol ilhowa ulrookso | x-kot
Valley of White Birds | en
Wang Gu Xian Qiong | x-zht
Wang Gu Xian Qiong 2 | x-zht
Wanghu Sim Cheong | x-kot
Wangpai Yushi | x-zht
Wangzhe Wai Chuan | x-zht
War of the Worlds: Goliath | my
Wara! Pyeonuijeom | x-kot
Wo De Ni Tian Shenqi | x-zht
Wo De Tian Jie Nuyou | x-zht
Wo Shi Jiang Xiao Bai | x-zht
Wo Shi Na Zha | x-zht
Wo Wei Ge Kuang | x-zht
Wojia Da Shixiong Naozi You Keng | x-zht
Wolf Daddy | x-kot
Wonderful Days | x-kot
Wu Geng Ji | x-zht
Wu Lan Qi Qi Ge | x-zht
Wukong Dazhan Er Lang Shen | x-zht
Xi Yang Yang Yu Hui Tai Lang | x-zht
Xi Yang Yang Yu Hui Tai Lang Zhi Hu Hu Sheng Wei | x-zht
Xi Yang Yang Yu Hui Tai Lang Zhi Kaixin Chuang Long Nian | x-zht
Xi Yang Yang Yu Hui Tai Lang Zhi Niu Qi Chong Tian | x-zht
Xi Yang Yang Yu Hui Tai Lang Zhi Tu Nian Ding Gua Gua | x-zht
Xiang Ling Ji | x-zht
Xiao Hua Xian | x-zht
Xiao Hua Xian 2 | x-zht
Xiao Hua Xian 3 | x-zht
Xiao Men Shen | x-zht
Xiao Taiji | x-zht
Xiao Yeyou | x-zht
Xing Fu Lu Shang | x-zht
Xing Ji | x-zht
Xing You Ji Zhi Feng Bao Fa Mi La | x-zht
Xiong Bing Lian | x-zht
Xiong Chumo | x-zht
Xiong Chumo Zhi: Qiu Ri Tuantuanzhuan | x-zht
Xiong Chumo Zhi: Tanxian Riji | x-zht
Xiong Chumo Zhi: Xiongxiong Leyuan 2 | x-zht
Xiong Chumo: Chunri Dui Dui Peng | x-zht
Xiong Chumo: Conglin Zhongdongyuan | x-zht
Xiong Chumo: Dongri Le Fantian | x-zht
Xiong Chumo: Duo Bao Qibing | x-zht
Xiong Chumo: Guonian | x-zht
Xiong Chumo: Huanqiu Da Maoxian | x-zht
Xiong Chumo: Nianhuo | x-zht
Xiong Chumo: Qihuan Kongjian | x-zht
Xiong Chumo: Xiari Lianlian Kan | x-zht
Xiong Chumo: Xiong Zin Guilai | x-zht
Xiong Chumo: Xiongxiong Leyuan | x-zht
Xiong Chumo: Xue Ling Xiong Feng | x-zht
Xiongmao He Xiao Yan Shu | x-zht
Xiyou ji Zhi da Sheng Gualai | x-zht
Xiyue Qi Tong | x-zht
Xiyue Qi Tong (2006) | x-zht
Xue Haizi | x-zht
Xue Se Cang Qiong | x-zht
Yao Shen Ji | x-zht
Yao Shen Ji 2 | x-zht
Yaoguai Mingdan | x-zht
Yi Kong Zhi Dian | x-zht
Yi Wan Nian Yi Hou | x-zht
Yin Shun Daoshi Chuan | x-zht
Yin Yang Shi: Ping An Wu Yu | x-zht
Young-sim | en
Youtai Nuhai Zai Shanghai | x-zht
Youtai Nuhai Zai Shanghai 2: Xiang Lian Mi Ma | x-zht
Yu Bang Xiang Zheng | x-zht
Ze Tian Ji | x-zht
Ze Tian Ji Di Er Ji | x-zht
Ze Tian Ji Di San Ji | x-zht
Zhan Long Si Qu | x-zht
Zhandou Wang Zhi Jufeng Zhan Hun | x-zht
Zhandou Wang Zhi Jufeng Zhan Hun 2 | x-zht
Zhandou Wang Zhi Jufeng Zhan Hun 3 | x-zht
Zhong Hua Xiao Zi | x-zht
Zhong Kui Chuan Qi: Sui Han San You | x-zht
Zhu Zhu Xia Fan Wai: Pin Zhuang Tegong Dui | x-zht
Zhu Zhu Xia: Bai Bian Lian Meng | x-zht
Zhu Zhu Xia: Bian Shen Xiao Ying Xiong | x-zht
Zhu Zhu Xia: Bian Shen Zhandui | x-zht
Zhu Zhu Xia: Chao Xing Meng Chong 1 | x-zht
Zhu Zhu Xia: Chao Xing Meng Chong 2 | x-zht
Zhu Zhu Xia: Chao Xing Meng Chong 3 | x-zht
Zhu Zhu Xia: Chao Xing Meng Chong 4 | x-zht
Zhu Zhu Xia: Da Nao Huang Gong | x-zht
Zhu Zhu Xia: Guang Ming Shou Wei Zhe | x-zht
Zhu Zhu Xia: Jimu Shijie De Tong Hua | x-zht
Zhu Zhu Xia: Jiong Jiong Wei Ji | x-zht
Zhu Zhu Xia: Meng Xiang Shou Wei Zhe | x-zht
Zhu Zhu Xia: Mo Huan Zhu Luo Ji | x-zht
Zhu Zhu Xia: Wu Ling Shou Wei Zhe | x-zht
Zhu Zhu Xia: Wu Xia 2008 | x-zht
Zhu Zhu Xia: Xingfu Jiuyuan Dui | x-zht
Zhu Zhu Xia: Ying Xiong Zhu Shao Nian | x-zht
Zhu Zhu Xia: Yong Chuang Juren Dao | x-zht
Zhu Zhu Xia: Yong Chuang Weilai Cheng | x-zht
Zhu Zhu Xia: Zhong Ji Jue Zhan | x-zht
Zhu Zhu Xia: Zhong Ji Jue Zhan Qian Ye Pian | x-zht

**Comment by ZeroQI** [comment]
i will replace x-jat with main in the agent, while it is 99.9% identical, it does differ for few titles.
Thanks for the list provided, closing this issue in the meantime
I am coding to avoid hard coded priorities for posters as we speak, will take few weeks possibly though
