### ISSUE TITLE
Shingeki no Kyojin

### ISSUE THREAD

**Issue by H3llt3ch** [ZeroQI/Hama.bundle#246]
Having an issue with Season 3 of Attack on Titan being picked up by Hama. Episodes 1-3 get picked up, but 4+ do not. I attribute this to the fact that My Anime List only has three episodes listed, though AniDB and others have the whole season. How can I force this working.

**Comment by ZeroQI** [comment]
As per the readme first line "If all video files are showing in plex at the right season and episode number, the scanner did its job". 
What does "not being picked up" mean? not showing or not getting metadata?
Are the files showing in Plex?
Please attach custom scanner logs  and also custom series logs, both in Hama agent data folders, location in the read-me

**Comment by ZeroQI** [comment]
no answer, no logs attached despite being documented in thee readme, closing
