### ISSUE TITLE
Multi season animes are not populating metadata info on defaulttvdbseason='a'

### ISSUE THREAD

**Issue by EndOfLine369** [ZeroQI/Hama.bundle#25]
https://gist.github.com/EndOfLine369/8ee08c812a5f3943e6cc/revisions
Linked file is based off of a 2016-03-21 pull.

If you agree on my changes, i'll create a fork for the changes so you can just pull into the master.

The proposed fix is attached w/ a minor log update as well. The issue is when defaulttvdbseason='a' it will have numbering set used in the 'tvdb_table' as just numbers 1->9999. As we could have the possibility of multiple seasons for any anime defined with asdefaulttvdbseason= 'a' by either using 'absolute_numbering' in the scanner or the files have been manually separated into separate season folders with new numbers. In which case we would need to override the numbering to be "s[0-9]+e[1-9][0-9]*"

```python
====Line 257====
FROM:
          numbering = getElementText(episode, 'absolute_number') if defaulttvdbseason=="a" else "s" + getElementText(episode, 'SeasonNumber') + "e" + getElementText(episode, 'EpisodeNumber')
TO:
          numbering = getElementText(episode, 'absolute_number') if (defaulttvdbseason=="a" and not (len(media.seasons)>2 or max(map(int, media.seasons.keys()))>1)) else "s" + getElementText(episode, 'SeasonNumber') + "e" + getElementText(episode, 'EpisodeNumber')

====Line 313====
FROM:
            for item_part in media_item.parts:  Log("File: '%s'" % item_part.file)
TO:
            for item_part in media_item.parts:  Log("File: '%s' '%s'" % (ep, item_part.file))

```

**Comment by EndOfLine369** [comment]
Actually, is there any reason to use numbering as 1->9999? Should we just do this?

```
====Line 257====
FROM:
          numbering = getElementText(episode, 'absolute_number') if defaulttvdbseason=="a" else "s" + getElementText(episode, 'SeasonNumber') + "e" + getElementText(episode, 'EpisodeNumber')
TO:
          numbering = "s" + getElementText(episode, 'SeasonNumber') + "e" + getElementText(episode, 'EpisodeNumber')
```

**Comment by ZeroQI** [comment]
The only thing feeding this array is:
if guid != "":
        try:
          Log("TVDB season mode enabled, serie url: 'http://thetvdb.com/api/A27AD9BE0DA63333/series/%s/all/en.xml'" % guid)
          tvdbanime =  etree.fromstring( urllib2.urlopen('http://thetvdb.com/api/A27AD9BE0DA63333/series/%s/all/en.xml' % guid).read() )
          for episode in tvdbanime.xpath('Episode'):
            SeasonNumber    = episode.xpath('SeasonNumber'   )[0].text if episode.xpath('SeasonNumber'   )[0].text else ''
            EpisodeNumber   = episode.xpath('EpisodeNumber'  )[0].text if episode.xpath('EpisodeNumber'  )[0].text else ''
            absolute_number = episode.xpath('absolute_number')[0].text if episode.xpath('absolute_number')[0].text else ''
            if absolute_number:  tvdb_mapping[int(absolute_number)] = (int(SeasonNumber), int(EpisodeNumber))
       

So IF somebody force a tvdbid in folder name or in a tvdb.id file in series folder or Extras folder inside it, it build a mapping list (abs ep number => (season, ep)) to make the absolute series show up with seasons, and is converted just before adding the files

If serie is split in seasons, it is in tvdb mode and i think i didn't account for season folders and tvdb,id forced. maybe i should put tvdbabs-xxxxxx to take tvdbid and let know there is a need for mapping or not. you fix isn't bad in that regards but better not mapping if not needed

**Comment by EndOfLine369** [comment]
Thanks for the feedback. I must think more on this as still trying to figure out all the code......

It seems to not really matter if 
`if tvdbid.isdigit(): ### TVDB ID exists ####`
to determine if you need to build the table and use abs numbering or season numbering. But if there is a season# >1 
`len(media.seasons)>2 or max(map(int, media.seasons.keys()))>1`
?

This same logic below could be used to build the tvdb_table right before the usage loop of `for media_episode in media.seasons[media_season].episodes:` as there will always be a `if tvdbid.isdigit():` as long as the mapping is in the master list. But it could then be all pointless as there is only a season1 (w/ maybe a season0) and it uses the orininal anidb id section.
```
If season1 in seasons && season count = 1:
  Build the table using abs ep numbering
elif season0 in seasons && season1 in seasons && season count = 2
   Build the table using s0eY for episodes with no abs tvdb number (specials) and use abs numbering for all other episodes (season1 eps)
else (a season list that is not just season1 (ignoring specials). Meaning a season1+ exists)
  Build the table using s0eY for numbering
```
I would move all of the TVDB work just under the `if not movie and (len(media.seasons)>2 or max(map(int, media.seasons.keys()))>1 or metadata.id.startswith("tvdb-")):` section as that is all it will only be used and would not waste any cycles. right?

**Comment by EndOfLine369** [comment]
Ok, it was stuck in my head.  =)
I have made updates to the code but not tested. You can see what I mentioned previously setup. 
https://gist.github.com/EndOfLine369/8ee08c812a5f3943e6cc
Take a look, see what you think and get back to me.

**Comment by EndOfLine369** [comment]
Take a look. It works with the updates in the scanner for tvdb2/tvdb3. in addition to the above issues.
https://gist.github.com/EndOfLine369/8ee08c812a5f3943e6cc

**Comment by EndOfLine369** [comment]
This can now be closed out as base has been updated with the fix per other issue ticket https://github.com/ZeroQI/Absolute-Series-Scanner/issues/11
