### ISSUE TITLE
Unable to Get Metada for Gundam Seed

### ISSUE THREAD

**Issue by miracle152004** [ZeroQI/Hama.bundle#250]
Hi,

every time I am trying to get the metadata for Gundam Seed I am getting the following error log in the agent-update.log:

`=== Update ==================================================================================================================================================
id: anidb-252, title: None, lang: en, force: True, movie: False
-------------------------------------------------------------------------------------------------------------------------------------------------------------
AnimeLists.GetMetadata() - tvdb_numbering: False
[+] AniDBid:   252, TVDBid:  74474, defaulttvdbseason:  1, offset:   0, name: Kidou Senshi Gundam SEED
    - season: [ 0],           [ 0], range:      [000-000], offset:   0, text: 1-4;2-7;3;8
Exception in the update function of agent named 'HamaTV', called with guid 'com.plexapp.agents.hama://anidb-252?lang=en' (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-10d48da0d/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 133, in update
    def update (self, metadata, media, lang, force ):  Update (metadata, media, lang, force,  False)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 108, in Update
    dict_AnimeLists, AniDBid, TVDBid, TMDbid, IMDbid, mappingList =  AnimeLists.GetMetadata(media, movie, error_log, metadata.id,                   AniDBMovieSets) #, AniDBTVDBMap
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/AnimeLists.py", line 109, in GetMetadata
    Log.Warn("'anime-list TVDBid missing.htm' log added as tvdb serie id missing in mapping file: '%s'" % TVDBid)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-10d48da0d/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

Serializing to /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Metadata/TV Shows/1/59dbf1589cf00b71b2fcb7e842cbcf594c043d3.bundle/Contents/com.plexapp.agents.hama/In$
Sending packed state data (104 bytes)
Response: [200] str, 16 bytes`

Could you please take a look.

Thanks.

Best regards
miracle152004

**Comment by ZeroQI** [comment]
Raised GitHub bug report for ScudLee's mapping file, https://github.com/ScudLee/anime-lists/issues/145
";1-4;2-7;3;8", Should be ";1-4;2-7;3-8;" which should not exist
Corrected source code to ignore such errors (never seen before)
Please update source code to latest, refresh metadata, and feedback.
Please consider donating

**Comment by miracle152004** [comment]
Hi,
Thanks.
It works now without problem.

Best regards
miracle152004
