### ISSUE TITLE
Unable to obtain metadata after fixing a match

### ISSUE THREAD

**Issue by NextFire** [ZeroQI/Hama.bundle#251]
Logs: [com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/2453002/com.plexapp.agents.hama.log)

Hello,
I have updated HAMA and ASS to latest version but I now get errors in logs and no metadata refresh after I do "fix match" on an anime, and trying for exemple here to switch from anidb (default match) to tvdb ([tvdb-345596]) for Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai.

**Comment by ZeroQI** [comment]
tvdbid '345596' doesn't exist in mapping file [https://github.com/ScudLee/anime-lists/blob/master/anime-list-master.xml] and hama cannot handle that, and that's rare enough to not have a tvdbid. Generally by the time i look it is resolved as the mapping file got updated...
```
  <anime anidbid="13900" tvdbid="" defaulttvdbseason="" episodeoffset="" tmdbid="" imdbid="">
    <name>Seishun Buta Yarou wa Bunny Girl Senpai no Yume o Minai</name>
  </anime>
```
It aired 2 days ago. i would recommand to update AnimeLists with the tvdb id and ep mappings
I uploaded a new Hama version to handle

**Comment by NextFire** [comment]
Ok thanks, it's working better now, I gave you some tips since it's not the first time you help me

**Comment by ZeroQI** [comment]
Thanks for that.

**Comment by NextFire** [comment]
It seems the anime-list-master.xml just been updated!

**Comment by ZeroQI** [comment]
Excellent, issue resolved and code manages this type of errors better, win-win
