### ISSUE TITLE
Bug - Anidb4 - Posters not downloading 

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#256]
Testing the latest HAMA released today.  I believe I found a bug (I can't mark it in this repository) 

I've moved my Durarara!! over to anidb4 (which works great).  I noticed that in seasons 3 and 4, episode posters are not downloading.  They do not appear to be in the logs either. 

See the difference:

```
metadata.seasons[ 2].episodes[ 12]
[?] rank: 0, source_title: TheTVDB, title: "Adversity Makes a Man Wise"
[x] title                          Sources: (TheTVDB), AniDB                                              Inside: '['TheTVDB', 'AniDB']'  Value: 'Adversity Makes a Man Wise'
[x] summary                        Sources: (TheTVDB),AniDB                                               Inside: '['TheTVDB', 'AniDB']'  Value: 'The flashpoints that had been smoldering in several places unleash major mayhem,..'
[x] originally_available_at        Sources: (TheTVDB), AniDB                                              Inside: '['TheTVDB', 'AniDB']'  Value: '2015-03-28'
[x] directors                ( 1)  Sources: (TheTVDB),AniDB                                               Inside: '['TheTVDB']'  Value: '[u'Takahiro Omori']'
[x] rating                         Sources: (AniDB), TheTVDB, MyAnimeList, TheMovieDb, OMDb               Inside: '['TheTVDB', 'AniDB']'  Value: '7.23'
[x] thumbs                   ( 1)  Sources: (TheTVDB)                                                     Inside: '['TheTVDB']'  Value: '{'https://thetvdb.plexapp.com/banners/episodes/133341/5143651.jpg': ('TheTVDB/episodes/5143651.jpg', 1, None)}'
[x] duration                       Sources: (TheTVDB), AniDB, MyAnimeList, TheMovieDb, OMDb               Inside: '['TheTVDB', 'AniDB']'  Value: '25'
[x] content_rating                 Sources: AniDB, (TheTVDB)                                              Inside: '['TheTVDB']'  Value: 'TV-14'
[x] absolute_index                 Sources: (TheTVDB)                                                     Inside: '['TheTVDB']'  Value: '36'
metadata.seasons[ 3]--------------------------------------------------------------------------------------------------------------------------------------
metadata.seasons[ 3].episodes[  1]
[?] rank: 0, source_title:   AniDB, title: "Love Thy Enemy"
[x] title                          Sources: TheTVDB, (AniDB)                                              Inside: '['AniDB']'  Value: 'Love Thy Enemy'
[x] summary                        Sources: TheTVDB,(AniDB)                                               Inside: '['AniDB']'  Value: 'With news of Izaya`s hospitalization quickly spreading, the information broker i..'
[x] originally_available_at        Sources: TheTVDB, (AniDB)                                              Inside: '['AniDB']'  Value: '2015-07-04'
[x] rating                         Sources: (AniDB), TheTVDB, MyAnimeList, TheMovieDb, OMDb               Inside: '['AniDB']'  Value: '4.76'
[x] duration                       Sources: TheTVDB, (AniDB), MyAnimeList, TheMovieDb, OMDb               Inside: '['AniDB']'  Value: '1500000'
```

[Anidb4.zip](https://github.com/ZeroQI/Hama.bundle/files/2519630/Anidb4.zip)

Just an observation -- I've also included a test library of how I have it named.  I'm using Durarara!! as a parent folder and the seasons within it.  This seems to work fine - the only thing I noticed is the scanner's .filelist overwrites itself on each sub-folder scan.  

[Test Library.zip](https://github.com/ZeroQI/Hama.bundle/files/2519648/Test.Library.zip)

**Comment by sven-7** [comment]
Question - in anidb4 - are all posters getting pushed to the main series poster and not the season level? I'm getting all of my posters on the series level, a single poster for season one, and none for seasons 2, 3, or 4.

**Comment by EndOfLine369** [comment]
This is not a bug. This is just the current state of things when using either 'anidb3' for the new seasons that are added at the end of known TVDB seasons OR 'anidb4' for **any** new season inserted around TVDB seasons.
As they are not recognized TVDB seasons, there is no season poster to pull.

**Comment by sven-7** [comment]
Ah, okay. I had assumed since it was pulling the metadata for episodes (i.e. descriptions) it was just missing the poster portion. Thanks for the info! I’ll close this.

**Comment by ZeroQI** [comment]
Anidb could be used to provide season posters but the use case is too limited, the code awfully complex already. I agree with bug report closure. Thanks for reporting and replying.

**Comment by EndOfLine369** [comment]
@sven-7 can you open up a ticket in ass about the filelist. I will fix (already know what to do) but need a reminder :)

@ZeroQI, we can have AniDB series posters be put in the season poster list for the ones its in in general. So if in this mode or even just if there is no TVDB poster for the season, the season would have posters added instead of just defaulting to match the Plex series poster

**Comment by sven-7** [comment]
> can you open up a ticket in ass about the filelist. I will fix (already know what to do) but need a reminder :)

Consider it done!

**Comment by sven-7** [comment]
Yep - worked perfectly.  Durarara!! is showing up with all relevant posters from AniDB. 

<img width="1142" alt="screen shot 2018-10-27 at 12 06 40 am" src="https://user-images.githubusercontent.com/18091557/47599436-5466de80-d97c-11e8-82dd-47cf20ea17d3.png">

**Comment by sven-7** [comment]
While messing around - it occurred to me that it's too bad Plex doesn't make better use of the "summary" field for seasons.  The only place I can see it is Plex Web (that I've tried thus far).  

I think a mode like anidb4 presents a unique opportunity to take the summary from the anidb id and place it as a season description.  TVDB doesn't support that kind of metadata (yet - apparently it's on the list to be added).  Not requesting this as a feature - more just throwing a random feature idea. 

It could theoretically look like this:

<img width="1162" alt="screen shot 2018-10-27 at 12 10 37 am" src="https://user-images.githubusercontent.com/18091557/47599474-ea026e00-d97c-11e8-9751-d7e73769fd7c.png">

**Comment by EndOfLine369** [comment]
What I would really love from Plex, is to be able to name the seasons. Then this summary would be a perfect match for that as well.

**Comment by MagellanSails** [comment]
I haven't bothered making that change in awhile, but I will see if I can dig it up / if it still works. If I remember correctly, Plex stores season names you just have to update the "edit season" dialog in plex web to expose the field. Then you can update it and lock it. 

I'll check in a few hours.

**Comment by ZeroQI** [comment]
Lambda was donne to update and download collection summary field. Should be able to do the same with season summaries
