### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#26]
I can't call this an issue, per say, but can the logs in \Plug-in Support\Data\com.plexapp.agents.hama\DataItems be deleted and refreshed?  I'd like to find a way to see what series or episode metadata is considered missing without having to manually comb through my library.  

Do the logs that are there refresh or build up over time?

**Comment by ZeroQI** [comment]
I created html lists of that in dataitems folder. All files described in agent readme whose link is in my signature

**Comment by sven-7** [comment]
If I delete the html files, will they re-populate? I notice the same things are in the files each time.

**Comment by ZeroQI** [comment]
Weird. I made them so it inly contain unique lines... yes it recreate them
upon deletion

**Comment by sven-7** [comment]
Perfect -- thanks.  

I think with the latests commits, if tvdb2 or 3 might be selected, it's creating some extra missing episodes.  The ones below aren't missing at all.  I have a lot more listed in the log (I'll save a copy before deleting in case you'd like to see it).

Here is an excerpt so that you can see:

>anidbid: 11210, Title: 'Dragon Ball Chou (Super)', Missing Episodes: [' s1e4', ' s1e3', ' s1e2', ' s1e1', ' s1e8', ' s1e7', ' s1e6', ' s1e5', ' s1e10', ' s1e9', ' s1e13', ' s1e12', ' s1e11', ' s1e15', ' s1e14', ' s1e19', ' s1e17', ' s1e16', ' s1e22', ' s1e21', ' s1e20', ' s1e25', ' s1e24', ' s1e23', ' s1e28', ' s1e27', ' s1e26', ' s1e33', ' s1e32', ' s1e31', ' s1e30', ' s1e29', ' s1e36', ' s1e35', ' s1e34', ' s1e40', ' s1e39', ' s1e38', ' s1e37']
anidbid: 11210, Title: 'Dragon Ball Chou (Super)', Missing Episodes: [' s1e40', ' s1e39', ' s1e38', ' s1e37']
anidbid: 02369, Title: 'Bleach', Missing Episodes: [' s1e74', ' s1e75', ' s1e134', ' s1e277', ' s1e276', ' s1e275', ' s1e278', ' s1e280', ' s1e282', ' s1e281', ' s1e279', ' s1e290', ' s1e289', ' s1e288', ' s1e287', ' s1e286', ' s1e285', ' s1e284', ' s1e283', ' s1e291', ' s1e294', ' s1e293', ' s1e292', ' s1e296', ' s1e295', ' s1e300', ' s1e299', ' s1e298', ' s1e297', ' s1e303', ' s1e302', ' s1e301', ' s1e304', ' s1e308', ' s1e307', ' s1e306', ' s1e305', ' s1e310', ' s1e309', ' s1e312', ' s1e311', ' s1e315', ' s1e314', ' s1e313', ' s1e316', ' s1e320', ' s1e319', ' s1e318', ' s1e317', ' s1e328', ' s1e327', ' s1e326', ' s1e325', ' s1e324', ' s1e323', ' s1e322', ' s1e321', ' s1e329', ' s1e330', ' s1e334', ' s1e333', ' s1e332', ' s1e331', ' s1e338', ' s1e337', ' s1e336', ' s1e335', ' s1e340', ' s1e339', ' s1e342', ' s1e341', ' s1e343', ' s1e347', ' s1e346', ' s1e345', ' s1e344', ' s1e348', ' s1e351', ' s1e350', ' s1e349', ' s1e352', ' s1e353', ' s1e354', ' s1e359', ' s1e358', ' s1e357', ' s1e356', ' s1e355', ' s1e360', ' s1e362', ' s1e361', ' s1e363', ' s1e364', ' s1e365', ' s1e366']
anidbid: 11210, Title: 'Dragon Ball Chou (Super)', Missing Episodes: [' s1e4', ' s1e3', ' s1e2', ' s1e8', ' s1e7', ' s1e6', ' s1e5', ' s1e10', ' s1e9', ' s1e13', ' s1e12', ' s1e11', ' s1e15', ' s1e14', ' s1e19', ' s1e18', ' s1e17', ' s1e16', ' s1e22', ' s1e21', ' s1e20', ' s1e25', ' s1e24', ' s1e23', ' s1e28', ' s1e27', ' s1e26', ' s1e33', ' s1e32', ' s1e31', ' s1e30', ' s1e29', ' s1e36', ' s1e35', ' s1e34', ' s1e40', ' s1e39', ' s1e38', ' s1e37']
anidbid: 11210, Title: 'Dragon Ball Super', Missing Episodes: [' s1e4', ' s1e3', ' s1e2', ' s1e1', ' s1e8', ' s1e7', ' s1e6', ' s1e5', ' s1e10', ' s1e9', ' s1e13', ' s1e12', ' s1e11', ' s1e15', ' s1e14', ' s1e19', ' s1e17', ' s1e16', ' s1e22', ' s1e21', ' s1e20', ' s1e25', ' s1e24', ' s1e23', ' s1e28', ' s1e27', ' s1e26', ' s1e33', ' s1e32', ' s1e31', ' s1e30', ' s1e29', ' s1e36', ' s1e35', ' s1e34', ' s1e40', ' s1e39', ' s1e38', ' s1e37']

**Comment by ZeroQI** [comment]
i think the latest Hama update solve that. please confirm

**Comment by sven-7** [comment]
Confirmed. Can close.
