### ISSUE TITLE
Python Error 123 on Windows

### ISSUE THREAD

**Issue by warsix4** [ZeroQI/Hama.bundle#262]
I am receiving this line in my error logs: 
`  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: u'\\\\?\\C:\\Users\\Administrator\\AppData\\Local\\Plex Media Server\\Plug-in Support\\Data\\com.plexapp.agents.hama\\DataItems\\_Logs\\Anime Subbed | Local'`

I believe it is because my libraries in Plex utilize the "|" symbol. Is there a fix for this or do I need to forego my plex library names?

**Comment by ZeroQI** [comment]
I can only avoid creatind a folder based on the library name which is problematic...
I could filter the character I guess...
Need to look at the the code in details

**Comment by warsix4** [comment]
Hi, just wanted to come back to you about this. Changing the library name
and removing the "|" symbol resolved my issue.
___


Cody Warmbo
warmbo.com

**Comment by ZeroQI** [comment]
I thought that would be the case, this fix should allow it without crashing as well.
Please test and close if resolved

**Comment by warsix4** [comment]
Confirmed working.
