### ISSUE TITLE
Image Priorities

### ISSUE THREAD

**Issue by EndOfLine369** [ZeroQI/Hama.bundle#263]
Hi @ZeroQI,

Need your help on this one.
Looks like image entries `['posters', 'art', 'banners', 'themes', 'thumbs']`

There are a few items found that I need you to help fix. The `UpdateMeta*` functions are eluding me on how it does its thing.

1. Majority of image rank is incorrectly hard coded (tvdb4, TMDB, FanartTV, OMDb) and only two calculated from Pref order (TVDB, AniDB)
2. If image priority changes (Pref order change) the image order in Plex does not get updated on refresh. If a new image gets added in with a higher priority than the existing highest, it wins out. But priorities of existing images do not get updated.
3. If an image is removed from the list, it does not get removed from Plex. Or at the least, moved down to the lowest priority (99). Believe this is only currently done for season posters but should be done on all.
4. And in general, why does all images from all sources get pulled/loaded? Should it not only load/pull down the source images for the first matched source? This would make refreshes faster as less to pull of files that will not be used by default. I barely, if ever, change the image used at highest priority. That is a lot of additional network traffic, time, and disk space to pull down items that are never used.

**Comment by sven-7** [comment]
Just adding comments...

If the priority is kept - where to tvdb4 images go for non-tvdb4 series? 

I do like getting all images, personally. Especially when I have a very mixed library of tvdb, anidb, and all their various modes.

**Comment by EndOfLine369** [comment]
Item 4 is more of a performance question. It should probably be a specific Pref entry to only download the first matched source as default or all sources as it currently does. So by default, it is more efficient but easy to update.

**Comment by EndOfLine369** [comment]
Oh, and for tvdb4 posters. It only pulls TVDB4 posters if `source == "tvdb4"` in `common.GetMetadata()`
`if movie or not source == "tvdb4": return {}`
If that wasn't there, it would populate the dict with the poster info (as all other sources do) and always pull it down at priority 1.

**Comment by sven-7** [comment]
I think an option to opt-in to download all would be a good idea. 

Hypothetically, if anidb was the first preference (for the library in general), but a series was a tvdb2, tvdb3, etc. how would it react?  Would it skip to that preference? 

Re: tvdb4 - that's what I thought.  I was only asking as I moved some things from tvdb4 to anidb4 to get the tvdb2 style numbering, but the posters from tvdb4 didn't come down (no big deal). Just looking to confirm.

**Comment by EndOfLine369** [comment]
> Hypothetically, if anidb was the first preference (for the library in general), but a series was a tvdb2, tvdb3, etc. how would it react? Would it skip to that preference?

AniDB would have the highest priority. HAMA pre beta chose data based on what source id used. Post beta, it is solely based on your preference listings (with tvdb4 as an exception is seems at this time).

For example, if I add in a AniDB movie using 'anidb-XXX' I could and actually do want the poster from IMDB and can define that as a pref higher listing. While series that do not have an IMDB listing from ScudLee's file would have nothing to pull and use the next available source like TVDB.
`TS-M 'poster' == tvdb4, TheMovieDb, TheTVDB, FanartTV, AniDB`

**Comment by EndOfLine369** [comment]
@ZeroQI, believe we would actually want to update the default to that. Bet people would want their movies to pull specific movie posters first than a random/incorrect TVDB poster (what I get and was annoyed with). Which is why I made the update and actually found these issues.
`TS-M 'poster' == tvdb4, TheMovieDb, TheTVDB, FanartTV, AniDB`

**Comment by ZeroQI** [comment]
1 - correct
2 - correct. Or maybe they do but active one doesn't get updated. can create a function to amend that maybe...
3 - there is a plex function to validate a list of urls and remove the ones no longer present (but not the active one)
4 - all goes in the dict but all pictures get downloaded but the active one is selected a per priority. Good point we should make a setting for that (i had in the past a setting called getsingleone).

Track Serie Movie field 'poster' priority order seem fine
- Let's change the default behaviour to download once and opt-in to download all a setting who skips after the first pic "FirstPicOnly" during the dict processing phase, through a setting "FirstPicOnly" who skips after the first pic during the dict processing phase (simpler than my earlier attempt)
- Would a magic function changing the active image be usefull? It's never been done in an agent to my knowledge...

**Comment by EndOfLine369** [comment]
> Let's change the default behaviour to download once and opt-in to download all a setting who skips after the first pic "FirstPicOnly" during the dict processing phase, through a setting "FirstPicOnly" who skips after the first pic during the dict processing phase (simpler than my earlier attempt)

I would not say the first pic. The first source. 'FirstPicSourceOnly'.

As sometimes there are better quality or different formats from a source. Perfect example of that is for long running series in TVDB get a multitude and varied types of season posters. And not the same set is always the top listing. Common for series like Bleach & Naruto (etc...). I would need all tvdb images to manually fix this inconsistency.

![image](https://user-images.githubusercontent.com/16750699/48665434-d3c76980-ea73-11e8-957e-07af08c8c7d5.png)

**Comment by ZeroQI** [comment]
Maybe it's because i am french but isn't 'FirstSourcePicOnly' more logical ?
Agreed on the source notheless. Will start thinking how to implement...

**Comment by EndOfLine369** [comment]
Lets just reverse the thinking and use "Load All Images" (default false). So default is to only load images from the first matched source.
`  { "id": "load_all_images",                    "label": "Load All Images",           "type": "bool",  "default": "false"                                                          },`

**Comment by ZeroQI** [comment]
sorry for the delay in replying.
I am off from 16th of December to the 6th of January so should have time coding that.

**Comment by ZeroQI** [comment]
Sorry for the very long response time, took weeks to correct the scanner for grouping folders, but started coding that
- disabling MyAnimeList as down since 6 month
- adding load_all_images, need to code it in commons.py still (so loading all images from first source we said?)
- need to implement pref order non hard-coded for: tvdb4, TMDB, FanartTV, OMDb
- remove pics not in list, that would make changing sources priorities remove images
- removing active image doesn't work but a function coded from Lambda code to replace active image may be possible

**Comment by ZeroQI** [comment]
Here is the current to-do list
- disabling MyAnimeList as down since 6 month
- adding load_all_images, need to code it in commons.py still (so loading all images from first source we said?)
- anidb-tvdb numbering equivalency if no mapping found
- "main" as priority back in settings for non-japanese works instead of x-jat (easy default setting)
- remove TheTVDB as studio source
- sorting anidb genres (genres below cut-off weight value are discarded)
- "Animation Works" then "Work" otherwise for animation studio
- AnimeList Studio Field support
- pref order non hard-coded for: tvdb4, TMDB, FanartTV, OMDb
- remove pics not in list, that would make changing sources priorities remove images
- removing active image doesn't work but a function coded from Lambda code to replace active image may be possible

**Comment by mdcx** [comment]
Hey, ZeroQI, can u add me on Google hangouts or discord? Or wherever for
that matter.

mike@mdcx.io for hangouts
Mdcx on discord

#mdcx on irc.rizon.net

Just wanna talk a bit about the todo and some other features

**Comment by ZeroQI** [comment]
My priority is
- ASS scanner
- Hama agent bugs
- Lambda (although hardly nobody uses it)
- Youtube bug

Here is the current to-do list, in progress
- disabling MyAnimeList as down since 6 month
- adding load_all_images, need to code it in commons.py still (so loading all images from first source we said?)
- anidb-tvdb numbering equivalency if no mapping found
- "main" as priority back in settings for non-japanese works instead of x-jat (easy default setting)
- remove TheTVDB as studio source
- sorting anidb genres (genres below cut-off weight value are discarded)
- pref order non hard-coded for: tvdb4, TMDB, FanartTV, OMDb
- remove pics not in list, that would make changing sources priorities remove images
- removing active image doesn't work but a function coded from Lambda code to replace active image may be possible

**Comment by EndOfLine369** [comment]
FYI, spent some time and hammered out some code for this long open issue ticket.
It's untested at this time but was local so shoved into a branch so I didn't loose it. https://github.com/ZeroQI/Hama.bundle/compare/EOL-Image-Priorities

**Comment by EndOfLine369** [comment]
With image priorities now done, the only piece left for this ticket is the implementation of `load_all_poster_sources`.

`  { "id": "load_all_poster_sources",  "label": "Load all poster metadata sources","type": "bool",  "default": "false"                                                          },`

**Comment by ZeroQI** [comment]
Listing all logical choices, not advocating a drop-down setting to select all as I want simplicity if possible, but that is a possibility.
(*) represent all options offered by the "load_all_poster_sources" scope...

List of images' fields involved: (we need to avoid duplicate posters and banners, but duplicate art, thumbs are not visually impacting negatively)
- image_field_restriction = [posters] (*)                      #include season and series and movies posters
- image_field_restriction = ['posters', 'banners']         #include season and series and movies posters
- image_field_restriction = ['posters', 'banners', 'art'] #include season and series and movies posters/art
- image_field_restriction = ['posters', 'banners', 'art', 'thumbs']

So image_field_restriction = ['posters', 'banners'] i would go for logically

There is a need for a setting to restrict the images downloaded:
- load_one_image_from_one_source
- load_one_image_from_all_sources
- load_all_images_from_one_source
- load_all_images_from_all_sources (*)

Note sure if going for load_all_images_from_all_sources bolean...

We need to break the 'source' or 'source list' loop withing the 'field' loop (for the list of fields involved) when we reach the conditions:
- selection contains  'from_one_source' and one image was loaded from one source, use a bolean 'image_source_found' set within the loop for source and reset for each field
- selection contains 'load_one_images' and one image was loaded

@EndOfLine369 What do you think?
- image_field_restriction = ['posters', 'banners'] which include season posters ?
- load_all_images_from_all_sources Boolean or drop-down setting with all 4 choices?

**Comment by EndOfLine369** [comment]
This is interesting and is a lot to think over.

Before that though, I think I might have found a way to unset the chosen poster image and have it default to the highest priority image which can only be done at this time by Plex Dance. I'm trying to figure out how to implement it cleanly. Currently, in my testing it requires 2 subsequent refreshes to happen. (1) to update the poster info/priorities (2) to reset based on previous poster info update. As when done in the `update()` call, the metadata has yet to be processed by Plex to have the updated info/priorities. So all it does is reset the image for the previous/old info/priorities. I've also thought about having it potentially dump out the commands needed into a shell/ps1 file that they can either choose to execute it as a whole manually after scan. That though is probably a last resort as we loose automation from things being fully handled internally. Ideally, I trying to find if these is some way to have a form of post processing function that is called after the update() one. Just like there is a `ValidatePrefs()` one that is outside the search/update.

**Comment by ZeroQI** [comment]
We could put it in ValidatePrefs() to be run once a day maybe?
Edit: i don't get why it's misbehaving but make sure you have no database corruption. Lost days of coding due to a funky database once

**Comment by EndOfLine369** [comment]
If corrupted, good. Best way to make sure it will work 100% of the time as I for one am not going to recreate my libraries.
I've now been able to get it to select the highest priority poster in the same refresh call after the new metadata is loaded.

**Comment by EndOfLine369** [comment]
Just refreshed my small ~70 series library that now has both the previously committed dynamic poster priority fix & now this poster reset function. Most were reset for the better as now following setting priorites. Rest stayed the same except 2 which changed to a non-related non-anime poster...

**Comment by EndOfLine369** [comment]
I think there is also an improvement needed to TheTVDB posters. To see if it is possible to have it prioritize poster languages according to HAMA language settings. As for one series I can see both English & Japanese posters but it chose Japanese as just happened to be the first entry in the TVDB json response Where I would want it to match my language settings and choose the English one. They use to have both language & ratings tied to them but when I last checked, the ratings were all zero so could be defunt system on their site. ☹️ Will have to look deeper on that.

**Comment by EndOfLine369** [comment]
Fixed/Enhanced image issues found in TheTVDB.
60555353593059e4d4f68d8e5a0bb71d82694caf - Remove redundant if test 
As is a blank string (Dict default) "isdigit()" will return false
1a7698a9a8c09354d745bf5300cf5c5cce2023d7 - Pull all banners from TVDB
be599afafaa671ceeccd82e60b5fc7cbe00bd87b - Fix rating count dict path
0d3401a3a591c8a0165e26c0f3fc642aa540306b - Adjust image priority per rating and main image 
This was accidently lost when converted to "common.poster_rank()". As images are sorted by rating average, just add the image count to the rank using "poster_rank()" already included "rank_adjustment" parameter. And if the image is the primary one assigned to the main entry, set it to the highest priority (0/no adjustment).

**Comment by EndOfLine369** [comment]
With images now correct and updating primary, found this bug:
403b026f4c1333d8e842b64a687b92dddc481aac - Fix "dict_FanartTV" to adjust seasons when "anidb4/tvdb6" …
With images now being set correctly, it was found that "dict_FanartTV" hosted mulit season posters so it also needs to be adjusted with "dict_TheTVDB" when "anidb4/tvdb6"

**Comment by ZeroQI** [comment]
@EndOfLine369 Any remaining issue on this ticket, or can we close? Anuthing you want me to work on?
You probably have seen Plex Arcade?

**Comment by faufnir** [comment]
@EndOfLine369 @ZeroQI Would really appreciate your help on this one, seems that poster priority is still being ignored for me? Am I missing something? See attached preferences file.

Thanks in advance~
[com.plexapp.agents.hama.zip](https://github.com/ZeroQI/Hama.bundle/files/13994260/com.plexapp.agents.hama.zip)
