### ISSUE TITLE
One Piece - Episode metadata off by one

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#264]
Hello -

Sorry to bring up another absolute episode issue.  Looks like the metadata is off by one for One Piece.  I'm assuming this happens after [episode 590](https://www.thetvdb.com/series/one-piece/episodes/4543896/edit), which is officially the absolute number, however, it is also officially a special.  Any thoughts on how I can get things re-aligned?  I've tried a handful of different configurations, but no luck.

Appreciate the help.

[OP Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/2593001/OP.Logs.zip)

**Comment by EndOfLine369** [comment]
Absolute numbers in TVDB are ignored unless using tvdb5.
Please fix your numbering to ignore any non-season 1+ episodes in your abs number count.

**Comment by sven-7** [comment]
Meaning I need to rename everything after episode 590 down by 1?

**Comment by EndOfLine369** [comment]
That, or use the episode offset ability in the scanner and have two folders
```
1-589 --> "G:\Series OS\One Piece [tvdb4-81797]"
591+  --> "G:\Series OS\One Piece [tvdb4-81797-e-1]"
```

**Comment by sven-7** [comment]
That did it -- that's a neat trick. Thanks for the advice!
