### ISSUE TITLE
anidb metadata (studio not fetched)

### ISSUE THREAD

**Issue by AsuraAce** [ZeroQI/Hama.bundle#269]
hi,

in some cases the animation studio wont be fetched, probably because anidb uses "animation work" (works) in some cases and "work" (doesn't work) in others.

any plans to fix this?

**Comment by ZeroQI** [comment]
Would you have a link to the http XML exemple in each case? If so it can be ammended

**Comment by AsuraAce** [comment]
do you mean a regular link?

if you look for "animation work" the studio displayed is the correct one (this works with hama).
https://anidb.net/perl-bin/animedb.pl?show=anime&aid=13831

here you have to look for "work" (animation studio is not present and therefore doesn't work with hama)
https://anidb.net/perl-bin/animedb.pl?show=anime&aid=10445

if you meant something else, i need a little bit of help, don't how to look up the http xml.

**Comment by EndOfLine369** [comment]
Hi @ZeroQI,

Studio is setup to be pulled from sources: AnimeLists / AniDB / TheMovieDB / TheTVDB

For AniDB, it uses AniDB's "Animation Work" for Plex 'studio'.
```python
        roles    = { "Animation Work":"studio", "Direction":"directors", "Series Composition":"producers", "Original Work":"writers", "Script":"writers", "Screenplay":"writers" }
```
We could potentially put in `"Work":"studio"` into the dict but if both are present, the one that is chosen could change or not be the correct/preferred one.
We would also have to update the test logic to maybe take the 'Animation Work' as priority...
```python
            if roles[role]=="studio":  SaveDict(creator.text, AniDB_dict, 'studio')
            else:                      SaveDict([creator.text], ep_roles, roles[role])
```


EX: Shokugeki no Souma https://anidb.net/perl-bin/animedb.pl?show=anime&aid=10901 :
```xml
<creators>
<name id="19696" type="Series Composition">Yasukawa Shougo</name>
<name id="720" type="Animation Work">J.C.Staff</name>
<name id="2932" type="Character Design">Shitaya Tomoyuki</name>
<name id="1531" type="Direction">Yonetani Yoshitomo</name>
<name id="10106" type="Music">Katou Tatsuya</name>
<name id="41316" type="Original Work">Tsukuda Yuuto</name>
<name id="41317" type="Original Work">Saeki Shun</name>
<name id="11736" type="Chief Animation Direction">Matsuura Mai</name>
<name id="997" type="Work">Mainichi Housou</name>
<name id="7078" type="Chief Animation Direction">Itou Youko</name>
</creators>
```

**Comment by ZeroQI** [comment]
@EndOfLine369 On the 3 examples put forth, I can see a working preference:
- "Animation Work" is the primary field
- "Work" if "Animation Work" is not present.
Plex only allow a single string so we take the first one only if multiples
We need to update the test logic to take the 'Animation Work' as priority

**Comment by KurtzPT** [comment]
Just noticed this problem on the following anime: 
**AniDB:** https://anidb.net/perl-bin/animedb.pl?show=anime&aid=979
**AnimeList:** https://myanimelist.net/anime/121/Fullmetal_Alchemist
**TVDB:** https://www.thetvdb.com/series/fullmetal-alchemist

The studio was set to "Animax" that is totally wrong. It seems it didn't get any studio from either anidb or animelist, so it got the Animax from tvdb.

**TVDB** network field should never be used to fill the plex studio field in my opinion, it's two total different things.
**AnimeList** does say "Studios: Bones", but somehow it wasn't picked up, so this is not really working well.

AniDB xml doesn't have any field available to use for studio so I guess at least in my case, the problem was that Hama never got the correct studio from AnimeList which is the 1st source entry to get the studio field.

`<creators>
<name id="130" type="Direction">Mizushima Seiji</name>
<name id="1007" type="Original Work">Arakawa Hiromu</name>
<name id="3626" type="Music">Ooshima Michiru</name>
<name id="7788" type="Chief Animation Direction">Itou Yoshiyuki</name>
<name id="7788" type="Character Design">Itou Yoshiyuki</name>
</creators>`

**Comment by KurtzPT** [comment]
Just researched a bit, seems MyAnimeList API is down for half a year or more. It seems the site was bought not long ago ( https://twitter.com/myanimelist/status/1085114516151635973 ).

Either wait for something to change with this new administration coming in for MAL, that hopefully will fix the API or I have a new suggestion for another source to use for scrapping information: **AniList**.
**Site:** https://www.anilist.co/
**API:** https://anilist.gitbook.io/anilist-apiv2-docs/

**Comment by ZeroQI** [comment]
i will remove tvdb as studio source, and MyAnimeList as it is down
AnimeLists has a studio field when AniDB is misisng it/is incorrect (rare)

**Comment by EndOfLine369** [comment]
Hey @ZeroQI, was taking a look at this and seems like the writer/director/... crew from AniDB stored in 'ep_roles' is not used. It was commented out in this commit. Remember why?
https://github.com/ZeroQI/Hama.bundle/commit/1c690e9e33ebfd4e28a9bf6801ec30178ba742a7#diff-2830fca5ce651439aa66390fb407992aR160

Believe I have this coded. Still testing. FYI, also looks like it was not adding in the crew if it was a movie either. Was also adding the the studio for more than just the primary AniDB id.

**Comment by ZeroQI** [comment]
@EndOfLine369 i don't remember but it should be enabled for primary AniDB id only and work for movies too.
From the look of it, i considered it and added commented as i hadn't tested it and could barely find series affected by it

**Comment by EndOfLine369** [comment]
Done

**Comment by ZeroQI** [comment]
Brilliant :)

**Comment by EndOfLine369** [comment]
@ZeroQI, noticed something strange when looking at log output regarding duration value requirements. Is these also even used by Plex? It seems that it actually pulls it from the video files directly.

Cut out some of the fluf from the dicts to make it clearer.
```python
TheTVDB_dict: {
  'duration': 1500000,
  'seasons': {    
    '0': {
      'episodes': {        
        '9': {
          'duration': '25', 'title': 'Pure Pure Pleiades - OVA'},

AniDB_dict: {
  'duration': 0,
  'seasons': {    
    '0': {      
      'episodes': {        
        '9': {
          'duration': 1800000, 'title': 'OAD'},
```
Pieces of code that log duration:
```python
#########################
AniDB.py:
          if GetXml(ep_obj, 'length').isdigit():
            SaveDict(int(GetXml(ep_obj, 'length'))*1000*60, AniDB_dict, 'seasons', season, 'episodes', episode, 'duration')  # AniDB stores it in minutes, Plex save duration in millisecs
            if season == "1":  numEpisodes, totalDuration = numEpisodes+1, totalDuration + int(GetXml(ep_obj, 'length'))
...
        if SaveDict(int(totalDuration)/int(numEpisodes) if int(numEpisodes) else 0, AniDB_dict, 'duration'):
          Log.Info("Duration: {}, numEpisodes: {}, average duration: {}".format(str(totalDuration), str(numEpisodes), AniDB_dict['duration']))
#########################
OMDb.py:
      try:     Log.Info("[ ] duration: {}".format(SaveDict( int(Dict(json,'Runtime').replace(' min','')) * 60 * 1000, OMDb_dict, 'duration')))  # Plex save duration in millisecs
#########################
TheMovieDb.py:
    Log.Info("[ ] duration: {}"               .format(SaveDict( Dict(json, 'runtime'),                            TheMovieDb_dict, 'duration'               )))
...
    try:     Log.Info("[ ] duration: {}".format(SaveDict( int(Dict(json, 'duration')) * 60 * 1000,  TheMovieDb_dict, 'duration')))
#########################
TheTVDBv2:
    if Dict(serie_json, 'runtime') and Dict(serie_json, 'runtime').isdigit():
      Log.Info('[ ] duration: {}'             .format(SaveDict(int(Dict(serie_json, 'runtime'))*60*1000, TheTVDB_dict, 'duration'               )))  #in ms in plex
...
        SaveDict( Dict(serie_json  , 'runtime'   ), TheTVDB_dict, 'seasons', season, 'episodes', episode, 'duration'               )
```

**Comment by ZeroQI** [comment]
Plex and AniDB use it in milliseconds Thetvdb in minutes.
The metadata for episodes allow to set it...
It use it to indicate series duration if i recall

**Comment by EndOfLine369** [comment]
So correct, Plex is the determination and you said it is in ms. So will need to correct TVDB to be in ms instead of its current min as shown in the above dict. And AniDB is not correctly listing the total on the series so that will need to be fixed.

**Comment by ZeroQI** [comment]
Both the episode and the series runtime fields are the runtime in ms of the/one episode

**Comment by EndOfLine369** [comment]
Ah, ok. Series level will be episode average.

**Comment by ZeroQI** [comment]
@EndOfLine369 It seems anidb studio if fetched from animelists and AniDB, if so, we can close this ticket.

**Comment by EndOfLine369** [comment]
AnimeLists's Studio is not being pulled if a tvdb source. 
And will fix the duration as noted above as well (tvdb ep is a min string/anidb series is missing)

**Comment by EndOfLine369** [comment]
Fixed in branch. Testing ongoing.

**Comment by EndOfLine369** [comment]
Branch merged
