### ISSUE TITLE
Series descriptions have invalid links

### ISSUE THREAD

**Issue by EndOfLine369** [ZeroQI/Hama.bundle#27]
Hey ZeroQI,

Looks like something changed, is being changed, or went wrong in the AniDB API for series description text.

I say 'went wrong' as the URLs are invalid "http://anidb.net/perl-bin/https://anidb.net/ch79575". And it doesn't even have the text for an '\<a\>' html tag for us to leave in.

**EX**: http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=11893
```
<description>On a continent ruled by sword and magic called Kunaaan, there are three kingdoms with a 
fragile power balance that could spell disaster and war at any moment. Another power, the evil dragon 
Daganzord, also resides on the continent, and no one is powerful enough to stop him from spreading 
destruction in his wake. Bairo and Kismitete, and a party of wizards attempted to seal the dragon, but 
were foiled. This event becomes known thereafter as the Balbagoa Tragedy. Bairo and Kismitete`s son 
http://anidb.net/perl-bin/https://anidb.net/ch79575 is saved by http://anidb.net/perl-bin/https://anidb.net/ch79568, 
and Hiiro swears to avenge his parents` deaths and trains himself with the sword. When Hiiro turns 16, 
he sets out on a journey to slay the dragon, and Gill accompanies him, having no choice. Along the way, 
they meet many types of people and gain companions on their journey.
Source: ANN</description>
```

**Comment by EndOfLine369** [comment]
Looks like there was a site update in AniDB on the 4th that could have inadvertently broken this...
http://anidb.net/perl-bin/animedb.pl?show=cmt&id=56691
I'm still checking their boards for any relevant thread. We might need to open up our own bug thread.

**Comment by ZeroQI** [comment]
We have to replace html links with <link> not to have to open links to get
the protagonist name

If you remove the perlbin part it reloads in
https://anidb.net/perl-bin/animedb.pl?show=character&charid=79575

**Comment by EndOfLine369** [comment]
Do you want me to open up a thread for the api description issue under "Board Index > Support" AniDB forum? We need them to fix this as we don't want to try and deal with this by resolving the url to pull char info as that would potentially cause AniDB to block the IP as the URL polls would be against the main site (for un-cached data) and not the api and just to get a name. At the least, it is not even giving the text that is being used in the link. If that was the case, we could easily just remove all url text :cry:. 

At the very least, we could do that to work with any url but it would still make the sentence broken.

**From**:
```
Bairo and Kismitete`s son http://anidb.net/perl-bin/https://anidb.net/ch79575 is saved by 
http://anidb.net/perl-bin/https://anidb.net/ch79568, and Hiiro swears to avenge his parents` 
deaths and trains himself with the sword.
```
**To**:
```
Bairo and Kismitete`s son  is saved by , and Hiiro swears to avenge his parents` deaths 
and trains himself with the sword.
```

**Comment by ZeroQI** [comment]
I agree "100%". I can see few ways to solve:
   . having AniDB give the name with the link (html tag), the cleanest
   . replace links with "<link>" but we loose meaning. dirty...
   . use TVDB description. hummm not ideal...

Can't access forums at the moment (ERR_TUNNEL_CONNECTION_FAILED) but please do report it.
I believe anybody doing metadata agents will be impacted so they will correct it.

**Comment by EndOfLine369** [comment]
Issue posted http://anidb.net/perl-bin/animedb.pl?show=cmt&id=56748

**Comment by ZeroQI** [comment]
Google showed forums.anidb.net but then they are deprecated... Thanks for that, much appreciated.

**Comment by EndOfLine369** [comment]
They have fixed the issue now and no update needed to the code as they put back as before.

EX:
```
<description>
On a continent ruled by sword and magic called Kunaaan, there are three kingdoms with a fragile power balance that could spell 
disaster and war at any moment. Another power, the evil dragon Daganzord, also resides on the continent, and no one is powerful 
enough to stop him from spreading destruction in his wake. Bairo and Kismitete, and a party of wizards attempted to seal the 
dragon, but were foiled. This event becomes known thereafter as the Balbagoa Tragedy. Bairo and Kismitete's son 
http://anidb.net/ch79575 [Hiiro] is saved by http://anidb.net/ch79568 [Gill], and Hiiro swears to avenge his parents' deaths and 
trains himself with the sword. When Hiiro turns 16, he sets out on a journey to slay the dragon, and Gill accompanies him, having 
no choice. Along the way, they meet many types of people and gain companions on their journey. Source: ANN
</description>
```

**Comment by EndOfLine369** [comment]
This has actually just been confirmed as resolved. Initial thought that it was resolved was from them making a creq change that made it look like the issue was fixed. 

https://anidb.net/perl-bin/animedb.pl?show=cmt&id=56748
```
post by ommina on Saturday, 23.04.2016 22:18

OK, new HTTPAPI code is running, but ANIME replies are cached for several hours (12, I think), so it may be a while before the changes start appearing.

It will return "http" for both http & https bbcode links. If the client wants to leave them as http, or turn everything into https, that is up to it.

UDP and IMSERVER updates will follow in the coming hours.
```

**Comment by ZeroQI** [comment]
This got fixed thanks to you. thanks
