### ISSUE TITLE
[TVDB] (Mainly TVDB3) Season posters not acquiring

### ISSUE THREAD

**Issue by DJScias** [ZeroQI/Hama.bundle#270]
Hello there,

Figured I'd finally make an issue since I've noticed some issues regarding tvdb (be it 1 or 3) when it comes to season posters. In case of "Legend of Galactic Heroes" using the folder name `Legend of the Galactic Heroes [tvdb3-81618]` (since I'd like to use TVDB's season ordering), I'm getting this:
![image](https://user-images.githubusercontent.com/439655/50563634-d548aa80-0d1e-11e9-94af-478db2357ed9.png)
[Legend of the Galactic Heroes [tvdb3-81618].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/2718594/Legend.of.the.Galactic.Heroes.tvdb3-81618.filelist.log)
[Legend of the Galactic Heroes [tvdb3-81618].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/2718595/Legend.of.the.Galactic.Heroes.tvdb3-81618.scanner.log)

Same with Bleach, using `Bleach [tvdb3-74796]`, I'm getting this:
![image](https://user-images.githubusercontent.com/439655/50563644-e4c7f380-0d1e-11e9-9526-b617fee019f8.png)
[Bleach [tvdb3-74796].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/2718596/Bleach.tvdb3-74796.filelist.log)
[Bleach [tvdb3-74796].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/2718597/Bleach.tvdb3-74796.scanner.log)

In attachment I have all the logs I could find regarding these two series (Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\). If I'm missing something, or if more info is needed feel free to let me know and I'll try my best in providing them ASAP.

Kind regards,
DJScias

**Comment by EndOfLine369** [comment]
Hi @DJScias,
Please provide the agent logs (EX: "Bleach [tvdb3-74796].agent-update.log").
Those will be in a library folder in the "_Logs" folder.

**Comment by DJScias** [comment]
Hello there,

Attached the two files I could find in regards to tvdb3-74796.
[Bleach [tvdb3-74796].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/2730117/Bleach.tvdb3-74796.agent-search.log)
[Bleach [tvdb3-74796].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/2730118/Bleach.tvdb3-74796.agent-update.log)

**Comment by EndOfLine369** [comment]
The agent log provided looks like its not an agent run that matches your scanner log run.
The log only shows an agent load run on a single episode existing 's01e063'/'s3e22'/'s3e63'
Per:
> Missing Episodes           : ["TVDBid: <a href='http://thetvdb.com/?tab=series&id=74796' target='_blank'>74796</a> | Title: 'Bleach' | Missing Episodes: ['1-20 (s1e1-20)', '21-41 (s2e1-21)', '42 (s3e1)', '43 (s3e2)', '44 (s3e3)', '45 (s3e4)', '46 (s3e5)', '47 (s3e6)', '48 (s3e7)', '49 (s3e8)', '50 (s3e9)', '51 (s3e10)', '52 (s3e11)', '53 (s3e12)', '54 (s3e13)', '55 (s3e14)', '56 (s3e15)', '57 (s3e16)', '58 (s3e17)', '59 (s3e18)', '60 (s3e19)', '61 (s3e20)', '62 (s3e21)', '64-91 (s4e1-28)', '92-109 (s5e1-18)', '110-131 (s6e1-22)', '132-151 (s7e1-20)', '152-167 (s8e1-16)', '168-189 (s9e1-22)', '190-205 (s10e1-16)', '206-212 (s11e1-7)', '213-229 (s12e1-17)', '230-265 (s13e1-36)', '266-316 (s14e1-51)', '317-342 (s15e1-26)', '343-366 (s16e1-24)']"]

I'm guessing you did this to try and narrow down the issue from a single file load.

You can see that your server/pc is having ssl issues:
> common.SaveFile() - Exception: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:1754), url: 'https://thetvdb.plexapp.com/banners/posters/74796-6.jpg', filename: 'TheTVDB/posters/74796-6.jpg'

**Comment by DJScias** [comment]
Hello there,

What would you suggest I do to get a clearer reproduction? Or to get past that SSL issue?

Remove the whole Bleach folder, clean everything and then try to re-add and give you those logs?

**Comment by DJScias** [comment]
Hello there,

Did the Plex dance and then re-added. These are the four logs that were produced:
[Bleach [tvdb3-74796].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/2730600/Bleach.tvdb3-74796.agent-search.log)
[Bleach [tvdb3-74796].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/2730601/Bleach.tvdb3-74796.scanner.log)
[Bleach [tvdb3-74796].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/2730602/Bleach.tvdb3-74796.filelist.log)
[Bleach [tvdb3-74796].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/2730603/Bleach.tvdb3-74796.agent-update.log)

This is what it currently looks like inside Plex:
![image](https://user-images.githubusercontent.com/439655/50738355-3cf56e80-11d3-11e9-8ef0-988d7331987b.png)

**Comment by ZeroQI** [comment]
```
metadata.seasons[ 1]--------------------------------------------------------------------------------------------------------------------------------------
[?] meta_new: {'https://thetvdb.plexapp.com/banners/seasons/74796-1-5.jpg': ('TheTVDB/seasons/74796-1-5.jpg', 7, 'https://thetvdb.plexapp.com/banners/_cache/seasons/74796-1-5.jpg'), 'https://thetvdb.plexapp.com/banners/seasons/74796-1.jpg': ('TheTVDB/seasons/74796-1.jpg', 33, 'https://thetvdb.plexapp.com/banners/_cache/seasons/74796-1.jpg'), 'https://thetvdb.plexapp.com/banners/seasons/74796-1-8.jpg': ('TheTVDB/seasons/74796-1-8.jpg', 12, 'https://thetvdb.plexapp.com/banners/_cache/seasons/74796-1-8.jpg'), 'https://thetvdb.plexapp.com/banners/seasons/28625-1.jpg': ('TheTVDB/seasons/28625-1.jpg', 23, 'https://thetvdb.plexapp.com/banners/_cache/seasons/28625-1.jpg'), 'https://thetvdb.plexapp.com/banners/seasons/74796-1-4.jpg': ('TheTVDB/seasons/74796-1-4.jpg', 32, 'https://thetvdb.plexapp.com/banners/_cache/seasons/74796-1-4.jpg'), 'https://thetvdb.plexapp.com/banners/seasons/74796-1-2.jpg': ('TheTVDB/seasons/74796-1-2.jpg', 25, 'https://thetvdb.plexapp.com/banners/_cache/seasons/74796-1-2.jpg')}, meta_old: []
[x] posters                  ( 6)  Sources: tvdb4, (TheTVDB), TheMovieDb, FanartTV, AniDB                 Inside: '[]'  Value: '{'https://thetvdb.plexapp.com/banners/seasons/74796-1-5.jpg': ('TheTVDB/seasons/74796-1-5.jpg', 7, 'https://thetvdb.plexapp.com/banners/_cache/seasons/74796-1-5.jpg'), 'https://thetvdb.plexapp.com/banners/seasons/74796-1.jpg': ('TheTVDB/seasons/74796-1.jpg', 33, 'https://thetvdb.plexapp.com/banners/_cache/seasons/74796-1.jpg'), 'https://thetvdb.plexapp.com/banners/seasons/74796-1-8.jpg': ('TheTVDB/seasons/74796-1-8.jpg', 12, 'https://thetvdb.plexapp.com/banners/_cache/seasons/74796-1-8.jpg'), 'https://thetvdb.plexapp.com/banners/seasons/28625-1.jpg': ('TheTVDB/seasons/28625-1.jpg', 23, 'https://thetvdb.plexapp.com/banners/_cache/seasons/28625-1.jpg'), 'https://thetvdb.plexapp.com/banners/seasons/74796-1-4.jpg': ('TheTVDB/seasons/74796-1-4.jpg', 32, 'https://thetvdb.plexapp.com/banners/_cache/seasons/74796-1-4.jpg'), 'https://thetvdb.plexapp.com/banners/seasons/74796-1-2.jpg': ('TheTVDB/seasons/74796-1-2.jpg', 25, 'https://thetvdb.plexapp.com/banners/_cache/seasons/74796-1-2.jpg')}'
common.SaveFile() - Exception: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:1754), url: 'https://thetvdb.plexapp.com/banners/seasons/74796-1-5.jpg', filename: 'TheTVDB/seasons/74796-1-5.jpg'
common.SaveFile() - Exception: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:1754), url: 'https://thetvdb.plexapp.com/banners/seasons/74796-1.jpg', filename: 'TheTVDB/seasons/74796-1.jpg'
common.SaveFile() - Exception: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:1754), url: 'https://thetvdb.plexapp.com/banners/seasons/74796-1-8.jpg', filename: 'TheTVDB/seasons/74796-1-8.jpg'
common.SaveFile() - Exception: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:1754), url: 'https://thetvdb.plexapp.com/banners/seasons/28625-1.jpg', filename: 'TheTVDB/seasons/28625-1.jpg'
common.SaveFile() - Exception: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:1754), url: 'https://thetvdb.plexapp.com/banners/seasons/74796-1-4.jpg', filename: 'TheTVDB/seasons/74796-1-4.jpg'
common.SaveFile() - Exception: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:1754), url: 'https://thetvdb.plexapp.com/banners/seasons/74796-1-2.jpg', filename: 'TheTVDB/seasons/74796-1-2.jpg'
```
Can you enter into a web browser and see if it downloads: https://thetvdb.plexapp.com/banners/seasons/74796-1-5.jpg

access to every season poster give the error SSLV3_ALERT_BAD_RECORD_MAC 
- It may be an ad-aware protection blocking anything with "banners" in the url...
- updating to latest Plex beta solved SSLV3_ALERT_BAD_RECORD_MAC in the past [https://forums.plex.tv/t/strange-issues-with-meta-agents-e-g-ofdb/232595]

**Comment by DJScias** [comment]
Hello there,

All the following pages worked:
* https://www.thetvdb.com/banners/seasons/74796-1.jpg
* https://www.thetvdb.com/banners/seasons/74796-1-8.jpg
* https://www.thetvdb.com/banners/seasons/28625-1.jpg
* https://www.thetvdb.com/banners/seasons/74796-1-4.jpg
* https://www.thetvdb.com/banners/seasons/74796-1-2.jpg

Except this one:
* https://www.thetvdb.com/banners/seasons/74796-1-5.jpg
![image](https://user-images.githubusercontent.com/439655/50923554-949f0e80-144d-11e9-9787-8ee554b2e73f.png)

However, after checking all the pages again and going to that last one, I do see it this time:
![image](https://user-images.githubusercontent.com/439655/50923680-e0ea4e80-144d-11e9-83b0-3e72828351f5.png)

So it seems there's errors every so often, which is weird. Is there anything you can suggest I do more?

**Comment by ZeroQI** [comment]
seeem like the poster works but getting an error from the agent
Check ad-aware/antivirus web protection software logs

**Comment by DJScias** [comment]
Hello there,

This ad-aware/antivirus web protection software logs are unrelated to Plex, aren't they? Because I don't know if Plex has any built-in antivirus web protection but I sure as hell don't have any running as this Agent is ran on a Synology NAS that doesn't access the internet except to update Plex and get metadata.

Could the Synology itself be trying to block the images from retrieving? As so far all the other Anime and Plex stuff work when it comes to posters.

**Comment by ZeroQI** [comment]
Unrelated to Plex and have Synology NAS too so not possible this way, it has to do with SSL certificates. You are using letsencrypt certificates with reverse proxy ?
Seem like only TheTVDB use https for posters

**Comment by DJScias** [comment]
Hello there,

I've not set up anything like letsencrypt certificates nor reverse proxy.

This is a Synology NAS out of the box that has Plex installed (through [this route](https://www.windowscentral.com/how-setup-plex-synology-ds218)) and using the Hama.bundle together with Absolute Series Scanner. Aside from running Plex it runs a Docker of Tautulli for Plex library statistics.

I mean, this issue isn't the end of the world to me so if it's only on my end and not a global bundle issue then I suppose that's fine too.. But it's mostly a QoL to actually have working season posters for TVDB3 as that'd make it a bit nicer in my opinion.

**Comment by ZeroQI** [comment]
Logs show different posters for seasons for the poster with lowest id but you have this weird ssl error "SSLV3_ALERT_BAD_RECORD_MAC~"
Please update Plex to latest version or try this linux fix:
https://forums.plex.tv/t/openssl-errors-when-plex-media-server-tries-to-talk-to-plex-api-or-download-codecs/186885/3

**Comment by DJScias** [comment]
Hello there,

At work atm so I had to SSH into my Synology NAS.

1. Plex is updated to latest Beta Channel on NAS.
![image](https://user-images.githubusercontent.com/439655/52274155-1c444400-294c-11e9-8473-dd4c8dcdfda6.png)

2. There's no `plexmediaserver` in `/usr/lib/` on my Synology NAS so I can't try this fix. I have a feeling there's still a difference between Linux and NAS installs as evident from the download page.
![image](https://user-images.githubusercontent.com/439655/52274334-a8566b80-294c-11e9-812d-003bc64a2291.png)
![image](https://user-images.githubusercontent.com/439655/52274270-6decce80-294c-11e9-9438-cc2e7850a3b9.png)

**Comment by ZeroQI** [comment]
Unfortunately, this is plex or machine specific (check firewall/security suite antivirus) as not agent related.
Thye agent find the right poster url, which plex on your machine won't load with that error...
It is linked to ssl library... other linux distrib move it, restart plex and it works...
Will close as the agent work on other platform so the source not at fault
