### ISSUE TITLE
Thumb not downloading for special episodes.

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#271]
I remember reporting an error similar to this a year ago or so: special episodes are not downloading the thumb image from tvdb.

Files attached below. 

[Black Lagoon [anidb-3395].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/2730015/Black.Lagoon.anidb-3395.scanner.log)
[Black Lagoon [anidb-3395].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/2730016/Black.Lagoon.anidb-3395.filelist.log)
[Black Lagoon [anidb-3395].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/2730019/Black.Lagoon.anidb-3395.agent-update.log)

**Comment by ZeroQI** [comment]
I have looked at the logs, while i see the thumbs per episode in the tvdb log section, it is missing the end of the logs showing the retained information and field priority. The logs do indicate the specials on thetvdb as non present, and the AnimeLists part show no mapping for said specials...

Looking at your file list you have 12 eps and 4 anidb specials and it seem only episode 5 in anidb is mapped to s00e00 in TheTVDB so are not mapped to thetvdb [https://raw.githubusercontent.com/ScudLee/anime-lists/master/anime-list-master.xml]
```
  <anime anidbid="3395" tvdbid="79604" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Black Lagoon</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;5-0;</mapping>
    </mapping-list>
  </anime>
```
Anidb specials you have: [http://anidb.net/perl-bin/animedb.pl?show=anime&aid=3395]
- S1 | High School Volume
- S2 | Magical Girl Volume
- S3 | The Melancholy of Balalaika
- S4 | Boys and Girls

TheTVDB has the 4 specials with similar tiitles in that order but the mapping file states to disregard episode 5 only.

My agent behaves as it should, the mapping had to be corrected.
https://github.com/ScudLee/anime-lists/issues/164

Closing this as it is mapping file related issue...

**Comment by KurtzPT** [comment]
I didn't said anything because I've been busy but this is not an issue with the mapping, the mapping already stated that all special episodes on anidb should be mapped to season 0 on tvdb (anidb s1 to s00e01, and so on) with the exception of episode 5 that should be mapped to s00e00. 

The mapping was always like this, I've even did some pull requests before on special episodes to AnimeList. Anyway, @ZeroQI  the ticket you opened has a reply that states what I said above:

> The mapping is already correct since anidb S specials are implicitly mapped to season 0 of tvdb with the same episode number i.e anidb S1 mapps to tvdb S0E1 by default. I see no reason to update the mapping.
> 
> See ScudLee on [issue 151](https://github.com/ScudLee/anime-lists/issues/151#issuecomment-431640847)
