### ISSUE TITLE
Hama does not show up after install with UAS

### ISSUE THREAD

**Issue by diksm8** [ZeroQI/Hama.bundle#274]
HAMA does not show up as an agent under library settings, agent settings or as a plugin after installing.
Tried installing manually and via UAS with Plugin Support folder installed.

Can anyone help me?

**Comment by ZeroQI** [comment]
Are other third party agents installing?
Please include logs:
[...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.hama.log (Agent logs)
[...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.system.log (show why the agent cannot launch)

**Comment by diksm8** [comment]
Absolute Series Scanner was working but HAMA was not.
I updated FreeNAS and reinstalled Plex and no longer have this issue.
