### ISSUE TITLE
TVDB issue hama agent.

### ISSUE THREAD

**Issue by oyooman** [ZeroQI/Hama.bundle#276]
hello i'm having a crash on hama agent with tvdb for (here black lagoon ) seral animes. 
agent + scanner already  updated to last version.

find the log below:

CRITICAL (core:574) - Exception in the update function of agent named 'HamaTV', called with guid 'com.plexapp.agents.hama://tvdb-79604?lang=en' (most recent call last):
  File "D:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-cc260c476\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "K:\Users\Oyoo\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 141, in update
    def update (self, metadata, media, lang, force ):  Update (metadata, media, lang, force,  False)
  File "K:\Users\Oyoo\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 125, in Update
    if common.AdjustMapping(source, mappingList, dict_TheTVDB):
  File "K:\Users\Oyoo\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\common.py", line 848, in AdjustMapping
    if str(season) in dict_TheTVDB['seasons']:  new_seasons[str(season + adjustment)] = dict_TheTVDB['seasons'].pop(str(season))
  File "D:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-cc260c476\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
KeyError: '6645'

**Comment by oyooman** [comment]
ok i though it was gone but not . 

i recreated an empty library adding only this one and having still the issue

**Comment by oyooman** [comment]
ahah... some kind of monologue ... i tried reinstall plex ... and voila its working again ..... 
i dont freaking understand what fucked up but it seems correct now ...

**Comment by ZeroQI** [comment]
Corrupted database shouldn't do that...
Code is badly handling a case si needs fixing.
Weird...

**Comment by oyooman** [comment]
well .. so far so good i've been updating the anime library with no issues from now. 

i may have try to much weird stuff :D 
sorry for the issue 
by the way thx for your work :)

**Comment by EndOfLine369** [comment]
This is not the same. Please provide the agent logs for this to be looked into.

**Comment by oyooman** [comment]
hello, 

i've set a TEST library containing only the hajime no hippo anime for which i have an issue also ( got several in issue but it not linked to the anime rather than some amount or queue or something like that ) 

stop plex server 
clean up the hama agent log
start plex server 
refresh the anime metadata.

below find the log.

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/2806822/com.plexapp.agents.hama.log)

**Comment by oyooman** [comment]
hi, 
have you had time to have a look into the issue ? 
i was thinking of some issue linked with the anidb auto ban, so i tried one refresh after 24h of no scan but no success i dont know how long their ban is running for... assuming this issue is linked with, thing that i'm totally not sure of. 

thx in advance.

**Comment by ZeroQI** [comment]
Not sure if linked `<error code="500">banned</error>`
error "KeyError: '1086'" but last line to crash doesn't match, 
  File "K:\Users\Oyoo\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\common.py", line 848, in AdjustMapping
    if str(season) in dict_TheTVDB['seasons']:  new_seasons[str(season + adjustment)] = dict_TheTVDB['seasons'].pop(str(season))

Log looks weird, bits missing, the series log in agent data folder would be more complete...
fribbtastic-api.net doesn't exist anymore... We should disable in code...
