### ISSUE TITLE
tvdb4 and specials mapping to anidb.

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#278]
I'm not sure if the following is the correct logic for tvdb4.

**Folder:** Dragon Ball [tvdb4-76666]
**Files wrongly matched:**

- [kenshin]_Dragon_Ball_S1_[DVD_704x528_x264_AC3]
- [kenshin]_Dragon_Ball_S2_[DVD_704x528_x264_AC3]

While all episodes are correctly matched and divided into seasons via tvdb4-mapping, what is the logic regarding the special files?

Those two specials don't really follow the AnimeList corrections:

>   <anime anidbid="231" tvdbid="76666" defaulttvdbseason="a" episodeoffset="" tmdbid="" imdbid="">
    <name>Dragon Ball</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-5;2-6;3-0;</mapping>
    </mapping-list>
  </anime>

S1 should be matched to s00e05 and S2 should be matched to s00e06. Unfortunately they are matched to s00e01 and s00e02. I feel like the special mappings on AnimeList should be respected in tvdb4, unless there's an entry on tvdb4-mapping file regarding the specials (there isn't one)

**Comment by ZeroQI** [comment]
if you want anidb to tvdb conversion that's anidb2 mode.
tvdb4 mode so tvdb specials numbering like all tvdb modes.
Behaving as expected, this serves cases where there are no AniDB entries, like tv series.

**Comment by KurtzPT** [comment]
anidb2 won't use the seasons numbering from tvdb4.mapping.xml. The only mode that uses tvdb4.mapping.xml is tvdb4 unless I'm missing something.

Also check my reply on #271

**Comment by ZeroQI** [comment]
That is correct.
If I change it then some might complain it doesn't follow tvdb numbering for specials...
I think anidb numbering for anidb mode and tvdb numbering for tvdb mode make sense to me...
Saw the reply, need to change the behaviour.

**Comment by KurtzPT** [comment]
It's no big of a deal I can just change the specials numbering, but I wonder if there's a case where I want to use tvdb4 mapping and some of the specials are not on tvdb... that would be a problem.

**Comment by ZeroQI** [comment]
I can understand but the code is very complex and some people may have absolute numbering for TV series so I chose to keep simple as the code is awfully complex as it is.
