### ISSUE TITLE
Season Posters

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#28]
I think this would be along the lines of an improvement, but is there any way to have a log that says when a season poster is missing? I find them easy to miss because Plex will automatically make a missing season cover the same as the main cover.

**Comment by ZeroQI** [comment]
Chech the poster html logs in agent data folder.
If a season poster is missing i can add that in there if not present already...

**Comment by sven-7** [comment]
Just checked -- nothing in that log indicating anything for missing season posters. I found a few just today, so I assume they would have been showing up over the last few weeks in that log.

**Comment by ZeroQI** [comment]
'TVDB season posters missing.htm' log created now with latest code
Didn't test so if doesn't crash it's all good

**Comment by EndOfLine369** [comment]
Any idea how we can refresh all metadata other then either (1) removing then re-adding all files or (2) going into each series and clicking 'Refresh'? 

I easily have 650+ series so neither is a great option. As we could also loose watch status on option (1).

**Comment by ZeroQI** [comment]
"Refresh all" in the library
my untested version crash straight away: Logs/PMS Plugins Logs/com.plexapp.system.log
uploading fix now

**Comment by EndOfLine369** [comment]
Doh. Forgot about that option :cry:.

**Comment by sven-7** [comment]
Question -- like the missing posters, do missing episode descriptions have the ability to log?

Was able to test and confirm the missing season poster log is working as expected. This can be closed out.

**Comment by ZeroQI** [comment]
That should be in an html log missing tvdb description alteady. Need to make sure it works with tvdb2 and tvdb3 mode
