### ISSUE TITLE
Since its a master project please add this PlexTrainingVideoScannerAndAgent

### ISSUE THREAD

**Issue by abesherman** [ZeroQI/Hama.bundle#280]
https://github.com/jmichas/PlexTrainingVideoScannerAndAgent

Thank you.

**Comment by ZeroQI** [comment]
This has nothing to do with my Http AniDB Metadata Agent (HAMA) as not anime related...
This has nothing to do with my Absolute Series Scanner (ASS) although support could be added but i see no point as mixed training/series will likely not happen in libraries...
- Scanner credit: # By Jason Michas original code borrowed from Mitchell Arends ExtendedPersonalMedia-Agent.bundle
- Agent credit: # By Jason Michas original code borrowed from Mitchell Arends ExtendedPersonalMedia-Agent.bundle

I am sorry, but i can't see any logic in this request nor even what you are trying to achieve...
