### ISSUE TITLE
Missing some posters Anime

### ISSUE THREAD

**Issue by takemyusername** [ZeroQI/Hama.bundle#282]
I'm missing some posters in my anime collection. 

This is how it looks(I've censored the 18+ images):

![main](https://user-images.githubusercontent.com/46269658/53448482-cb3de200-3a17-11e9-926e-76a4024608f4.png)

But the Meta is found in anidb: 

![fix](https://user-images.githubusercontent.com/46269658/53448579-06d8ac00-3a18-11e9-892f-f33eccbf3318.png)

it's not loading any meta after matching: 

![main2](https://user-images.githubusercontent.com/46269658/53448596-16f08b80-3a18-11e9-89dc-fc471b23069f.png)

i've tried the following: 
Reinstall hama/absolute scanner, manually match anime, check if there's a poster in anidb(yes there is) and delete cache and library so hama wil redo everything. 

i've all the mandatory folders in dataitems folder.  i also have ~530 anime in total and this problem affects around 40-50 items i think.

**Comment by ZeroQI** [comment]
Seem like the agent crash
Pick a series and paste tgis series specific log from agent data folder.

**Comment by takemyusername** [comment]
i hope you mean this one:

[Momiji.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/2907699/Momiji.agent-update.log)

**Comment by ZeroQI** [comment]
You're banned on anidb
[!] File received too small (<64 bytes), file: "<error code="500">banned</error>"

**Comment by takemyusername** [comment]
You mean my ip is banned for the frequent requests ? only hama uses anidb on my pc..

**Comment by ZeroQI** [comment]
yes

**Comment by takemyusername** [comment]
i've tried using express vpn with 3 different locations with no luck. 

on the anidb website error code 500 means "LOGIN_FAILED" 
https://wiki.anidb.net/w/UDP_API_Definition

which i have in my log: 
[!] File received too small (<64 bytes), file: "<error code="500">banned</error>"

any thoughts on this ?

**Comment by ZeroQI** [comment]
The text 'banned' is what is received from anidb between 'error' XML tags
It use custom port for http api your VPN mustn't accound for...

**Comment by takemyusername** [comment]
The weird thing is, sometimes i use filebot to rename anime. Filebot also uses anidb api. Since i'm banned now i tried using filebot and the api requests are handled fine while i'm banned on the hama side...

you have any advice before i close this thread ?

**Comment by ZeroQI** [comment]
Try again in 24h. Your IP is temo banned for http api. Filebot may use TCP api

**Comment by takemyusername** [comment]
Alright, thank you for your time !
