### ISSUE TITLE
Anidb Specials not mapping to tvdb.

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#284]
Folder: Air Gear [anidb-4196]
File: Air Gear S1.mkv

It just doesn't match it at all. The anime-list-master.xml file is correct on the Air Gear entry (This special is S1 on anidb and the match on tvdb is s00e01, so it doesn't need an entry).

**Comment by KurtzPT** [comment]
Hama is assuming that when anime-list-master.xml mapping doesn't have a mapping-list tag, that the specials aren't mapped to tvdb, which is wrong.

According to the devs who did the list, when the special numbering on anidb matches the special numbering on tvdb, it's not needed to add the mapping-list tag.

Kinda related to #271

**Comment by ZeroQI** [comment]
I never implemented it in hama volontarily, when i did the reverse mapping, it prevented it from working.
Need to see how to implement

**Comment by KurtzPT** [comment]
Well I'm sure this was working before because I'm redoing my lib and I didn't had this problem before. It's kinda bad because most specials are not being matched correctly at the moment with the latest version of Hama

**Comment by ZeroQI** [comment]
This needs sorting urgently i agree. Here is the current to-do list
- anidb-tvdb numbering equivalency if no mapping found
- "main" as priority back in settings for non-japanese works instead of x-jat (easy default setting)
- remove TheTVDB as studio source
- sorting anidb genres (genres below cut-off weight value are discarded)
- "Animation Works" then "Work" otherwise for animation studio
- Check source priority for posters priority index to not be hard-wire
- AnimeList Studio Field support

**Comment by EndOfLine369** [comment]
@ZeroQI,

I a'm not seeing an issue here. Pulls TVDB info just fine.
EX:
```
metadata.seasons[ 0]--------------------------------------------------------------------------------------------------------------------------------------
[?] meta_new: {'https://thetvdb.plexapp.com/banners/seasons/79796-0.jpg': ('TheTVDB/seasons/79796-0.jpg', 14, 'https://thetvdb.plexapp.com/banners/_cache/seasons/79796-0.jpg')}, meta_old: ['http://thetvdb.com/banners/seasons/79796-0.jpg', 'https://thetvdb.plexapp.com/banners/seasons/79796-0.jpg']
[=] posters                  ( 1)  Sources: tvdb4, TheMovieDb, (TheTVDB), FanartTV, AniDB                 Inside: '[]'  Value: '{'https://thetvdb.plexapp.com/banners/seasons/79796-0.jpg': ('TheTVDB/seasons/79796-0.jpg', 14, 'https://thetvdb.plexapp.com/banners/_cache/seasons/79796-0.jpg')}'
metadata.seasons[ 0].episodes[  1]
[?] rank: 0, source_title: TheTVDB, title: "Episode 21.5: Special Trick "
[=] title                          Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB']'  Value: 'Episode 21.5: Special Trick '
[=] summary                        Sources: (TheTVDB), AniDB                                              Inside: '['TheTVDB']'  Value: 'Episode 21.5: Takes part a while after Ikki accepts Simcas offer to become the n..'
[=] originally_available_at        Sources: AniDB,(TheTVDB)                                               Inside: '['TheTVDB']'  Value: '2007-03-21'
[=] writers                  ( 1)  Sources: AniDB,(TheTVDB)                                               Inside: '['TheTVDB']'  Value: '['Oogure Ito']'
[=] directors                ( 1)  Sources: AniDB,(TheTVDB)                                               Inside: '['TheTVDB']'  Value: '['Kamegaki Hajime']'
[=] rating                         Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB']'  Value: '10'
[=] thumbs                   ( 1)  Sources: (TheTVDB)                                                     Inside: '['TheTVDB']'  Value: '{'https://thetvdb.plexapp.com/banners/episodes/79796/371467.jpg': ('TheTVDB/episodes/371467.jpg', 1, None)}'
[=] duration                       Sources: (TheTVDB), AniDB, MyAnimeList, TheMovieDb, OMDb               Inside: '['TheTVDB']'  Value: '25'
[=] content_rating                 Sources: AniDB,(TheTVDB)                                               Inside: '['TheTVDB']'  Value: 'TV-MA'
```

@KurtzPT, please provide your logs.

**Comment by KurtzPT** [comment]
Updated Hama with the latest merge PR.

Tried a new library with only one file in it:
[file] Kurogane no Linebarrels [anidb-5629]\Kurogane no Linebarrels S1.mkv

anime-list-master.xml mapping:

>   <anime anidbid="5629" tvdbid="84261" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Kurogane no Linebarrels</name>
  </anime>

It should map to the first episode here:
https://www.thetvdb.com/series/linebarrels-of-iron/seasons/0

update log:
[_unknown_folder.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/2932157/_unknown_folder.agent-update.log)

**Comment by EndOfLine369** [comment]
Thanks for the example/log. Believe I know what needs to be done.
```
TheTVDB.GetMetadata() - TVDBid: '84261'
[ ] title: Linebarrels of Iron
[ ]    s0e1 s00e000 anidbid: xxxxxxx air_date: 2009-08-07
```

**Comment by EndOfLine369** [comment]
@KurtzPT, replace your running of 'AnimeLists.py' with https://raw.githubusercontent.com/ZeroQI/Hama.bundle/EOL-branch/Contents/Code/AnimeLists.py and test.

@ZeroQI, take a look at https://github.com/ZeroQI/Hama.bundle/commit/bbb78ac350d451ef94f18cf7724e0d0148dea9bc and let me know what you think.
I record the number of entries for each tvdb id in the mapping list. The take the single id count into mappingList. This is then used in 'anidb_ep'. Also did some code simplification in 'anidb_ep' function.

**Comment by KurtzPT** [comment]
> @KurtzPT, Make sure you're on the latest master and replace your running instance of 'AnimeLists.py' with https://raw.githubusercontent.com/ZeroQI/Hama.bundle/EOL-branch/Contents/Code/AnimeLists.py and test.
> 
> @ZeroQI, take a look at [bbb78ac](https://github.com/ZeroQI/Hama.bundle/commit/bbb78ac350d451ef94f18cf7724e0d0148dea9bc) & [e23fbcf](https://github.com/ZeroQI/Hama.bundle/commit/e23fbcf37cef0e31687e61929b8ae2dc3308003a) and let me know what you think.
> I record the number of entries for each tvdb id in the mapping list. Then take the single id count into mappingList. This is then used in 'anidb_ep'. Also did some code simplification in 'anidb_ep' function.

Update + replaced AnimeLists.py from EOL-branch and it fixed the example I gave above.

**Comment by EndOfLine369** [comment]
FYI @KurtzPT / @ZeroQI, found an issue in AnimeList logic in testing. This is now fixed https://github.com/ZeroQI/Hama.bundle/commit/4a1db809c6c60555ba882b828613008227ef1b89

**Comment by EndOfLine369** [comment]
Master updated
