### ISSUE TITLE
[Suggestion] Sort tags

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#286]
I noticed that all genres that Hama parses from AniDB are not sorted alphabetically, QOL improvement would be sorting it before adding to Plex.

**Comment by ZeroQI** [comment]
Tags are sorted through weight in AniDB. we would loose meaning, it's a tricky choice for me...

**Comment by KurtzPT** [comment]
I noticed the weight setting, but I also noticed the tags being show on the anidb page of a certain anime don't really follow that weight. 

For example https://anidb.net/perl-bin/animedb.pl?show=anime&aid=4597

AniDB page:
![image](https://user-images.githubusercontent.com/14930057/53742411-79221400-3e90-11e9-9793-b79e29654978.png)

Tags on plex:
![image](https://user-images.githubusercontent.com/14930057/53742427-7f17f500-3e90-11e9-87be-28384c85decc.png)

The "Present" tag, it's not even displayed on AniDB page (And it should be the 2nd tag with the more weight if its sorted by weight)

**Comment by EndOfLine369** [comment]
@KurtzPT, I'm not seeing that ordering issue in Genres. All mine I looked at are alphabetical (both anidb & tvdb source tags)

**Comment by EndOfLine369** [comment]
Ah, its tvdb that is sorted.
I use `Sources: (TheTVDB), AniDB, MyAnimeList, TheMovieDb, OMDb` so mine are sorted.
```
TheTVDB.GetMetadata() - TVDBid: '79796',
[ ] title: Air Gear
[ ] genres: ['Action', 'Adventure', 'Animation', 'Sport']
```
AniDB is not:
```
AniDBid: 4196
[ ] 'title': Air Gear
[ ] 'genre' (9/57 above 400 weight): ['Present', 'Earth', 'Alternative present', 'Japan', 'Inline skating', 'Asia', 'Action', 'Ecchi', 'Sports']
```

@ZeroQI, for consistency between sources, we should probably sort AniDB for consistency as we can't weight TVDB.

**Comment by EndOfLine369** [comment]
Actually, looks like AniDB code does not order them by weight at all. Its just based on the 'xpath' iterable return.
```python
        for tag in xml.xpath('tags/tag'):
          if GetXml(tag, 'name') and tag.get('weight', '').isdigit() and int(tag.get('weight', '') or '200') >= int(Prefs['MinimumWeight'] or '200'):
            SaveDict( [string.capwords(GetXml(tag, 'name'), '-')], AniDB_dict, 'genres')
            if GetXml(tag, 'name').lower() in RESTRICTED_GENRE:  AniDB_dict['content_rating'] = RESTRICTED_GENRE[ GetXml(tag, 'name').lower() ]
```

**Comment by ZeroQI** [comment]
For consistency with TheTVDB we need to sort AniDB then.A clever one-liner should do:
If Dict(AniDB_dict, 'genres'): 
 AniDB_dict['genres'].sort()

**Comment by KurtzPT** [comment]
> Ah, its tvdb that is sorted.
> I use `Sources: (TheTVDB), AniDB, MyAnimeList, TheMovieDb, OMDb` so mine are sorted.
> 
> ```
> TheTVDB.GetMetadata() - TVDBid: '79796',
> [ ] title: Air Gear
> [ ] genres: ['Action', 'Adventure', 'Animation', 'Sport']
> ```
> AniDB is not:
> 
> ```
> AniDBid: 4196
> [ ] 'title': Air Gear
> [ ] 'genre' (9/57 above 400 weight): ['Present', 'Earth', 'Alternative present', 'Japan', 'Inline skating', 'Asia', 'Action', 'Ecchi', 'Sports']
> ```
> @ZeroQI, for consistency between sources, we should probably sort AniDB for consistency as we can't weight TVDB.
> 
> Actually, looks like AniDB code does not order them by weight at all. Its just based on the 'xpath' iterable return.
> 
> ```python
>         for tag in xml.xpath('tags/tag'):
>           if GetXml(tag, 'name') and tag.get('weight', '').isdigit() and int(tag.get('weight', '') or '200') >= int(Prefs['MinimumWeight'] or '200'):
>             SaveDict( [string.capwords(GetXml(tag, 'name'), '-')], AniDB_dict, 'genres')
>             if GetXml(tag, 'name').lower() in RESTRICTED_GENRE:  AniDB_dict['content_rating'] = RESTRICTED_GENRE[ GetXml(tag, 'name').lower() ]
> ```

Yes, I'm using AniDB tags as the first preference on source.

**Comment by EndOfLine369** [comment]
Sorted all source's genre entries to make sure all are sorted the same.
