### ISSUE TITLE
Hama can't get data from AniDB

### ISSUE THREAD

**Issue by Ninelpienel** [ZeroQI/Hama.bundle#287]
Hey, Hama won't get all data. My collection looks like this: https://i.imgur.com/utlwzgZ.jpg
Here are my log files: https://my.mixtape.moe/gqwpmi.zip

**Comment by ZeroQI** [comment]
def GetXml          (xml,      field                ):  return xml.xpath(field)[0].text if xml.xpath(field) and xml.xpath(field)[0].text not in (None, '', 'N/A', 'null') else ''  #allow isdigit() checks
AttributeError: 'str' object has no attribute 'xpath'

Need to disable MyAnimeList, it seems that it cause a crash.
We can avoid the crash maybe for more security:
    def GetXml          (xml,      field                ):  return xml.xpath(field)[0].text if not isstring(xml) and xml.xpath(field) and xml.xpath(field)[0].text not in (None, '', 'N/A', 'null') else ''  #allow isdigit() checks

**Comment by Ninelpienel** [comment]
How can I disable MyAnimeList?

**Comment by no-idee** [comment]
It look's like a **DNS Error**. 

MyAnimeList.GetMetadata() try's to load something from "fribbtastic-api.net"

**Comment by Ninelpienel** [comment]
> It look's like a **DNS Error**.
> 
> MyAnimeList.GetMetadata() try's to load something from "fribbtastic-api.net"

These are URLs from the "MyAnimeList.py".

**Comment by ZeroQI** [comment]
We need to disable in the code. for now replace in __init__.py
`dict_MyAnimeList = MyAnimeList.GetMetadata(movie, MALid ) if MALid  else {} #
`with
`dict_MyAnimeList                                              = {}
`

**Comment by Ninelpienel** [comment]
> dict_MyAnimeList = MyAnimeList.GetMetadata(movie, MALid ) if MALid else {} #

Thx! It works! I have some other questions.

- Can I hide OPs and EDs? I don't want to list them as "Specials": https://i.imgur.com/ei52tOz.png
- Can I define that every season get the same cover as the series itself? https://i.imgur.com/9poh4BI.jpg

**Comment by ZeroQI** [comment]
Put specials into an "Extras" folder or use .plexignore files.

That's the first time somebody asks that, I was multiple times asked for the opposite...

**Comment by Ninelpienel** [comment]
> Put specials into an "Extras" folder or use .plexignore files.

I can't move the files because the OPs and EDs are linked into the episodes/mkvs.

> That's the first time somebody asks that, I was multiple times asked for the opposite...

Problem is that most of those season covers are not original covers. They look not really good or the it used some random manga/light novel covers.

**Comment by ZeroQI** [comment]
Hide season folder if single season folder 
Right now if there isn't seasons poster it uses the series one but no setting to change the behaviour, just remove sources...

.plexignore at root of section/library
- *_OP*
- *_ED*

**Comment by EndOfLine369** [comment]
Master updated to handle your string response from MAL

**Comment by ZeroQI** [comment]
@Ninelpienel Please confirm
-  latest code solve MAL issue (should we temp disable MAL since hasn't been working for 6 months?)
- create .plexignore file at the root of library with both exceptions above in it and confirm OPs/EDs are not picked up by scanner (need plex dance as unchanged folders will not call again scanner)

**Comment by Ninelpienel** [comment]
> @Ninelpienel Please confirm
> 
> * latest code solve MAL issue (should we temp disable MAL since hasn't been working for 6 months?)

It works fine with the new init.py.

> * create .plexignore file at the root of library with both exceptions above in it and confirm OPs/EDs are not picked up by scanner (need plex dance as unchanged folders will not call again scanner)

This works fine, too! Thank you! (Pictures: https://i.imgur.com/ceYAhuD.png https://i.imgur.com/txVLzXP.jpg)

**Comment by ZeroQI** [comment]
You should set Plex to not display season folders for single seasons and it will be even more seamless.

**Comment by Ninelpienel** [comment]
> not display season folders for single seasons

I can only find the setting in the show options. Can I set this option as standard so that I don't need to change it for every new show?

**Comment by ZeroQI** [comment]
yep library settings. that and hide item in collections and it becomes pretty seamless

**Comment by Ninelpienel** [comment]
Okay, it seems like it still doesn't work for me correctly. When I add a new anime to my collection it still doesn't find the data. https://i.imgur.com/6GEw7ru.png

[_root_.agent.log](https://github.com/ZeroQI/Hama.bundle/files/2947784/_root_.agent.log)

**Comment by ZeroQI** [comment]
dict_AnimeLists, AniDBid, TVDBid, TMDbid, IMDbid, mappingList =  AnimeLists.GetMetadata(media, movie, error_log, metadata.id)
TypeError: GetMetadata() takes exactly 5 arguments (4 given)

def GetMetadata(media, movie, error_log, id):

Your AnimeList.py is not updated
