### ISSUE TITLE
Glitches with Specials

### ISSUE THREAD

**Issue by Xalaxis** [ZeroQI/Hama.bundle#29]
So far I have noticed:
Watching Normal episodes counting as watching the specials numbered the same and vice versa
Watching a special makes it infinitely replicate until it is marked as unwatched
Watching a Normal episode makes the special episodes infinitely replicate.

This all seems _very_ strange.  Are there any logs you might suggest or do you think it could be related to something to do with Plex instead?

**Comment by Xalaxis** [comment]
Even stranger: None of these bugs seem to occur when using the Android app.

**Comment by Xalaxis** [comment]
I'll keep you posted

**Comment by EndOfLine369** [comment]
Hama updates the metadata on the plex server. It has no dealings with watched status. Sounds like your Plex server or more likely the client your using to connect to your server is in issue here as you even said that the view of your server info from your Android app is fine. Please raise your issue with Plex support.

**Comment by ZeroQI** [comment]
i second that. the scanner put the videos in plex, the agent fill the metadata in.
Watch flags are not even available to scanners nor agents. not an agent issue, especially since your mobile talk to the server using the same agent and has no issues

**Comment by Xalaxis** [comment]
Cheers.  I'll raise it with them if I see it occurring again.  Luckily it seems to have calmed down suddenly as of last week.
