### ISSUE TITLE
Dragon Ball GT [anidb-233] episode metadata

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#292]
**Anime Folder:** Dragon Ball GT [anidb-233]
**TheTVDB:** https://www.thetvdb.com/series/dragon-ball-gt
**Log:** [Dragon Ball GT [anidb-233].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/2993386/Dragon.Ball.GT.anidb-233.agent-update.log)
**Mapping:**
```
  <anime anidbid="233" tvdbid="79275" defaulttvdbseason="a" episodeoffset="" tmdbid="" imdbid="">
    <name>Dragon Ball GT</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-0;2-1;</mapping>
    </mapping-list>
  </anime>
```

I didn't check the logs, but I think it's a Hama issue and not a scanner issue, episodes don't have any metadata from tvdb (at least the thumbs).

**Comment by EndOfLine369** [comment]
Looks like an issue in `AnimeLists.anidb_ep()`.

Your example and another one I pulled are almost exactly the same but diff output. Only addition is the s0 entries...
```python
>>> mappingList1 = {'TVDB': {'sa': {'233': '0'}, 's0e0': ('0', '1', '233'), 's0e1': ('0', '2', '233')}, 'tvdbcount': 1, 'episodeoffset': '0', 'defaulttvdbseason': 'a', 'name': 'Dragon Ball GT'}
>>> mappingList2 = {'TVDB': {'sa': {'1382': '0'}}, 'tvdbcount': 1, 'episodeoffset': '0', 'defaulttvdbseason': 'a', 'name': 'Zoids'}
>>> anidb_ep(mappingList1, '1', '1')
('0', '0', 'xxxxxxx')
>>> anidb_ep(mappingList2, '1', '1')
('1', '1', '1382')
```

**Comment by EndOfLine369** [comment]
@ZeroQI, I can simplify multiple pieces of the code if we just override the `mappingList['defaulttvdbseason']` value of `'a' -> '1'` in the `AnimeLists.GetMetadata()`.
Do you see any reason I should not do this?

**Comment by EndOfLine369** [comment]
Seems we are also at a problem of not being able to map in tvdb if a single anidb series is across multiple tvdb seasons when a `anidb` source id entry. Unclear how or even if we would be able to do it.

The `'a' -> '1'` would at least fix the `defaulttvdbseason` season's episodes but not the later seasons from the same anidbid as just noted.

**Comment by EndOfLine369** [comment]
Simplifications done in branch. Testing ongoing.

**Comment by ZeroQI** [comment]
The 'a' serves for long series to avoid seasons mapping so is used in few places (4 times in TheTVDBv2.py) but searching in Notepad++ for 'a' should do.
Changing to '1' could lead to issues on animelists seasons 2+ mappings missing. Tread carefully

**Comment by EndOfLine369** [comment]
Almost all 'a' i found (i noted the two exceptions) would just set it to '1' https://github.com/ZeroQI/Hama.bundle/pull/293/commits/1598f09639a5669e647553a67c1832b3731fe879 and mapping files will have 'a' even if its not the only anidb series (also if it starts as s1 and is for 2+ seasons).

**Comment by EndOfLine369** [comment]
Almost all 'a' i found (i noted the two exceptions) would just set it to '1' or have both ['a', '1'] in the test https://github.com/ZeroQI/Hama.bundle/pull/293/commits/1598f09639a5669e647553a67c1832b3731fe879 and mapping files can have 'a' even if its not the only anidb series (also if it starts as s1 and is for 2+ seasons). See PR draft for code updates.

**Comment by ZeroQI** [comment]
@KurtzPT please try this fix and report. The branch it is part of will be integrated in the main branch after tests

**Comment by KurtzPT** [comment]
Just tried out the EOL-Branch, it seems it's fixed.

**Comment by ZeroQI** [comment]
I am going to close this to reduce the number of solved issues. The branch should've merged shortly.

Thanks @EndOfLine369 for the fix

**Comment by EndOfLine369** [comment]
Branch merged
