### ISSUE TITLE
Interrogation about cache and how com.plexapp.agents.hama keeps its data

### ISSUE THREAD

**Issue by whinette** [ZeroQI/Hama.bundle#294]
Hello,

I've recently migrated my pms from a shield tv to a beefier server.
I was astounded by the size of hama folders, but as a lot of versions has passed I thought maybe it was a migration reliquat.

This night I finished my migration, metadata from scratch (I only imported the pms db and re downloaded all the metadata) but the issue is still there.

I understand that hama keeps a copy of everything in its own folder (`Plug-in Support\Data\com.plexapp.agents.hama\DataItems`) and I am cool with that.

But I think there is something that has been forgotten in the metadata.
If I understand correctly, hama will lookup for metadata, then combine with plex source in the _combined and/or _stored folder.
But it looks like that after combination the com.plexapp.agents.hama isn't cleaned up

For example with the folder `Plex Media Server\Metadata\TV Shows\2\5e90cd14451e208d4985e0a8de8e826f5afb5a0.bundle\Contents`

![image](https://user-images.githubusercontent.com/6152660/54914734-ef48f200-4ef5-11e9-9ea5-b23c70349234.png)

Am I missing something? Are both folder used by pms?

**Comment by ZeroQI** [comment]
Thèse are PMS folders only.
Hama writes to the agent data folder only to keep a copy when the metadata source becomes unavailable: Plug-in Support\Data\com.plexapp.agents.hama\DataItems
