### ISSUE TITLE
Simply doesn't work at all

### ISSUE THREAD

**Issue by jonasprokopf** [ZeroQI/Hama.bundle#297]
Hey, I'm too tired to write what's happening, so I figured I'd just capture what I see.
https://youtu.be/8GTDY7N2Ig0

Logs: https://drive.google.com/open?id=1varpksBW1CokN4j7DM-f_XsoE18rdcQe
(Doesn't include "[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/root_folder.scanner.log" because there's no such log in my folder)

Thanks and I hope you can help me, I need my hentai nice and tagged^^

**Comment by DarthKnight12** [comment]
try using the tvdb id (ie look up discipline thetvdb on google it will redirect you to the correct page, then on show overview you see a line called id copy that and when you match on plex use Discipline [tvdb2-thetvdbid] (you can of course chose any type of tvdb typ that you want (look it up on ASS)

**Comment by EndOfLine369** [comment]
Your logs look like a version of easily >6 months old state of the agent. Please always update your agent before posting any issues. As are all probably already resolved if your that out-of-date.

Once you've updated your install and you still see the issue, provide your logs and state your issue for us to look into it.

**Comment by jonasprokopf** [comment]
Ok, I've now updated everything as instructed and it sadly still doesn't work.
Here's the logs: https://drive.google.com/folderview?id=1Y84WHVOX6PQzK8bqVbe6WeuyeyslsrLF
Thanks.

**Comment by ZeroQI** [comment]
It seems it crashes straight away, if so, nothing will match anymore but logs show all is good
In Discipline search logs no filename is showing. you might want to re-scan.

Restart plex services, try to match, then send the logs
- [...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.hama.log (Agent logs)
- [...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.system.log (show why the agent cannot launch)
Readme troubleshooting steps list the files to include so i do not know why these weren't included for an issue where the agent doesn't do anything.

**Comment by ZeroQI** [comment]
?
