### ISSUE TITLE
Caracter ";" in show name

### ISSUE THREAD

**Issue by hergonoway** [ZeroQI/Hama.bundle#301]
Hello, 

I've just add Chaos series in my library with the following 3 folders : 
- Chaos;Child [anidb-11166]
- Chaos;Head [anidb-6088]
- Chaos;Child Silent Sky [anidb-13057]

But it seems that ";" in the folder name is an issue for HAMA, on first pass it grouped all 3 folders under a single show with a TVDB reference. All episodes regroup multiple files for 1 episode entry, weird. if I remove the ";" of the name for the 3 folders, refresh metadata, there  everything works fine (don't need to do that for the episodes files only the folder)

Once refreshed correctly, the X-jap name is correctly shown in plex, with the ";" (O__o)

![image](https://user-images.githubusercontent.com/8405448/56729987-ed718900-6756-11e9-866c-7e441b5b7128.png)

**Comment by ZeroQI** [comment]
Please confirme you are using Absolute Sériés Scanner for this Plex library as Plex series scanner drop all after a semicolon and it used to work.
If so please attaché ASS scanner logs
If not consider donating :D

**Comment by hergonoway** [comment]
Already donated ;)

<img width="353" alt="Plex 2019-04-25 14-02-36" src="https://user-images.githubusercontent.com/8405448/56734346-d5a00200-6762-11e9-9648-91b3fa6b20dd.png">

Yes I use ASS, you need XX.scanner.log in /Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/Logs ?

**Comment by ZeroQI** [comment]
Yes, the series scanner log in the first folder mentioned

**Comment by hergonoway** [comment]
So I changed back folder names : 

- 'Chaos Child [anidb-11166]' --> 'Chaos;Child [anidb-11166]'
- 'Chaos Head [anidb-6088]' --> 'Chaos;Head [anidb-6088]'
- 'Chaos Child - Silent Sky [anidb-13057]' --> 'Chaos;Child Silent Sky [anidb-13057]'

And I went back to the initial problem, so reproductability checked :) : 
![image](https://user-images.githubusercontent.com/8405448/56760726-18320080-679c-11e9-8ed4-a4d6ac748415.png)

Unfortunatly, nothing shows up in 
`/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs` after hiting refresh metadata or Scan folder

![image](https://user-images.githubusercontent.com/8405448/56761258-38ae8a80-679d-11e9-8bd7-d24e74628b57.png)

**Comment by EndOfLine369** [comment]
Need some logs.
Look for errors in `_root_.scanner.log` & `[...]/Plex Media Server/Logs/Plex Media Scanner.log`

**Comment by hergonoway** [comment]
Back from holiday, in order to generate good logs I've removed concerned folders (like last time), refresh and put them back. But from last time there's improvment, I dunno if it's from last commits to ASS or Hama, but now I've got 3 entries instead of 1 now : 

![image](https://user-images.githubusercontent.com/8405448/57026930-3fc11700-6c3b-11e9-9b87-566642c84d62.png)

This time, even if there's no metadata, there're 3 entries with correct name and [anidb-XXX] is correct. If I refresh metadata nothing update.

If I try to manually "associate" nothing shows up : 
![image](https://user-images.githubusercontent.com/8405448/57027081-b52ce780-6c3b-11e9-91e9-81c12307aa00.png)

but if I change ";" to " " in search option so from : 
![image](https://user-images.githubusercontent.com/8405448/57027159-e9a0a380-6c3b-11e9-9825-4a17fdefda24.png)
to
![image](https://user-images.githubusercontent.com/8405448/57027169-f624fc00-6c3b-11e9-9b99-435fb81d5ab9.png)

I've got a match this time.

![image](https://user-images.githubusercontent.com/8405448/57027134-d68dd380-6c3b-11e9-8959-319915c20416.png)

**Comment by ZeroQI** [comment]
Scanner behave propertly now, there was an error previously making it crash, that would explain former behaviour.

Needs agent logs to see why HAMA search is failing

**Comment by ZeroQI** [comment]
I need agent series logs to see why HAMA search is failing

**Comment by ZeroQI** [comment]
we had scanner issue in code then anidb issue causing unreadable title xml file
update to latest, delete in agent data folders anidb tite xml file, should work

**Comment by hergonoway** [comment]
you mean deleting this folder : 
`/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/AniDB`

**Comment by ZeroQI** [comment]
anime-titles.xml only

**Comment by hergonoway** [comment]
done, 

well now it's a bit worse, it merges 2 show into one (as double file for 2 episodes) and both names what's left are less compliant than before : 
![image](https://user-images.githubusercontent.com/8405448/57196468-73fb4700-6f5d-11e9-9267-3bc3b32f8b6c.png)

**Comment by ZeroQI** [comment]
Need hama agent search logs for all series (drag and drop files)

**Comment by hergonoway** [comment]
so basically everthing in "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs" ?

**Comment by hergonoway** [comment]
I found the right logs I think >
[Chaos;Child [anidb-11166].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/3145874/Chaos.Child.anidb-11166.agent-search.log)
[Chaos;Child [anidb-11166].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3145875/Chaos.Child.anidb-11166.agent-update.log)
[Chaos;Child Silent Sky [anidb-13057].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/3145876/Chaos.Child.Silent.Sky.anidb-13057.agent-search.log)
[Chaos;Head [anidb-6088].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/3145877/Chaos.Head.anidb-6088.agent-search.log)
[Chaos;Head [anidb-6088].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3145878/Chaos.Head.anidb-6088.agent-update.log)

**Comment by ZeroQI** [comment]
The involved series search logs *.search.log tells me the title received by the agent is cut from ';' and only get "chaos" as seach title, hence the result we are seeing...
Once HAMA assigns the same id, it groups them together...

I need the scanner logs for all 3 to see if it gives "chaos" only as title or if the leftover ';' mage plex trunk the title...

**Comment by hergonoway** [comment]
I removed the concerned fodler around 21h10, resfreshed, and put them back, and refreshed.

I don't have any *.scanner log regarding these shows or with the word "chaos" in it @ /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/

only one log file changed is : 
![image](https://user-images.githubusercontent.com/8405448/57199163-32c65f80-6f7c-11e9-8505-1892617faed0.png)
[_root_.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/3145931/_root_.scanner.log)

If I go further in a folder named after my library name : I've got : 
![image](https://user-images.githubusercontent.com/8405448/57199421-f6483300-6f7e-11e9-9a7c-a387940f6e3b.png)
[_root_-data-Anime-Archive.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/3145947/_root_-data-Anime-Archive.filelist.log)
[_root_-data-Anime-Archive.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/3145948/_root_-data-Anime-Archive.scanner.log)
[_root_.agent.log](https://github.com/ZeroQI/Hama.bundle/files/3145949/_root_.agent.log)
[Chaos Child [anidb-11166].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/3145950/Chaos.Child.anidb-11166.filelist.log)
[Chaos Child [anidb-11166].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/3145951/Chaos.Child.anidb-11166.scanner.log)
[Chaos Head [anidb-6088].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/3145952/Chaos.Head.anidb-6088.filelist.log)
[Chaos Head [anidb-6088].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/3145953/Chaos.Head.anidb-6088.scanner.log)
[Chaos;Child [anidb-11166].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/3145954/Chaos.Child.anidb-11166.agent-search.log)
[Chaos;Child [anidb-11166].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3145955/Chaos.Child.anidb-11166.agent-update.log)
[Chaos;Head [anidb-6088].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/3145956/Chaos.Head.anidb-6088.agent-search.log)
[Chaos;Head [anidb-6088].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3145957/Chaos.Head.anidb-6088.agent-update.log)

Finally here's Plex Media Scanner Log : 
[Plex Media Scanner.log](https://github.com/ZeroQI/Hama.bundle/files/3145932/Plex.Media.Scanner.log)

**Comment by ZeroQI** [comment]
With that i can progress
- The scanner let the title with semicolon pass and shouldn't (should replace it with a space) as HAMA receive the title truncated before it due to Plex internal cleansing, losing the forced ID...
- ';' is part of FILTER_CHARS so should be removed and i tested semicolon but never with forced ids...

In ASS line 550, can you test replacing
`  folder_show  = reverse_path[0] if reverse_path else ""`
with:
`  folder_show  = clean_string(reverse_path[0]) if reverse_path else ""``
If it works, will change ASS code asap...

**Comment by EndOfLine369** [comment]
That won't work. You'll remove all bracket info. IE all force id info.

**Comment by ZeroQI** [comment]
Even with line 576?
`          folder_show = "%s [%s-%s]" % (clean_string(reverse_path[0]), os.path.splitext(file)[0], id)`

**Comment by EndOfLine369** [comment]
Thats after `SOURCE_IDS.search` that you would be breaking.

**Comment by EndOfLine369** [comment]
And that code is for the `SOURCE_ID_FILES` pull which you would WANT to remove any bracket setup as your setting your own force id string.

**Comment by EndOfLine369** [comment]
If all you want to do is remove the ';':
`folder_show  = reverse_path[0].replace(';',' ') if reverse_path else ""`

**Comment by hergonoway** [comment]
Applied the following change : 

![image](https://user-images.githubusercontent.com/8405448/57200349-20075700-6f8b-11e9-8035-03e7c2f92983.png)

it works : 
![image](https://user-images.githubusercontent.com/8405448/57200354-34e3ea80-6f8b-11e9-8171-bcceab61ea1e.png)

but something odd shows before gathering metadata, something like "Chaos;Child [main-X-jap] [anidb-11166]" didn't have the "[main-X-jap]" part before

**Comment by EndOfLine369** [comment]
You got that strange `[main-X-jap]` as the scanner incorrectly removed the force id. And relied on the AniDB search function for a match.

**Comment by EndOfLine369** [comment]
@hergonoway, please test with
`folder_show = reverse_path[0].replace(';',' ') if reverse_path else ""`
Should still work for your case and not remove the force id put in the foldername. So you will also not see that search function add of `[main-X-jap]` from the incorrect removal of the foldername force id.

**Comment by hergonoway** [comment]
Perform the above edit, 

result is good : 
![image](https://user-images.githubusercontent.com/8405448/57201857-ba24ca80-6f9e-11e9-95c3-099f3d3475c7.png)

**Comment by ZeroQI** [comment]
should we apply replacing FILTER_CHARS instead of just ';'?

**Comment by EndOfLine369** [comment]
........maybe?
Could outsource the loop into its own function to be called in `clean_string()` & `folder_show = filter_chars(reverse_path[0]) if reverse_path else ""`
```python
def filter_chars(string):
  for char, subst in zip(list(FILTER_CHARS), [" " for x in range(len(FILTER_CHARS))]) + [("`", "'"), ("(", " ( "), (")", " ) ")]:    # remove leftover parenthesis (work with code a bit above)
    if char in string:                              string = string.replace(char, subst)                                             # translate anidb apostrophes into normal ones #s = s.replace('&', 'and')
  return string
```

**Comment by ZeroQI** [comment]
@EndOfLine369 looks good to me.

**Comment by EndOfLine369** [comment]
done
