### ISSUE TITLE
Mixed library?

### ISSUE THREAD

**Issue by maciekish** [ZeroQI/Hama.bundle#303]
Will Hama also cover regular TV Shows using TheTVDB so i can have a mixed library of regular shows and anime? Or do i need to have two separate libraries one with the Plex agent and one for anime with this agent?

**Comment by ZeroQI** [comment]
If using multiple seasons, it will match using TheTVDB.
If you have TheTVDB series with a single season however, it will not match them property as it will try with AniDB first and there is a lot of anime with a lot of titles in many languages and it will match something wrongly...
- you can either edit the title to give the  TVDB id with [tvdb-xxxxxx] or match manually or select manually thetvdb for that library
- If you value Anime so much you want better metadata, then it deserves its own library...
- you can simply just use TheTVDB agent for your whole library.
