### ISSUE TITLE
No finding matches for any anime newly added

### ISSUE THREAD

**Issue by trolhamonas** [ZeroQI/Hama.bundle#310]
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3149951/com.plexapp.agents.hama.log)
The log shows some errors
I reinstalled the plugin and tested on two separate machines both found no matches on any show that i added

**Comment by snoopy82481** [comment]
I'm having the same issue. I'm going to attach my log also.  I have removed the library and re-added it, same issue. I have downloaded hama and ASS removed library, restarted server, added hama and ASS back into it, and added library back to plex. Same issue. Logs are in Verbose mode.
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3150613/com.plexapp.agents.hama.log)

**Comment by elmexy** [comment]
I was having the same issue today. But i fixed by doing what the person in #309 did.
Manually put the [anime-titles.xml](http://anidb.net/api/anime-titles.xml.gz) in Plug-in Support\Data\com.plexapp.agents.hama\DataItems\AniDB\

**Comment by snoopy82481** [comment]
I did that, I’m going to refresh my library today to see if it gets fixed. Just to over come the possibility of the ban.

**Comment by snoopy82481** [comment]
I had to remove hama from the plugins and then remove the hama data from plug-ins support and then readd hama to get it to fix itself.

**Comment by ZeroQI** [comment]
I  will keep monitoring such issues to see if further fix needed to prevent that
