### ISSUE TITLE
[Question] Episode Titles

### ISSUE THREAD

**Issue by Jpeterson1352** [ZeroQI/Hama.bundle#312]
I recently update my HAMA and all new anime that I add have the episode titles as the official titles from aniDB. Is there a way to change it so that it uses the english main titles instead?

**Comment by icemouton** [comment]
I noticed this as well, ever since I "repaired" my issue with anime-titles.xml and updated hamma, episode and show titles all show up in japanese which I don't really hate, but I know for a fact they were pulling the english titles before..

**Comment by ZeroQI** [comment]
No logs attached...
Did you both had a look in the agent settings, Did you put the language AND title priority as desired?
episode priority is "AniDB, TheTVDB | TheTVDB, AniDB" by defalt, left part is series, right part is episode when '|' is present
Episode language is "x-jat, en, ja" so it will take romaji first which is jpanese spelt with roman alphabet which will come from AniDB
Language first then source priority in that language, then next language, and it takes the first found that way...
