### ISSUE TITLE
Plug-in.Support.folders.zip is missing

### ISSUE THREAD

**Issue by fakemoon** [ZeroQI/Hama.bundle#313]
Hi, I tried to install Hama.bundle on my new NAS server, but find that the URL https://github.com/ZeroQI/Hama.bundle/releases/download/v1.0/Plug-in.Support.folders.zip is in status 404.
Searched throw github releases and repo files, and went to google trying to find a alternative. Both method failed. Is this file not available anymore, or it is just taken down temporarily?
Thank you.

**Comment by ZeroQI** [comment]
I removed it yesterday as folders are created automatically since quite some time, needed to update the readme but lacked time to do so. My apologies and thanks for following the readme

**Comment by fakemoon** [comment]
Thanks a lot! It's working now.
