### ISSUE TITLE
AniDBMustAuthError: You must be authed to execute commands besides AUTH and PING

### ISSUE THREAD

**Issue by squeekr** [ZeroQI/Hama.bundle#316]
running into an issue, new to all this with anime on my plex. installed everything correctly as far as i can tell, but running into the error above. not sure where to go from here. here are the logs.

[com.plexapp.agents.anidb.log](https://github.com/ZeroQI/Hama.bundle/files/3205035/com.plexapp.agents.anidb.log)

thanks so much in advance!

**Comment by ZeroQI** [comment]
Wrong place, this log is from ANIDB agent, not HAMA agent whose page you are on and certainly didn't download the agent from...
Make sure you put correct anidb login and password in agent settings.
Support page is here for this agent https://forums.plex.tv/t/anidb-metadata-agent/15015
