### ISSUE TITLE
HAMA fails to fetch data from AniDB.

### ISSUE THREAD

**Issue by BUEKO** [ZeroQI/Hama.bundle#318]
It wasn't originally imported from the AniDB only, but in the course of repeated testing, it's not being imported from the TVDB for some reason. 

No keywords will be searched for manually. (gurren, gurren lagann, グレンラガン, ...)
In addition, the temporarily installed OSX version for trial and error allowed the same file to be added to the library without any problems. But I want to solve the problem on the main server.
I copied the name of the AniDB list I got from OSX version, ( 天元突破 グレンラガン [official(ja)] [anidb-4575] ) so I tried manually searching the server in question. 
But for some reason, the search works well at this time.
Why does this happen?

Upload my log file and screenshot together.
[BUEKO.zip](https://github.com/ZeroQI/Hama.bundle/files/3233551/BUEKO.zip)

(The sentence may be strange because English is not the native language. Please excuse me.)

<img width="731" alt="screenshot 2019-05-30 01 39 05" src="https://user-images.githubusercontent.com/51087093/58575535-3b5d3d80-827d-11e9-8b72-b1ad6905a288.png">
<img width="734" alt="screenshot 2019-05-30 01 39 34" src="https://user-images.githubusercontent.com/51087093/58575536-3b5d3d80-827d-11e9-9942-ae03f1f93a7a.png">
<img width="730" alt="screenshot 2019-05-30 01 39 40" src="https://user-images.githubusercontent.com/51087093/58575537-3b5d3d80-827d-11e9-8402-284ddf5eb00b.png">

**Comment by ZeroQI** [comment]
You saved an HTML page for AnimeLists/anime-list-master.xml that start with:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
```
i copied the content in a file and renammed to html extension and seems that way...
Solve the file format first or delete the file

**Comment by BUEKO** [comment]
It's a rudimentary mistake. Corrected as noted, removed the cache folder and scanned it again, and it works normally.
That was very thoughtful of you!
