### ISSUE TITLE
Most TVDB posters fail to download.

### ISSUE THREAD

**Issue by Kevman323** [ZeroQI/Hama.bundle#321]
I'm not entirely sure what is going on here, and it's getting late, so I'm going to stop looking into it for tonight, but there is an issue causing most TVDB posters not to load for shows. Shows with a lot of posters sometimes work, but smaller shows fail. In the "SHOW.agent-update.log" files, this appears in the TVDB section.
```
--- images -----------------------------
language_posters: ['en']
[!] File received too small (<64 bytes), file: "None"
```
It seems that when downloading the image summary with the tvdb api, it may be too small, and causing an issue. It comes from when the section was reworked in https://github.com/ZeroQI/Hama.bundle/commit/a46862ec76f5e27e625885cdd583127baa9a5b20 
If I change
` if len(file_downloaded)<64:       Log.Info('[!] File received too small (<64 bytes), file: "{}"'.format(file))`
to
` if len(file_downloaded)<0:       Log.Info('[!] File received too small (<64 bytes), file: "{}"'.format(file))`
The posters download correctly, and show up just fine, but it obviously removes whatever was trying to be done there.

**Comment by ZeroQI** [comment]
Could you please paste the content of the TheTVDB xml page with poster link cached by hama in agent data folders? Will then fix it asap... 
I need to display the content of the file being skipped as well if any

**Comment by Kevman323** [comment]
Sorry, which file are you looking for? There are like a million different types of logs here, and I'm not seeing any xml in the tvdb dataitems folder.

**Comment by Kevman323** [comment]
If you are referring to the json files saved per series, the following files are missing from series where posters are not downloaded.
`images_en.json`
`images_fanart_en.json`
`images_poster_en.json`
`images_season_en.json`

When looking at a series that I fixed with my edit, the `images_en.json` file saved for it is only 54 bytes, making it fall below the 64 byte line.  The TVDB ID for this series is 355624.

**Comment by ZeroQI** [comment]
Yes these files, they are json indeed and not xml, my bad.
Could you please attach them here?
I need to estimate the minimum length to set limits accordingly

**Comment by ZeroQI** [comment]
Please comment if not resolved in latest update

**Comment by MIIB1** [comment]
Hi
same problem i install last update but no luck
