### ISSUE TITLE
networking:219 errors with TVDB, then tvdb4 with all eps in one season folder metadata issue

### ISSUE THREAD

**Issue by clowncracker** [ZeroQI/Hama.bundle#322]
I am unable to get TVDB data to load.  In this case I was trying to match Dragon Ball Z w/ tvdb4.  I keep getting networking:219 errors.

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3327352/com.plexapp.agents.hama.log)

`2019-06-24 20:03:39,708 (7f3e92c77700) :  DEBUG (networking:166) - Requesting 'https://api.thetvdb.com/series/81472?en'`
`2019-06-24 20:03:39,817 (7f3e92c77700) :  ERROR (networking:219) - Error opening URL 'https://api.thetvdb.com/series/81472?en'`
`2019-06-24 20:03:39,823 (7f3e92c77700) :  DEBUG (networking:166) - Requesting 'https://api.thetvdb.com/series/81472/actors'`
`2019-06-24 20:03:39,906 (7f3e92c77700) :  ERROR (networking:219) - Error opening URL 'https://api.thetvdb.com/series/81472/actors'`
`2019-06-24 20:03:39,913 (7f3e92c77700) :  DEBUG (networking:166) - Requesting 'https://api.thetvdb.com/series/81472/episodes?page=1'`
`2019-06-24 20:03:39,989 (7f3e92c77700) :  ERROR (networking:219) - Error opening URL 'https://api.thetvdb.com/series/81472/episodes?page=1'`
`2019-06-24 20:03:39,994 (7f3e92c77700) :  DEBUG (networking:166) - Requesting 'https://api.thetvdb.com/series/81472/episodes?page=2'`
`2019-06-24 20:03:40,100 (7f3e92c77700) :  ERROR (networking:219) - Error opening URL 'https://api.thetvdb.com/series/81472/episodes?page=2'`
`2019-06-24 20:03:40,107 (7f3e92c77700) :  DEBUG (networking:166) - Requesting 'https://api.thetvdb.com/series/81472/episodes?page=3'`
`2019-06-24 20:03:40,189 (7f3e92c77700) :  ERROR (networking:219) - Error opening URL 'https://api.thetvdb.com/series/81472/episodes?page=3'`
`2019-06-24 20:03:40,194 (7f3e92c77700) :  DEBUG (networking:166) - Requesting 'https://api.thetvdb.com/series/81472/episodes?page=4'`
`2019-06-24 20:03:40,271 (7f3e92c77700) :  ERROR (networking:219) - Error opening URL 'https://api.thetvdb.com/series/81472/episodes?page=4'`
`2019-06-24 20:03:40,285 (7f3e92c77700) :  DEBUG (networking:166) - Requesting 'https://api.thetvdb.com/episodes/355412'`
`2019-06-24 20:03:40,389 (7f3e92c77700) :  ERROR (networking:219) - Error opening URL 'https://api.thetvdb.com/episodes/355412'`
`2019-06-24 20:03:40,394 (7f3e92c77700) :  DEBUG (networking:166) - Requesting 'https://api.thetvdb.com/episodes/355413'`
`2019-06-24 20:03:40,467 (7f3e92c77700) :  ERROR (networking:219) - Error opening URL 'https://api.thetvdb.com/episodes/355413'`
`2019-06-24 20:03:40,472 (7f3e92c77700) :  DEBUG (networking:166) - Requesting 'https://api.thetvdb.com/episodes/355414'`

**Comment by ZeroQI** [comment]
HAMA uses log redirection so the log you attached have tons of bits missing and is not very usefull

API worked here https://api.thetvdb.com/swagger#!/Series/get_series_id so TheTVDB API OK

Common.py line 387 should handle that

Have recently been hacked on paypal with RAT+socks port for unauth transactions so:
- full windows reinstall
- github desktop installed
- cloned HAMA and ASSrepository
- installed PlexMediaServer-1.16.0.1226-7eb2c8f6f-x86
- installed ASS+HAMA from cloned repo
- added library using ASS+HAMA
- went to Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs
- since library token not present logs in _unknown_folder.agent-update.log

Works for me...

**Comment by clowncracker** [comment]
The issue is only with HAMA, TVDB works on my other libraries.  Firewall isn't preventing anything and I am using the latest code.  Episode descriptions + posters are not populating for everything after episode 40 (season 2).  What other logs should I provide?

**Comment by ZeroQI** [comment]
i need the series update log in Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs
It may be in a sub-folder with the library name

**Comment by clowncracker** [comment]
[Dragon Ball Z.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/3331926/Dragon.Ball.Z.agent-search.log)
[Dragon Ball Z.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3331927/Dragon.Ball.Z.agent-update.log)
[Dragon Ball Z.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/3331928/Dragon.Ball.Z.filelist.log)
[Dragon Ball Z.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/3331929/Dragon.Ball.Z.scanner.log)

**Comment by ZeroQI** [comment]
Thank you. I configured the same, but works for windows server for me, you have linux
Line for TheTVDB auth is 391
Line for failed loading is 398
The technical bits are actually in the hama log you first gave and it display debug level BUT your logs are missing the below and can't figure out why:
`https://api.thetvdb.com/series/283998/actors, headers: {'Accept-Language': 'en', 'Content-type': 'application/json', 'User-agent': 'Plex/HAMA'}, HEADERS_TVDB: {'Authorization': u'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjE2ODk0ODQsImlkIjoiSEFNQSIsIm9yaWdfaWF0IjoxNTYxNjAzMDg0fQ.roUzswBkqBMKpJ9w2-kTP9cWpJb-H56ztIvpIv2Q4EKTuMDIVOSwmWr2XKuOODlp_E7xEZh52cRgqo88oRh0i6cb5h6fvmtPYOlPn-u_EzMobtOTt7thoHfDIGXhZGgXhKWMhcoEYiUK8UFAon4UH62G4dXLaGGZpnHKYpv3eHgsVxSlxffryocRdflYhs8r43qermZiE1IZsHnAUx3oN87vleq7CZCgDooplUwLvyvs3u6U6V3d7Dj2Qbrq5iN_29WcPeKJFnjnIfjMxBweM_ilYJZIUkAvBk7r6dlfRTaSJ7QBc6DMtwg65nOgr4iROeFs0Q3TJY_3mK5N7QBK_Q'}
`

**Comment by clowncracker** [comment]
Are there any other logs I can provide or something I can do to help find a solution?

**Comment by clowncracker** [comment]
@ZeroQI anything I can do?

**Comment by clowncracker** [comment]
@ZeroQI I created a new Plex server with a different docker and I still have TVDB issues.  Here are the new logs:

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3347740/com.plexapp.agents.hama.log)
[Dragon Ball Z.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/3347741/Dragon.Ball.Z.agent-search.log)
[Dragon Ball Z.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3347742/Dragon.Ball.Z.agent-update.log)
[Dragon Ball Z.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/3347743/Dragon.Ball.Z.filelist.log)
[Dragon Ball Z.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/3347744/Dragon.Ball.Z.scanner.log)

**Comment by ZeroQI** [comment]
updated master, please test and report

**Comment by clowncracker** [comment]
It looks like the networking:219 issue went away, but the posters and episode descriptions still didn't update.

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3355632/com.plexapp.agents.hama.log)
[Dragon Ball Z.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/3355633/Dragon.Ball.Z.agent-search.log)
[Dragon Ball Z.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3355634/Dragon.Ball.Z.agent-update.log)
[Dragon Ball Z.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/3355635/Dragon.Ball.Z.filelist.log)
[Dragon Ball Z.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/3355636/Dragon.Ball.Z.scanner.log)

**Comment by clowncracker** [comment]
@ZeroQI anything I can do?

**Comment by ZeroQI** [comment]
@clowncracker you used a season folder and all episodes in it while there is a tvdb mapping setting in the scanner tvdb mapping file...

Did you want to avail of the tvdb4 mode to put eps in season for each saga automatically or you wanted volontarilly all eps in a single season 1 ?

Because there is a mapping hama expect it used but it was overritten by the season folder... 
You could use a local mapping tvdb4 mapping for this tvdbid but otherwise empty and this should be solved

**Comment by clowncracker** [comment]
Maybe I'm not understanding how tvdb4 works?  Ideally I would want all of the metadata to pull in for episodes 1-291 (as season 1) and also pull in for the specials (specials).

Is my folder structure wrong?  Should I be making updates to the tvdb xml file?

**Comment by ZeroQI** [comment]
If you had not put a season folder, it would try to append mappings, since there is no local mapping file with `<anime tvdbid="81472" name="Dragon Ball Z">` in it, it would have loaded the mapping from tvdb4 here: https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/tvdb4.mapping.xml
```
  <anime tvdbid="81472" name="Dragon Ball Z">
    01|001|039|Saiyan Saga
    02|040|074|Namek And Captian Ginyu Sagas
    03|075|107|Frieza Saga
    04|108|139|Garlic Jr., Trunks and Androids Sagas
    05|140|165|Imperfect Cell and Perfect Cell Sagas
    06|166|194|Cell Games Saga
    07|195|219|Great Saiyaman and World Tournament Sagas
    08|220|253|Babidi and Majin Buu Sagas
    09|254|291|Fusion and Kid Buu Sagas
  </anime>
```
and created 9 seasons and the metadata would match...
Since you force a single season but there is a mapping HAMA wrongly applies it... 
Only happens with series with a different season mapping than the mapping file, which is rare enough...

I don't want to apply detection in the final loop and mapping seem to be line 139-140 of TheTVDBv2.py.
I believe the following addition will re-test for tvdb4 only if the file mapped exist and reset to existing file otherwise. Please test and report

```
      elif season!='0' and metadata_source=='tvdb4':  
        ms, usl                         = Dict(mappingList, 'absolute_map', 'max_season'), Dict(mappingList, 'absolute_map', 'unknown_series_length')
        if ms and usl:  season, episode = Dict(mappingList, 'absolute_map', str(abs_number), default=(ms if usl else str(int(ms)+1), None))[0], str(abs_number)

        if metadata_source=='tvdb4' and (season not in media.seasons or episode not in media.seasons[season].episodes):
          for s in media.seasons:
          if str(abs_number) in media.seasons[s].episodes:
            season, episode = s, abs_number
            break
```

**Comment by clowncracker** [comment]
No metadata loaded at all with that fix.  Attached the updated TheTVDBv2.py as well.

[Dragon Ball Z.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/3366112/Dragon.Ball.Z.filelist.log)
[Dragon Ball Z.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/3366113/Dragon.Ball.Z.scanner.log)
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3366114/com.plexapp.agents.hama.log)
[Dragon Ball Z.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/3366115/Dragon.Ball.Z.agent-search.log)
[Dragon Ball Z.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3366116/Dragon.Ball.Z.agent-update.log)
[TheTVDBv2.zip](https://github.com/ZeroQI/Hama.bundle/files/3366117/TheTVDBv2.zip)

**Comment by ZeroQI** [comment]
"IndentationError: expected an indented block"
Off by one or more spaces (or used tabs)

**Comment by clowncracker** [comment]
I fixed the code, still no metadata for episodes 40+.

[Dragon Ball Z.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3366132/Dragon.Ball.Z.agent-update.log)
[Dragon Ball Z.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/3366133/Dragon.Ball.Z.filelist.log)
[Dragon Ball Z.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/3366134/Dragon.Ball.Z.scanner.log)
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3366135/com.plexapp.agents.hama.log)
[Dragon Ball Z.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/3366136/Dragon.Ball.Z.agent-search.log)
[TheTVDBv2.zip](https://github.com/ZeroQI/Hama.bundle/files/3366137/TheTVDBv2.zip)

**Comment by ZeroQI** [comment]
Before new code
`[X]   s9e38 s09e038 anidbid:         air_date: 1996-01-31 abs_number: 291, title: Goku's Next Journey`
After new code
`[X]   s9e38 s01e291 anidbid:         air_date: 1996-01-31 abs_number: 291, title: Goku's Next Journey`

Looking at TheTVDB_dict returned it's near perfect now, but the absolute ep number is not a string...
Please correct by changing `season, episode = s, abs_number` to `season, episode = s, str(abs_number)`
```
      elif season!='0' and metadata_source=='tvdb4':  
        ms, usl                         = Dict(mappingList, 'absolute_map', 'max_season'), Dict(mappingList, 'absolute_map', 'unknown_series_length')
        if ms and usl:  season, episode = Dict(mappingList, 'absolute_map', str(abs_number), default=(ms if usl else str(int(ms)+1), None))[0], str(abs_number)

        if metadata_source=='tvdb4' and (season not in media.seasons or episode not in media.seasons[season].episodes):
          for s in media.seasons:
          if str(abs_number) in media.seasons[s].episodes:
            season, episode = s, str(abs_number)
            break
```

**Comment by ZeroQI** [comment]
@clowncracker if change works, will integrate on master code, just need "str()" arount "abs_number"

**Comment by clowncracker** [comment]
@ZeroQI sorry for the delay, looks like it works.  Thanks for all your help!

**Comment by clowncracker** [comment]
@ZeroQI, the 219 error came back after the latest update.

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3454943/com.plexapp.agents.hama.log)
[Isekai Cheat Magician.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3454944/Isekai.Cheat.Magician.agent-update.log)

**Comment by ZeroQI** [comment]
Error opening URL 'http://api.tmdb.org/3/movie/90215?
Error opening URL 'http://webservice.fanart.tv/v3/tv/360708?api_key=cfa9dc054d221b8d107f8411cd20b13f'
Error opening URL 'http://api.tmdb.org/3/movie/tt10362632?
http://webservice.fanart.tv/v3/tv/360502?api_key=cfa9dc054d221b8d107f8411cd20b13f

there's no tvdb error in there...
fanart tv seem to genuinely have no meta for that series...
is something actually not gathering metadata like before? some 219 errors are normal, before other people were impacted and had meta issue...

**Comment by clowncracker** [comment]
Why isn't the episode name updating?  There's clearly data there from the hama log.

Line 193: [X] s1e  4 => s1e  4 air_date: 2019-07-31 language_rank: 0, title: "Crimson Pact"
Line 401: [?] rank: 0, source_title: TheTVDB, title: "Episode 4"

**Comment by ZeroQI** [comment]
```
metadata.seasons[ 1].episodes[  4]
[?] rank: 0, source_title: TheTVDB, title: "Episode 4"
[=] title                          Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB', 'AniDB']'  Value: 'Episode 4'
```
Your agent settings says to pick for episode title TheTVDB as source first (if language are at the same level) which has "Episode 4" and it does...

**Comment by EndOfLine369** [comment]
@ZeroQI, we use to in tthe past (quite a while ago) ignore episode titles that were "Episode \d". I think we should add it into the AniDB & TVDB episode title checks and clear out the string if it matches. Sound good to you?

**Comment by EndOfLine369** [comment]
Only potential problem would be when both sources are "Episode \d"...

**Comment by ZeroQI** [comment]
@EndOfLine369 I don't see that as a problem...
Using open bug https://github.com/ZeroQI/Hama.bundle/issues/329 for correcting

**Comment by clowncracker** [comment]
That's odd, since the library has the title preference as the following:
T-EM 'title' : AniDB, TheTVDB | TheTVDB, AniDB

That would indicate that the tile should be pulling from AniDB first, right?  I checked DefaultPrefs.json and it has the same setting.

**Comment by clowncracker** [comment]
Also of note it looks like TVDB was updated with an episode title.  I did the Plex dance and no episode title is still loading.

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3458439/com.plexapp.agents.hama.log)
[Isekai Cheat Magician.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3458440/Isekai.Cheat.Magician.agent-update.log)

**Comment by ZeroQI** [comment]
Episode's title comes from TheTVDB
If your episodes gets no title your Plex database is corrupted as HAMA provides them

metadata.seasons[ 1].episodes[  1]
[?] rank: 0, source_title: TheTVDB, title: "Lost Ones from Another World"
[=] title                          Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB', 'AniDB']'  Value: 'Lost Ones from Another World'

metadata.seasons[ 1].episodes[  2]
[?] rank: 0, source_title: TheTVDB, title: "Magic Training"
[=] title                          Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB', 'AniDB']'  Value: 'Magic Training'

metadata.seasons[ 1].episodes[  3]
[?] rank: 0, source_title: TheTVDB, title: "Beginner Adventurers"
[=] title                          Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB', 'AniDB']'  Value: 'Beginner Adventurers'

metadata.seasons[ 1].episodes[  4]
[?] rank: 0, source_title: TheTVDB, title: "Episode 4"
[=] title                          Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB', 'AniDB']'  Value: 'Episode 4'

**Comment by clowncracker** [comment]
Why is the title reverting to TVDB when the preferences are set to AniDB?

Also - TVDB has a title for episode 4: https://www.thetvdb.com/series/isekai-cheat-magician/episodes/7254225

**Comment by ZeroQI** [comment]
The episode 4 that aired yesterday? Thetvdb meta was cached, file is 17 hours old:
`common.LoadFile() - File cached locally - url: 'https://api.thetvdb.com/series/360708/actors', Filename: 'TheTVDB/json/360708/actors_en.json', Age: '63257.5513666', Ended: None
`
17 hours!!!!!!!

Title priority: AniDB, TheTVDB | TheTVDB, AniDB 
= for series title: AniDB, TheTVDB
= for episodes title: TheTVDB, AniDB 

TheTVDB is first for episode titles, you are wasting my time...

**Comment by clowncracker** [comment]
Is it possible to force update the TVDB cache or to use live data if available?  If I add something to my library the same day it releases, it would be ideal if I didn't need to wait 24 hours for the metadata.

The poster didn't even fetch for this show:

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3458846/com.plexapp.agents.hama.log)
[Machikado Mazoku.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3458847/Machikado.Mazoku.agent-update.log)
