### ISSUE TITLE
Hama selectively refuses to scrape from anidb

### ISSUE THREAD

**Issue by lewdnasty** [ZeroQI/Hama.bundle#324]
Sorry, dumb with Git.

I have several shows that absolute refuse to scrape from anidb. For example, 
'X:\Video\Anime\JoJo's Bizarre Adventure - Diamond is Unbreakable' 
and
'X:\Video\Anime\Jojo's Bizarre Adventure'
is only pulling from tvdb, while 
'X:\Video\Anime\JoJo's Bizarre Adventure - Stardust Crusaders'
scrapes just fine. There are several inconsistent shows like this and I am unable to identify any patterns that could be of use. using 'aid:xxxx' also fails to directly pull for issue shows (as well as appending such to the folder name), so I am at a loss as what to do. Any help would be appreciated, and thanks overall for keeping hama supported, killer program so far and plex wouldn't hold nearly the same appeal without it. Let me know if there's anything I can do to help diagnose this issue.

EDIT:

For additional clarification, files are named according to the plex standard. It doesn't struggle to 'identify' the show per se, it struggles to allow certain shows to even access anidb. Even if I wanted to identify them as something super popular (like Bleach or One Piece for example,) only the tvdb equivalents show up for those specific folders. I have deleted and redownloaded the current anime-titles.xml and restarted the server. been plex dancing like a madman trying to figure this out. Current version of Hama.

**Comment by lewdnasty** [comment]
Sorry, dumb with Git.

I have several shows that absolute refuse to scrape from anidb. For example, 
'X:\Video\Anime\JoJo's Bizarre Adventure - Diamond is Unbreakable' 
and
'X:\Video\Anime\Jojo's Bizarre Adventure'
is only pulling from tvdb, while 
'X:\Video\Anime\JoJo's Bizarre Adventure - Stardust Crusaders'
scrapes just fine. There are several inconsistent shows like this and I am unable to identify any patterns that could be of use. using 'aid:xxxx' also fails to directly pull for issue shows, so I am at a loss as what to do. Any help would be appreciated, and thanks overall for keeping hama supported, killer program so far and plex wouldn't hold nearly the same appeal without it. Let me know if there's anything I can do to help diagnose this issue.

**Comment by ZeroQI** [comment]
Logs

**Comment by lewdnasty** [comment]
[JoJo's Bizarre Adventure - Diamond is Unbreakable.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/3387460/JoJo.s.Bizarre.Adventure.-.Diamond.is.Unbreakable.agent-search.log)
One of the trouble folders. As previously stated, if I was to search the exact same string on a different folder, it would pull up all expected results from anidb.

**Comment by ZeroQI** [comment]
HAMA searches from:
- from AniDB if the series have season 1 episodes maximum...
- TVDB titles first if there is episodes after season 1

If you have season 2+ eps, clearly you are not following anidb numbering since it only have a single series but if the match doesn't reach 80% then clearly you are not using tvdb titles for series
Working as designed.
