### ISSUE TITLE
TVDB4 Specials marked as missing in log

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#328]
Just creating a new thread from #298 regarding specials that aren't absolute being marked as missing in the logs.

[logs.zip](https://github.com/ZeroQI/Hama.bundle/files/3449659/logs.zip)

**Comment by ZeroQI** [comment]
Specials present on disks (looking at metadata loop at the ebd that cycle through present media):
- one piece metadata.seasons[ 0].episodes[ 37]
- one piece metadata.seasons[ 0].episodes[ 38]

TVDB detection ok: (tick in front of the ep.)

[X]   s0e37 s25e000 anidbid:         air_date: 2017-08-26 abs_number: 0, title: Episode of East Blue: Luffy and His Four Crewmates' Great Adventure
 - [ ] summary: This is an abridged retelling of the first five Straw Hat Pirates' development during East Blue Saga. As the Straw Hat Pirates prepare to leave East Blue and enter the Grand Line, each of them reminis..
 - [1] language_rank: 0, language:   en, title: Episode of East Blue: Luffy and His Four Crewmates' Great Adventure
common.SaveFile() - CachePath: 'C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems', file: 'TheTVDB/json/81797\episode_6292428_en.json'
 - [ ] thumb: https://thetvdb.plexapp.com/banners/episodes/81797/6292428.jpg
[X]   s0e38 s25e000 anidbid:         air_date: 2018-08-25 abs_number: 0, title: Episode of Skypiea
 - [ ] summary: 
 - [1] language_rank: 0, language:   en, title: Episode of Skypiea

Logs file: said episodes s00e37 and s00e38 are NOT missing in logs so working

TVDBid: 81797 | Title: 'One Piece' | Missing Episodes: ['0 (s0e1)', '0 (s0e2)', '0 (s0e3)', '0 (s0e4)', '0 (s0e5)', '0 (s0e6)', '0 (s0e7)', '0 (s0e8)', '0 (s0e9)', '0 (s0e10)', '0 (s0e11)', '0 (s0e12)', '0 (s0e13)', '0 (s0e14)', '0 (s0e15)', '0 (s0e16)', '0 (s0e17)', '0 (s0e18)', '0 (s0e19)', '0 (s0e20)', '0 (s0e21)', '0 (s0e22)', '0 (s0e23)', '0 (s0e24)', '0 (s0e26)', '0 (s0e27)', '0 (s0e28)', '0 (s0e29)', '0 (s0e30)', '0 (s0e31)', '0 (s0e32)', '0 (s0e33)', '0 (s0e34)', '0 (s0e35)', '0 (s0e36)']

Please indicate series name, season and ep number of missing episode if i am mistaken, closing in the meantime
