### ISSUE TITLE
Newest Version of Plex AND TheTVDB 

### ISSUE THREAD

**Issue by DarthKnight12** [ZeroQI/Hama.bundle#330]
Seems like the newest version of Plex (web 4.0) has completely killed HAMA (can not be found and loaded anymore). Apparently plex has changed the plugins again. Also TVDB has revamped its site to include something they call flexible seasons (in the case of One Piece i guess this will eliminate the problem E591 had)

**Comment by ifonefox** [comment]
Are you accessing plex via plex.tv? That version of plex web is on 4, while the localhost:32400 is still on 3. https://forums.plex.tv/t/plugins-arent-always-showing-up/440310/4


In version 4, plugins are now located in `Settings/Manage/Plugins` https://forums.plex.tv/t/plugins-arent-always-showing-up/440310/6

**Comment by sven-7** [comment]
I'm not having any issues with HAMA -- mine is running as expected.

**Comment by clowncracker** [comment]
It looks like TVDB is having API issues right now: https://forums.thetvdb.com/viewtopic.php?f=118&t=57657

Recent updates to TVDB data won't populate in Plex.

**Comment by ZeroQI** [comment]
agent working for sven-7 so closing. data pulled updated by hama, not an agent issue

**Comment by DarthKnight12** [comment]
hama will not even show up for me under settings (still 4.0 issue cannot access 3.x version) and it is not selectable under library managment for me

**Comment by mdcx** [comment]
Did you try moving the plug to the new location per the recommendation
further up in the thread?

**Comment by DarthKnight12** [comment]
On root there is no folder called settings

**Comment by ifonefox** [comment]
On https://app.plex.tv I am able to see Hama as an available agent. If you go to settings (the wrench and screwdriver icon in the top-right), there is an "Agents" option under "Settings" in list on the left side. For "Movies", there should be a HamaMovies options; for television, there should be a HamaTV option. Do those options exist for you @DarthKnight12?

**Comment by DarthKnight12** [comment]
No these options do not exist for me (I know what you're talking about). I have checked it multiple times for the library settings ASS does exist but if I go to agents in settings Hama will not show up

**Comment by DarthKnight12** [comment]
i think i found the issue: when plex updated to 4.0 apparently it wiped the entire plugins root folder empty, readded everything and now it works

**Comment by Koyakami** [comment]
Just to note that I've got the same issue and in my "plug-ins" folder I have hama.bundle but yet even after plex restart, I still don't see it in my localhost or app.plex.tv under settings -> agents -> any of them. Was there anything else you added to that folder to get Hama working?

Thanks

**Comment by ZeroQI** [comment]
@Koyakami try other agent and check file rights.

**Comment by ZeroQI** [comment]
@Koyonami please confirm your OS and versions so we can confirm if others in the exact same environment are impacted

**Comment by DarthKnight12** [comment]
ok so i managed to get it working again and 99.99999 % has matched correctly....but one single show....you guessed right....one piece.... it will not match, i have removed the library, readded it cleaned the trash analysed the database reoptimized it, deleted hama readded it and updated ass again and sofar nothing one piece just wont match

**Comment by ZeroQI** [comment]
So initial issue resolved?
One piece.search.log will have the answer
