### ISSUE TITLE
function error and UnicodeDecodeError

### ISSUE THREAD

**Issue by morecool** [ZeroQI/Hama.bundle#333]
Aug  5 11:02:37 media sh[4027]: common:415: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
Aug  5 11:02:37 media sh[4027]: AnimeLists:35: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
Aug  5 11:02:38 media sh[4027]: AnimeLists:21: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
Aug  5 11:02:38 media sh[4027]: AnimeLists:23: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
Aug  5 11:02:38 media sh[4027]: AnimeLists:24: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
Aug  5 11:02:39 media sh[4027]: AnimeLists:60: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
Aug  5 11:02:43 media sh[4027]: Traceback (most recent call last):
Aug  5 11:02:43 media sh[4027]:   File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/logging/handlers.py", line 76, in emit
Aug  5 11:02:43 media sh[4027]:     if self.shouldRollover(record):
Aug  5 11:02:43 media sh[4027]:   File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
Aug  5 11:02:43 media sh[4027]:     msg = "%s\n" % self.format(record)
Aug  5 11:02:43 media sh[4027]:   File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/logging/__init__.py", line 734, in format
Aug  5 11:02:43 media sh[4027]:     return fmt.format(record)
Aug  5 11:02:43 media sh[4027]:   File "/usr/lib/plexmediaserver/Resources/Plug-ins-22929c8a2/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 77, in format
Aug  5 11:02:43 media sh[4027]:     record.__dict__[key] = uni(record.__dict__[key])
Aug  5 11:02:43 media sh[4027]: UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 167: invalid start byte
Aug  5 11:02:43 media sh[4027]: Logged from file sandbox.py, line 19
Aug  5 11:02:43 media sh[4027]: AniDB:368: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.

environment : Debian 9 / 10

**Comment by ZeroQI** [comment]
Aug 5 11:02:43 media sh[4027]: UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 167: invalid start byte

This is insufficient sadly. Have the series log or title and that cause this error?

**Comment by morecool** [comment]
I don't know any reason. 
my environment is almost korean, english title


debian 10 x64
python 2.7.16

**Comment by ZeroQI** [comment]
Could be a specific Korean character giving issue but I have no specific error in Hama code mention just framework code ones...
If you do not have a series that fail getting metadata and this series custom log to submit then I am not sure how to solve nor if it even is a Hama agent issue, could be a framework issue...
