### ISSUE TITLE
[Feature Request] Append to title

### ISSUE THREAD

**Issue by avluis** [ZeroQI/Hama.bundle#334]
Since Plex has yet to [address the issue](https://forums.plex.tv/t/bug-report-unable-to-update-original-title-in-tv-show-and-season-summary/183240) with the `Original Title` field I was hoping to request a low priority alternative -- I filed [something similar](https://github.com/ZeroQI/Absolute-Series-Scanner/issues/89) to this on the wrong repo.

Given the series `Hataraku Saibou` along with `T-EM 'title'` set to `AniDB, TheTVDB | AniDB, TheTVDB` and `Serie Language Priority` set to `main, x-jat, en, ja` would love to have the option to append an alternative title to the `T-EM 'title'` field.

What I'm thinking of are two new fields in the agent settings;
- `T-EM alt 'title' separator`; takes the exact string value of this field and appends it to `T-EM 'title'`
- `T-EM alt 'title' language`; takes one or a comma separated lang string to resolve and append its value to `T-EM alt 'title' separator`

So `T-EM alt 'title' separator` is set to ` | ` (note the spaces) and `T-EM alt 'title' language` set to `en, x-jat, main, ja` would result in ` | Cells at Work!` being appended to `T-EM 'title'`.

So in the case of `Hataraku Saibou`, it would appear in Plex as `Hataraku Saibou | Cells at Work!`

Two conditions to consider as well:
- If no alternative title is available then nothing will be appended
- And if the alternative title matches the existing title then nothing will be appended

How feasible is this?

**Comment by ZeroQI** [comment]
i don't want two more settings trying to keep it simple
- use sort title for alt title but list will be out of order
- use 'main' language to get anidb main title which should be the most known title

The simplest would be a  Local source for title where it retains the series folder title.
Are your series folder labeled like that?

**Comment by avluis** [comment]
My series directory follows the anidb naming convention with the `anidb3` modifier, so for ex:
`Dr. Stone [anidb3-14491]` or `FateGrand Order Zettai Majuu Sensen Babylonia [anidb3-14238]`.

Only issue for that is that any unsupported characters are dropped when added so the names won't necessarily reflect the actual series name.

Though, I do need to mention; finally got some traction with the bug report on the [Plex forums](https://forums.plex.tv/t/bug-report-unable-to-update-original-title-in-tv-show-and-season-summary/183240/6) so this may not be needed if the original title field is finally fixed.

Only issue I would see after that bug is hopefully fixed is being able to set the language preference for the original title field.
In the long run, my issue is that I'm not able to choose the language for each field with the current implementation (being language priority for the respective fields).

**Comment by ZeroQI** [comment]
@avluis If they make the original title work, will support it fully in the same fashion as the title currently.
"Only issue for that is that any unsupported characters are dropped when added so the names won't necessarily reflect the actual series name." like what ?

"In the long run, my issue is that I'm not able to choose the language for each field with the current implementation (being language priority for the respective fields)."
Which fields?
- Summary is driven by the library language 
- titles follow the language specified first, then the metadata source. In other words, if you select chinese first, it will pick the first chinese title in the order of the metadata sources, then proceed with the next language

**Comment by avluis** [comment]
- `like what ?` LN based series have a tendency to make use of punctuation marks that aren't valid directory names so they are usually cleaned up, ex; `\ " : / * < > ? ,` to name a few; so the directory name will not match the actual series name if it is parsed.

- `Which fields?` `title`, `title_sort` and `original_title` (once its working) would follow what is defined in `Serie Language Priority`, right? In my case, that is set to `main, x-jat, en, ja`.

Basically, I would like to be able to set a language priority for one of those fields (mainly; `original_title`) **separately** from what is defined in `Serie Language Priority` to be able to set the priority to `en, x-jat, main, ja`.

The logic behind this is to be able to set an alternative language from whatever is already defined for `title` & `title_sort`.

Ideally, these fields should be unlinked altogether so the user can define the language desired for those fields.
I need to check out your agent template and see if I can design a conditional UI within the confines of Plex to accommodate this.
I'm also wondering if it is possible to be able to define these items in the hama configuration xml and not have them exposed to the Plex UI at all.

**Comment by ZeroQI** [comment]
If/when the field is working I will add it to HAMA
Now shall it includes a separate language priority using 'main' keyword and meta source for consistency...

**Comment by avluis** [comment]
If the field language priority is set to `main` keyword then it would fit best as the name of the field is `original_title` (if we go by AniDB naming convention).

This way I can set `Serie Language Priority` to `en, x-jat, main, ja` for `title` & `title_sort` and `original_title` would stay as `main` which would accomplish what I'm trying to do.

I'm thinking this should be a good middle ground between keeping the agent UI as it currently is while not altering the behavior of `Serie Language Priority` for `title` & `title_sort` just to accommodate this request.

**Comment by ZeroQI** [comment]
Once the field original_title is able to be changed by agents i will support it
It will be the original title which for anidb is the main title.

**Comment by ZeroQI** [comment]
'original title' is set for movies and series already in common.py FieldListMovies and FieldListSeries and filled in AniDB and TVDB already, so technically already supporting it... Should show in logging in series update.log already.
Plex issue if not showing up in Plex web GUI
