### ISSUE TITLE
Weird Matching in Naruto Shippuuden to Opening/Ending because of name

### ISSUE THREAD

**Issue by mweber03** [ZeroQI/Hama.bundle#336]
My directory is `Naruto Shippuden [anidb2-4880]`

I've got 2 episodes matching oddly.

`Naruto Shippuden - 379 - An Opening` to `Opening 01` in Specials
`Naruto Shippuden - 393 - A True Ending` to `Ending 01` in Specials

Looks like something to do with the word search

[Naruto Shippuden [anidb2-4880].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3511725/Naruto.Shippuden.anidb2-4880.agent-update.log)

[Naruto Shippuden [anidb2-4880].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/3511726/Naruto.Shippuden.anidb2-4880.scanner.log)

I got it to work temporarily by renaming them to:
`Naruto Shippuden - 379 1x379 - An Opening`
`Naruto Shippuden - 393 1x393 - A True Ending`
But I'd rather not do this if I can help it.

**Comment by ZeroQI** [comment]
You are banned:
```
URL: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=4880', Creating cached file: '/tmp/ASS-anidb-4880.xml'
-- Sleeping 6sec to prevent AniDB ban
-- Bad response received: <error code="500">banned</error>
```

The very first lines of the readme
`If all video files are showing in plex at the right season and episode number, the scanner did its job. Please view ASS readme here: https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/README.md`

The anidb2 mode is supposed to put seasons and doesn't

You have multiple times the same episode number, not supported by scanner as if it sees the same number multiple times it will skip it and use the next number and use regex then. 
```
"Naruto Shippuden [tvdb-79824]" s01e007                         "Word Search" "Assemble!" "Naruto Shippuden - 373 - Team 7 Assemble!.mkv"
"Naruto Shippuden [tvdb-79824]" s01e373                         "ANIDB_RX-5" "Team Seven, Assemble!!" "Naruto Shippuden - 373 - Team Seven, Assemble!!.mkv"
"Naruto Shippuden [tvdb-79824]" s00e101                         "ANIDB_RX-1" "Opening 01" "Naruto Shippuden - 379 - An Opening.mkv"
"Naruto Shippuden [tvdb-79824]" s00e101                         "ANIDB_RX-1" "Opening 01" "Naruto Shippuden - 379 - An Opening.mp4"```
"Naruto Shippuden [tvdb-79824]" s00e151                         "ANIDB_RX-2" "Ending 01" "Naruto Shippuden - 393 - A True Ending.mkv"
"Naruto Shippuden [tvdb-79824]" s00e151                         "ANIDB_RX-2" "Ending 01" "Naruto Shippuden - 393 - A True Ending.mp4"
```
You created an agent issue for a clear scanner issue (wrong ep number, seasons missing).
closing.
