### ISSUE TITLE
Refresh Metadata

### ISSUE THREAD

**Issue by mweber03** [ZeroQI/Hama.bundle#337]
I switched the title setting from: `AniDB,TheTVDB` to `TheTVDB,AniDB` but how do I get Plex to pick up the change for an existing series.

I tried `Refresh Metadata` but the titles I expected to change didn't.

Is there something else I need to do?

Some episodes look like they're nothing even pulling data (their title and release date are unchanged from the default). Examples: 386, 388, 351+

[Naruto Shippuden [anidb2-4880].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3511735/Naruto.Shippuden.anidb2-4880.agent-update.log)

[Naruto Shippuden [anidb2-4880].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/3511736/Naruto.Shippuden.anidb2-4880.scanner.log)

**Comment by ZeroQI** [comment]
Metadata Fields (items #), type, source provider, value
[=] title                          Sources: (TheTVDB),AniDB                                               Inside: '['TheTVDB', 'AniDB']'  Value: 'Naruto Shippuden'
[=] title_sort                     Sources: AniDB,(TheTVDB)                                               Inside: '['TheTVDB']'  Value: 'Naruto Shippuden'

metadata.seasons[ 1].episodes[  1]
[?] rank: 0, source_title: TheTVDB, title: "Homecoming"
[=] title                          Sources: (TheTVDB),AniDB                                               Inside: '['TheTVDB']'  Value: 'Homecoming'

Parenthesis are around TheTVDB so it is the source that was selected.
If the metadata is not updated there Plex has an issue

There is no metadata for episodes from s01e33... and no other seasons...
You are using anidb2 so the scanner is meant to put eps using tvdb numbering but the scanner failed to do that, so no metadata. 

The very first lines of the readme
`If all video files are showing in plex at the right season and episode number, the scanner did its job. Please view ASS readme here: https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/README.md`

This is a clear scanner issue. it cannot find metadata as seasons are missing and anidb2 is mapped to tvdb numbering and seasons are missing
Closing as HAMA behaves as expected
