### ISSUE TITLE
Issues getting Hama to match

### ISSUE THREAD

**Issue by Uutama** [ZeroQI/Hama.bundle#338]
Every once in a while I try to install HAMA in hopes that it will work for me. I've never been able to get it to work. Maybe I just suck at it, but I've never had any other issues with any other agent before. I've tried to fix it time and time again, but I'm finally giving up. I need help.

Anyway, the agent loads into Plex and is recognized. ASS and HamaTV are selected as my agents in my anime library. No search results are found immediately after attempting a search. I think that it's not pulling the lists from AniDB, potentially? I've read to delete the title cache xml, but either I am deleting the wrong file or it's not working.

Here are my logs.
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3524532/com.plexapp.agents.hama.log)

**Comment by ZeroQI** [comment]
It fails to download anidb files...
using latest version as this issue was solved not too long ago normally?
Please indicate the link used

**Comment by Uutama** [comment]
I used the download from this link.
https://github.com/ZeroQI/Hama.bundle
I tried manually putting in the anime lists with the links provided in the metadata sources of the description:
ScudLee's XMLs: https://github.com/ScudLee/anime-lists/ ScudLee's XBMC AniDB mod agent: http://forum.xbmc.org/showthread.php?tid=142835&pid=1432010#pid1432010

**Comment by ZeroQI** [comment]
Get the latest source zip in github release for hama https://github.com/ZeroQI/Hama.bundle > "Clone or download > Download Zip Folders 
https://raw.githubusercontent.com/ScudLee/anime-lists/master/animetitles.xml to be saved 'anime-titles.xml'

**Comment by Uutama** [comment]
It seems to be working after saving as 'anime-titles.xml'
Still, will this cause issues when updating the lists?
Otherwise, it should be okay.

**Comment by ZeroQI** [comment]
nothing will work without....
wondering why it didn't download for you...
could be a write issue in agent data folder but weird if other files are written there, a firewall preventing that file only or an old hama version...
make no sense currently...

**Comment by avluis** [comment]
@ZeroQI With the latest version; I'm still seeing a compressed version of anime-titles.xml replace the uncompressed copy --- still monitoring to see if this coincides with an anidb ban or if the extraction is failing somehow.
Current copy is from 17.08.2019 so waiting on cache to expire.

**Comment by avluis** [comment]
@ZeroQI `anime-titles.xml` was replaced yesterday (30.08.2019) at 15:47 -- appended `.gz` to it and sure enough; it is an archive -- I'll go ahead and open an issue to try and track this behavior down.
[anime-titles.xml.gz](https://github.com/ZeroQI/Hama.bundle/files/3562961/anime-titles.xml.gz)
