### ISSUE TITLE
HAMA agent is not extracting anime-titles.xml properly

### ISSUE THREAD

**Issue by avluis** [ZeroQI/Hama.bundle#340]
I've been observing this behavior sometime after the HAMA agent received a few updates to address the `anime-titles.xml` downloading a compressed copy of said file.

Unfortunately it seems the issue wasn't fully addressed as I've found my copy of the file is the compressed archive after cache invalidates and downloads a fresh copy.
Mentioned this [here](https://github.com/ZeroQI/Hama.bundle/issues/338#issuecomment-524081329) but decided to open an issue instead.

HAMA is supposed to extract this file, correct?
[anime-titles.xml.gz](https://github.com/ZeroQI/Hama.bundle/files/3562961/anime-titles.xml.gz)

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3562967/com.plexapp.agents.hama.log)
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3562970/com.plexapp.agents.hama.log)
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3562973/com.plexapp.agents.hama.log)

**Comment by ZeroQI** [comment]
This log is a bit short as I redirect logging to separate files.
Can you include a .update.log file in agent data folders?

**Comment by avluis** [comment]
I'm sorry; I've re-read the README a few times but I'm not finding an .update.log that's relevant to the agent itself -- there's plenty of logs for the series themselves though -- is that what you're looking for?

Just in case; here are a few files that are around the time the `anime-titles.xml` file was replaced:
[Dr. Stone [anidb3-14491].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3563545/Dr.Stone.anidb3-14491.agent-update.log)
[Araburu Kisetsu no Otome-domo yo. [anidb3-14512].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3563546/Araburu.Kisetsu.no.Otome-domo.yo.anidb3-14512.agent-update.log)
[Toaru Kagaku no Accelerator [anidb3-14440].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3563547/Toaru.Kagaku.no.Accelerator.anidb3-14440.agent-update.log)
[Dungeon ni Deai o Motomeru no wa Machigatte Iru Darouka Familia Myth [anidb3-10894].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3563548/Dungeon.ni.Deai.o.Motomeru.no.wa.Machigatte.Iru.Darouka.Familia.Myth.anidb3-10894.agent-update.log)


There is the this file that is sort of relevant: 
[_root_.agent.log](https://github.com/ZeroQI/Hama.bundle/files/3563544/_root_.agent.log)

**Comment by ZeroQI** [comment]
@avluis That's the ones and you are right, nothing much useable for that in there. The only line saying something is: 
`common.LoadFile() - File cached locally - url: 'http://anidb.net/api/anime-titles.xml.gz', Filename: 'AniDB/anime-titles.xml', Age: '7257.39261961', Ended: None`

I checked and my file was compressed, the test for anidb was not working so the anti-ban for anidb not working and only decompressed once, so put twice in case as it was double compressed, so definitely an important bug

Please check latest release and report

**Comment by avluis** [comment]
Got it -- I'll pull latest and wait for cache to expire to verify the fix.

**Comment by ZeroQI** [comment]
if you delete the file and it will re-download quicker...

**Comment by avluis** [comment]
Awesome! Thank you for confirming and for fixing this!
