### ISSUE TITLE
Metadata failover and image bug

### ISSUE THREAD

**Issue by Kinsiinoo** [ZeroQI/Hama.bundle#342]
Infinity Train (Life with Louie and some other series) load all metadata and download the posters, arts, etc. but this happen:

![p08](https://user-images.githubusercontent.com/20649992/64475498-d078a800-d183-11e9-86fd-6059e1aa781a.png)
![p09](https://user-images.githubusercontent.com/20649992/64475515-f9993880-d183-11e9-9141-4f170019ab51.png)
![p10](https://user-images.githubusercontent.com/20649992/64475537-61e81a00-d184-11e9-812d-d1221ffd6102.png)

- Posters won't load, but if i edit the series there are a lot of poster options (same for seasons).
- Title always contains the "thetvdb id".
- Episode titles didn't failover to the next language. 
(HU-->EN, 1.episode, hu, title: , en, title: The Grid Car)

I'm using the latest Hama and ASS.

[Infinity Train.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3586644/Infinity.Train.agent-update.log)

**Comment by ZeroQI** [comment]
There is no series 'title' found which is a requirement for applying metadata to the series, explaining thebahaviour...
I managed to reproduce the issue:
- TheTVDB series title is using library language only...
- episode title have empty titles too...

**Comment by Kinsiinoo** [comment]
Thanks!

**Comment by ZeroQI** [comment]
that will fx the serie part.
still the ep overview and title broken to fix but can only do that tomorrow afternoon now

**Comment by ZeroQI** [comment]
Please test and close if resolved, should be normally.

**Comment by Kinsiinoo** [comment]
Works perfectly well now. Thank you! 😄
