### ISSUE TITLE
Series/Episode naming fails when including "de" as priority for german

### ISSUE THREAD

**Issue by Baine** [ZeroQI/Hama.bundle#347]
I've got the following as Series/Episode Language priority:
```de, en, main, jap```
testing series: https://anidb.net/anime/2854

with de inside that list, the series title ends up as  `Tokyo Juushouden` (main title)
without de, the title turns into `10 Tokyo Warriors` (official english title)

My intent is to use german names where possible, fall back to english, and only then use the main title where necessary.

if you need any additional logs, please let me know :)

Edit: just noticed that while it fails for this show, it works for many others...
for example this one is correctly named `Are you lost?`: https://anidb.net/anime/14710

**Comment by ZeroQI** [comment]
Using scudlee's 2 week old backup of AniDB's title xml: https://raw.githubusercontent.com/ScudLee/anime-lists/master/animetitles.xml
```
	<anime aid="2854">
		<title type="main" xml:lang="x-jat">Tokyo Juushouden</title>
		<title type="official" xml:lang="en">10 Tokyo Warriors</title>
		<title type="official" xml:lang="es">La Leyenda de los 10 Guerreros de Tokio: el origen</title>
		<title type="official" xml:lang="ja">倒凶十将伝</title>
		<title type="syn" xml:lang="ar">محاربو طوكيو العشرة</title>
		<title type="syn" xml:lang="en">10 Warriors of Tokyo</title>
		<title type="syn" xml:lang="en">Ten Tokyo Warriors</title>
	</anime>
```
There is an implied failover so it never reach english, needs to be fixed.
I need Hama agent data folder update logs for that series if you could.

**Comment by Baine** [comment]
should be available here, if that's the correct fole:
[](http://0x0.st/ztKp.log)

**Comment by ZeroQI** [comment]
TheTVDB
language_series : ['de', 'en', 'jap'] => should be 'ja' to be functional
[ ] language_rank: 0 > correct
[ ] title: Tokyo Juushouden > correct
[ ] original_title: Tokyo Juushouden

TheTVDB v1 http API: http://thetvdb.com/api/A27AD9BE0DA63333/series/{}/all/{}.xml
http://thetvdb.com/api/A27AD9BE0DA63333/series/129751/all/de.xml
`<SeriesName>Tokyo Juushouden</SeriesName>` is indeed the german title in thetvdb. 

AniDB
language_posters: ['de', 'en']
[ ] title: 10 Tokyo Warriors > correct
[ ] original_title: Tokyo Juushouden
[ ] language_rank: 1 > correct

```
	<anime aid="2854">
		<title type="main" xml:lang="x-jat">Tokyo Juushouden</title>
		<title type="official" xml:lang="en">10 Tokyo Warriors</title>
		<title type="official" xml:lang="es">La Leyenda de los 10 Guerreros de Tokio: el origen</title>
		<title type="official" xml:lang="ja">倒凶十将伝</title>
		<title type="syn" xml:lang="ar">محاربو طوكيو العشرة</title>
		<title type="syn" xml:lang="en">10 Warriors of Tokyo</title>
		<title type="syn" xml:lang="en">Ten Tokyo Warriors</title>
	</anime>
```

Sorry, but it is working as designed

**Comment by Baine** [comment]
hmm, alright then. thanks for checking it though :) I'll close this one.

**Comment by ZeroQI** [comment]
You can remove TheTVDB from the series titles source so you pull only from AniDB. For ep titles in foreign languages TheTVDB is better though...
