### ISSUE TITLE
Folder name with dots & multiple seasons

### ISSUE THREAD

**Issue by Sada-Mio** [ZeroQI/Hama.bundle#348]
Single season anime title using **dots** instead of **spaces** is able to match in Plex. 

However, if the folder contains multiple seasons (Season 01, Season 02 etc..) it is not able to match. Even Forced ID is ignored or not used. 

Kimi.ni.Todoke.From.Me.To.You (**matches**)
\--Season 01

Kimi.ni.Todoke.From.Me.To.You (**matches**)
--episode_files...

Kimi ni Todoke From Me To You (**matches using spaces**)
\--Season 01
\--Season 02

Kimi.ni.Todoke.From.Me.To.You (**Fails using dots**)
\--Season 01
\--Season 02

Kimi.ni.Todoke.From.Me.To.You.[anidb-6466] (**Fails using dots+ID**)
\--Season 01
\--Season 02

Kimi.ni.Todoke.From.Me.To.You (**Fails**)
\--Season 02

TheTVDB.Search() in agent-search.log has no data match when it fails with multiple seasons.

**Comment by ZeroQI** [comment]
Thanks, dunno how i never spotted it... Closing now
