### ISSUE TITLE
Error in log calling for 'TMDB' folder

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#35]
I've been having trouble getting the metadata loaded for 'Joker Game' and I've been looking through the logs.  The TVDB API seems to have the episode descriptions in it, but it's not making it into Plex.  

I also noticed that there was a line stating 'TMDB' directory did not exist.  Once I created it, it placed a poster for the show in it immediately.  

Hama Log:  
[hama log.zip](https://github.com/ZeroQI/Hama.bundle/files/238685/hama.log.zip)

**Comment by EndOfLine369** [comment]
All directories stated in the readme for installation are required for all data to be loaded correctly. As even if you state an anidb id, it will still pull/save tvdb info as well as other sources.

**Comment by sven-7** [comment]
It doesn't look like 'TMDB' is listed in the readme as one of the required folders to add. It's mentioned elsewhere, but not in the folder list.

**Comment by EndOfLine369** [comment]
Put in pull request #37 to get the Readme updated.
https://github.com/ZeroQI/Hama.bundle/pull/37/files

**Comment by sven-7** [comment]
Great. Closed #35.
