### ISSUE TITLE
HAMA loading images from thumbnail urls

### ISSUE THREAD

**Issue by EndOfLine369** [ZeroQI/Hama.bundle#350]
@ZeroQI, just noticed something from looking at this...
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/common.py#L437
Why is HAMA downloading the thumbnails?

Big difference.
EX:
https://cdn.anidb.net/images/150/226372.jpg-thumb.jpg
https://cdn.anidb.net/images/main/226372.jpg
Wondered why some times the poster would look fuzzy or details were not as defined as I would see on the site.

_Originally posted by @EndOfLine369 in https://github.com/ZeroQI/Hama.bundle/issues/194#issuecomment-538603866_

**Comment by ZeroQI** [comment]
` file = (ssl_open((url_thumbnail or url).replace('thetvdb.com', 'thetvdb.plexapp.com')) if 'thetvdb.com' in url else False) or ssl_open(url_thumbnail or url)
`
Was following framework recommendation for thumbnail present:
https://us.v-cdn.net/6025034/uploads/editor/d8/o4v3wv0k7oe5.pdf page 45
metadata.posters[full_poster_url] = Proxy.Preview(poster_thumbnail_data)

Now yes we can load the full file but that may make the database bigger...
Might improve AniDB behavior...

**Comment by EndOfLine369** [comment]
Hmmm.....
So if I read that right, Plex itself will supposedly pull down the the full image url data into the db when we go into view the actual series/season. Or when we change a poster to a different available poster.

I guess that makes sense. Assuming that is how Plex still works from that 2011 doc which seems to be the case when I look at the setup in Plex's included "TheTVDB.bundle".

If a series had 10 possible posters, space wise we would only want to load the highest numbered poster full image unless we decide to change the poster and then it would load the other poster's full image only at that time.

**Comment by sven-7** [comment]
What about an option to opt-in to downloading all full sized images?  Unless AniDB and TheTVDB have some policy against it, that might be viable.  Especially if the end user doesn't care about the size of the database?

**Comment by ZeroQI** [comment]
Plex display the thumbnail for selection when changing it, then download the full size poster if selected. This is as designed. This does not translate into low resolution for selected posters unless there is a bug
```
      if filename and Data.Exists(filename):  status += ", Found locally"; file = Data.Load(filename)
      else:
        file = ssl_open( (url_thumbnail or url).replace('thetvdb.com', 'thetvdb.plexapp.com') if 'thetvdb.com' in url else url_thumbnail or url) #simplified code
        if file:  status += ", Downloaded and Saved locally";  SaveFile(filename, file)
      if file:  metatype[ url ] = Proxy.Preview(file, sort_order=num) if url_thumbnail else Proxy.Media(file, sort_order=num)
```
If you poster is blurry and an highter resolution exist on AniDB, then please attach logs so i can ensure the right link is given.
- Please check in agent data folders the picture to check it looks shit as well
- AniDB has shite low res posters at times, which is why i favoured higher fixed resolution TheTVDB posters. If this is the case, update AniDB with better resolution poster, pretty sure your issue is here...
- might be a low res resizing issue from Plex, but unlikely

**Comment by EndOfLine369** [comment]
I think i'm seeing the fuzziness now with the new series for this season so only AniDB posters for now. Seems like its just the bad image quality. Size is fine but looks like it itself is a bad upscale.... =S
Suspect that is why I don't see if for long as all it takes is for the TVDB to get some decent images and override AniDB poster.

**Comment by EndOfLine369** [comment]
So the only question I think that is still out there is do we want to bypass this thumbnail load for AniDB posters even if they are not the high priority? This would be done to prevent additional hits to their site out of HAMA's control for image loads.

Which would be to remove the `ANIDB_PIC_THUMB_URL.format(GetXml(xml, 'picture').split('.')[0])`
at these lines:
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/AniDB.py#L184
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/AniDB.py#L286

**Comment by ZeroQI** [comment]
It spares a load if AniDB is the poster used, due to that I think we could comment the lines in question. Could limit banning for big library scans so let's go for it

**Comment by ZeroQI** [comment]
Excellent, thanks @EndOfLine369
