### ISSUE TITLE
No more plugins in Plex version 1.18.0.1913?

### ISSUE THREAD

**Issue by Caf** [ZeroQI/Hama.bundle#353]
I'm reinstalling a new Mac Mini from scratch, with a new Plex, and it seems I can't reinstall HAMA... I did it before, I know what I do but it just don't show up in the Plex UI... I just wanted to know if it's me or not, or did I miss a workaround? I do have the same problem with SubZero but I can't install Kitana (yet)...

If they killed that kind of plugin, that's a sad day... :/ (and thanks for your work anyway :) )

**Comment by ZeroQI** [comment]
logs missing

**Comment by Caf** [comment]
Yes, but sadly and to my surprise, the folder is not even created anymore (in Application Support or in the package content). I'll keep digging this week-end but I have the feeling that latest version does something weird... I just have an update-log.txt in AppSupport, nothing in Diagnostics, etc.

**Comment by EndOfLine369** [comment]
I just upgraded to this version yesterday on windows & unix. No issue seen in recognizing HAMA. Please make sure your installation is correct.

**Comment by sven-7** [comment]
I'm on Windows 1.18.0.1944 and working fine.

**Comment by fawzib** [comment]
still works fine. this plugin is gold for anime collections

**Comment by ZeroQI** [comment]
Not a global issue since users using same [1.18.0.1913] or more recent [1.18.0.1944] don't have issues
Closing

**Comment by Caf** [comment]
Did you try installing from scratch on it? I can't test further anyway because, just for fun I guess, my NAS decided to act up this week-end... Waiting for new hard drives. :x
