### ISSUE TITLE
Cant seem to find this

### ISSUE THREAD

**Issue by fawzib** [ZeroQI/Hama.bundle#355]
I tried every combination and searching this wont give any result

`Fate/Kaleid Liner Prisma Illya Zwei!`
also tried:
`2wei!`

should find:
`https://anidb.net/anime/10091`

I verified that this title exist in the animetitles.xml file.

**Comment by ZeroQI** [comment]
Logs, you know the things i list in the README to gather in the troubleshooting section...
I need more specifically the *.search.log for your series, located in agent data folder:
- [...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/(Library_name/)series_root_folder.agent-search.log (guid assignment)

**Comment by fawzib** [comment]
`=============================================================================================================================================================
common.PlexLog(file="C:\Users\alien\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime\Fate.agent-search.log", movie=False)
[!] file:       "S:\Media Cloud\Anime\Fate\Fate Kaleid Liner Prisma Illya\Fate kaleid liner Prisma Illya 2wei! [TV][S2]\Fate.Kaleid.Liner.Prisma.Illya.S02E10.1080p-Hi10P.BluRay.FLAC2.0.x264-SOLA.[5739DB2C].mkv"
[ ] library:    "Anime"
[ ] root:       "S:\Media Cloud\Anime"
[ ] path:       "Fate\Fate Kaleid Liner Prisma Illya\Fate kaleid liner Prisma Illya 2wei! [TV][S2]"
[ ] Plex root:  "C:\Users\alien\AppData\Local\Plex Media Server"
[ ] Log folder: "Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime"
[ ] Log file:   "Fate.agent-search.log"
[ ] Logger:     "0x26b8"
[ ] mode:       "w"
=== Search() ================================================================================================================================================
title: 'Prisma Illya Zwei!', name: 'None', filename: 'None', manual: 'True', year: 'None'
start: 2019-10-13 18:39:48,343000
=============================================================================================================================================================
--- force id ------------------------------------------------------------------------------------------------------------------------------------------------
--- source searches -----------------------------------------------------------------------------------------------------------------------------------------
=== TheTVDB.Search() ========================================================================================================================================
=============================================================================================================================================================
end: 2019-10-13 18:39:48,604000
`

**Comment by ZeroQI** [comment]
This is neither a normal folder neither a grouping folder: \Fate\Fate Kaleid Liner Prisma Illya\Fate kaleid liner Prisma Illya 2wei! [TV][S2]...

The agent considers you have multiple seasons and call TheTVDB as it should for multiple seasons which can't find the japanese title then..**.Working exactly as designed.**

Use forced ids, but if anything goes wrong it is unsupported as instead to use series folder  in root folder or in a grouping folder you used 1 further depth without using season folder...

Alternatively use the below to use anidb match and be supported
- Fate/Fate kaleid liner Prisma Illya 2wei!
- Fate/[03] Fate kaleid liner Prisma Illya 2wei!
-  Fate\Fate kaleid liner Prisma Illya 2wei! [TV][S2] [anidb-10091]...
