### ISSUE TITLE
Failing to match with (year) in the title 

### ISSUE THREAD

**Issue by hacktoberman** [ZeroQI/Hama.bundle#359]
I renamed my anime to have (year) in the title of the folder per plex recommendation for naming, and now half of my anime fails to match. Here is an example folder name "The Asterisk War - The Academy City on the Water (2015)" and an episode "Season 01/The Asterisk War - The Academy City on the Water (2015) - S01E01 - Witch of the Resplendent Flames [HDTV-1080p].mkv". To be clear, it isn't some sort of issue with the extra - being from asterisk wars naming. "Is it Wrong to Try to Pick Up Girls in a Dungeon! (2015)" and many others have the same issue.

The following image shows the defaulted search options and the matches it can see. It can't find any match with a (year). However, if I simply remove the (year), it immediately finds the series with a 100 rating. https://imgur.com/a/fAAEcRn

Before I renamed to include (year), hama would correctly identify everything, now it is failing on at least half of my library... But plex standard says that including (year) in the folder and episode can be used whenever, and should be used when there are multiple series w/ the same name. 

https://support.plex.tv/articles/naming-and-organizing-your-tv-show-files/

**Comment by ZeroQI** [comment]
These recommendations are based on default metadata agents, especially Themoviedb which will use the year properly for movie libraries.

You have to use one of AniDB titles for single season anime or TheTVDB for multi season anime with my agent. I worked hard to increase the recognition rate for people following AniDB or tvdb titles and supporting both movies and series in series li ready.

Sadly no medatada agent for anime request the year to be added
It is the right thing to do for non-animated movies in movie ok rarys with TheMovieDb ag nt only sadly...

Working as designed.

**Comment by ZeroQI** [comment]
For shows with the same or similar names (e.g. remakes, US vs UK versions, etc.), include the year alongside the series title in folder and file names, e.g. “Doctor Who (1963)” and “Doctor Who (2005)”.

Simply put if the title include the year in TheTVDB in the title.use it... It didn't say to use the year on every title....

**Comment by hacktoberman** [comment]
Sure it doesn't say to use it everywhere, but it says that you can use it. And sonarr has a naming scheme that you set up, so I set it to include (year) so that those cases would be covered...  This does work with non-anime. Would be it possible then with hama to just ignore the (year) in a title for matching purposes then if it doesn't find anything with it?

**Comment by ZeroQI** [comment]
I need search logs as it should find something albeit at lower than 80%
match leaving the series unmatched...

**Comment by EndOfLine369** [comment]
@hacktoberman, HAMA cannot ignore the year in a series title. There are many anime series that have the year incorporated into the official title. EX "Boku no Hero Academia (2019)". If HAMA tried to remove that "(2019)" from the title, it would go from 1 match to 10.
