### ISSUE TITLE
TheTVDB Language Error

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#360]
@ZeroQI -- have you seen this before from TheTVDB?  Initially spotted this for the latest episode of Psycho-Pass (S03E01) and has English title and summaries for the episode already. Noticed it for a few others as well. The rest of the series comes back fine, but for some reason this one isn't. I'm getting this back on several episodes -- not sure if TheTVDB has changed something in their API?

`"errors":{"invalidLanguage":"Some translations were not available in the specified language"}}`

Here is the JSON for the latest My Hero Academia episode:

`{"data":{"id":7381252,"airedSeason":4,"airedSeasonID":814583,"airedEpisodeNumber":3,"episodeName":"Boy Meets...","firstAired":"2019-10-26","guestStars":[],"director":"||","directors":[],"writers":[],"overview":null,"language":{"episodeName":"en","overview":"en"},"productionCode":"","showUrl":"","lastUpdated":1571593321,"dvdDiscid":"","dvdSeason":0,"dvdEpisodeNumber":0,"dvdChapter":null,"absoluteNumber":66,"filename":"episodes/305074/7381252.jpg","seriesId":305074,"lastUpdatedBy":519809,"airsAfterSeason":null,"airsBeforeSeason":null,"airsBeforeEpisode":null,"thumbAuthor":458736,"thumbAdded":"2019-10-19 03:40:33","thumbWidth":"400","thumbHeight":"225","imdbId":"tt11075840","siteRating":0,"siteRatingCount":0},"errors":{"invalidLanguage":"Some translations were not available in the specified language"}}`

**Comment by ZeroQI** [comment]
Multiple languages are loaded per episode, one of them is impacted
Seem like some titles are missing in English? TheTVDB need updating then?

**Comment by sven-7** [comment]
There are English titles and summaries in both of them. Super bizarre. Is it doing that for you as well? It seems to be all recent episodes for TheTVDB I’ve added.

**Comment by ZeroQI** [comment]
Overview is null. Need to be updated and check logs again

**Comment by sven-7** [comment]
I can confirm this is resolved. It must have been an API issue on TheTVDB's side.  Thanks for the support, as always!
