### ISSUE TITLE
In TVDB4 mode how to ignore absolute number from tvdb db and use number in file name instead

### ISSUE THREAD

**Issue by StudioEtrange** [ZeroQI/Hama.bundle#366]
Hello

**ABSTRACT**

In **tvdb4 mode**, how can I ignore episode absolute number from tvdb and i use instead the episode absolute number (from file name)

**CONTEXT**

I have problem trying to get metadata for Hunter X Hunter (2011)
https://www.thetvdb.com/series/hunter-x-hunter-2011/seasons/all
https://anidb.net/anime/8550

**TREE FOLDERS**

```
ANIMATION/Hunter X Hunter/Hunter X Hunter (2011) [tvdb4-252322]/Hunter x hunter 001.mkv
                                                                ....
                                                                Hunter x hunter 148.mkv
```

**SOURCE FILES**

[tvd4.mapping.xml](https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/tvdb4.mapping.xml) seems to be ok

```
 <anime tvdbid="252322" name="Hunter x Hunter (2011)">
    01|001|021|Hunter Exam Arc
    02|022|026|Zoldyck Family Arc
    03|027|036|Heavens Arena Arc
    04|037|058|Yorknew City Arc
    05|059|075|Greed Island Arc
    06|076|136|Chimera Ant Arc
    07|137|148|13th Hunter Chairman Arc
  </anime>
```

[Scudlee file](https://raw.githubusercontent.com/ScudLee/anime-lists/master/anime-list-full.xml) content about Hunter x Hunter

```
<anime anidbid="8550" tvdbid="252322" defaulttvdbseason="a">
    <name>Hunter x Hunter (2011)</name>
</anime>
```

**PROBLEMS**

Some absolute number in tvdb are wrong or missing.

for example
* **E27** (absolute number) _should match_ [**S01E27**](https://www.thetvdb.com/series/hunter-x-hunter-2011/episodes/4298326) from tvdb db and **should appear** as S03E27 in plex cause of tvdb4 ==> **It is OK** because in tvdb db S01E27 _have_ 27 as absolute number

* **E22** (absolute number) _should match_ [**S01E22**](https://www.thetvdb.com/series/hunter-x-hunter-2011/episodes/4229910) from tvdb db and **should appear** as S02E22 in plex cause of tvdb4 ==> **It is KO** because in tvdb db S01E22 _have_ 80 instead of 22 as absolute number which is wrong for me! In plex it show up as S02E22 BUT with title and abstract from tvdb **S02E22** _(because 80th episode is S02E22 !)_

Log with absolute number 80 instead of 22 :
```
'22': {'absolute_index': 80, 'content_rating': 'TV-14', 'directors': [u'\u5c71\u57ce\u667a\u6075'], 'duration': 1500000, 'language_rank': 0, 'originally_available_at': '2013-05-19', 'rating': 8.5, 'summary': 'Pokkuru et Ponzu utilisent les abeilles de Ponzu pour envoyer des messages et demander Ã  l\'Association des Hunters de les aider Ã  Ã©liminer les fourmis-chimÃ¨res.', 'thumbs': {'https://thetvdb.plexapp.com/banners/episodes/252322/4567216.jpg': ('TheTVDB/episodes/4567216.jpg', 1, None), 'https://thetvdb.plexapp.com/banners/episodes/252322/4229910.jpg': ('TheTVDB/episodes/4229910.jpg', 1, None)}, 'title': 'Aveu et DÃ©sastre !', 'writers': [u'\u4e0a\u4ee3\u52d9']},
```
[Link to the full log](https://uptobox.com/5rrq0v4vzwja)

**QUESTION MARK**
_As i have some problem with some other show with **missing** or **wrong** numbers, how can i completely ignore absolute number recorded in tvdb ? And use file number from file name ?_

for example, i want in **tvdb4** that `Hunter x hunter 022.mkv` match absolute number **22** and **not 80** from tvdb db.

**Comment by ZeroQI** [comment]
Issue is exactly tvdb s2e22-s2e26 which should point to tvdb4 s06e080-84 after mapping which seem to failsafe to itself s2e22-s2e26, overriding metadata... 
```
[X]   s2e21 s06e079 anidbid:         air_date: 2013-05-12 abs_number: 79, title: No Good N.G.L
 - [1] title:   [fr] No Good N.G.L
 - [1] summary: [fr] Après un contrôle draconien, Gon est ses nouveaux amis entrent dans NGL. Ils pensent que la fourmi-chimère s'y trouve. Mais ils ne sont pas les seuls !
common.LoadFile() - File cached locally - url: 'https://api.thetvdb.com/episodes/4562021', Filename: 'TheTVDB/json/252322/episode_4562021_en.json', Age: '6869.82996273', Ended: None
 - [ ] thumb: https://thetvdb.plexapp.com/banners/episodes/252322/4562021.jpg
[X]   s2e22 s02e022 anidbid:         air_date: 2013-05-19 abs_number: 80, title: Aveu et Désastre !
 - [1] title:   [fr] Aveu et Désastre !
 - [1] summary: [fr] Pokkuru et Ponzu utilisent les abeilles de Ponzu pour envoyer des messages et demander à l'Association des Hunters de les aider à éliminer les fourmis-chimères.
common.LoadFile() - File cached locally - url: 'https://api.thetvdb.com/episodes/4567216', Filename: 'TheTVDB/json/252322/episode_4567216_en.json', Age: '6869.64660668', Ended: None
 - [ ] thumb: https://thetvdb.plexapp.com/banners/episodes/252322/4567216.jpg
[X]   s2e23 s02e023 anidbid:         air_date: 2013-05-26 abs_number: 81, title: Début des combats
 - [1] title:   [fr] Début des combats
 - [1] summary: [fr] Gon, Kirua et Kaito découvrent les ruines d'un village détruit. Ils y font leur première rencontre avec une fourmi-chimère.
common.LoadFile() - File cached locally - url: 'https://api.thetvdb.com/episodes/4574974', Filename: 'TheTVDB/json/252322/episode_4574974_en.json', Age: '6869.46720767', Ended: None
 - [ ] thumb: https://thetvdb.plexapp.com/banners/episodes/252322/4574974.jpg
[X]   s2e24 s02e024 anidbid:         air_date: 2013-06-02 abs_number: 82, title: La roulette de Kaito !
 - [1] title:   [fr] La roulette de Kaito !
 - [1] summary: [fr] Les fourmis-chimères les plus agressives ont mangé les méchants qui géraient le NGL et sont encore plus redoutables.
common.LoadFile() - File cached locally - url: 'https://api.thetvdb.com/episodes/4579034', Filename: 'TheTVDB/json/252322/episode_4579034_en.json', Age: '6869.27579761', Ended: None
 - [ ] thumb: https://thetvdb.plexapp.com/banners/episodes/252322/4579034.jpg
[X]   s2e25 s02e025 anidbid:         air_date: 2013-06-09 abs_number: 83, title: Évolution par influence
 - [1] title:   [fr] Évolution par influence
 - [1] summary: [fr] L'Association des Hunters a envoyé une force pour exterminer les fourmis-chimères. Pendant ce temps, Gon et ses amis sont la cible des insectes.
common.LoadFile() - File cached locally - url: 'https://api.thetvdb.com/episodes/4579035', Filename: 'TheTVDB/json/252322/episode_4579035_en.json', Age: '6869.08439946', Ended: None
 - [ ] thumb: https://thetvdb.plexapp.com/banners/episodes/252322/4579035.jpg
[X]   s2e26 s02e026 anidbid:         air_date: 2013-06-16 abs_number: 84, title: Éveil du destin !
 - [1] title:   [fr] Éveil du destin !
 - [1] summary: [fr] Hagya envoie ses soldats jusqu'à Gon, Kirua et Kaito afin de capturer des spécimens humains. Gon et ses amis essaient de parer les attaques des fourmis-chimères.
common.LoadFile() - File cached locally - url: 'https://api.thetvdb.com/episodes/4589443', Filename: 'TheTVDB/json/252322/episode_4589443_en.json', Age: '6868.90500164', Ended: None
 - [ ] thumb: https://thetvdb.plexapp.com/banners/episodes/252322/4589443.jpg
[X]   s2e27 s06e085 anidbid:         air_date: 2013-06-23 abs_number: 85, title: Ombre et lumière !
 - [1] title:   [fr] Ombre et lumière !
 - [1] summary: [fr] Kaito, Gon et Kirua suivent Hagya. Ils sont à la recherche du nid de fourmis-chimères où la reine les attend.
common.LoadFile() - File cached locally - url: 'https://api.thetvdb.com/episodes/4593944', Filename: 'TheTVDB/json/252322/episode_4593944_en.json', Age: '6868.70561361', Ended: None
 - [ ] thumb: https://thetvdb.plexapp.com/banners/episodes/252322/4593944.jpg
```

**Comment by StudioEtrange** [comment]
Oh ok !
What should i do ?

**Comment by ZeroQI** [comment]
It is recognised as a bug, so we need to fix it
- we know what is wrong data wise for s02e22-26 
- we need to find the code responsible [TheTVDBv2 lines 141-148]
- issue is s02e22-26 exist on disk so not translated while it should so the test `if season not in media.seasons or episode not in media.seasons[season].episodes:` needs to be written again to let pass tvdb4 by adding "or xxxx " (to be determined, prob a list combrehension)

TheTVDBv2 lines 141-148
```
      elif metadata_source=='tvdb4':  
        ms, usl                         = Dict(mappingList, 'absolute_map', 'max_season'), Dict(mappingList, 'absolute_map', 'unknown_series_length')
        if ms and usl:  season, episode = Dict(mappingList, 'absolute_map', str(abs_number), default=(ms if usl else str(int(ms)+1), None))[0], str(abs_number)
        if season not in media.seasons or episode not in media.seasons[season].episodes:  #tvdb4 with custom season folder mapping
          for s in media.seasons:
            if str(abs_number) in media.seasons[s].episodes:  #if str(abs_number) in list_abs_eps
              season, episode = s, str(abs_number)
              break  
```
absolute_map:
`absolute_map: {'1': ('1', '1'), '2': ('1', '2'), '3': ('1', '3'), '4': ('1', '4'), '5': ('1', '5'), '6': ('1', '6'), '7': ('1', '7'), '8': ('1', '8'), '9': ('1', '9'), '10': ('1', '10'), '11': ('1', '11'), '12': ('1', '12'), '13': ('1', '13'), '14': ('1', '14'), '15': ('1', '15'), '16': ('1', '16'), '17': ('1', '17'), '18': ('1', '18'), '19': ('1', '19'), '20': ('1', '20'), '21': ('1', '21'), '22': ('2', '22'), '23': ('2', '23'), '24': ('2', '24'), '25': ('2', '25'), '26': ('2', '26'), '27': ('3', '27'), '28': ('3', '28'), '29': ('3', '29'), '30': ('3', '30'), '31': ('3', '31'), '32': ('3', '32'), '33': ('3', '33'), '34': ('3', '34'), '35': ('3', '35'), '36': ('3', '36'), '37': ('4', '37'), '38': ('4', '38'), '39': ('4', '39'), '40': ('4', '40'), '41': ('4', '41'), '42': ('4', '42'), '43': ('4', '43'), '44': ('4', '44'), '45': ('4', '45'), '46': ('4', '46'), '47': ('4', '47'), '48': ('4', '48'), '49': ('4', '49'), '50': ('4', '50'), '51': ('4', '51'), '52': ('4', '52'), '53': ('4', '53'), '54': ('4', '54'), '55': ('4', '55'), '56': ('4', '56'), '57': ('4', '57'), '58': ('4', '58'), '59': ('5', '59'), '60': ('5', '60'), '61': ('5', '61'), '62': ('5', '62'), '63': ('5', '63'), '64': ('5', '64'), '65': ('5', '65'), '66': ('5', '66'), '67': ('5', '67'), '68': ('5', '68'), '69': ('5', '69'), '70': ('5', '70'), '71': ('5', '71'), '72': ('5', '72'), '73': ('5', '73'), '74': ('5', '74'), '75': ('5', '75'), '76': ('6', '76'), '77': ('6', '77'), '78': ('6', '78'), '79': ('6', '79'), '80': ('6', '80'), '81': ('6', '81'), '82': ('6', '82'), '83': ('6', '83'), '84': ('6', '84'), '85': ('6', '85'), '86': ('6', '86'), '87': ('6', '87'), '88': ('6', '88'), '89': ('6', '89'), '90': ('6', '90'), '91': ('6', '91'), '92': ('6', '92'), '93': ('6', '93'), '94': ('6', '94'), '95': ('6', '95'), '96': ('6', '96'), '97': ('6', '97'), '98': ('6', '98'), '99': ('6', '99'), '100': ('6', '100'), '101': ('6', '101'), '102': ('6', '102'), '103': ('6', '103'), '104': ('6', '104'), '105': ('6', '105'), '106': ('6', '106'), '107': ('6', '107'), '108': ('6', '108'), '109': ('6', '109'), '110': ('6', '110'), '111': ('6', '111'), '112': ('6', '112'), '113': ('6', '113'), '114': ('6', '114'), '115': ('6', '115'), '116': ('6', '116'), '117': ('6', '117'), '118': ('6', '118'), '119': ('6', '119'), '120': ('6', '120'), '121': ('6', '121'), '122': ('6', '122'), '123': ('6', '123'), '124': ('6', '124'), '125': ('6', '125'), '126': ('6', '126'), '127': ('6', '127'), '128': ('6', '128'), '129': ('6', '129'), '130': ('6', '130'), '131': ('6', '131'), '132': ('6', '132'), '133': ('6', '133'), '134': ('6', '134'), '135': ('6', '135'), '136': ('6', '136'), '137': ('7', '137'), '138': ('7', '138'), '139': ('7', '139'), '140': ('7', '140'), '141': ('7', '141'), '142': ('7', '142'), '143': ('7', '143'), '144': ('7', '144'), '145': ('7', '145'), '146': ('7', '146'), '147': ('7', '147'), '148': ('7', '148'), 'max_season': '7', 'unknown_series_length': False}`

**Comment by ZeroQI** [comment]
I coded a simpler code to fix in TheTVDBv2.py, as tvdb3 and 4 are following tvdb absolute numbering, and there is no ep number duplicatees so i can simplify the code greatly from
```
      ### ep translation
      anidbid=""
      abs_number = Dict(episode_json, 'absoluteNumber', default=0 if season=='0' else abs_number+1)
      if anidb_numbering:
        if Dict(mappingList, 'defaulttvdbseason_a'):  season, episode          = '1', str(abs_number)
        else:                                         season, episode, anidbid = anidb_ep(mappingList, season, episode)
      elif metadata_source=='tvdb3':  
        episode             = str(abs_number)
      elif metadata_source=='tvdb4':  
        ms, usl                         = Dict(mappingList, 'absolute_map', 'max_season'), Dict(mappingList, 'absolute_map', 'unknown_series_length')
        if ms and usl:  season, episode = Dict(mappingList, 'absolute_map', str(abs_number), default=(ms if usl else str(int(ms)+1), None))[0], str(abs_number)
        if season not in media.seasons or episode not in media.seasons[season].episodes:  #tvdb4 with custom season folder mapping
          for s in media.seasons:
            if str(abs_number) in media.seasons[s].episodes:  #if str(abs_number) in list_abs_eps
              season, episode = s, str(abs_number)
              break      
      elif metadata_source=='tvdb5':  
        episode, abs_number = str(Dict(episode_json, 'absoluteNumber') or abs_number), int(Dict(episode_json, 'absoluteNumber') or abs_number)
```
to:
```
      ### ep translation [Thetvdb absolute numbering followed, including in specials to stay accurate with scudlee's mapping]
      anidbid=""
      abs_number = Dict(episode_json, 'absoluteNumber', default=0 if season=='0' else abs_number+1)
      if anidb_numbering:
        if Dict(mappingList, 'defaulttvdbseason_a'):  season, episode          = '1', str(abs_number)
        else:                                         season, episode, anidbid = anidb_ep(mappingList, season, episode)
      elif metadata_source in ('tvdb3', 'tvdb4'):  
        if str(abs_number) in list_abs_eps:  #if abs id exists on disk, leave specials with no translation
          for s in media.seasons:
            if str(abs_number) in media.seasons[s].episodes:
              season, episode = s, str(abs_number)
              break
          else:  continue
      elif metadata_source=='tvdb5':  
        episode = str(abs_number)
```

**Comment by ZeroQI** [comment]
Closing as should be resolved and submitter was not interested in trying the fix in 11 days
Please reply if this isn't fixed

**Comment by StudioEtrange** [comment]
I was interrested in testing! 
But with just the code you post eleven days ago, i did not know how to test this!


I qa

**Comment by StudioEtrange** [comment]
Now I updated Hama with UAS, so your 5hours ago commit is included,
and it solved the issue I exposed.

If you need I test something, say it, for some people like me it could be not obvious or we dont always know how to test.

Thank you for the fix!

**Comment by ZeroQI** [comment]
Apologies
I don't use the agent for myself anymore so I expect users to test code. I
am glad it solve your issue. I did include the file and source code to
replace and new code in my post...

Merci pour ce retour cher compatriote et jeune padawan :p
