### ISSUE TITLE
Invalid response is being saved

### ISSUE THREAD

**Issue by EndOfLine369** [ZeroQI/Hama.bundle#367]
Hey @ZeroQI,
`common.SaveFile()` should not be saving this.
EX:
```
common.LoadFile() - File cached locally - url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=8235', Filename: 'AniDB/xml/8235.xml', Age: '19626425.7714', Ended: None
common.SaveFile() - CachePath: '/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems', file: 'AniDB/xml/8235.xml'
ERROR: Invalid str returned: "<error code="500">banned</error>"
```
Also, I find it annoying to have to clear the plex cache as well when this is hit.
If we query a url with cache time X, but then query it with time Y (where Y<X), would it lower the cache time? Or once the cache time is set on a url, it's hard set till it expires?
If we could recall it and lower it, we could possible re-query the url on a ban hit to lower it to ~24hrs. So the plex cache will handle itself. So an initial 6day Plex cache would go down to a 1day cache.

Looks like we should add an additional `file_downloaded.startswith("<error")` test in the `if file_downloaded` section before the SaveFile call?
```
EX Responses:
<error code="500">banned</error>
<error>Anime not found</error>
<error>aid Missing or Invalid</error>
```

**Comment by sven-7** [comment]
I'd definitely be a fan of lowering the cache time (I still get banned from AniDB if I full library refresh...alas...). I think that makes sense to change it.

**Comment by ZeroQI** [comment]
Plex cache is set to a day
Local HAMA cache is dynamic now, long for completed series and should not be shortened, sort for series in progress and can be set to a day. I

This page should not be cached, I agree for the fix

**Comment by EndOfLine369** [comment]
Added the test for AniDB error response.

Hmmm.....looks like the cache age change is never actually being applied (variable 'Ended' <> 'ended') and is a good thing. Looks like for AniDB (haven't looked at TVDB) there is an assumption that if an enddate is set, it will actually be done which is not the case (EX below). It just means they know when it will end.

If this feature is truly wanted to be implemented, it should be taking the end date, add time to it (to allow for post series meta wrapup), and only if that date is <now should it extend it. I would also only extend it to 1yr cache if the series has been done for a while. Meta will evolve for a series over time especially if it is part of a long running series and series can easily have 1-2 years between seasons.

Would think:
* ended > 2 years ago = 1 year cache
* ended > 1 year ago = 3 month cache
* ended > 6 months ago = 1 month cache
* else = standard cache

```xml
<?xml version="1.0" encoding="UTF-8"?><anime id="13844" restricted="false">
<type>TV Series</type>
<episodecount>12</episodecount>
<startdate>2019-10-07</startdate>
<enddate>2019-12-23</enddate>
...
```

**Comment by ZeroQI** [comment]
@EndOfLine369 Excellent breakdown. Most of a library is old series, at least for some, so I would like to take the strain out. I think this dynamic cache is the way to go.
