### ISSUE TITLE
TheTVDB - Authorization Error: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)

### ISSUE THREAD

**Issue by clowncracker** [ZeroQI/Hama.bundle#368]
I keep getting this error, which is preventing any metadata from being loaded.

[_root_.agent.log](https://github.com/ZeroQI/Hama.bundle/files/3849210/_root_.agent.log)
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3849214/com.plexapp.agents.hama.log)

**Comment by avluis** [comment]
Just a quick FYI: TheTVDB website was having a few issues yesterday and was down that evening.
This may not be your issue but your logs indicate that the agent was attempting to retrieve metadata around that time.

**Comment by EndOfLine369** [comment]
HAMA uses Plex's `HTTP.Request()` for this call. It uses this call for everything except image pulls. So its something internal in Plex that is not good at handling whatever they have done to their service. HAMA has no control over the protocol.

**Comment by EndOfLine369** [comment]
Plex has the TVDB agent automatically included in their installs, so I would not doubt that one of the upcoming beta releases will fix this. Until then, sounds like TVDB data will not be available.

**Comment by DJScias** [comment]
It seems this talks about the issue as well: https://forums.thetvdb.com/viewtopic.php?f=17&t=60223&sid=9cc29d2b0b8ae2275d673d3c36aa7980

In case you want to read it here:

> Some client systems including ours (TV Time) and Plex were getting SSL handshake issues when trying to access the v2 API. We found that this was caused by a number of things including older clients only supporting SSL 3.0 instead of TLS. We've set the API so it will work for SSL 3.0 now, but those clients should consider supporting TLS as SSL 3.0 support will be removed in the next version of our API.
>
> Additionally, Plex found the handshake issue to be caused by the urllib2 and httplib libraries they were using. They are carefully fixing this and deploying for their users, but other developers should be aware that older libraries could be causing this issue.
>
> Finally, TV Time was getting this due to the Java version our older importer was using. We fixed this internally by building the job with Java 8.
>
> If your app or system is having SSL handshake issues, please debug the SSL connection and look into these resolutions. If you're able to solve with a different library, please post your fix here so other developers can benefit as well

**Comment by EndOfLine369** [comment]
heh......hehehehe.........mwa..........mwahahahhahahaHAHAHAHAHAHAHAHAHAHAHAHA!!!!!!!!!!!!!!!

**Comment by EndOfLine369** [comment]
Found a bug in Plex's code found with TVDB's SNI setup and provided them the fix. They are testing.

**Comment by theroninhunter** [comment]
So do we just wait for Plex to update their libraries?

**Comment by DJScias** [comment]
https://forums.plex.tv/t/thetvdb-metadata-v3-api-and-related-issues/491771/153?u=djscias

Apparently they've done the necessary changes.. So I went and got myself the latest beta release (which is also the normal release, due to its importance) **1.18.2.2058** and it seems after refreshing my metadata the handshake errors are gone.

I might be the only one though, so perhaps if others can check and see if the logs no longer shows them then we can probably conclude it's fixed.. For now.

**Comment by ZeroQI** [comment]
Thanks for the information. this should impact linux users mainly. what was your OS for information?

**Comment by DJScias** [comment]
I'm running a Synology DS918+ NAS for Plex, so basically Linux.

**Comment by EndOfLine369** [comment]
Upgraded to their new release.
Looks like actually just took out the bugged file all together 😄 as was a workaround file and went back to the standard python libraries.
