### ISSUE TITLE
Cache age change is not being applied

### ISSUE THREAD

**Issue by EndOfLine369** [ZeroQI/Hama.bundle#369]
Hmmm.....looks like the cache age change is never actually being applied (variable 'Ended' <> 'ended') and is a good thing. Looks like for AniDB (haven't looked at TVDB) there is an assumption that if an enddate is set, it will actually be done which is not the case (EX below). It just means they know when it will end.

If this feature is truly wanted to be implemented, it should be taking the end date, add time to it (to allow for post series meta wrapup), and only if that date is <now should it extend it. I would also only extend it to 1yr cache if the series has been done for a while. Meta will evolve for a series over time especially if it is part of a long running series and series can easily have 1-2 years between seasons.

Would think:
* ended > 2 years ago = 1 year cache
* ended > 1 year ago = 3 month cache
* ended > 6 months ago = 1 month cache
* else = standard cache

```xml
<?xml version="1.0" encoding="UTF-8"?><anime id="13844" restricted="false">
<type>TV Series</type>
<episodecount>12</episodecount>
<startdate>2019-10-07</startdate>
<enddate>2019-12-23</enddate>
...
```

_Originally posted by @EndOfLine369 in https://github.com/ZeroQI/Hama.bundle/issues/367#issuecomment-554741010_

**Comment by ZeroQI** [comment]
@EndOfLine369 Excellent breakdown. Most of a library is old series, at least for some, so I would like to take the strain out. I think this dynamic cache is the way to go.

**Comment by sven-7** [comment]
How would this affect the Plex option to “refresh all metadata”? Does that override this? I’m fully okay with that — it might help prevent the AniDB bans when doing that.

**Comment by ZeroQI** [comment]
I just pull new data according to how long ago the series/movies aired
That's the plan, having recent meta where it needs and delay the rest...

**Comment by sven-7** [comment]
That'd be great. I can get thru most of my library on a "refresh all metadata" but eventually end up with a ban unless I switch my IP to a VPN halfway thru.

**Comment by sven-7** [comment]
Nothing for this has been implemented yet, right?  I did a refresh and was banned after about 150 series.

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/common.py line 364-375
Line 374
`  if not file or file_age > cache if ended==None else CACHE_1DAY*364 if ended else CACHE_1DAY*0.9: #last ep aired no title bolean improvement 'or lastEpAiredNoTitle'?`
Thetvdb doesn't give end date but status? if so could calculate last aired date or since some status are never accurate let's use file age instead:
- Please test `  if not file or file_age > CACHE_1YEAR*2 if file_age > CACHE_1YEAR else CACHE_1YEAR if file_age > CACHE_1MONTH*3 or else CACHE_1MONTH if file_age > CACHE_1MONTH else CACHE_1DAY`
- improvement possible: change file_age to converted aired date if available (anidb) and calculate latest air date (tvdb)

**Comment by EndOfLine369** [comment]
Got a few enhancements/cleanups/reductions done on EOL branch. This will be next on my list.
https://github.com/ZeroQI/Hama.bundle/commits/EOL/Contents

**Comment by ZeroQI** [comment]
@EndOfLine369 I counted 13 to date, so more than a few :D Love the code reduction. Will look in depth latter

**Comment by EndOfLine369** [comment]
Pushed into the branch.
```
EX:
common.LoadFile() - File cached locally - url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10901', Filename: 'AniDB\xml\10901.xml', Age: '29.63 days', Limit: '365 days'
[ ] title: Food Wars! Shokugeki no Soma

common.LoadFile() - File cached locally - url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=8312', Filename: 'AniDB\xml\8312.xml', Age: '29.63 days', Limit: '365 days'
[ ] title: Naruto Shippuuden Movie 5

common.LoadFile() - File cached locally - url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=12661', Filename: 'AniDB\xml\12661.xml', Age: '0.00 days', Limit: '6 days'
[ ] title: Boruto: Naruto Next Generations

common.LoadFile() - File cached locally - url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=8357', Filename: 'AniDB\xml\8357.xml', Age: '29.65 days', Limit: '365 days'
[ ] title: Kizumonogatari
```

**Comment by EndOfLine369** [comment]
After review, it is not possible to make the TVDB files smart. Only the series json had any indication it was done or not. All of the other jsons pulled would still have standard cache time so just leaving it as is.

**Comment by EndOfLine369** [comment]
The only thing I can think of is possibly putting in the login directly in the TVDB module. A standard cache pull of the series json, and based on that pull or Ended or not, it adjusts all later json pulls. As is the only way for the later json pulls to know what was in the series json. Thoughts @ZeroQI?

**Comment by ZeroQI** [comment]
Seem like a good idea. Ended date should be in a format compatible with the cache is elapsed time
Most important is AniDB though as you can be banned...

**Comment by sven-7** [comment]
AniDB has a `<enddate> `line in their xml files. Sadly, you can't base anything off of that unless you are able to get the xml in the first place due to ban.... I suppose a file could be built over time with that info or it could be sourced separately from AniDB somehow?

Examples:

Ongoing series: 

```
<?xml version="1.0" encoding="UTF-8"?><anime id="14819" restricted="false">
<type>TV Series</type>
<episodecount>24</episodecount>
<startdate>2019-10-09</startdate>
<titles>
<title xml:lang="x-jat" type="main">Nanatsu no Taizai: Kamigami no Gekirin</title>
```

Finished series: 

```
<?xml version="1.0" encoding="UTF-8"?><anime id="9807" restricted="false">
<type>TV Series</type>
<episodecount>25</episodecount>
<startdate>2013-09-22</startdate>
<enddate>2014-03-30</enddate>
<titles>
<title xml:lang="x-jat" type="main">Magi: The Kingdom of Magic</title>
```

**Comment by EndOfLine369** [comment]
@sven-7, AniDB is already handled. As mentioned above https://github.com/ZeroQI/Hama.bundle/issues/369#issuecomment-558455893
The question is on the other sources.

**Comment by sven-7** [comment]
Ah, my bad. I missed that one!

**Comment by EndOfLine369** [comment]
Btw, feel free to switch your install to the branch if you want to use it as is at this time. Still making more updates aside from this ticket's cache management. It is only somewhat tested so do not be surprised if you run into a crash/error. Use at your own risk. 😄 Still more coming down the pipeline.

**Comment by EndOfLine369** [comment]
@sven-7, can you please help test. Either switch your clone to the EOL branch or you can dl the files from here [https://github.com/ZeroQI/Hama.bundle/archive/EOL.zip](https://github.com/ZeroQI/Hama.bundle/archive/EOL.zip). I'm still mulling over how to code some smart TVDB caching. But AniDB is the big one with the ban triggers.

**Comment by sven-7** [comment]
Yep - sorry for the delay, been down sick for a few days. Will start to take a look today/tomorrow.

**Comment by sven-7** [comment]
Hi @EndOfLine369 - I tested out a full refresh.  I was banned from AniDB after ~138ish series and about 30 minutes in to the refresh.

**Comment by EndOfLine369** [comment]
Based on your previous posts, did you incorrectly delete your Data files before the refresh? This does nothing for pulls from scratch. That is unavoidable.

**Comment by sven-7** [comment]
Hmm.  Not this time, but there probably wasn't much data in there anyway as I've probably deleted it within the last week. So.... might as well be from scratch. Bummer.

I'll marginally refresh the library 30-40 series at a time over the next day to build the library back up to full data. Then start giving it another go.

**Comment by EndOfLine369** [comment]
You never needed to purge data. And yes, anidb xml pull is based off series age.

**Comment by ZeroQI** [comment]
Shall we count uncached anidb pull numbers and delay further not to be banned
Seemingly one packet every 4s should pass long term according https://github.com/ShokoAnime/ShokoServer/issues/379

**Comment by EndOfLine369** [comment]
Not true. We already have a 6 sec sleep in the anidb calls.
https://github.com/ZeroQI/Hama.bundle/blob/EOL/Contents/Code/AniDB.py#L167
`sleep=6`

**Comment by ZeroQI** [comment]
There is 6s sleep time indeed in common.py for AniDB. Tried editing from my phone but github didn't agree, huge delay...

would lead to bans:
- pulling twice the title database per day
- Pulling the same data multiple times 
- pulling more than once every two seconds
- pulling more than once over 4s on long runs

If we have lock working despite multiple thread, it shouldn't ban if there is local files as we put 6s delay BUT it could be pulling AniDB posters and tripping the protection ? Posters download for anidb need to use the locking mechanism and pause too.

**Comment by sven-7** [comment]
Slowly refreshing the library one letter of the alphabet at a time to build it back up for testing.

The scanner also pulls from AniDB too, right? Does the scanner and HAMA pulling back-to-back have any effect on this?  I typically am not pulling the same thing more than once per 24 hours, so it has to be volume related on my end.

I feel like the ban always results after a few big series get pulled too. Inevitably, it ends up pulling Dragon Ball, Dragon Ball Z, Detective Conan, etc. pretty close together.

**Comment by sven-7** [comment]
I think I may have found something worth looking at. In two instances, I've been banned for a refresh on a single show.  

One is Lupin III, which pulls at least 15 AniDB .xml (before banning) that are related to Lupin. Maybe the timeout isn't applying here? I have this series on plain tvdb, with episode formatting as SXEE for all five seasons since the absolute numbering on TVDB is missing for chunks. 

The other is The Disastrous Life of Saiki K. This is on TVDB4 with a custom mapping file. 

Here are the agent logs.  It doesn't look like the scanner leaves log anymore?

[Lupin III.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3918025/Lupin.III.agent-update.log)
[The Disastrous Life of Saiki K.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3918026/The.Disastrous.Life.of.Saiki.K.agent-update.log)

**Comment by EndOfLine369** [comment]
Check `_root_.agent.log` for url calls/times.

**Comment by sven-7** [comment]
It looks like there is a 6s delay. The log I posted should be from when I started to refresh the letter 'L' in the alphabet. Lupin requests are at the end. That's the only HAMA log showing up with 'banned' in it. 


[log.txt](https://github.com/ZeroQI/Hama.bundle/files/3919776/log.txt)

**Comment by EndOfLine369** [comment]
> If we have lock working despite multiple thread, it shouldn't ban if there is local files as we put 6s delay BUT it could be pulling AniDB posters and tripping the protection ? Posters download for anidb need to use the locking mechanism and pause too.

Lock is working fine. And posters are not the trigger. Perfect example is in @sven-7's "Lupin III" example where the ban triggered in the middle of the meta pull. Well before poster pull. If anything, the posters only add to the leeching threshold. But even then, once a poster is pulled, it is never pulled again.

> The scanner also pulls from AniDB too, right? Does the scanner and HAMA pulling back-to-back have any effect on this? I typically am not pulling the same thing more than once per 24 hours, so it has to be volume related on my end. Though if the Scanner pull has any effect (I see files in `/AppData/Local/Temp/`.

Files are not getting added into Plex by scanning. This is solely a metadata refresh by HAMA so scanner's pulls do not trigger the ban. Not saying it doesn't have the potential to cause it but I have not seen any issues in an xml being pulled twice, once by ASS then again by HAMA.

> I feel like the ban always results after a few big series get pulled too. Inevitably, it ends up pulling Dragon Ball, Dragon Ball Z, Detective Conan, etc. pretty close together.

Exactly, its not that we are pulling too fast or same entry repetitively (flooding). Is it a volume issue. Based on my experience, if we pull too many xmls at once, it will hit a ban as we are seen as leeching.

> EDIT: My other thought could be tvdb2/3/4 or anidb 2/3/4 shows. Are those requests getting pulled with the delay or all at the same time

Any included AniDB xml pull, no matter the source mode, has the 6 sec sleep.

> One is Lupin III, which pulls at least 15 AniDB .xml (before banning) that are related to Lupin. Maybe the timeout isn't applying here? I have this series on plain tvdb, with episode formatting as SXEE for all five seasons since the absolute numbering on TVDB is missing for chunks.
> 
> The other is The Disastrous Life of Saiki K. This is on TVDB4 with a custom mapping file.

Just adds to the leeching threshold they monitor. Based on the log you provided, Lupin III includes pulling 40 xmls in ~4min.

> It looks like there is a 6s delay. The log I posted should be from when I started to refresh the letter 'L' in the alphabet. Lupin requests are at the end. That's the only HAMA log showing up with 'banned' in it.

The 40 xmls just put it that bit over their leeching threshold.

**Comment by sven-7** [comment]
Thanks for such a thorough response. 

> Just adds to the leeching threshold they monitor. Based on the log you provided, Lupin III includes pulling 40 xmls in ~4min.
> 


> 
> The 40 xmls just put it that bit over their leeching threshold.

In sum, it sounds like the bans I'm experiencing are volume based and likely marginally passing the threshold for 4m/40xml. 

Do you think the cases for this are fringe enough to not warrant any changes?  The 6s delay gets you to exactly 4m/40xml, but maybe that's in a perfect world?  It's likely only on library add or first time HAMA usage, that a ban will trigger. I imagine _sometimes_ a ban will and _sometimes_ a ban won't happen.  It's probably a matter of circumstances of how the call goes.

**Comment by EndOfLine369** [comment]
The only thing I can think we can do to prevent a leeching ban is keep a running total of xml pulls over the last running 1 hr and be a bouncer. Lock out any new requests until we see less than X (maybe 100?) within the last hour then allow more and keep the hourly volume in check.

**Comment by sven-7** [comment]
I think that's a creative solution to the problem.  I suppose it's a matter of identifying what the time to xml ratio/threshold is.  I think 100 within an hour seems reasonable.  

The initial library load will take a while, but better than a ban.  Especially because each time you do a refresh, you'll likely only refresh the same part of the library and the later parts never get AniDB data.

**Comment by EndOfLine369** [comment]
The other thing is to just start rejecting to process refreshes once that limit it reached instead of locking out pending requests. Plex would probably like that better. Problem would be how to let the user know (without having them look at the logs) that that is what happened when they see no metadata loaded or updated.

**Comment by sven-7** [comment]
> The other thing is to just start rejecting to process refreshes once that limit it reached instead of locking out pending requests. Plex would probably like that better.

In that model, would the refresh pick back up once the limit is over?

> Problem would be how to let the user know (without having them look at the logs) that that is what happened when they see no metadata loaded or updated.

Agree that's a tough part to document. We could list it in the readme, but I feel like people often skip over that. Still - I think it's a good throttle to have implemented.

**Comment by EndOfLine369** [comment]
> > The other thing is to just start rejecting to process refreshes once that limit it reached instead of locking out pending requests. Plex would probably like that better.
> 
> In that model, would the refresh pick back up once the limit is over?

You would just have to do another refresh call after that 1 hr. The earlier series refreshed will not repull the xml and all meta should match as previous. It would only start again where it left off when it started rejecting to do more work.

> > Problem would be how to let the user know (without having them look at the logs) that that is what happened when they see no metadata loaded or updated.
> 
> Agree that's a tough part to document. We could list it in the readme, but I feel like people often skip over that. Still - I think it's a good throttle to have implemented.

Yeah, they are more likely to not see it in the readme and post in the forum of create a ticket here for a bau behavior. Would have to possibly do something on the title to make it abs clear. And I could see issues/complaints in trying to do that.

**Comment by EndOfLine369** [comment]
@ZeroQI, thoughts on either of these two potential approaches to prevent leeching bans?

**Comment by ZeroQI** [comment]
I would lean towards that too but would search for the way to avoid ban, but only if we cannot avoid it.
1- is there a 6s delay in the scanner for anidb files if pulled? Could it use cache only if available?
2- is there a magical value that allow the agent to run for long series aka 12s or more? By mesuring the numer of series and time to get banned, we could discover the sweet spot value to avoid being banned
3-can we generate the message that plex display about update status ?
That is why i want to cache the most, to avoid ban at all cost

**Comment by sven-7** [comment]
@EndOfLine369 - in your current theory, what would happen if the limit hits in the middle of a series?  Would it finish that one out and refuse the next or drop midway thru?

Having some sort of sliding scale might be interesting based off of series length and content (predicted or known) in the xml.  For series >26eps it's 6s, for series between 27-59 it's 8s, 60-99 it's 10s, and 100+ it's 12s?

I was being really careful today, but got banned again. I think it was just sheer volume within an hour (even tho I had breaks of several minutes between batches).

**Comment by EndOfLine369** [comment]
> I would lean towards that too but would search for the way to avoid ban, but only if we cannot avoid it.
> 1- is there a 6s delay in the scanner for anidb files if pulled? Could it use cache only if available?

Yep, 6s. https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py#L184

> 2- is there a magical value that allow the agent to run for long series aka 12s or more? By mesuring the numer of series and time to get banned, we could discover the sweet spot value to avoid being banned

Asked and will never be answered a year ago. It is not in their interest to ever detail their threshold/methods. https://anidb.net/forum/thread/85427

> 3-can we generate the message that plex display about update status ?
> That is why i want to cache the most, to avoid ban at all cost

They don't do the alert message popups anymore for a while now. You have to directly look at the alerts page. But even then, don't see anything in their python so only their compiled code has that function.

> @EndOfLine369 - in your current theory, what would happen if the limit hits in the middle of a series? Would it finish that one out and refuse the next or drop midway thru?

It would just pause midway through and continue on once headroom is freed up.

> Having some sort of sliding scale might be interesting based off of series length and content (predicted or known) in the xml. For series >26eps it's 6s, for series between 27-59 it's 8s, 60-99 it's 10s, and 100+ it's 12s?

A sliding scale would still potentially hit the leeching threshold. Best to let it run as fast as it can if it can stay under that limit as bau.

> I was being really careful today, but got banned again. I think it was just sheer volume within an hour (even tho I had breaks of several minutes between batches).

You can look at your "DataItems/AniDB/xml" folder and see how many and in what times you got before you got banned.

**Comment by sven-7** [comment]
> Asked and will never be answered a year ago. It is not in their interest to ever detail their threshold/methods. https://anidb.net/forum/thread/85427

Yeah. Here, they say 300 (within a day) should be fine. That confirms for me we're fine on the 6s part, but it's the overall number of xml over an unknown time period that we're up against.  https://anidb.net/forum/thread/92150

**Comment by ZeroQI** [comment]
there is either a day limit for requests or a continuous limit per hour and
we need to raise the timing until we figure out the numbers...

**Comment by sven-7** [comment]
Here is some data from yesterday over the course of 120 minutes:

- Over 70 minutes I did 186 xml files and was not banned. 
- Took a 100 minute break and did 36 more (took an additional 20 minutes) and that resulted in a ban. 
- The final was 222 xml in 2 hours and that equals a ban.

So right now, it could be an average of 100/hour and I broke that?

**Comment by EndOfLine369** [comment]
Throttle option added to LoadFile()
AniDB is set for max of 100 over 1 hr.

**Comment by EndOfLine369** [comment]
Enhanced HAMA:
[Reduce AniDB xml pulls via mappingList['possible_anidb3']](ba81911)
Reduces the AniDB xml pulls for anidb3 setups. Since it is translated and added in as 'tvdb', it could also possibly be a plain 'tvdb' entry when seen by HAMA. So we only want to pull all AniDB xmls on a possible 'anidb3' entry. So 'possible_anidb3' is defined if an episode number of >100 is found which is what ASS will add it in as.

**Comment by EndOfLine369** [comment]
Tweaked the cache age some more.
[Cache limit age cap increased and caculated instead of fixed values](23420b5)
2 years didn't see old enough to require a 1 year cache. Series ended age has been increased to 5 years of a cap of 1 year cache. And the series <5yrs ended cache limit is not dynamically calculated based on the percentage of where it is withing that 5 years.

EX (see 'Limit:'):
```
common.LoadFile() - File cached locally - Filename: 'AniDB\xml\10901.xml', Age: '2.92 days', Limit: '307 days', url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10901'
[ ] title: Food Wars! Shokugeki no Soma
common.LoadFile() - File cached locally - Filename: 'AniDB\xml\11828.xml', Age: '2.92 days', Limit: '234 days', url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=11828'
common.LoadFile() - File cached locally - Filename: 'AniDB\xml\13244.xml', Age: '0.02 days', Limit: '144 days', url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=13244'
common.LoadFile() - File cached locally - Filename: 'AniDB\xml\13658.xml', Age: '0.02 days', Limit: '106 days', url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=13658'
common.LoadFile() - File cached locally - Filename: 'AniDB\xml\14951.xml', Age: '0.02 days', Limit: '6 days', url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=14951'
```

**Comment by EndOfLine369** [comment]
Let me know if you can think of a better way to space out the limit better pragmatically. And if you see issues in AniDB bans from a full library refresh with the throttle limiter now in place.

**Comment by sven-7** [comment]
I’ll try to test this today or tomorrow. 

So series of 5+ years has a 1 year cache. How are the others breaking down percentage wise? If it’s 2.5 years old it’s essentially a six month cache? Does that make ongoing series close to or just a bit more than a daily cache?

**Comment by EndOfLine369** [comment]
Anything still yet to end or <=30 days since end is still at the 6day cache

**Comment by sven-7** [comment]
Okay, cool. I’ll try it out and see what happens.

**Comment by EndOfLine369** [comment]
Sure, let me know how it goes fellow insomniac 😈

**Comment by sven-7** [comment]
I've gotta run for now, but after 215 series over 35 minutes -- no ban! 🤘🏼Looks like only about 20 new AniDB xml's have been updated as a result of the full refresh right now. So - thus far, it's looking good. I'll update with the final metrics when I can get back to it.

**Comment by EndOfLine369** [comment]
How did it go on the clean full refresh @sven-7 with the AniDB 100req/1hr throttle?

**Comment by sven-7** [comment]
I just tried and still banned.

It looks like it did 100 from 10:00AM to 10:18AM, then at 11:00AM it started up again instead of 11:19AM. It only made it 22 (over 3 minutes) before the ban hit.

**Comment by EndOfLine369** [comment]
Feel free to decrease the threshold `throttle=['AniDB', CACHE_1HOUR, 100]`.

https://github.com/ZeroQI/Hama.bundle/blob/EOL/Contents/Code/AniDB.py#L173
`xml = common.LoadFile(filename=AniDBid+".xml", relativeDirectory=os.path.join("AniDB", "xml"), url=ANIDB_HTTP_API_URL+AniDBid, cache=cache, sleep=6, throttle=['AniDB', CACHE_1HOUR, 100])`

**Comment by EndOfLine369** [comment]
Really appreciate the help in ban testing. Thinking of just removing the throttle param from the AniDB call an merge all of the changes. Once we get a better idea of how must we have to lower to prevent a ban, we can put the arg back into the LoadFile call.

**Comment by sven-7** [comment]
I agree to commit the rest, except for the cache. 

I'm running a test with 75 as the cap for HAMA. I do wonder, watching the logs come in from the Scanner, if we have to factor the AniDB xml's that the scanner is pulling in.  Before HAMA even started, ASS pulled down around 60 AniDB xml's during its scan to `/AppData/Local/Temp/`. I'm guessing that AniDB will look at me as if I'm pulling 60 + 75 over the first hour, plus some of them might be duplicates.

**Comment by EndOfLine369** [comment]
If I read that post right, you cleared the xml files then created a new library to test? Opposed to clearing the xmls and then full refresh?

The former would indeed be truer to what would happen on an initial library creation involving both ASS & HAMA. The latter would verify HAMA on a full refresh where a good deal of xmls need to be pulled down.

**Comment by sven-7** [comment]
Not entirely - no new library.  I cleared out the following before running the full refresh:
```
\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\AniDB\xml\
\Plug-in Support\Caches\
\AppData\Local\Temp\
```
Full refresh/scan start time: 10:23pm

- 64 AniDB xml files were downloaded via ASS
- HAMA started a few minutes later around 10:29 and the first 75 took ended at 10:44pm
- HAMA paused until 11:29pm and downloaded the next 75 and ended at 11:45pm
- HAMA paused until 12:29pm and made it 72 xml files before a ban kicked in at 12:48am.

By my calculations, that is a total of 286 xml files over 2h25m or 145 minutes. 222 of which were downloaded by HAMA.  It definitely was a longer time to ban than the last time I conducted this.  

I'm also aware that my IP address has been banned several times over the past few weeks, so I could be on a more restricted list at this point.  Especially because they consider requests after ban, so if HAMA keeps going once I'm banned, it's still counting those requests against me.

**Comment by EndOfLine369** [comment]
Ah, must be grouping folders that are force scanned on every library scan. Only reason left I can think of why ASS would be download anything on a full refresh (that inherently triggers a library scan at the start). I guess grouping folder setup would require caching to be enhanced in ASS as well...

**Comment by EndOfLine369** [comment]
Might also want to put a timed lock on any further AniDB calls once a ban response is first hit. Instead of allowing the additional calls to continue to go through and just hit an expected ban response (in HAMA).

**Comment by sven-7** [comment]
Yes - looks like all of those are grouped folders.  I don't mind ungrouping them. Since I've started using the AniDB modes more I've moved away from that kind of organization, so those are more legacy ones. Ultimately, most of them seem to be AniDB2/3/4 series that are under a single folder for organizational purposes. 

I think that's an interesting concept. Once the first ban hits, HAMA pauses for X amount of time and retries to see if the ban is still in place?

**Comment by EndOfLine369** [comment]
It would not pause anything. It would just start bypassing the url calls and use the cached version or no data available if no cache.

**Comment by sven-7** [comment]
I think the HAMA control would be more than efficient (aside from the initial library load for ASS). That way, you could run another full refresh likely sooner rather than later, due to stopping the AniDB call. Then it will bypass the ones that it just cached on the next go around.

**Comment by EndOfLine369** [comment]
Created a branch in ASS now as well. Will add this to some of the TODOs i've noted over time (now up to 5 with this cache item). Will let you know.

**Comment by sven-7** [comment]
First, I took care of all grouping folders so there would not be any calls from ASS.

Second, I changed the timing to 10s per xml and 60 over 1HOUR. 

I made it about 270 over four hours before a ban hit. The 10s in reality probably hurt more than helped. Because the '1hour' is from start-to-start not end-to-start, there was only about 40-45 minutes in between the calls. 

Going to do a second refresh and see how the caching works out.

**Comment by EndOfLine369** [comment]
Updates for ASS there now as well and a couple more for HAMA.
HAMA: [Hama.bundle#374](https://github.com/ZeroQI/Hama.bundle/pull/374)
ASS: [Absolute-Series-Scanner#251](https://github.com/ZeroQI/Absolute-Series-Scanner/pull/251)

**Comment by ZeroQI** [comment]
Any change in the behaviour since the updates, by any chance ?

**Comment by sven-7** [comment]
I need to do some more extensive testing. I haven't noticed anything yet, but will report back if I do.  I think given the sensitivities of AniDB, this is probably as good as we can get.

**Comment by EndOfLine369** [comment]
I did a full refresh against my main library. It hit the throttle hard 3 times, softly hit it quite a few times, downloaded 450+ xmls, never hit a ban.

**Comment by EndOfLine369** [comment]
All changes merged in ASS & HAMA
