### ISSUE TITLE
Themes - HTTP Error 403 Forbidden

### ISSUE THREAD

**Issue by theroninhunter** [ZeroQI/Hama.bundle#370]
I've updated to the latest HAMA agent from GitHub and j
[Goblin Slayer.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3865684/Goblin.Slayer.agent-update.log)
ust added Goblin Slayer to my Plex server and the theme music does not work.

Looked inside /share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/Anime/Goblin Slayer.agent-update.log which shows an error.

--- themes --------------------------------------------------------------------------------------------------------------------------------------------------
result code: 'HTTP Error 403: Forbidden', url: 'http://tvthemes.plexapp.com/350166.mp3'

**Comment by ZeroQI** [comment]
When I click on the link it doesn't download neither so it is not a failure of the agent to download, it's a plexapp site server issue returning error 403 (forbidden) so the file is there, otherwise it would be 404...

Not an agent issue
