### ISSUE TITLE
Only anime that are rated X don't get metadata.

### ISSUE THREAD

**Issue by varoOP** [ZeroQI/Hama.bundle#372]
So previously , HAMA wasn't working for me at all and I was very lazy about explaining my issue. O I apologize for that and really appreciate your work!
I followed your troubleshooting instructions and HAMA started working again perfectly after I rebuilt my plex library. 
I have my anime and hentai in two separate libraries using HamaTV as metadata agent.
There's only one thing that isn't working and it's as the title says. 
Metadata , especially for hentai anime isn't retrieved and in the log for it , the error 500 i.e banned is shown. 
I'll upload logs for two of the hentai anime it can't retrieve metadata for , Koikishi Purely kiss and Kara no shoujo.
So I gave it a day thinking I got banned after building a library of over 100 anime. 
Today , I tried to refresh my hentai library again but still banned. 
Then I added an anime called Bakemonogatari to my anime library which retrieved data without any problems. 
So I think only hentai anime are banned it seems ? 
Or Bakemonogatari could just be using tvdb to retrieve metadata and I am banned on aniDB anyway. 
Here are the logs so you can help me pin point the problem   :
Monogatari ones : 
Monogatari.agent-update.log : https://paste.ubuntu.com/p/tXTZ4k33tB/
Monogatari.agent-search.log : https://paste.ubuntu.com/p/g8ftrdW96d/
Hentai ones :
Koikishi.agent-update.log : https://paste.ubuntu.com/p/gwmRmRqHQz/
kara no shoujo.agent-update.log : https://paste.ubuntu.com/p/ScQTxFThrY/

There are no agent-search logs for the hentai at all.
Please let me know if anymore logs are needed.

**Comment by ZeroQI** [comment]
Banned is an AniDB thing. It doesn't look cached and indeed AniDB banned which is 1h or 24h usually but not hentai specific...
No hentai stored in TheTVDB.
Hama version from the 17th of November corrects the banned response from being cached

**Comment by varoOP** [comment]
So I should just wait till the ban is lifted and retry then.
Thanks!

**Comment by varoOP** [comment]
Ok wait I'll post the root logs!

**Comment by varoOP** [comment]
Here are the logs : 
_root_.agent-search.log : https://paste.ubuntu.com/p/HPq6PyvMMC/
_root_.agent-update.log : https://paste.ubuntu.com/p/CkJQ2mhpP8/
_root_.agent.log : https://paste.ubuntu.com/p/XBjX8WXCsK/
..agent-update.log : https://paste.ubuntu.com/p/YzTvgpC6Rn/

**Comment by varoOP** [comment]
Ban lifted. 
Working perfectly!
