### ISSUE TITLE
Episodes classified as other, won't have their metadata pulled.

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#379]
Tehse are the files in question:

> 
> [file] Ginga Eiyuu Densetsu Die Neue These (2019) [anidb-13473]/[HorribleSubs] Legend of the Galactic Heroes - Die Neue These - O1 [1080p].mkv
> [file] Ginga Eiyuu Densetsu Die Neue These (2019) [anidb-13473]/[HorribleSubs] Legend of the Galactic Heroes - Die Neue These - O2 [1080p].mkv
> [file] Ginga Eiyuu Densetsu Die Neue These (2019) [anidb-13473]/[HorribleSubs] Legend of the Galactic Heroes - Die Neue These - O3 [1080p].mkv
> [file] Ginga Eiyuu Densetsu Die Neue These (2019) [anidb-13473]/[HorribleSubs] Legend of the Galactic Heroes - Die Neue These - O4 [1080p].mkv
> [file] Ginga Eiyuu Densetsu Die Neue These (2019) [anidb-13473]/[HorribleSubs] Legend of the Galactic Heroes - Die Neue These - O5 [1080p].mkv
> [file] Ginga Eiyuu Densetsu Die Neue These (2019) [anidb-13473]/[HorribleSubs] Legend of the Galactic Heroes - Die Neue These - O6 [1080p].mkv
> [file] Ginga Eiyuu Densetsu Die Neue These (2019) [anidb-13473]/[HorribleSubs] Legend of the Galactic Heroes - Die Neue These - O7 [1080p].mkv
> [file] Ginga Eiyuu Densetsu Die Neue These (2019) [anidb-13473]/[HorribleSubs] Legend of the Galactic Heroes - Die Neue These - O8 [1080p].mkv
> [file] Ginga Eiyuu Densetsu Die Neue These (2019) [anidb-13473]/[HorribleSubs] Legend of the Galactic Heroes - Die Neue These - O9 [1080p].mkv
> [file] Ginga Eiyuu Densetsu Die Neue These (2019) [anidb-13473]/[HorribleSubs] Legend of the Galactic Heroes - Die Neue These - O10 [1080p].mkv
> [file] Ginga Eiyuu Densetsu Die Neue These (2019) [anidb-13473]/[HorribleSubs] Legend of the Galactic Heroes - Die Neue These - O11 [1080p].mkv
> [file] Ginga Eiyuu Densetsu Die Neue These (2019) [anidb-13473]/[HorribleSubs] Legend of the Galactic Heroes - Die Neue These - O12 [1080p].mkv
> 

Logs:
[Ginga Eiyuu Densetsu Die Neue These (2019) [anidb-13473].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/4049698/Ginga.Eiyuu.Densetsu.Die.Neue.These.2019.anidb-13473.scanner.log)
[Ginga Eiyuu Densetsu Die Neue These (2019) [anidb-13473].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4049719/Ginga.Eiyuu.Densetsu.Die.Neue.These.2019.anidb-13473.agent-update.log)

They look like this:

![image](https://user-images.githubusercontent.com/14930057/72209297-b2f67a80-34a4-11ea-9a9a-10da021833f1.png)

This probably is an ASS Scanner problem since they are numbered 500+ (which according to ASS Readme, it's the range for unmapped files)

**Comment by ZeroQI** [comment]
Notes
- Wrong ep number assigned, it's a scanner issue
- You put the letter 'O' in front of the episode number 'O1' instead of '01', you can compare with the size of the '0' in the '1080p' part of the filename
