### ISSUE TITLE
“Your changes could not be saved.” issue after updating HamaTV plug in

### ISSUE THREAD

**Issue by jisongkun** [ZeroQI/Hama.bundle#380]
i checked all installation locations. the old version of hamatv agent doest not give me error but it wont download posters anymore. i cloned the newest version, but it wont let me save the setting. the ASS scanner works fine. removing Hama.bundle folder from plugin folder "fixes" the problem of saving.

could anyone help me here? thanks in advanced.
![1](https://user-images.githubusercontent.com/42218064/73334594-1d325c00-42a8-11ea-9faa-35cd9e8184b6.jpg)
![2](https://user-images.githubusercontent.com/42218064/73334599-215e7980-42a8-11ea-8f6a-4bd2942a491b.jpg)

**Comment by ZeroQI** [comment]
removing Hama.bundle folder from plugin folder "fixes" the problem of saving:
If you removed '-master' from the foldername, then that is the correct install procedure

**Comment by jisongkun** [comment]
> > removing Hama.bundle folder from plugin folder "fixes" the problem of saving:
> 
> If you removed '-master' from the foldername, then that is the correct install procedure

thanks a lot for your help and thanks again for your hard work on this plugin. please see the address bar in my second attachment, i did remove the '-master' out of the folder name, the issue still presents. :(

**Comment by ZeroQI** [comment]
I need logs.
- [...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.hama.log (Agent logs)
- [...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.system.log (show why the agent cannot launch)
- [...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.system.log (show why the agent cannot launch)

**Comment by ZeroQI** [comment]
Logs please?

**Comment by jisongkun** [comment]
> Logs please?

sorry for the late reply. here is the log file, please see the attachment. thanks again.
[PMS Plugin Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/4202130/PMS.Plugin.Logs.zip)

**Comment by ZeroQI** [comment]
ImportError: No module named tvdb4
why are you missing tvdb4.py? Show me the content of 'contents' folder
Did you just update __init__.py?

**Comment by jisongkun** [comment]
> ImportError: No module named tvdb4
> why are you missing tvdb4.py? Show me the content of 'contents' folder
> Did you just update **init**.py?

no, i believe l cloned all files. 
![Screen Shot 2020-02-14 at 8 09 56 PM](https://user-images.githubusercontent.com/42218064/74531309-49680100-4f67-11ea-8580-ccd7474132de.png)
![Screen Shot 2020-02-14 at 8 10 39 PM](https://user-images.githubusercontent.com/42218064/74531317-4bca5b00-4f67-11ea-8072-c2309b9f5808.png)

**Comment by ZeroQI** [comment]
It cannot find tvdb4.py but it is there...
I have no clue but it seems only your machine is impacted
If running Windows try "chkdsk /f C:" and schedule for next boot and "sfc /scannnow"

**Comment by ZeroQI** [comment]
Can you check if it is failing since plex was updated ?

**Comment by jisongkun** [comment]
> Can you check if it is failing since plex was updated ?

thanks for the reply. I don't have access to my server at the moment, I will get back to you as soon as possible.

**Comment by ZeroQI** [comment]
Any update ?

**Comment by jisongkun** [comment]
> Any update ?

I took another look today. after the Plex server update. I was able to save the setting and using the HamaTV plugin, but I'm still not getting any cover pictures for some reason. :( but I guess this might be a different problem now. :)

![Plex](https://user-images.githubusercontent.com/42218064/76108139-fab50080-6014-11ea-8c64-8fe5be3ef430.jpg)
[Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/4299567/Logs.zip)

**Comment by ZeroQI** [comment]
Original error is gone
There are other errors but i need the agent logs for the series, located in agent data folders for now
Seem like an internet access issue, like a firewall or "Security suite"

**Comment by ZeroQI** [comment]
different problem and seem specific to you as another user got a temporary tvdb issue but working back yesterday. Clothing this one in the meantime. check custom series logs, answer is there (or your security suite block urls with banner in the URL)...
