### ISSUE TITLE
Lambda collection and default pref : potential issue ?

### ISSUE THREAD

**Issue by hergonoway** [ZeroQI/Hama.bundle#381]
I can't find enough info about how collections work between Lambda and Hama.

Context : I'm currently using Lambda on one server in order to force a certain amount of data on the other one (poster, etc) while keeping Hama on the second one for filling holes. So basically in Agent settings, my first server got Hama then Lambda, and the second one Local Media Assets TV then Hama. Seems about right, but I've got a concern for Collections generated by the first server.

Does the "Local" parameter in T--M 'collections' use or check the "_Collections" folder generated by Lambda (set in root mode) ? If yes is there some kind of potential loop with the default prefs "Local, AniDB, TheMovieDb, AnimeLists" which may lead to collection never being updated ?

**Comment by ZeroQI** [comment]
Lamdba backup or restore metadata. There is no interaction with agents per se...
No, HAMA doesn't use or check the "_Collections" folder generated by Lambda.

By local, it means collections field will be present if agrouping folder present.
For example: /root/Grouping folder/serie/ep ##.ext will use "Grouping folder" collection field...
