### ISSUE TITLE
Collection behavior issue

### ISSUE THREAD

**Issue by hergonoway** [ZeroQI/Hama.bundle#382]
Hello, 

I've recently added the Euphonium full series + movies, there're 2 seasons with a summary movie after each season, a movie side story and finally a movie sequel to the last season.  

![image](https://user-images.githubusercontent.com/8405448/76036689-118c2200-5f45-11ea-8842-166a2775f7ec.png)

Everything seemed to work as expect until Hama build the Collection. (my current Pref for T--M 'collections' is set to : "AnimeLists, TheMovieDb, AniDB" )
It has built the "Sound! Euphonium Collection" Collection but without the last movie (a13207). 

![image](https://user-images.githubusercontent.com/8405448/76036737-32ed0e00-5f45-11ea-87d9-e5d8f69aaa83.png)

The relationship exist in AniDB, it's even a sequel not even a summary or side story  [https://anidb.net/anime/13207/relation/graph](url) : 
![image](https://user-images.githubusercontent.com/8405448/76036150-a2fa9480-5f43-11ea-9826-e4ba9494c9ba.png)

in /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/AniDB/xml/13207.xml I can see that the relationship is correctly taggued with the 2nd season (prequel) (a11746) which is in the Collection : 

```
<?xml version="1.0" encoding="UTF-8"?><anime id="13207" restricted="false">
<type>Movie</type>
<episodecount>1</episodecount>
<startdate>2019-04-19</startdate>
<enddate>2019-04-19</enddate>
<titles>
<title xml:lang="x-jat" type="main">Gekijouban Hibike! Euphonium: Chikai no Finale</title>
<title xml:lang="ja" type="official">劇場版 響け! ユーフォニアム ~誓いのフィナーレ~</title>
<title xml:lang="en" type="official">Sound! Euphonium: The Movie - Our Promise - A Brand New Day</title>
<title xml:lang="zh-Hans" type="official">吹响吧！上低音号~誓言的终曲~</title>
</titles>
<relatedanime>
<anime id="14935" type="Sequel">Hibike! Euphonium: Kumiko 3 Nensei Hen</anime>
<anime id="11746" type="Prequel">Hibike! Euphonium 2</anime>
</relatedanime>
```
and in the corresponding xml for this 2nd season (a11746) I see the relationship with a13207 correctly taggued as sequel in /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/AniDB/xml/11746.xml

```
<?xml version="1.0" encoding="UTF-8"?><anime id="11746" restricted="false">
<type>TV Series</type>
<episodecount>13</episodecount>
<startdate>2016-10-06</startdate>
<enddate>2016-12-29</enddate>
<titles>
<title xml:lang="x-jat" type="main">Hibike! Euphonium 2</title>
<title xml:lang="ru" type="synonym">Играй, эуфониум! 2</title>
<title xml:lang="ja" type="official">響け! ユーフォニアム 2</title>
<title xml:lang="en" type="official">Sound! Euphonium 2</title>
<title xml:lang="ko" type="official">울려라! 유포니엄 2</title>
<title xml:lang="zh-Hans" type="official">吹响！悠风号 第二季</title>
</titles>
<relatedanime>
<anime id="13207" type="Sequel">Gekijouban Hibike! Euphonium: Chikai no Finale</anime>
<anime id="10889" type="Prequel">Hibike! Euphonium</anime>
<anime id="13491" type="Side Story">Liz to Aoi Tori</anime>
<anime id="12962" type="Summary">Gekijouban Hibike! Euphonium: Todoketai Melody</anime>
</relatedanime>
```
Any idea ?

Additional question : I've check the DefaultPrefs.json and saw that currently "Anidb" is in 1st position for T--M 'collections' with "AniDB, TheMovieDb, AnimeLists". I was told numberous times by the past to put AnimeLists in 1st, so my config is set like so since 2018. But it's also mentionned in the readme.md that "Collection mapping from ScudLee's movie collection ammended with AniDB RelatedAnime field" which would let me think that I should keep AnimeLists before Anidb. Well what's the best recommendation from the devs for T--M 'collections' ?

**Comment by ZeroQI** [comment]
i need the Hama logs for the movie to see the collection field logs for it, as it is set as a string for each series

**Comment by hergonoway** [comment]
this one ? ->  
[Gekijouban Hibike! Euphonium Chikai no Finale [anidb-13207].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4295907/Gekijouban.Hibike.Euphonium.Chikai.no.Finale.anidb-13207.agent-update.log)

**Comment by ZeroQI** [comment]
[ ] collection: TVDBid '' is not part of any collection
There is no tvdb id associated, limit the possibilities..

**Comment by hergonoway** [comment]
I don't understand, it has a TVDB Movie ID, its also listed in "Special" here https://www.thetvdb.com/series/sound-euphonium/episodes/6944923 from the main show with the TVDB id 289884. If I understand what you said, it's the id which hold the "TVDB Collection"

This show (289884) got also in its Special, listed just above my problematic movie, another movie "Liz and the Blue Bird" : https://www.thetvdb.com/series/sound-euphonium/episodes/6476500

but this one is in the collection [Gekijouban Hibike! Euphonium Todoketai Melody [anidb-12962].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4297990/Gekijouban.Hibike.Euphonium.Todoketai.Melody.anidb-12962.agent-update.log)

**Comment by ZeroQI** [comment]
https://raw.githubusercontent.com/ScudLee/anime-lists/master/anime-list-master.xml for anidb id 13207 give the following mapping:
```
  <anime anidbid="13207" tvdbid="" defaulttvdbseason="" episodeoffset="" tmdbid="" imdbid="">
    <name>Gekijouban Hibike! Euphonium: Chikai no Finale</name>
  </anime>
```
It should be from what you told me:
```
  <anime anidbid="13207" tvdbid="289884" defaulttvdbseason="0" episodeoffset="18" tmdbid="" imdbid="tt7089882">
    <name>Gekijouban Hibike! Euphonium: Chikai no Finale</name>
  </anime>
```

Created bug report https://github.com/ScudLee/anime-lists/issues/314
Agent behaving as expected, closing
