### ISSUE TITLE
Some Problem is occured on tvdb API

### ISSUE THREAD

**Issue by gspmkjh** [ZeroQI/Hama.bundle#384]
Sadly TVDB API seems to have stopped supporting some function.
Both TVDB Agent(plex native agent) and HAMA Agent does not  work properly.

https://forums.thetvdb.com/viewtopic.php?p=168202&sid=24b7db3ab44e559c2a6e6677e853d3e4#p168202

https://www.filebot.net/forums/viewtopic.php?f=6&t=11417&p=47938#p47937

https://www.filebot.net/forums/viewtopic.php?f=10&p=47939#p47939

Sadly, yesterday I just delete my Library and local metadata after HDD migration.

**Comment by ZeroQI** [comment]
Logs????
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/TheTVDBv2.py
change line 18 and 19 to http://... and report

**Comment by gspmkjh** [comment]
Fortunately, It works again today without any code edit. thanks.

**Comment by ZeroQI** [comment]
Thanks for letting me know.
Tvdb timeout issue, good to know
