### ISSUE TITLE
Hama Preferring TheTVDB over info that exists in Anidb

### ISSUE THREAD

**Issue by vyressi** [ZeroQI/Hama.bundle#385]
Trying to get S1 of anidb-14238 to reflect proper title and art.

Performed Plex Dance
Also wiped local plugin caches.
Hama was at default options, where anidb was first and thetvdb was second choice for titles.

The Director, Studio, Description, Release Date, really everything except the episode title and the episode poster displayed with anidb's information, but Hama kept pulling up s00e004 of thetvdb-353666 which is on anidb as an episode of anidb-14579.

I tried naming the file S00, s00e001, renaming folder itself, putting anidb tag after folder to force matching, to no avail.

All other episodes matched properly.  Just episode 0, S1 was causing an issue.

This behavior persisted until I removed thetvdb from the hama options for that library.

**Comment by ZeroQI** [comment]
Scanner logs and Hama custom logs for given series missing

**Comment by vyressi** [comment]
Thanks for the input, will do!  I didn't realize this mapping was a place to check before submitting an issue.
