### ISSUE TITLE
FileBot Xattr Metadata (TV) agent as secondary agent for HAMA

### ISSUE THREAD

**Issue by IIeTp** [ZeroQI/Hama.bundle#387]
Greetings! The Filebot agent can extract information from .xattr files and only need to transfer it to a foreign agent, for example, HAMA. [Here](https://github.com/filebot/plex-agents/blob/master/Plug-ins/Xattr.bundle/Contents/Code/__init__.py#L75) is an example with which he knows how to work now (although these agents do not support searching by id, they accept information about the file name and year of release). I want HAMA to learn how to accept serial id information for a more accurate search.
[Here](https://github.com/filebot/plex-agents/blob/master/Plug-ins/Xattr.bundle/Contents/Code/filebot.py#L97) is an example of what the Xattr agent returns for the rest of the agents.

I tried setting the values ​​for the HAMA agent, but it looks like HAMA cannot accept anything from other agents.

**Comment by ZeroQI** [comment]
The plan is to modify the scanner so it bring support to thetvdb and themoviedb agents don't need to be modified... I would have to add support for tvdbid as title in Hama though
https://github.com/ZeroQI/Absolute-Series-Scanner/issues/262

**Comment by IIeTp** [comment]
Yes, I understand. I like the .xattr scanner in that it only adds files that have metadata to it. if the ASS scanner has the option to search for files with c .xattr metadata only, then this issue can be closed immediately.

**Comment by ZeroQI** [comment]
I don't get it... Why not using .xattr scanner alongside Hama then?

**Comment by IIeTp** [comment]
The standard .xattr scanner + HAMA bundle does not use id. I tried to configure the .xattr scanner so that it only gave the HAMA agent id from the series, but it did not work. I will most likely have to do change the scanner to the standard name + id.
`The Letter for the King [373452]` like this

**Comment by ZeroQI** [comment]
From hama "The Letter for the King [tvdb-373452]" or for tvdb agent "373452" would force the id from the scanner by setting the series title to that string

**Comment by IIeTp** [comment]
if the HAMA agent could receive information from the Xattr agent, then one could try to give the necessary information for the HAMA according to the template "name + tvdb-id".

which way do you think is better?
if you follow the variant from the first message, the xattr agent will be able to work with other databases too (together with HAMA).

**Comment by ZeroQI** [comment]
Primary agents decides the id. 
Secondary agents need to match the unique id and can provide info not found by the primary agent... IT cannot force the unique ID used by the primary agent, just match it...

The ONLY info really worth is the ID. hama search either uses the .xattr id or the scanner does. 

my id for Hama isn't composed of just TheMovieDb or tvdb id, but uses:
anidb-xxxx
tvdb-xxxxx
tmdb-xxxx

Since my ID differs from the other agents, this method cannot be used with hama unless Filebot agent is modified specifically for hama. 

Easier again for the scanner to format the title to force the tvdbid or tmdb id and hama to support thetvdb id as title for series and "title [anidb-xxxx]" for movies/series with an anidb id...

**Comment by IIeTp** [comment]
I redid the xattr scanner, now HAMA understands the [tvdb-id] that the scanner passes to it.
but nothing worked with tsdb and anidb. is this not supported now?
Example Oruchuban Ebichu [anidb-150]

**Comment by ZeroQI** [comment]
if the series title contain at the end a space then "[anidb-150]" or "tsdb-12345]" then it should force the id. i need the search logs for the series in the agent data folders logs

**Comment by IIeTp** [comment]
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/4396968/com.plexapp.agents.hama.log)

**Comment by ZeroQI** [comment]
I do log redirection. 
I need this file (path taken from the readme troubleshooting section):
[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/(Library_name/)series_root_folder.agent-search.log (guid assignment)

**Comment by IIeTp** [comment]
[..agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/4397122/default.agent-search.log)

**Comment by ZeroQI** [comment]
'show': 'Oruchuban Ebichu [anidb-150]'
"D:\Downloads\Black Mirror 3 - LostFilm.TV [1080p]\Black.Mirror.S03E02.1080p.rus.LostFilm.TV.mkv"...

```
    if movie or max(map(int, media.seasons.keys()))<=1:  maxi, n =         AniDB.Search(results, media, lang, manual, movie)
TypeError: int() argument must be a string or a number, not 'NoneType'
```
We  have a crash...
media.seasons() seem to be empty... Why would there be no seasons recorded in Plex despite episodes? Not sure why it crashes

**Comment by IIeTp** [comment]
Yes. and everything works with TVDB. can I help you with something else to resolve the issue?

**Comment by IIeTp** [comment]
fixed. 
the problem was with .xattr files, for absolute order the season number was not written. What seasonally logic should anidb have for seasons?

**Comment by IIeTp** [comment]
> fixed.
> the problem was with .xattr files, for absolute order the season number was not written. What seasonally logic should anidb have for seasons?

season 1 and specials?

**Comment by ZeroQI** [comment]
Anidb has specials SPx and openings/Endings so season 0 apart from that, all else is season 1 from Plex point of view

The scanner should have added for eps a Season number and episode number... If it didn't that explain but the file should not have been added to Plex :/

**Comment by IIeTp** [comment]
it was added because the season value was -1.
