### ISSUE TITLE
posters missing

### ISSUE THREAD

**Issue by IIeTp** [ZeroQI/Hama.bundle#389]
Hello. No posters from these series appear. Take a look, please. HAMA has default settings.
https://thetvdb.com/series/velikaya-voyna
[Великая война (2010) [TVDB-153081].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4429454/2010.TVDB-153081.agent-update.log)

https://thetvdb.com/series/namedni

**Comment by IIeTp** [comment]
I tried with other settings. Changed the language of the library to Russian. I put the priority of the Russian language (ru, en).
[com.plexapp.agents.hama.json.txt](https://github.com/ZeroQI/Hama.bundle/files/4429558/com.plexapp.agents.hama.json.txt)

cleared the json folder of this series so that it matches it again. 

[series_ru.json.txt](https://github.com/ZeroQI/Hama.bundle/files/4429553/series_ru.json.txt)
It refers to "posters/153081-1.jpg", but this file does not exist.
As I understand it, HAMA defines the poster language using the TVDB API, https://thetvdb.com/artwork/641991 is English here.
Please, tell me what am I doing wrong?

**Comment by ZeroQI** [comment]
`<load_all_porter_sources>false</load_all_porter_sources>`

**Comment by IIeTp** [comment]
Yes, it should, but it doesn’t load. no poster file. with other series everything is fine. Plex sees Russian and English posters being loaded.
![2020-04-03_111153](https://user-images.githubusercontent.com/52212265/78404440-1ce77180-7607-11ea-88c1-8b0a278aa113.png)
in this screenshot 3 series with a Russian poster, 2 without a poster (there is a poster on TVDB), the rest with an English poster

**Comment by ZeroQI** [comment]
Could you please upload the below and the latest series update log so i work out the logic?
- TheTVDB/json/153081\images_en.json
- TheTVDB/json/153081\images_ru.json

**Comment by IIeTp** [comment]
[com.plexapp.agents.hama\DataItems\TheTVDB\json\153081\images_en.json.txt](https://github.com/ZeroQI/Hama.bundle/files/4429919/images_en.json.txt)
[com.plexapp.agents.hama\DataItems\TheTVDB\json\153081\images_ru.json.txt](https://github.com/ZeroQI/Hama.bundle/files/4429920/images_ru.json.txt)

Is that what you needed?

**Comment by ZeroQI** [comment]
Contents/Code/TheTVDBv2.py lime 303
From
`          if bannerTypes[bannerType]==0 or bannerType in ('seasonwide', 'series') or movie and not bannerType in ('fanart', 'poster'):  continue  #Loop if no images`
To:
`          if bannerTypes[bannerType]==0 or bannerType =='seasonwide' or movie and not bannerType in ('fanart', 'poster'):  continue  #Loop if no images`

**Comment by IIeTp** [comment]
updated Contents/Code/TheTVDBv2.py, deleted the complex folder app.agents.hama\DataItems\TheTVDB\json\153081, re-created the library, still the poster did not appear.
Here are the contents of the folder just in case.
[153081.zip](https://github.com/ZeroQI/Hama.bundle/files/4430082/153081.zip)

**Comment by ZeroQI** [comment]
Poster is in series_ru but not images ru.
Could be
- cache per filename so won't return json output with poster until depleted (unlikely poster was english)
- no poster in image json when only one present? (well i see 2...)
- TVDB API issue => they are tweaking for tvdb3 API, hightly possible

**Comment by IIeTp** [comment]
I just tried changing the agent to TVDB, posters appeared, so most likely everything is fine with the API.

**Comment by ZeroQI** [comment]
The agent use the API 1, 2 or 3?
I have proven 1 works and 2 give no poster in the json...

**Comment by IIeTp** [comment]
Великая война [tvdb-153081] - does not work
Великая война [tvdb2-153081] - works!

now i have a little problem. I edited the filebot scanner to pass "seriesname [tvdb-id]" for HAMA, but it turns out that tvdb v1 does not always receive posters. Should I change v1 to v2 or is it a bug in the HAMA agent and will it be fixed?

**Comment by IIeTp** [comment]
> The agent use the API 1, 2 or 3?
> I have proven 1 works and 2 give no poster in the json...

[Plex Media Server\Resources\Plug-ins-77cb9455c\TheTVDB.bundle\Contents\Code\\__init__.py](https://github.com/ZeroQI/Hama.bundle/files/4434587/__init__.py.txt)

did you ask which API uses standard TVDB? I mistakenly decided that you asked about HAMA and did not answer this question. TVDB uses APIv2 and pulls out all the posters ...
I tried changing [tvdb-id] to [tvdb2-id], the poster appeared only in this series. In another series, the poster is still missing.

**Comment by ZeroQI** [comment]
Thetvdb can use API v1, v2 or v3, my agent use v2, and apparently so does the official tvdb agent.
Make sense since v3 is worked on and not finalized if i followed correctly
I know about HAMA, i wrote most of it :D

it makes no sense why tvdb2 mode works and not tvdb mode, both using tvdb v2 api...
Calls to thetvdb should be identical...
Need to compare both update logs and hope i see something different...

**Comment by ZeroQI** [comment]
cache should be depleted for now...
Issue still present? If so, could you attach both tvdb and tvdb2 generated logs?

**Comment by ZeroQI** [comment]
Is the Issue still present? If so, could you please attach both tvdb and tvdb2 generated logs?

**Comment by IIeTp** [comment]
> Is the Issue still present? If so, could you please attach both tvdb and tvdb2 generated logs?

I apologize for the delay in this question. other things appeared. I will try tomorrow to analyze this issue again and give the logs.

**Comment by ZeroQI** [comment]
Hiya, any update?

**Comment by ZeroQI** [comment]
Any update?

**Comment by IIeTp** [comment]
I apologize for the delay. it seems that for english everything worked well. I solved the problem for myself with TVDB (the original agent with modifications to search by id), so I think it's better to close the ticket, maybe the next api will not have such a problem (it is planned to be released within a few months, there will be wider support for alternative series lists: dvd, netflix, etc.)
