### ISSUE TITLE
Series Language Priority not always work

### ISSUE THREAD

**Issue by Akior** [ZeroQI/Hama.bundle#390]
I got ENG series name even only RU is set
![image](https://user-images.githubusercontent.com/5903863/78834065-a11a6a00-79f6-11ea-94f0-e591473a8b66.png)
![image](https://user-images.githubusercontent.com/5903863/78834088-ae375900-79f6-11ea-8814-0bd7ae324f16.png)
![image](https://user-images.githubusercontent.com/5903863/78834150-cc04be00-79f6-11ea-8ff1-e6438fd7f553.png)
The file naming is:
/media/g/Anime/Восьмой сын [tvdb-374787]/Hachi-nan_tte_Sore_wa_Nai_deshou!_[01]_[AniLibria_TV]_[WEBRip_1080p].mkv

Same problem with Interspecies Reviewers (New Anime) and Clannad (Old Anime) but NOT with Arte or Listeners or else. 

Is there tvdb problem ?

logs:
[Восьмой сын [tvdb-374787].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4452911/tvdb-374787.agent-update.log)
[Восьмой сын [tvdb-374787].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/4452912/tvdb-374787.agent-search.log)

**Comment by ZeroQI** [comment]
End of update Logs
[=] title                          Sources: (TheTVDB)                                                     Inside: '['TheTVDB', 'AniDB', 'TheMovieDb']'  Value: 'The 8th Son? Are You Kidding Me?'
[=] title_sort                     Sources: (TheTVDB)                                                     Inside: '['TheTVDB']'  Value: 'The 8th Son? Are You Kidding Me?'

Thetvdb logs:
common.LoadFile() - File cached locally - Filename: 'TheTVDB/json/374787/series_en.json', Age: '0.01 days', Limit: '6 days', url: 'https://api.thetvdb.com/series/374787?en'
[ ] language_rank: 0
[ ] title: The 8th Son? Are You Kidding Me?
[ ] original_title: The 8th Son? Are You Kidding Me?
common.LoadFile() - File cached locally - Filename: 'TheTVDB/json/374787/series_ru.json', Age: '5.51 days', Limit: '6 days', url: 'https://api.thetvdb.com/series/374787?ru'
[ ] language_rank: 1
[ ] title: The 8th Son? Are You Kidding Me?
[ ] original_title: The 8th Son? Are You Kidding Me?

https://thetvdb.com/series/the-eighth-son-that-cant-be-right gives russian titles yet the API v1 link does not:

https://thetvdb.com/api/A27AD9BE0DA63333/series/374787/en.xml
`<SeriesName>The 8th Son? Are You Kidding Me?</SeriesName>`

https://thetvdb.com/api/A27AD9BE0DA63333/series/374787/ru.xml
`<SeriesName>The 8th Son? Are You Kidding Me?</SeriesName>`

First aired 2020-04-02????
As thetvdb doesn't give russian titles in the API, not the agent at fault.

**Comment by EndOfLine369** [comment]
@ZeroQI, this actually looks like a bug. You can get the v2 response from their API swagger test site.

![image](https://user-images.githubusercontent.com/16750699/78845580-8fbd6780-79ce-11ea-9584-c17b294a8373.png)

**Comment by EndOfLine369** [comment]
@Akior, can you please provide the file "TheTVDB/json/374787/series_ru.json"

**Comment by Akior** [comment]
Here.
[series_ru.zip](https://github.com/ZeroQI/Hama.bundle/files/4454315/series_ru.zip)

**Comment by ZeroQI** [comment]
Title is in English...I think you pull meta when the title was not updated yet in thetvdb
- delete json cache
- try to match manually for a serie called "clear-cache" but cancel
- refresh metadata

**Comment by Akior** [comment]
I try delete json cache and It works.
Thank you.
