### ISSUE TITLE
How can I sync latest metadata from AniDB?

### ISSUE THREAD

**Issue by BananaWanted** [ZeroQI/Hama.bundle#391]
I've contributed a bunch of changes directly on `anidb.net`, so I'd like the changes to be sync to my Plex library. I've tried `Refresh All Metadata` but it didn't work.

For now I think the following steps should do the job:
1. Go to `https://github.com/ScudLee/anime-lists` and ask them to update `animetitles.xml`, as said in their `README.md`.
2. After `animetitles.xml` updated, manually invalidate the cached files in my Plex HAMA installation. (though I don't know how I could do this)
3. Run `Refresh All Metadata` from Plex web UI

I'm wondering if there's an easier way to do this. Either asking `anime-lists` or invalidate cache are not easy. Since the whole process takes so long, given Anidb updates quite frequently, the local metadata is easily got out-dated.

**Comment by ZeroQI** [comment]
why step 1 ? we use anidb for the file i believe
- delete the file cache but the anidb title database in hama agent data folder/anidb...
- match searching for "clear-cache" then cancel
- refresh metadata

**Comment by BananaWanted** [comment]
Thank you for reply

Following your instructions, I removed `Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/AniDB` and then `Refresh All Metadata`, everything are now synced nicely.

There's no need for those complicated steps. I understood the way Hama working in a wrong way... I thought it's using anime-lists as part of metadata source.

Again thank you for helping

**Comment by ZeroQI** [comment]
It is using AnimeLists master file to cross reference anidb to tvdb but the title file is actually a copy of AniDB's title file...
