### ISSUE TITLE
Collections issues, lost again

### ISSUE THREAD

**Issue by hergonoway** [ZeroQI/Hama.bundle#392]
Hello, 

still don't known what sorcery is behind the collection mecanism, but here's my settings : TM Collections : AniDB, AnimeLists, TheMovieDb

anime concerned : 
- Saenai Heroine no Sodatekata [TV Series][anidb-10538]
- Saenai Heroine no Sodatekata Flat [TV Series][anidb-11221]

should be both in a collection,  11221 is a direct sequel from 10538. There's no collection in either 11221 or 10538. Apparently tvdbid is mandatory for Hama and should be in scudlee's listing in order for Hama to create the collection... correct me if I'm wrong because I still don't understand how collection system really works. (Why tvdbid ? what about my settings, there no tvdb mention in it, what does it implies , plouf I'm lost (ノ#-_-)ノ ミ　┴┴)

in "https://raw.githubusercontent.com/ScudLee/anime-lists/master/anime-list.xml" these 2 entries got tvdbid="281275" : 
```
  <anime anidbid="10538" tvdbid="281275" defaulttvdbseason="1">
    <name>Saenai Heroine no Sodatekata</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-1;</mapping>
      <mapping anidbseason="1" tvdbseason="1">;2-1;3-2;4-3;5-4;6-5;7-6;8-7;9-8;10-9;11-10;12-11;13-12;</mapping>
    </mapping-list>
  </anime>
```
and there
```
<anime anidbid="11221" tvdbid="281275" defaulttvdbseason="2">
    <name>Saenai Heroine no Sodatekata Flat</name>
  </anime>
```
and even the movie
```
  <anime anidbid="13626" tvdbid="281275" defaulttvdbseason="0" episodeoffset="2">
    <name>Saenai Heroine no Sodatekata Fine</name>
  </anime>
```

from TVDB side everthing seems correct : https://www.thetvdb.com/series/saekano-how-to-raise-a-boring-girlfriend

please tell me which log should help I dunno which one to pick for this issue.

**Comment by ZeroQI** [comment]
The very TSEM letters before each field in Hama setting means Track Series Episodes Movies
- in this case T--M means Track and Movies only ...

"Local, AniDB, TheMovieDb, AnimeLists" are the default sources for collections
- AnimeLists have a separate collection list tag for Movies [https://github.com/ScudLee/anime-lists/blob/master/anime-movieset-list.xml] which Hama complements with series based on thetvdbid. Your series do not exist there
- Local would create a collection if series are in a grouping folder (cannot tell from information given)
- AniDB give a collection field, but not for this series
- TheTVDB part could have given if coded a collection field to anidb numbered series but the field would have to be the same for both series when called separately but using the tvdbid would be weird, meaning any anidb series would be in a collection named after the tvdbid for example. If using the library setting to not show items in collection that's a useless folder depth in the Gui for no reason... I believe it is better not create a collection than putting wrong collections everywhere for that reason, and that i did not code a tvdbid based collection...

Hama creates series specific logs which would show
- in which sources the collection is present
- if AnimeLists find the id in movie collection, if they supplemented to it the tvdb id
- You chose not to include Logs. Not cool, I have to lose time when i specifically make readable logs to spare time...

My advice: in Plex web GUI for both series, type Saekano in collection field...
No other metadata system has collection for series to my knowledge, or movies+series libraries, supporting anidb+tvdb numbering seamlessly, etc...

**Comment by hergonoway** [comment]
> You chose not to include Logs. Not cool, I have to lose time when i specifically make readable logs to spare time...

Come on, I said "please tell me which log should help I dunno which one to pick for this issue." 
in the doubt, I've picked up the log there : "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/Anime" dunno if there're the best, but these are logs : 
- [Saenai Heroine no Sodatekata [TV Series][anidb-10538].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4486196/Saenai.Heroine.no.Sodatekata.TV.Series.anidb-10538.agent-update.log)
- [Saenai Heroine no Sodatekata Flat [TV Series][anidb-11221].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4486197/Saenai.Heroine.no.Sodatekata.Flat.TV.Series.anidb-11221.agent-update.log)

We can see in 10538 : 

```
--- AniDBTVDBMap --------------------------------------------------------------------------------------------------------------------------------------------
[+] AniDBid: 10538, TVDBid: 281275, defaulttvdbseason:   1, offset:   0, name: Saenai Heroine no Sodatekata
    - season: [ 1],           [ 0], range:       [000-000], offset:   0, text: 1-1
    - season: [ 1],           [ 1], range:       [000-000], offset:   0, text: 2-1;3-2;4-3;5-4;6-5;7-6;8-7;9-8;10-9;11-10;12-11;13-12
             -----          ------
             10538          281275
[ ] collection: TVDBid '281275' is not part of any collection
[ ] studio: 
```
I suppose : "TVDBid '281275' is not part of any collection" is the thing that makes that there's no collection. 

I don't understand where's the issue, it's very similar to (https://github.com/ZeroQI/Hama.bundle/issues/382) 

where you said : 
> [ ] collection: TVDBid '' is not part of any collection
> There is no tvdb id associated, limit the possibilities..
> It uses the same tvdbid to create collection, not every id related to each other
> Dragon ball will not create collections with DBZ despite being related, we have to draw the line somewhere...

the fix was to update https://raw.githubusercontent.com/ScudLee/anime-lists/master/anime-list-master.xml but in this case there's explicitely `tvdbid="289884"` for both entries.  




==== side note ===
**also** : you said "AniDB give a collection field, but not for this series", I may be wrong but (I use a lot anidb), the term "collection" in anidb, with this specific name, is only related to music, it list singles, albums, etc. It's not the same meaning as collections in Plex I think (ie saga). If you search all "collections" in anidb (https://anidb.net/collection/?do.search=1), types of result are only "single" or "album".

**Comment by ZeroQI** [comment]
The issue with collections is that is it a field per movies or per series.
- if you want to rename it, you have to rename every collection field in all concerned medias
- also, each time the agent is called, it has to find the same collection name regardless of the series in that collection it is called for
- there is a collection field in the xml i get fron AniDB http api, not sure if populated but i support its inclusion

These are the right logs.
- There is no movies collection for this anime as https://github.com/ScudLee/anime-lists/blob/master/anime-movieset-list.xml  does not list a movie collection, not even for Euphonium that has 4 movies
- Euphonium collection was given by "AnimeLists" indeed so your logic is good, the same tvdbid no longer create a collection for series sharing the same tvdbid but it used to
`[=] collections              ( 1)  Sources: (AnimeLists), TheMovieDb, AniDB                               Inside: '['AnimeLists', 'TheMovieDb']'  Value: '['Sound! Euphonium Collection']'`

Since you documented precisely, here is the code responsible:
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/AnimeLists.py line 224
```
  ### Update collection/studio
  TVDB_collection, title, studio = [], '', ''
  for anime in AniDBTVDBMapFull.iter('anime') if AniDBTVDBMapFull and TVDB_winner.isdigit() else []:
    if anime.get('tvdbid',  "") == TVDB_winner:
      TVDB_collection.append(anime.get("anidbid", ""))
      if anime_core(anime)[3]:  #[3]==is_primary_series
        title = AniDB.GetAniDBTitle(AniDB.AniDBTitlesDB.xpath('/animetitles/anime[@aid="{}"]/title'.format(anime.get("anidbid", ""))))[0]  #returns [title, main, language_rank]
        studio = GetXml(anime, "supplemental-info/studio")
  if len(TVDB_collection)>1 and title:  # Require that there be at least 2 anidb mappings for a collection
    Log.Info("[ ] collection: TVDBid '%s' is part of collection: '%s', related_anime_list: %s" % (TVDB_winner, SaveDict([title + ' Collection'], AnimeLists_dict, 'collections'), TVDB_collection))
  else:  Log.Info("[ ] collection: TVDBid '%s' is not part of any collection" % TVDB_winner)
  Log.Info("[ ] studio: {}".format(SaveDict(studio, AnimeLists_dict, 'studio')))
```
Here are the mappings anidb to tvdb. Logs help tremendously figuring mappings used.
```
 --- AniDBTVDBMap --------------------------------------------------------------------------------------------------------------------------------------------
[+] AniDBid: 11221, TVDBid: 281275, defaulttvdbseason:   2, offset:   0, name: Saenai Heroine no Sodatekata Flat
             -----          ------
             11221          281275
[ ] collection: TVDBid '281275' is not part of any collection
[ ] studio: 
```

```
--- AniDBTVDBMap --------------------------------------------------------------------------------------------------------------------------------------------
[+] AniDBid: 10538, TVDBid: 281275, defaulttvdbseason:   1, offset:   0, name: Saenai Heroine no Sodatekata
    - season: [ 1],           [ 0], range:       [000-000], offset:   0, text: 1-1
    - season: [ 1],           [ 1], range:       [000-000], offset:   0, text: 2-1;3-2;4-3;5-4;6-5;7-6;8-7;9-8;10-9;11-10;12-11;13-12
             -----          ------
             10538          281275
[ ] collection: TVDBid '281275' is not part of any collection
[ ] studio: 
```
Code analysis:
- AniDBTVDBMapFull is scudlee mapping file+local mapping file if any
- TVDB_winner is the tvdbid found for that series = 281275
- for every tvdbid matching TVDB_winner [281275], the anidbid goes in TVDB_collection
- if you have more than 1 item in TVDB_collection and a title meaning it found a primary series defined as `True if defaulttvdbseason == '1' and episodeoffset == '0' and s1_mapping_count == 0 else False`.
- that is the issue, you do have two series with tvdbid 281275, the second is defaulttvdbseason == '1' and episodeoffset == '0' HOWEVER s1_mapping_count is not empty. This was a failsafe by EndOfLine369 since i am not the only coder, and was to avoid something but not sure what

Action possible
- Do nothing
- workaround: use 'local' source for the collection and put series together in a grouping folder and they will be in a collection named like the grouping folder. Less ideal for compatibility with some tools requiring all movies/series folders at root level though...
- Fix by removing ' and s1_mapping_count == 0' line 96 from [def anime_core(anime):] to allow more series to be considered primary, filling title variable, and using it as collection string

@EndOfLine369 Can you remember what the ' and s1_mapping_count == 0' failsafe was meant to avoid?

**Comment by hergonoway** [comment]
well I don't like doing nothing :) or adding the collection manually in the ui (because multi server), also Local system seems about right but I dunno the behavior with lambda or other things than hama, also I'm using adbren's script to populate my folders daily, and manual top folder is going to be difficult to handle. For me, adding the entry to https://github.com/ScudLee/anime-lists/blob/master/anime-movieset-list.xml sound  the best solution right ? 

about removing ' and s1_mapping_count == 0' line 96, I'm not at ease with this solution since the collection for these specific 2 animes is really really obvious (there're 2 shows, one is prequel is other one a direct sequel), I'll wait the feedback from @EndOfLine369 about that

**Comment by ZeroQI** [comment]
The issue with the movie collection is that the name is accurate. Can't have a collection of a single movie.
We will need to tweak the test and EndOfLine369 feedback's would be welcome

**Comment by EndOfLine369** [comment]
@ZeroQI 
https://github.com/ZeroQI/Hama.bundle/commit/8581975837a48f9ce3e045b7ce0d568bfdc50037

**Comment by EndOfLine369** [comment]
@ZeroQI, https://github.com/ZeroQI/Hama.bundle/commit/8581975837a48f9ce3e045b7ce0d568bfdc50037 & https://github.com/ZeroQI/Hama.bundle/commit/784e0337fba2abc52fb42d433048e4f2491aad5b

Problem here is we have a s1->s1 mapping that is actually remapping to s1e1 `<mapping anidbseason="1" tvdbseason="1">;2-1;...` where the assumption is that if there is any remapping of s1->s0/s1 its not the primary.

I _**think**_ we would have to check for `"mapping-list/mapping[@anidbseason='1'][@tvdbseason='1'][text()[contains(lower-case(.), '-1;')]]"` in combination...

**Comment by EndOfLine369** [comment]
Done

**Comment by hergonoway** [comment]
hello, just updated Hama, Saenai Heroine no Sodatekata [anidb-10538] & Saenai Heroine no Sodatekata Flat [anidb-11221] now generate a collection for the 2 shows as expected.

**Comment by ZeroQI** [comment]
Thanks for the change and the test to you both.

**Comment by hergonoway** [comment]
@ZeroQI  & @EndOfLine369  : I'm not reopening this issue ( :p ) but got currently an side  exchange where you may give your vision : [Scudlee's issue 327](https://github.com/ScudLee/anime-lists/issues/327)
