### ISSUE TITLE
Add support for OpenSubtitles.org

### ISSUE THREAD

**Issue by ArKaGarCa** [ZeroQI/Hama.bundle#393]
I recently noticed that the AniDB Plugin indeed has support for the download of subtitles from OpenSubtitles.org. Could it be added to this plugin as well? I don't want to depend solely on AniDB as HAMA has many other cool features that AniDB lacks.

**Comment by ZeroQI** [comment]
"I recently noticed [where?] that the AniDB Plugin [which?] indeed has support [source] for the download of subtitles from OpenSubtitles.org" 
- https://forums.plex.tv/t/anidb-metadata-agent/15015 which is the other AniDB metadata agent for Plex doesn't support that
- on Plex? Kodi? emby? Source please as download of subtitles always was done by external plugin IMO...

"Could it be added to this plugin as well?" 
=> Why would that be better than a dedicated subtitle downloader like the excellent Sub-Zero [https://github.com/pannal/Sub-Zero.bundle]?

"I don't want to depend solely on AniDB as HAMA has many other cool features that AniDB lacks."
- AniDB is a metadata source
- HAMA is a Plex metadata agent using AniDB as one of the sources
- none of which support subtitles (although AniDB could list external subtitle info alongside media file info)
- How is it linked in any way to Hama or AniDB?

**Comment by ZeroQI** [comment]
Closing temporarily. Feel free to reply if i missed something

**Comment by ArKaGarCa** [comment]
Hi! First of all,I'm sorry for the lack of info on my first comment. I'll try to give all the info you mentioned on your response here. Also, I apologize in advance for any error that this may have, English is not my native language and I'm still not used to using it fluently.

As you mentioned, the AniDB plugin I had installed on my plex server was the one that was on plex forums. I don't know if it was a bug, but on the agents tab, I could select OpenSubtitles for AniDB Agent on the shows tab. But I didn't use it because Hama was simply better (It got more data from more sites). After noticing that Hama didn't have support for downloading subtitles, I thought it could be done and left my comment here.

After reading your comment I discovered Sub-Zero, which I'm in the process of installing as I write this. Thanks a lot for showing me this plugin, it seems promising and a lot better than the OpenSubtitles one.

**Comment by ZeroQI** [comment]
The agent show a single line there so is not part of the agent, Being AniDB or Hama...
The primary agent can accept other agents, maybe Hama can be improved there to allow the subtitles agent. Will check Anidb permissions there but the secondary subtitles agent should be programmed in a way it doesn't require enablement from primary agents, like the local media assets agent...
