### ISSUE TITLE
Episode language priority setting doesn't work

### ISSUE THREAD

**Issue by BUEKO** [ZeroQI/Hama.bundle#395]
All items do not apply as the language priority setting in the TVDB.

![image](https://user-images.githubusercontent.com/51087093/81072104-9fbe5d80-8f20-11ea-9a40-75eda653f1df.png)

As shown above, HAMA is set in the order of ko, jp, and en.
If there is no Korean data, I would like to adopt Japanese data.

![image](https://user-images.githubusercontent.com/51087093/81072133-a947c580-8f20-11ea-842b-38428e74636f.png)

However, if there is no Korean data, the results are replaced by English information without reading the japanese data.
Is there a solution?

[87501.zip](https://github.com/ZeroQI/Hama.bundle/files/4581034/87501.zip)

**Comment by ZeroQI** [comment]
i really need the series logs ing the 'agent data folder/logs' folder, so very close to where you got these ('agent data folder/TheTVDB/...' )

**Comment by BUEKO** [comment]
Thank you for your cooperation.
Here's the log.

[_Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/4590343/_Logs.zip)

**Comment by ZeroQI** [comment]
Series 'けいおん!'
- TheTVDB s01e01-14  have japanese titles
- AniDB s01e01-12 have japanese titles
- note: maybe 'main, en' would be better?

metadata.seasons[ 1].episodes[  1]
[?] rank: 1, source_title: TheTVDB, title: "廃部!"
[x] title                          Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB', 'AniDB']'  Value: '廃部!'

metadata.seasons[ 1].episodes[  2]
[?] rank: 1, source_title: TheTVDB, title: "楽器!"
[x] title                          Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB', 'AniDB']'  Value: '楽器!'

Clearly the agent series specific logs show it found the right title...
The TV Series title is updated in logs (important or NO metadata gets updated), so Plex should update the title given...
Either
- fields are locked
- there is a secondary metadata agent overwritting everything (Lambda with metadata source set as local)
- you have a database corruption 
- "All items do not apply as the language priority setting in the TVDB" = WRONG. Only anidb3 log impacted

**anidb3 ep titles are in English**

[X]    s1e1 s01e001 anidbid:         air_date: 2009-04-03 abs_number: 1, title: Abolition of the Club!
 - [ ] summary: 
 - [1] language_rank: 0, language:   ko, title: Abolition of the Club!

Thetvdb has korean titles (doesn't mean the API return them though, we need to check, there are bugs at times as they are developing v3 API still if i am correct)
- https://thetvdb.com/series/k-on/episodes/494711

Korean titles are present (and in english) according logs
We need to check the json files
- episodes_page1_ko.json have english titles
- individual episode json files for japanese have english titles

common.LoadFile() - file cached - CacheTime: 'Tue May  5 04:24:03 2020', Limit: 'Wed May  6 04:24:03 2020', url: 'https://api.thetvdb.com/series/87501/episodes?page=1', Filename: 'TheTVDB/json/87501/episodes_page1_ko.json' file_valid: 'True'

Please delete that cached file and refresh metadata

**Comment by BUEKO** [comment]
/Plug-in Support/Caches/com.plexapp.agents.hama
/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/TheTVDB/json

Delete all cache and metadata,


![image](https://user-images.githubusercontent.com/51087093/81751502-8605b300-94ea-11ea-9662-e02e02d5a766.png)

And I changed to [main, en]


![image](https://user-images.githubusercontent.com/51087093/81751516-8ef68480-94ea-11ea-8ee7-19850b825738.png)


And I changed it to anidb4 when scanning ASS.

Last, Refresh metadata after re-running the server...




![image](https://user-images.githubusercontent.com/51087093/81751534-99188300-94ea-11ea-9781-f20d509ca3c3.png)
![image](https://user-images.githubusercontent.com/51087093/81751541-9cac0a00-94ea-11ea-8d2c-b66c28ddb972.png)
![image](https://user-images.githubusercontent.com/51087093/81751551-9f0e6400-94ea-11ea-888b-736152bed52d.png)


Season 1 has been updated in Korean.
However, season 2 and Special, which do not have Korean data, are still.
I want Japanese next to Korean.

The same result comes from designating Episode language priority as [ko, ja, en]


[87501.zip](https://github.com/ZeroQI/Hama.bundle/files/4618742/87501.zip)

[_Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/4618770/_Logs.zip)
(I tried after deleting Logs, so there were no new logs recorded by the file name of [けいおん!].)

**Comment by ZeroQI** [comment]
Seem like TheTVDB API v2 returns wrong language
- web page shows ko titles
- episode_2374481_ko.json season 2 title ep is in english...
- Same for episodes_page1_ko.json season 2 eps...

If you delete the *.json files inside 87501 folder AND custom match a series by searching for the title "clear-cache" then cancel, then refresh metadata, if the json files still have english titles the issue is likely with the TVDB API...

**Comment by EndOfLine369** [comment]
![image](https://user-images.githubusercontent.com/16750699/82102958-d7729580-96d6-11ea-8f35-9da516f11f59.png)

**Comment by ZeroQI** [comment]
@EndOfLine369 my brain is pretty dead lately... You are right and as suspected, TheTVDB API gives 'ko' titles in English so not agent related....

**Comment by ZeroQI** [comment]
Third party issue, TheTVDB has to be asked to fix it
