### ISSUE TITLE
pt-BR language support

### ISSUE THREAD

**Issue by lunks** [ZeroQI/Hama.bundle#397]
Could support for pt-BR episode names be added? AniDB and TheTVDB seem to have them but only pt (Portugal) support is available.

**Comment by ZeroQI** [comment]
You are confusing me...
It should be handled already if anidb or TheTVDB supports it
Which of AniDB and/or TheTVDB have episodes names in pt-br?

**Comment by lunks** [comment]
I assumed because of https://github.com/ZeroQI/Hama.bundle/blob/fb5cfd515edbd3cf2186262d14ebc05a0b97c5ee/Contents/Code/__init__.py#L159-L169 that it didn't have support for it. I'll give it a shot and report back.

**Comment by lunks** [comment]
Happy to report it works. Thanks!
