### ISSUE TITLE
[anidb] Re:Zero - Other Episodes

### ISSUE THREAD

**Issue by DJScias** [ZeroQI/Hama.bundle#398]
Hello there,

Been trying to get Re:Zero working but apparently there's the normal 25 episodes AND the new director's cut 13.

On [AniDB](https://anidb.net/anime/11370) they are used as the Other episodes, numbering from O1-O13. All of them have accompanying titles and metadata.

However when I put them in the folder `Zero kara Hajimeru Isekai Seikatsu [anidb-11370]` it produces this in Specials:
![image](https://user-images.githubusercontent.com/439655/82554611-919a4f00-9b66-11ea-9b7a-89d5e887b657.png)

I've named them with O's and the metadata exists on AniDB so I'm not sure what's going on.

Below I've accompanied the, mandatory, scanner logs. If more are required, do let me know:
[Zero kara Hajimeru Isekai Seikatsu [anidb-11370].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4662178/Zero.kara.Hajimeru.Isekai.Seikatsu.anidb-11370.filelist.log)
[Zero kara Hajimeru Isekai Seikatsu [anidb-11370].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4662179/Zero.kara.Hajimeru.Isekai.Seikatsu.anidb-11370.scanner.log)

Thanks in advance.

**Comment by ZeroQI** [comment]
Moved the bug report to Hama for you (transfer option on the right towards the bottom)
Never tested the Oxx much as i never had the occasion
Go in agent data folders /  Logs / Library name / series.update.log and i need the log for the series
Thanks for the donation

**Comment by DJScias** [comment]
Thanks for the transfer.

I've actually checked that folder before, but for some bizarre reason the agent hasn't been creating new logs so the Zero one is missing.
![image](https://user-images.githubusercontent.com/439655/82586897-95df6000-9b98-11ea-95f3-0b2721e1acce.png)


Will see if I can figure out why it's not creating any new ones and then get back to you.

**Comment by ZeroQI** [comment]
Maybe update metadata and check hama general logs, and check in parent folder just in case it couldn't get the library file to get the library name

**Comment by purposelycryptic** [comment]
Not sure if it's related, but those episodes are weird on AniDB as well. They are simultaneously considered as both "O" episodes and regular double episodes; if you add them to your MyList, both are registered, and if you use AniAdd, it considers them as double episodes (except for O1, since the original was already a double-length), i.e., O2 is also simultaneously considered E02-E03, etc.

Not sure if that helps/contributes anything, but I remember having issues getting the metadata for those too.

**Comment by DJScias** [comment]
Hello there,

I removed the folder and re-added it just to be certain and it didn't generate an actual named log but instead it chose to go with `_unknown_folder`.

It still didn't resolve any metadata for the Other episodes on Plex, unfortunately.

Regardless, here's the `agent-search` and `agent-update` log respectively that's generated specially for Re:Zero's folder.
[_unknown_folder.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/4671679/_unknown_folder.agent-search.log)
[_unknown_folder.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4671677/_unknown_folder.agent-update.log)


If there's anything more you need, feel free to ask.

**Comment by ZeroQI** [comment]
You're the only one using Oxx to be honest
- AniDB has info on Oxx: http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=11370
- AniDB log output doesn't list Oxx eps (epno type="6") so code needs changing

After checking https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/AniDB.py
- line 319 is not executed
- line 269 contain Oxx eps? 71 ep entries, 58 with logs output

Not sure why it doesn't load all eps in the loop

**Comment by DJScias** [comment]
That's weird.

Is there a specific check you would want me to do here?

**Comment by ZeroQI** [comment]
Line 269
`        for ep_obj in sorted(xml.xpath('episodes/episode'), key=lambda x: [int(x.xpath('epno')[0].get('type')), int(x.xpath('epno')[0].text if x.xpath('epno')[0].text.isdigit() else x.xpath('epno')[0].text[1:])]):`
Could it be that by sorting per number removing the letter, it removes the dupplicate numbers (OP1, O1, SP1)?
`<epno type="6">O1</epno>`
Am bad with lambda sorting function...

**Comment by ZeroQI** [comment]
Though about this simplification, but needs to be tested:
`for ep_obj in sorted(xml.xpath('episodes/episode'), key=lambda x: [int(x.xpath('epno')[0].get('type')), x.xpath('epno')[0].text]:`

**Comment by DJScias** [comment]
Do you want me to replace the line you put in your previous post (3 days ago) with this new one? Or how would you like me to test it?

**Comment by ZeroQI** [comment]
If you could do that, that would be great. I do believe because the sort string in the comparison string is identical it did overwrite the info, so it should solve it. If not, let me know

**Comment by ZeroQI** [comment]
same in logs, not listed at all.
It is meant per source to list all eps and show '[X]' in front if the file is present and '[ ]' if not...
Net to reproduce on my computer and modify the code live

**Comment by sven-7** [comment]
@ZeroQI have you looked to see if TheTVDB's API is including metadata for their "other" equivalent with their new alternate orders? 

https://thetvdb.com/series/re-zero-starting-life-in-another-world/seasons/alternate/1

**Comment by ZeroQI** [comment]
@sven-7 Discussed in https://github.com/ZeroQI/Hama.bundle/issues/401

> Another possibility would be a new tvdb6 DVD mode to convert TheTVDB DVD numbering to TVDB numbering at scanner level and the agent will receive a normal tvdb mode, and would not need modification. I would include it if somebody made it (using tvdb5 as base, for example).
> 
> Adding comment for future reference, in case the demand for DVD numbering rises (and if TVDB API v3 allows it as its release is more or less imminent)

**Comment by avluis** [comment]
Hey there! Just wanted to throw my input in here as I have this series and I'm also using AniDB's other (O) prefix for the director's cut.
Below are two images showing how my files are named and how they are eventually added by Plex.

![re-zero-o eps 2020-07-07 075658](https://user-images.githubusercontent.com/875593/86777984-d5b6b580-c027-11ea-94f3-2158ea421ce2.png)
![re-zero-o eps plex 2020-07-07 075731](https://user-images.githubusercontent.com/875593/86777995-d94a3c80-c027-11ea-8998-0a3ae3cc736a.png)

My files are typically downloaded and scanned early enough to pick up either no metadata (which results on them not being added to the anime directory); once AniDB has the entry, they are moved and renamed accordingly.
There will be situations where the entry is not complete (or the creq not yet approved/pending) so the files may not be named properly until then.
For example, O13 is the cut of E24-E25 so it ended up with that until I renamed it manually today while testing the issue seen here (this is with the latest scanner and agent from a few hours ago):
![re-zero-o eps O13 2020-07-07 080034](https://user-images.githubusercontent.com/875593/86778861-dd2a8e80-c028-11ea-9f3c-99bb70f93f9a.png)
I've edited enough metadata in AniDB to know how their system works so I expected the episode numbers to jump around for this series.

I need to perform a quick Plex Dance(tm) to force a metadata refresh so I'll post logs in a few; hopefully, there is some info to go off from to assist with this.

**Comment by ZeroQI** [comment]
ANIDB_RX-4 for "Ox - title" named eps so starting 401+, scanner put eps at the right place
Agent AniDB part however consider the files not present in Plex/disk:
```
[ ] s0e101 => s0e  0 epNumType: 3
[ ] s0e102 => s0e  0 epNumType: 3
[ ] s0e151 => s0e  0 epNumType: 3
[ ] s0e152 => s0e  0 epNumType: 3
[ ] s0e153 => s0e  0 epNumType: 3
[ ] s0e201 => s0e  0 epNumType: 4
[ ] s0e202 => s0e  0 epNumType: 4
[ ] s0e401 => s0e  0 epNumType: 6
[ ] s0e402 => s0e  0 epNumType: 6
[ ] s0e403 => s0e  0 epNumType: 6
[ ] s0e404 => s0e  0 epNumType: 6
[ ] s0e405 => s0e  0 epNumType: 6
[ ] s0e406 => s0e  0 epNumType: 6
[ ] s0e407 => s0e  0 epNumType: 6
[ ] s0e408 => s0e  0 epNumType: 6
[ ] s0e409 => s0e  0 epNumType: 6
[ ] s0e410 => s0e  0 epNumType: 6
[ ] s0e411 => s0e  0 epNumType: 6
[ ] s0e412 => s0e  0 epNumType: 6
[ ] s0e413 => s0e  0 epNumType: 6
```
The dual way mapping seem buggy, unless the files are NOT in TheTVDB, or not in mapping file, therefore cannot map them...

The unique id is "tvdb-305089" qhereas the files shows anidb3 forced id... 
Did you manualy forced a TVDB id and therefore it cannot recognise anidb specials as it follows TheTVDB specials convention ?

**Comment by Renari** [comment]
I've ran into this issue as well with slightly different results.

![image](https://user-images.githubusercontent.com/1839179/87273615-98c74480-c4a7-11ea-9da5-c0aa34232585.png)

As you can see the first 3 episodes received metadata. My filenames are like this `Re Zero 2020 - Season 1 O1.mkv`. All of the other files are similar to your results though where they obtain none of the metadata. I originally thought this was an issue with having `en, x-jat` as the preferred episode language order but it appears that is not the case.

**Comment by ZeroQI** [comment]
Would you be able to attach the series log please?

**Comment by Renari** [comment]
[ReZero Kara Hajimeru Isekai Seikatsu.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/4911282/ReZero.Kara.Hajimeru.Isekai.Seikatsu.filelist.log)
[ReZero Kara Hajimeru Isekai Seikatsu.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/4911283/ReZero.Kara.Hajimeru.Isekai.Seikatsu.scanner.log)
[ReZero Kara Hajimeru Isekai Seikatsu.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4911284/ReZero.Kara.Hajimeru.Isekai.Seikatsu.agent-update.log)

**Comment by Renari** [comment]
Following @avluis 's example I tried putting the `Oxx` identifier out front but my results were much different than theirs.
![image](https://user-images.githubusercontent.com/1839179/87288773-c7eead80-c4c9-11ea-86ea-03c98e1337cf.png)

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/AniDB.py
Line 263 for the ep loop
`for ep_obj in sorted(xml.xpath('episodes/episode'), key=lambda x: [int(x.xpath('epno')[0].get('type')), int(x.xpath('epno')[0].text if x.xpath('epno')[0].text.isdigit() else x.xpath('epno')[0].text[1:])]):`

Maybe shorten to:
`for ep_obj in sorted(xml.xpath('episodes/episode'), key=lambda x: [int(x.xpath('epno')[0].get('type')), int(x.xpath('epno')[0].text]):`

Anidb logs show 61 eps, 81 in XML, only the first 3 Others (s00e401-403) are found
From 404 they are not found. That is not funny....
it seems it doesn't loop all episode entities as every 'continue' display a line in logs beforehands, no break

Troubleshooting notes
- Need to output the number of episodes in the loop and see if some missing indeed and which part of the code above failed
Maybe output EpNum and EpNumType for each entry too...
- Compare with and without sorted to check if sorted mess things up...

**Comment by Renari** [comment]
I feel this is actually a problem with 403 because the metadata grabbed for that entry is incomplete. I'll try to look into it this weekend.

**Comment by ZeroQI** [comment]
I don't know if it crash in that loop or mangle the list of ep medatada in the initial part...
If you get half metadata for one ep and there was more metadata avail, then that's a good track to follow

**Comment by EndOfLine369** [comment]
No issue seen in replication attempt.
HAMA is working as expected.

![image](https://user-images.githubusercontent.com/16750699/88461476-659e9100-ce69-11ea-8b33-92bb391adeff.png)
![image](https://user-images.githubusercontent.com/16750699/88461520-d2b22680-ce69-11ea-9971-008687a5bb55.png)

**Comment by EndOfLine369** [comment]
This is probably an issue in your cached file for AniDB since the series ended years ago "2016-09-19".
Your cache file is `Age: '180.46 days'` old and will only re-download at `Limit: '278 days'` due to series end date.
`common.LoadFile() - File cached locally - Filename: 'AniDB/xml/11370.xml', Age: '180.46 days', Limit: '278 days', url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=11370'`

These "Other" "Director`s Cut" entries were only just aired so only just added to the series.
![image](https://user-images.githubusercontent.com/16750699/88461645-ea3ddf00-ce6a-11ea-9222-3d435c3f227d.png)

Check your `'AniDB/xml/11370.xml'` local cache file and you will probably see only episodes up to 403 in the xml. Attach it here please. Then delete the file and refresh metadata.

**Comment by Renari** [comment]
I looked for those files, I have two instances of them.

```
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/AniDB
```
[11370.zip](https://github.com/ZeroQI/Hama.bundle/files/4976990/11370.zip)

```
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/AniDB/xml
```
[11370.zip](https://github.com/ZeroQI/Hama.bundle/files/4976991/11370.zip)

**Comment by EndOfLine369** [comment]
First one is old HAMA version path. Second one confirms its your cache. Nothing after episode 3.
```
<episode id="225907" update="2020-01-05">
<epno type="6">O3</epno>
<length>50</length>
<airdate>2020-01-15</airdate>
<title xml:lang="en">Director`s Cut: Episode 3</title>
</episode>
</episodes>
</anime>
```

Remove both & refresh metadata and you should be sorted.

**Comment by ZeroQI** [comment]
Never though about specials for ended series.
The long cache time can do harm there...
Maybe we should put 1 to 3 month max...

**Comment by DJScias** [comment]
Hello there,

Are there any specific steps I should take so far? Or is this still something that's been looked at?

**Comment by ZeroQI** [comment]
"Remove both & refresh metadata and you should be sorted."

**Comment by DJScias** [comment]
Only had one file myself (in the `xml` directory).

Removed it and refreshed metadata:
![image](https://user-images.githubusercontent.com/439655/88487594-eb642e80-cf86-11ea-9d3a-8b35ef48087a.png)

All seems well now, thank you!

What exactly was the issue then? Too old cached metadata ignored all the Agent changes you guys did until now?

**Comment by ZeroQI** [comment]
I made an adaptive algorythm that do not refresh much when a series is completed since some years...
Your file was outdated but considered valid, so when you delete it, it pulls a new one...

**Comment by EndOfLine369** [comment]
> Maybe we should put 1 to 3 month max...

Absolutely not. That will undo alot if not all of work to prevent AniDB banns.

I made the algorithm and in design it looks at the 'enddate' of the series. Based on how long that date is from now, it adds time to the max age a locally cached file is still considered valid.

The situation here is we have a long ended series that has newly aired non-normal/special episodes which would not be in consideration of a series enddate.
What will probably need to be done is it will need to check BOTH the series enddate & the oldest air date of all episodes. The newest date of all is our entry then to be used for cache time calculation.

> <episode id="225907" update="2020-01-05">
> <epno type="6">O3</epno>
> <length>50</length>
> <airdate>2020-01-15</airdate>
> <title xml:lang="en">Director`s Cut: Episode 3</title>
> </episode>
> </episodes>
> </anime>

In this situation, we can clearly see that it saw some of the newly added specials `<airdate>2020-01-15</airdate>`. So if the episode air dates were put into the evaluation of when a series was truely ended, it would have adjusted the cache age off of "2020-01-15" instead of "2016-09-19".

**Comment by ZeroQI** [comment]
That is true we hardly ever have AniDB banning now nd this system lowered the number of calls to AniDB, and the adaptative cache was for that very reason...

The inclusion. Of the last files dates would have mitigated the issue, that is true...
