### ISSUE TITLE
create a release and use github for download instead of forum link

### ISSUE THREAD

**Issue by jrobeson** [ZeroQI/Hama.bundle#4]
I'd like to suggest that you use github to tag and create releases and then folks can download directly from here instead of having to bounce back to the forums to get the file.

I read that you were new to git (although i think that was awhile ago), so if you want a little bit of assistance i can help you out with that.

I'd also suggest that you tag your releases as major,minor.patch  like so http://semver.org/

**Comment by ZeroQI** [comment]
closing this
