### ISSUE TITLE
Show song names in episode titles for AniDB openings/endings

### ISSUE THREAD

**Issue by JoshuaGerdes** [ZeroQI/Hama.bundle#400]
Currently, HAMA populates the episode title for openings and endings that are listed in AniDB. However, the title it uses is the "Main Title" from AniDB which is usually just something like "Opening 1", "Ending 1", etc. It would be useful if the episode title could also include the title from the Song that is indicated in the episode.

For example, in the first opening of Tensei Shitara Slime Datta Ken/That Time I Got Reincarnated as a Slime (https://anidb.net/episode/208850), the Main Title is "Opening 1" which is what will currently be shown in Plex. However, the AniDB page also indicates that the song title associated with this opening is "Nameless Story". It would be good if the episode title shown in Plex could be "Opening 1 - Nameless Story" instead of just "Opening 1" in this case.

**Comment by ZeroQI** [comment]
AniDB HTTP API output for that series: http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=13871

Here is opening 1 output:
```
<episode id="208850" update="2018-10-02">
<epno type="3">C1</epno>
<length>2</length>
<airdate>2018-10-02</airdate>
<rating votes="4">7.36</rating>
<title xml:lang="en">Opening 1</title>
</episode>
```

Currently the information is the HTTP API, may be in the UDP client (to be confirmed, requires login/password)
I will not parse raw html per episode to get this data not offered in the API, but if you query and get AniDB to add it to the XML output of the HTTP API in any form,I will add support for it. Easier would be for their title to include it.
