### ISSUE TITLE
HAMA won't pull DVD ordering of TVDB.

### ISSUE THREAD

**Issue by varoOP** [ZeroQI/Hama.bundle#401]
Here's what happened :  
1) Put Black Lagoon in a folder following the DVD TVDB order. (3 seasons)
2) Set episode ordering to DVD order in advanced settings.
3) Refresh metadata. 
4) HAMA still pulls metadata according to airing order from TVDB. 
5) Use the TVDB metadata agent instead of HAMA and refresh metadata. 
6) It uses the DVD order metadata.

**Comment by ZeroQI** [comment]
There is a DVD order agent before Plex added the field in advanced settings but it's a regular agent:
http://h3athens.net/guides/fix-dvd-order-naming-plex.html

It does behave like a normal agent, supports only DVD order on TheTVDB so not usable for me.

I do not know
- how to tell plex the dvd numbering season and episode number (undocumented medatada fields?). I would have checked the tvdb agent code but most agents were removed from https://github.com/plexinc-agents and not showing in Plug-Ins folder
- how the agent can know this Library drop-down setting 'DVD order' in the library 'advanced settings' is selected in Plex

**Comment by varoOP** [comment]
I found the code in : /usr/lib/plexmediaserver/Resources/Plug-ins-69560ce1e/TheTVDB.bundle/Contents/Code$

I pasted it here for you : https://paste.ubuntu.com/p/d3RtXDztGw/

Hope it makes it possible to add the support! 
Thanks a lot for offering to add it!

**Comment by EndOfLine369** [comment]
Trying to match a dvd order would also break any AniDB meta as there is no mapping according to dvd order.

**Comment by varoOP** [comment]
That's fair. 
Thanks for looking into it!

**Comment by ZeroQI** [comment]
The correct use case is to use anidb or TVDB numbering, and i added few modes to assist with nor renaming files but just the series folder
Another possibility would be a new tvdb6 DVD mode to convert TheTVDB DVD numbering to TVDB numbering at scanner level and the agent will receive a normal tvdb mode, and would not need modification. I would include it if somebody made it (using tvdb5 as base for example). 

Adding comment for future reference, in case the demand for DVD numbering rises (and if TVDB API v3 allows it as it release is more or less imminent)

**Comment by reconman** [comment]
The [Monogatari series](https://thetvdb.com/series/monogatari/) is another candidate for needing DVD order. The absolute order is a pure mess and the mods locked it, so it will forever remain useless.

**Comment by ZeroQI** [comment]
Monogataries is the worst series to do naming for,  you should use the tvdb standalone DVD order agent, or thetvdb agent and set series/library to use DVD order which is a plex functionnality, just for that series to be honest.
I have no way to have mapping from anidb to TheTVDB dvd order

**Comment by reconman** [comment]
I tried searching for ways to change the agent for one series, but was not able to find any answers in forum posts. Is there a way to do that?
