### ISSUE TITLE
Episode only shows up in Plex with 2 copies in directory

### ISSUE THREAD

**Issue by mweber03** [ZeroQI/Hama.bundle#402]
I'm not sure if this is related to Hama, but I'm getting a really weird issue where I need two copies of one specific episode for it to show up in Plex.

What happened was, I loaded 3 series in everything was fine, all episodes loaded. I loaded in My Hero Academia Season 4 and noticed an episode was missing in Plex, episode S04E02. Tried renaming it in various ways, still didn't show up. Made a copy and then it showed up in Plex but only one (the path referenced the copy). Deleted the original, which wasn't the file Plex was referencing, and it disappeared, Re-added the original and it reappeared (this time the file reference was to the original. Copied it again, so there was 3, now Plex recognized 2 copies of it,

This is just so bizarre and I couldn't find any related errors in the logs. It seems completely unrelated to the name, there just has to be another copy of the file. Do you have any suggestions?

**Comment by mweber03** [comment]
Update, I removed the directory, cleared it and dropped it back in, now episode 10 is missing.

**Comment by mweber03** [comment]
On the third removal and re-add all 25 episodes showed up. So weird. But I guess it's working so, whatever.

**Comment by ZeroQI** [comment]
Seem like a scanner issue so only scanner logs could tell. You may have a corrupted database.
I would clean bundles and optimise datVase in libraries option...
