### ISSUE TITLE
Forcing Anidb series ID leads to wrong date

### ISSUE THREAD

**Issue by Columbo199X** [ZeroQI/Hama.bundle#403]
I recently switched from adding each series separately to Plex to only having one directory to add it automaticly.
However this lead to a problem after readding the series.
This is the main directory set in the Plex Libary: 
A:\Anime
This is how the directory on my hdd looks like:
Anime/Dirty Pair/Dirty Pair [anidb-401]
Anime/Dirty Pair/Dirty Pair - Project EDEN [anidb-1032]
Both entrys get added properly but they both show up with the same release date. So even though Project Eden released in 1987 it shows 15. July 1985 which is the release date of the original Dirty Pair series. 
This only happens when there are multiple entries in one folder.

**Comment by Roshri** [comment]
How to procceed when the ban is lifted? Even after refreshing metadata, it keeps getting the date from TVDB, in my case it's happening with the gundam movies.

[Mobile Suit Gundam III Encounters in Space.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4872117/Mobile.Suit.Gundam.III.Encounters.in.Space.agent-update.log)
[Mobile Suit Gundam II Soldiers of Tomorrow.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4872119/Mobile.Suit.Gundam.II.Soldiers.of.Tomorrow.agent-update.log)
[Mobile Suit Gundam I.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4872120/Mobile.Suit.Gundam.I.agent-update.log)

**Comment by EndOfLine369** [comment]
Your running on old code. Always upgrade to latest before raising an issue.

**Comment by Roshri** [comment]
I thought I just had updated to the latest. Downloaded and replaced the existing files.

**Comment by EndOfLine369** [comment]
You have the line "common.GetMetadata()" which has not existed since January 13th.

**Comment by Roshri** [comment]
So I removed both the old scanner, the old agent and the old logs. And installed from the latest zip
Now I'm getting the logs of every fresh scan in a single file is this the intended behavior?
[_root_.agent.log](https://github.com/ZeroQI/Hama.bundle/files/4872171/_root_.agent.log)
[_unknown_folder.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/4872172/_unknown_folder.agent-search.log)
[_unknown_folder.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4872173/_unknown_folder.agent-update.log)

**Comment by ZeroQI** [comment]
The agent cannot open the Plex library XML.
You probably updated plex.
Create a Plex token file as per ASS readme

**Comment by Roshri** [comment]
Created a token file and located it in the root folder, as that was what I understood from the ASS readme.
Still the same _unknown_folder log. 
I might be creating the file wrong.
I copied the token="xxxxxx" and saved it as a file named it "X-Plex-Token.id" and placed it in the root folder in AppData/Local/Plex Media Server

**Comment by ZeroQI** [comment]
Token file seem good. Need to look at it on my pc, not at home and on phone currently and too long to scroll

**Comment by ZeroQI** [comment]
Using old logs:

[=] originally_available_at Sources: AniDB,(TheTVDB) Inside: '['TheTVDB']' Value: '1979-07-16'
[=] originally_available_at Sources: AniDB,(TheTVDB) Inside: '['TheTVDB']' Value: '1979-07-16'
[=] originally_available_at Sources: AniDB,(TheTVDB) Inside: '['TheTVDB']' Value: '1979-07-16'
Working as designed [although the design could be altered]

ERROR: Invalid str returned: "banned" so no AniDB metadata
originally_available_at selects AniDB then TheTVDB, and only TheTVDB provided a date but all seasons point to the same TVDB series, therefore the same date
You need to fix the banning, then the metadata will refresh normally
