### ISSUE TITLE
Exception: 'HTTP Error 404: Not Found' error on logs and hama not getting newly added anime's datas

### ISSUE THREAD

**Issue by NeHalem90** [ZeroQI/Hama.bundle#404]
I got 

`ERROR (networking:196) - Error opening URL 'http://localhost:32400/library/sections/'`

on com.plexapp.agents.hama.log, so i looked at _unknown_folder.agent-update.log, written in hama.log
and it said 

`ERROR: common.LoadFile() - issue loading url: 'http://api.tmdb.org/3/movie/tt10054654?api_key=7f4a0bd0bd3315bb832e17feda70b5cd&append_to_response=releases,credits,trailers,external_ids&language=en', filename: 'IMDb-tt10054654.json', Headers: {'Content-type': 'application/json', 'User-agent': 'Plex/HAMA'}, Exception: 'HTTP Error 404: Not Found'
`

all over the place. I tried changing localhost to 127.0.0.1, but did no good.
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/4870013/com.plexapp.agents.hama.log)
[_unknown_folder.agent-update_part.log](https://github.com/ZeroQI/Hama.bundle/files/4870023/_unknown_folder.agent-update_part.log)

I uploaded part of log, as it exceeded 10mb.
thanks

and I use freenas(freeBSD) btw

**Comment by ZeroQI** [comment]
Did you create a Plex Media Server/X-Plex-Token.id file containing the Plex token id by logging on plex.tv/desktop, then https://plex.tv/devices.xml, it will be MediaContainer/Device ... token="xxxxxxxxxxxxxx"? (as per ASS readme)

**Comment by NeHalem90** [comment]
first, I cannot get plex.tv/devices.xml, as it said i have no permission, even after i log in. 
plex.tv/desktop is not available, because i installed it in jail in freenas. 
The series that i have problem is pretty much everything, but ones before plex update uses local data, so none of serises added after upgrading plex is available. 
I'm thinking of reinstalling plex and hama, because i think upgrading plex may have caused this problem.

**Comment by NeHalem90** [comment]
[_root_-mnt-video-anime.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/4870543/_root_-mnt-video-anime.filelist.log)
[_root_-mnt-video-anime.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/4870544/_root_-mnt-video-anime.scanner.log)
these two are the ones, but weirldly, none of series which had problem didn't through any logs.
So, I'll attach any random series ones.
[Ghost in the Shell.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/4870553/Ghost.in.the.Shell.filelist.log)
[Ghost in the Shell.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/4870554/Ghost.in.the.Shell.scanner.log)

thank you

**Comment by ZeroQI** [comment]
These folders are misnamed and will not match automatically:
- /Strike the Blood/Strike the Blood s01 => will use "Strike the Blood s01" as title as not the right format for season folder
- /Seitokai Yakuindomo/Seitokai Yakuindomo Season 01 => will use "Seitokai Yakuindomo Season 01" as title as not the right format for season folder
- Monogatari/(01)Bakemonogatari => will use "(01)Bakemonogatari" as title, you should have used "[01] Bakemonogatari" as square bracket content is removed
- Youjo Senki/Youjo Senki (2019) (BD 1920x1080 x264 FLAC) => will use "Youjo Senki (2019) (BD 1920x1080 x264 FLAC)" as title, you should have used "Youjo Senki (2019) [BD 1920x1080 x264 FLAC]" as square bracket content is removed

What does "hama not getting newly added anime's datas" even mean?
- Does the files show up in plex at the right season and episode number? if so the scanner is working correctly
- Is it a metadata gathering or matching issue? If so, did you try matching manually the series?

**Comment by NeHalem90** [comment]
I have been using that folder scheme without any problem before, so i will reinstall plex, and let you know.

**Comment by NeHalem90** [comment]
I reinstalled plex and hama(eventually), and everything wored fine again!
I'll change folder naming though thanks!

**Comment by ZeroQI** [comment]
Weird... Seem like a Plex issue, especially if the unique Id was given to the series and it wasn't running the metadata update... Glad you got it fixed

**Comment by NeHalem90** [comment]
Hi, almost same issue happened when I added a new anime(Danna ga Nani wo Itteiru ka Wakaranai Ken )to root, 
ASS picks newly added anime up and get season 01, 02 and stuff, but metadata is not being picked up. 
So i'm pretty sure its a agent issue, not Ass.
[_root_.agent.log](https://github.com/ZeroQI/Hama.bundle/files/4874969/_root_.agent.log)

Please request any log you need, I'll find it rightaway,.

**Comment by NeHalem90** [comment]
Hi
I deleted all Logs, and performed Refresh metadata of 'Danna ga Nani wo Itteiru ka Wakaranai Ken'
these are all the logs. 
I think this is not ASS problem because animes are all showing up on library.
IMO, 
`DEBUG (networking:143) - Requesting 'http://localhost:32400/library/sections/'
ERROR (networking:196) - Error opening URL 'http://localhost:32400/library/sections/'
DEBUG (sandbox:19) - PLEX_LIBRARY_URL - Exception: 'HTTP Error 401: Unauthorized'`
These are the problems
[Plex Tuner Service.log](https://github.com/ZeroQI/Hama.bundle/files/4879712/Plex.Tuner.Service.log)
[Plex Media Server.log](https://github.com/ZeroQI/Hama.bundle/files/4879714/Plex.Media.Server.log)
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/4879715/com.plexapp.agents.hama.log)
[com.plexapp.agents.imdb.log](https://github.com/ZeroQI/Hama.bundle/files/4879716/com.plexapp.agents.imdb.log)
[com.plexapp.agents.localmedia.log](https://github.com/ZeroQI/Hama.bundle/files/4879717/com.plexapp.agents.localmedia.log)
[com.plexapp.system.log](https://github.com/ZeroQI/Hama.bundle/files/4879718/com.plexapp.system.log)

Here are all clean logs by
1. Deleting all Logs
2. Restart plexmediaserver service
3. refreshing anime 'Danna ga Nani wo Itteiru ka Wakaranai Ken's metadata. 

thankyou!

**Comment by ZeroQI** [comment]
you need to check ASS readme and add a plex token file so HAMA and ASS can access the library XML

seem like the search fails, and search TheTVDB (which it should do if there was more than one season)
https://www.thetvdb.com/series/i-cant-understand-what-my-husband-is-saying

You are not using TVDB title "I Can't Understand What My Husband Is Saying" but an alias "Danna ga Nani wo Itteiru ka Wakaranai Ken"... I do not support aliases for TheTVDB yet.

```
=============================================================================================================================================================
common.PlexLog(file="/usr/local/plexdata-plexpass/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/_unknown_folder.agent-search.log", movie=False)
[!] file:       "/mnt/video/anime/Danna ga Nani wo Itteiru ka Wakaranai Ken/Danna ga Nani wo Itteiru ka Wakaranai Ken S01E11.mkv"
[ ] library:    ""
[ ] root:       ""
[ ] path:       "_unknown_folder"
[ ] Plex root:  "/usr/local/plexdata-plexpass/Plex Media Server"
[ ] Log folder: "Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs"
[ ] Log file:   "_unknown_folder.agent-search.log"
[ ] Logger:     "0x809e43500"
[ ] mode:       "a"
=== Search() ================================================================================================================================================
title: 'Danna ga Nani wo Itteiru ka Wakaranai Ken', name: 'None', filename: '%2Fmnt%2Fvideo%2Fanime%2FDanna%20ga%20Nani%20wo%20Itteiru%20ka%20Wakaranai%20Ken%2FDanna%20ga%20Nani%20wo%20Itteiru%20ka%20Wakaranai%20Ken%20S02E13%2Emkv', manual: 'False', year: 'None'
start: 2020-07-07 00:32:11,866286
=============================================================================================================================================================
--- force id ------------------------------------------------------------------------------------------------------------------------------------------------
--- source searches -----------------------------------------------------------------------------------------------------------------------------------------
=== TheTVDB.Search() ========================================================================================================================================
TVDB  - score: ' 19', id: '285357', title: 'I Can't Understand What My Husband Is Saying'
=============================================================================================================================================================
end: 2020-07-07 00:32:11,876905
=============================================================================================================================================================
```

**Comment by NeHalem90** [comment]
I thought my way of saying was bad, so I reopened another issue.
SO sorry

**Comment by ZeroQI** [comment]
See https://github.com/ZeroQI/Hama.bundle/issues/407 for the new issue logged
