### ISSUE TITLE
One Piece TVDB4 Specials misbehaving

### ISSUE THREAD

**Issue by TrafalgaT** [ZeroQI/Hama.bundle#405]
I noticed recently that all specials past special 30 (S31 - One Piece: Episode of Sabo) get meta matched to the episode 31 instead of the special

[One Piece [tvdb4-81797].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4850671/One.Piece.tvdb4-81797.scanner.log)
[One Piece [tvdb4-81797].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4850672/One.Piece.tvdb4-81797.filelist.log)

**Comment by TrafalgaT** [comment]
ill try my best to find those files, right now i have to wait for the dance to finish, but if the problem presists ill dig into it. its kinda tricky finding the right logs on qnap for me because there are just so many different log folders and different individual log files.

**Comment by ZeroQI** [comment]
should be in agent data folders for HAMA agent

**Comment by TrafalgaT** [comment]
so:

1) I did the Plex Dance, unsuccessfully. Back to status Quo, all the metadata has been matched, but in case of the specials, it has reverted to the previous state. All episodes past special number 30 (S31 - Episode of Sabo), all specials get matched to the 'series' episode number E031+.

2) I have tried to locate the log, and the attached log seems to maybe be the one you need ? I tried this one 

/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs

but its empty so there are no logs in there

**Comment by ZeroQI** [comment]
Without logs, it's tricky to solve... The code was altered in both ASS and HAMA yesterday to not require the token anymore...
is there folders with the library name in there ?

Can you confirm in Plex that for episode 31, it is showing in Plex as the same series and in season 0 at episode 31 ?

**Comment by TrafalgaT** [comment]
ok so this is what it looks like in plex 

![s00_view_plex_31plus](https://user-images.githubusercontent.com/45255267/86749343-7663a000-c03d-11ea-8623-690c93a70d7b.png)

these correspond to the actual 'arc' episodes E31.....E38

and as for my library itself this is what the library folder looks like 
![library](https://user-images.githubusercontent.com/45255267/86749613-aca11f80-c03d-11ea-9969-99f17e934887.png) and the example for one piece
![one_piece_example](https://user-images.githubusercontent.com/45255267/86749841-d5c1b000-c03d-11ea-836f-f3d2d3c51950.png)

**Comment by ZeroQI** [comment]
Logs shows no episode present physically apart from  s00e39
"/share/CACHEDEV2_DATA/TV Anime/One Piece [tvdb4-81797]/S00 - Specials/[0.1] Arc Movies/One Piece - 39 -  Stampede.mkv"

I do not see the scanner logs about adding specials for some reason...
you do use transparent folders but it seem to skip so shouldn't be showing in plex...
```
=================================================================================
============================================================================
Library: 'TV Anime', root: '/share/CACHEDEV2_DATA/TV Anime', path: 'One Piece [tvdb4-81797]/S00 - Specials', files: '0', dirs: '2'
Plex scan start: 2020-07-07 10:05:42,894914
plexignore_files: '[]', plexignore_dirs: '[]'
=============================================================================================================================================================
[folder] One Piece [tvdb4-81797]/S00 - Specials/[0.1] Arc Movies
[folder] One Piece [tvdb4-81797]/S00 - Specials/[0.2] Arc Special Episodes
[no files detected] Grouping folder skip as >1 folder [return]
=============================================================================================================================================================
```

I am confused...

**Comment by TrafalgaT** [comment]
you are not the only one who is confused..... they show up as Specials (example attached)

![unnamed](https://user-images.githubusercontent.com/45255267/86817119-e34e5880-c084-11ea-98e0-853b37bc87ba.png)

**Comment by meisnate12** [comment]
I have the same setup using tvdb4 and I'm having the same problem except that for me only the first 8 specials work, which is the same number of episodes that I have in Season 1 or the show. I added all of Season 2 to Season1 to total 30 episodes in Season 1 and then removed one piece did the plex dance and readded it. After which the first 30 episodes in the specials all had the right names. It seems like however many episodes that are in season 1 lets the same number of specials get the right meta data but after that for some reason it takes the meta data from the next series episode.

**Comment by meisnate12** [comment]
Here are my logs if it helps any

[One Piece [tvdb4-81797].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/4929125/One.Piece.tvdb4-81797.agent-search.log)
[One Piece [tvdb4-81797].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4929126/One.Piece.tvdb4-81797.agent-update.log)
[One Piece [tvdb4-81797].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/4929127/One.Piece.tvdb4-81797.filelist.log)
[One Piece [tvdb4-81797].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/4929128/One.Piece.tvdb4-81797.scanner.log)

**Comment by ZeroQI** [comment]
Let's use impacted s00e34 ONE PIECE FILM GOLD showing "Everyone's Gathered! Usopp Speaks the Truth About Nami!"
Metadata at the end of thetvdb part is already wrong
`        '34': {'absolute_index': 34, 'content_rating': 'TV-Y7', 'duration': 1500000, 'language_rank': 0, 'originally_available_at': '2000-07-26', 'rating': 7.8, 'summary': 'A fierce argument over where Nami\'s loyalties lie divides the Straw Hat Pirates and only one thing\'s for sure - no one is willing to risk their life for a traitor.', 'thumbs': {'https://thetvdb.plexapp.com/banners/episodes/81797/5540965.jpg': ('TheTVDB/episodes/5540965.jpg', 1, None), 'https://thetvdb.plexapp.com/banners/episodes/81797/361923.jpg': ('TheTVDB/episodes/361923.jpg', 1, None)}, 'title': 'Everyone\'s Gathered! Usopp Speaks the Truth About Nami!'},`

```
[X]   s0e34 s00e034 anidbid:         air_date: 2016-07-23 abs_number: 0, title: One Piece Film Gold
 - [1] title:   [en] One Piece Film Gold
common.LoadFile() - File cached locally - Filename: 'TheTVDB/json/81797/episode_5540965_ja.json', Age: '0.51 days', Limit: '6 days', url: 'https://api.thetvdb.com/episodes/5540965'
 - [2] summary: [ja] 新世界の“怪物”が動き出す!!!物語の舞台は、世界中の名立たる海賊、海兵、大富豪たちが集う、世界最大のエンターテインメントシティ“グラン・テゾーロ”。そこでルフィたちの前に現れたのは、金の力で世界政府ですら容易く動かし、天竜人をも懐柔する絶対的な権力を持つ“黄金帝”ギルド・テゾーロ。豪華絢爛な街の裏ではテゾーロによる圧倒的な支配が渦巻き、ルフィたちはなすすべもなく街の非情なルールに飲み込まれていく。そんな中、テゾーロから天竜人への「史上最高額の天上金」の存在が明らかとなり、その支配力は世界を揺るがすほどの暴走をはじめていた。遂に動き出した新世界の“怪物”に、ざわめきはじめる世界政府、そして革命軍――。「自由とは、支配とは」この海を制するための答えを求め、ルフィたちの信念を懸けた闘いが幕を開けようとしていた。
 - [ ] thumb: https://thetvdb.plexapp.com/banners/episodes/81797/5540965.jpg

```
Meta is ok but over-written by:
```
[X]    s3e4 s00e034 anidbid:         air_date: 2000-07-26 abs_number: 34, title: Everyone's Gathered! Usopp Speaks the Truth About Nami!
 - [1] title:   [en] Everyone's Gathered! Usopp Speaks the Truth About Nami!
 - [1] summary: [en] A fierce argument over where Nami's loyalties lie divides the Straw Hat Pirates and only one thing's for sure - no one is willing to risk their life for a traitor.
common.LoadFile() - File cached locally - Filename: 'TheTVDB/json/81797/episode_361923_ja.json', Age: '1.46 days', Limit: '6 days', url: 'https://api.thetvdb.com/episodes/361923'
 - [ ] thumb: https://thetvdb.plexapp.com/banners/episodes/81797/361923.jpg
```

The 

https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/TheTVDBv2.py
- numbering ok line 146
- season, ep wrong in 167-175 (tvdb4)
```
      elif metadata_source in ('tvdb3', 'tvdb4'):  
        if str(abs_number) in list_abs_eps:  #if abs id exists on disk, leave specials with no translation
          for s in media.seasons:
            if str(abs_number) in media.seasons[s].episodes:
              season, episode = s, str(abs_number)
              break
          else:  continue
```
if abs number on disk, we pick the first season that have the abs_number and season becomes this season, episode becomes the abs number
So s003e4 abs number 34 should become s003e34 (or others if assigned manually) but not   s00e34
shall we skip if already exist?
Please test replacing line 167-173 with:
```
      elif metadata_source in ('tvdb3', 'tvdb4'):  
        if str(abs_number) in list_abs_eps:  #if abs id exists on disk, leave specials with no translation
          for s in media.seasons:
            if str(abs_number) in media.seasons[s].episodes and not Dict(TheTVDB_dict, 'seasons', s, 'episodes', str(abs_number)):
              season, episode = s, str(abs_number)
              break
          else:  continue
```
i

**Comment by TrafalgaT** [comment]
tried it and the meta did not change for the affected specials

**Comment by ZeroQI** [comment]
Give me your code update and the update log and I should be able to fix...

**Comment by meisnate12** [comment]
[TheTVDBv2.txt](https://github.com/ZeroQI/Hama.bundle/files/4934917/TheTVDBv2.txt)
[One Piece [tvdb4-81797].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4934974/One.Piece.tvdb4-81797.agent-update.log)

**Comment by TrafalgaT** [comment]
> so i tried you fix and its better but still has a small bug. All the special episodes that have metadata on TVDB now work fine but i have 5 more videos i include in the specials that dont have metadata on TVDB and those still picked up the metadata for episodes 40-45 where they shouldn't have had any metadata
> ![Image 1](https://user-images.githubusercontent.com/1631064/87726487-1ed7d980-c78d-11ea-8bae-9493d6b63840.png)

i do not know what you did, i did the same edit to the thetvdbv2.py file and for  me it is still like it used to be, still missmatched specials

**Comment by meisnate12** [comment]
i removed one piece from my library then cleaned my bundles and emptied my trash i restarted plex after that then one it was back up i readded one piece

**Comment by TrafalgaT** [comment]
Ok things are getting weird at this stage. All the mismatched episode have now correctly matched to the respective special meta.....the only thing is the thumbnails are still the “episode” tvdb thumbnail and not from the special (all of this is with the latest advises line changes to thetvdb2.py file that @ZeroQI mentioned above

**Comment by ZeroQI** [comment]
You might need to check the thumbs in plex as the previous screenshot will sadly be the main one but a second one should be loaded

**Comment by ZeroQI** [comment]
@meisnate12 opened log, it seems ep 40-44 are impacted
[X]   s3e10 s00e040 anidbid:         air_date: 2000-09-06 abs_number: 40, title: Proud Warriors! Sanji and Usopp's Fierce Battles!
[X]   s3e11 s00e041 anidbid:         air_date: 2000-09-13 abs_number: 41, title: Luffy at Full Power! Nami's Determination and the Straw Hat!
[X]   s3e12 s00e042 anidbid:         air_date: 2000-09-27 abs_number: 42, title: Explosion! Fishman Arlong's Fierce Assault from the Sea!
[X]   s3e13 s00e043 anidbid:         air_date: 2000-09-27 abs_number: 43, title: End of the Fishman Empire! Nami's My Friend!
[X]   s3e14 s00e044 anidbid:         air_date: 2000-10-11 abs_number: 44, title: Setting Out With a Smile! Farewell, Hometown Cocoyashi Village!

According TheTVDB specials are s00e01-39: https://thetvdb.com/series/one-piece/seasons/official/0
While you do not respect numbering as there no specials 41-44, these episodes should not be getting metadata indeed
- Issue: anybody with a special with no metadata at the same ep number as an absolute number episode, the special will have the ep metadata
- Fix: if a special has an absolute episode, then it is mapped to season 1+, there is never a need for custom mapping to season 0. Please replace previous quoted code with shorter replacement and report if working as expected:
```
      elif metadata_source in ('tvdb3', 'tvdb4'):  
        for s in media.seasons:  #if abs id exists on disk, leave specials with no translation
          if  str(abs_number) in list_abs_eps and str(abs_number) in media.seasons[s].episodes and s!="0":
            season, episode = s, str(abs_number)
            break
```

**Comment by meisnate12** [comment]
yup that last code change fixed it completely for me
