### ISSUE TITLE
PLEX_LIBRARY_URL - Exception: 'HTTP Error 401: Unauthorized' Error

### ISSUE THREAD

**Issue by NeHalem90** [ZeroQI/Hama.bundle#407]
Cannot get metadata for newely added Anime, 'Danna ga Nani wo Itteiru ka Wakaranai Ken'
But after looking at Log, found out all metadatas were just from local data, which was downloaded when hama was working.
So, hama bundle is not working.
It tends to work just after installing plex, and stops working a few days later.

1. I Cleaned out all Logs, and restart plex media server
2. Scan Library(anime)
3. Reload metadata of entire library(anime)
so the logs below does seems clean.

`Requesting 'http://localhost:32400/library/sections/'`
`Error opening URL 'http://localhost:32400/library/sections/'`
`PLEX_LIBRARY_URL - Exception: 'HTTP Error 401: Unauthorized'`

was shown agent logs.
I did add X-Plex-Token.id

got all the logs below. 
please let me know if you need anything else.

[_unknown_folder.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4880349/_unknown_folder.agent-update.log)
[_unknown_folder.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/4880350/_unknown_folder.agent-search.log)
[_root_.agent.log](https://github.com/ZeroQI/Hama.bundle/files/4880352/_root_.agent.log)
[_root_-mnt-video-anime.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/4880354/_root_-mnt-video-anime.filelist.log)
[_root_-mnt-video-anime.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/4880355/_root_-mnt-video-anime.scanner.log)
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/4880357/com.plexapp.agents.hama.log)
[Plex Media Server.log](https://github.com/ZeroQI/Hama.bundle/files/4880358/Plex.Media.Server.log)

**Comment by NeHalem90** [comment]
Thank you so much for such kind reply. I'd like to give you a donation

**Comment by ZeroQI** [comment]
You need to check ASS readme and add a plex token file so HAMA and ASS can access the library XML

seem like the search fails, and search TheTVDB (which it should do if there was more than one season)
https://www.thetvdb.com/series/i-cant-understand-what-my-husband-is-saying

You are not using TVDB title "I Can't Understand What My Husband Is Saying" but an alias "Danna ga Nani wo Itteiru ka Wakaranai Ken" which hama do not support aliases for TheTVDB yet.

```
=============================================================================================================================================================
common.PlexLog(file="/usr/local/plexdata-plexpass/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/_unknown_folder.agent-search.log", movie=False)
[!] file:       "/mnt/video/anime/Danna ga Nani wo Itteiru ka Wakaranai Ken/Danna ga Nani wo Itteiru ka Wakaranai Ken S01E11.mkv"
[ ] library:    ""
[ ] root:       ""
[ ] path:       "_unknown_folder"
[ ] Plex root:  "/usr/local/plexdata-plexpass/Plex Media Server"
[ ] Log folder: "Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs"
[ ] Log file:   "_unknown_folder.agent-search.log"
[ ] Logger:     "0x809e43500"
[ ] mode:       "a"
=== Search() ================================================================================================================================================
title: 'Danna ga Nani wo Itteiru ka Wakaranai Ken', name: 'None', filename: '%2Fmnt%2Fvideo%2Fanime%2FDanna%20ga%20Nani%20wo%20Itteiru%20ka%20Wakaranai%20Ken%2FDanna%20ga%20Nani%20wo%20Itteiru%20ka%20Wakaranai%20Ken%20S02E13%2Emkv', manual: 'False', year: 'None'
start: 2020-07-07 00:32:11,866286
=============================================================================================================================================================
--- force id ------------------------------------------------------------------------------------------------------------------------------------------------
--- source searches -----------------------------------------------------------------------------------------------------------------------------------------
=== TheTVDB.Search() ========================================================================================================================================
TVDB  - score: ' 19', id: '285357', title: 'I Can't Understand What My Husband Is Saying'
=============================================================================================================================================================
end: 2020-07-07 00:32:11,876905
=============================================================================================================================================================
```

[Edit]
- Thank you very much for the donation. I do not use Plex anymore for myself, so it is easy to lose motivation and focus
- Logging the reply from the other thread so each ticket is properly documented, and adding reflections
- TheTVDB didn't use to have alias, now it does and support movies, so I may have to support that but TheTVDB API v3 is not final yet to my knowledge, so waiting (and few bugs to solve before that)...
- your naming title would have no issues if using anidb numbering (single seasons), it's just that TheTVDB use horrible english titles and if multiple season, it only search TheTVDB main title (for now)
- Some people would group in a parent folder each season using AniDB numbering and use 'local' as collection source in settings, and order in the folder with '[01]' before the first series as square brackets gets scrubbed, etc...

**Comment by EndOfLine369** [comment]
Plex token is now pulled from the env in both HAMA & ASS.
