### ISSUE TITLE
Hama not grabbing all metadata, weird title issue

### ISSUE THREAD

**Issue by ToolB0xx** [ZeroQI/Hama.bundle#411]
```2020-07-11 17:35:49,833 (7fbc71ffb700) :  INFO (common:135) - ==== common.PlexLog(file="/home/plexdata/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/Anime/K-ON!.agent-update.log")
2020-07-11 17:35:50,342 (7fbc71ffb700) :  CRITICAL (agentkit:1095) - Exception in the update function of agent named 'HamaTV', called with guid 'com.plexapp.agents.hama://tvdb-87501?lang=en' (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-864bbcbb7/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1093, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/home/plexdata/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 165, in update
    def update (self, metadata, media, lang, force ):  Update (metadata, media, lang, force,  False)
  File "/home/plexdata/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 140, in Update
    dict_AniDB, ANNid, MALid                                      =       AniDB.GetMetadata(media, movie, error_log,       source, AniDBid, TVDBid, AnimeLists.AniDBMovieSets, mappingList)
  File "/home/plexdata/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/AniDB.py", line 347, in GetMetadata
    if missing_eps:  error_log['Missing Specials' if season=='0' else 'Missing Episodes'].append("AniDBid: %s | Title: '%s' | Missing Episodes: %s" % (common.WEB_LINK % (common.ANIDB_SERIE_URL + AniDBid, AniDBid), AniDB_dict['title'], str(missing_eps)))
  File "/home/plexdata/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/common.py", line 158, in GetXml
    def GetXml          (xml,      field                ):  return xml.xpath(field)[0].text if xml.xpath(field) and xml.xpath(field)[0].text not in (None, '', 'N/A', 'null') else ''  #allow isdigit() checks
AttributeError: 'str' object has no attribute 'xpath'

2020-07-11 17:35:50,342 (7fbc71ffb700) :  DEBUG (model:229) - Serializing to /home/plexdata/Library/Application Support/Plex Media Server/Metadata/TV Shows/2/b1ffaa1304a424309bbf916dffd842c20ab761d.bundle/Contents/com.plexapp.agents.hama/Info.xml
```
![seriesIDthingy](https://user-images.githubusercontent.com/10215024/87234742-0f7a1a00-c3a2-11ea-8793-4c85d2e46d8a.png)

While trying to refresh my metadata for some of my series, Hama stopped working or correctly grabbing all the info at one point. I've had this issue of the **TVDB** or **AniDB** identifiers appearing after series, and all it took was another refresh to get rid of it and get the metadata grabbed and updated. However, now it is not grabbing anything, and even swapping metadata I previously had to this now broken format, which is strange. Adding new series shows no results either, no grabbing metadata of any kind, not even the broken title format, no art or anything. I tried going from the latest version of Hama https://github.com/ZeroQI/Hama.bundle/commit/c44961c64b96546daa157b98a3063d1bf907b6a6 (The one with some support added for AniList) and a few revisions before the initial changes for AniList, https://github.com/ZeroQI/Hama.bundle/commit/f075b75d860c28e5d28bc69c9e9653220cb33c40, to no avail. The aforementioned block of code seems to be the only thing haunting the logs, I did some quick digging, the only thing I found close to it was the dreaded **AniDB** `anime-titles.xml` issues, which I've checked and insured it is not corrupted and is the latest available one. 

Not sure if this had been seen before previously, but if it was, I couldn't find one like this anywhere in the open or closed issues. If you need any more files let me know. Thanks!

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/4907694/com.plexapp.agents.hama.log)
[Series-XMLs.zip](https://github.com/ZeroQI/Hama.bundle/files/4907693/Series-XMLs.zip)

[GANTZ.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4907689/GANTZ.agent-update.log)
[K-ON!.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4907690/K-ON.agent-update.log)
[Gunslinger Girl.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4907691/Gunslinger.Girl.agent-update.log)
[Yuusha ni Narenakatta Ore wa Shibushibu Shuushoku wo Ketsui Shimashita.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/4907692/Yuusha.ni.Narenakatta.Ore.wa.Shibushibu.Shuushoku.wo.Ketsui.Shimashita.agent-update.log)

**Comment by ZeroQI** [comment]
I wouldn't trust 100% the lines mentionned by the logs, i ofter have seen the wrong lines shown and the error totally elsewhere, but the error message is valid: AttributeError: 'str' object has no attribute 'xpath'

Likely, the file return is valid but not an XML
The files cached by the agent in agent data folders could help, note  sure if AniDB or TheTVDB ones

Logs all stop during the AniDB section and the latest line displayed is: --- xxxx.series ------------, just before the XML loading
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/AniDB.py line 162

Maybe trap the xml loading by replacing line 165 with:
```
    try:        xml_cache  = common.LoadFileCache(filename=AniDBid+".xml", relativeDirectory=os.path.join("AniDB", "xml"))[0]
    except:  xml_cache = None    
```

**Comment by ToolB0xx** [comment]
Went ahead and tried that out, no changes in behavior or log files, went ahead and added some more catches, seems like code execution completely stops at Line 167 (As in it executes up to that point, and this line is most likely responsible for the current crash) https://github.com/ZeroQI/Hama.bundle/blob/c7ebfb73a9b590a79fa1247795ba5a3432b1368a/Contents/Code/AniDB.py#L167

**Comment by ToolB0xx** [comment]
Well I seemed to have fixed it. Not sure exactly what it was or what might still be broken. What I did was changed https://github.com/ZeroQI/Hama.bundle/blob/c7ebfb73a9b590a79fa1247795ba5a3432b1368a/Contents/Code/AniDB.py#L167 to
```
try:
  ed = GetXml(xml_cache, 'enddate')
except:
  ed = datetime.datetime.now().strftime("%Y-%m-%d") 
```

**Comment by ZeroQI** [comment]
@ToolB0xx  Well done!
- It probably downloaded multiple time the same xml, but i established hama file caching in agent data folders to prevent that, put if plex crashes, the plex cache may be lost
- AniDB banning last 24 hours
- Saw more of these lately, may be due to new series or new ep with partial metadata (no end date)

**Comment by ZeroQI** [comment]
Integrated your fix in the main code after re-working it slightly, thanks. that will prevent many crashes, probably more in new series with field missing in the XML, causing the crash...

Please close the ticket if the new code works, you should have been de-banned by now

**Comment by EndOfLine369** [comment]
@ZeroQI, that is not the issue here. `AttributeError: 'str' object has no attribute 'xpath'` via `GetXml(xml_cache, 'enddate')` means that `xml_cache` got a string returned from `common.LoadFileCache()`. Meaning the file he had cached was not a valid xml.

**Comment by ZeroQI** [comment]
@EndOfLine369 This message is present in the general hama log, but not the series specific log
We definitely need to check that but should have gotten a similar message further if that was the case and not output anything else due to the crash...

AniDBmight have changed the shape of the banning message...
We need 2 failsafe:
- non xml files should definitely not be cached
- if a cached xml file gives an error loading, it should be deleted

**Comment by EndOfLine369** [comment]
Simple test for string added
https://github.com/ZeroQI/Hama.bundle/blob/7d063fc9b45615669b4a92363470dd5e5fdf8bb6/Contents/Code/AniDB.py#L166

Same thing is already done later to make sure we don't get a banned or other string response from AniDB.
https://github.com/ZeroQI/Hama.bundle/blob/7d063fc9b45615669b4a92363470dd5e5fdf8bb6/Contents/Code/AniDB.py#L178

**Comment by ZeroQI** [comment]
issue still present?

**Comment by ToolB0xx** [comment]
I can download the latest version of Hama and try what @EndOfLine369 suggested. I'll see what is lying in wait in that .xml file

**Comment by ZeroQI** [comment]
any update by any chance?

**Comment by ToolB0xx** [comment]
Sorry It's taken awhile to get back to you, I've since downloaded the latest version, but I haven't really had any new media to add, so I haven't seen any issues appear as of yet. So I guess you could say it's working great so far

**Comment by ZeroQI** [comment]
No need for new Media, if the error is gone from the series you had an issue with after HAMA update and metadata update we close the case...

**Comment by ToolB0xx** [comment]
Alright, sounds good. I haven't noticed any more issues since the update, and everything has a proper title, so I will go ahead and mark as closed. Thanks.
