### ISSUE TITLE
Anime filler support?

### ISSUE THREAD

**Issue by ricreis394** [ZeroQI/Hama.bundle#413]
Hello,

first time using this and for now it seems to work very good.
Does this allow to mark in plex an episode as a filler?

**Comment by ZeroQI** [comment]
there is no agent facing metadata fields to specify that. closing issue.

Similar request to [https://www.reddit.com/r/PleX/comments/bfwnv4/i_have_a_show_with_a_lot_of_filler_episodes_i/], you could mark filler eps as watched so you can watch the rest sequentially
