### ISSUE TITLE
Artwork invalid or wrong

### ISSUE THREAD

**Issue by Entixs** [ZeroQI/Hama.bundle#415]
Hi,

my friend started using hamatv and flat out informed me that the artwork is pulling non-anime artwork. One of the artworks was porn which should not be getting pulled by hamatv.

Vinland Saga is one of them that is haviung Silver Fleet pulled as the poster

https://everdev.net/ss/tefojp43.png

Can you please let me know why this is a thing?

**Comment by EndOfLine369** [comment]
All depends on mapping done off of the original source/id your entry is mapped off of. Logs are required but I suspect its from bad SchudLee mapping. I already had this happen as well and raised the issue https://github.com/ScudLee/anime-lists/issues/342 from bad TMDB ids. Your logs will tell you where that poster came from and you can request the needed corrected mapping to be done. HAMA does not own this mapping.

EX:
  <anime anidbid="13945" tvdbid="359274" defaulttvdbseason="1" episodeoffset="" tmdbid="88803" imdbid="">
    <name>Vinland Saga</name>
  </anime>

https://www.themoviedb.org/movie/88803  <-- The Silver Fleet (1943)
