### ISSUE TITLE
Missing meta data

### ISSUE THREAD

**Issue by Columbo199X** [ZeroQI/Hama.bundle#416]
In the past I've added around 300 entries to my library using ASS+HAMA without issues.
Now all of a sudden when I add a new series (doesn't matter which one) and update the library, no meta data get's loaded or only some part of it.
Apart from the title everything is missing. No poster, summary or release date etc. I have set hama to mainly use AniDB and have noticed that the xml file corosponding to the series is missing in 
`C:\Users\XXXX\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\AniDB\xml`
So why is that? Could it be that I've added too many series at a time?

**Comment by ZeroQI** [comment]
Logs would tell why, and you are probably banned for 24h.

**Comment by Columbo199X** [comment]
Here are the logs (hope it's the right one)
[_root_.agent.log](https://github.com/ZeroQI/Hama.bundle/files/5062644/_root_.agent.log)
Looking through it myself I guess you're right I got banned :(
