### ISSUE TITLE
Not getting any AniDB Results

### ISSUE THREAD

**Issue by Auno94** [ZeroQI/Hama.bundle#422]
So I am moving my library from one server to another and I have the issue that I get only TVDB results  (HAMA is set to default) and no AniDB Results are shown

**Comment by ZeroQI** [comment]
I have this issue where people create bug reports without giving an example nor logs, despite logs location being in the readme.
- Find the logs, read the logs.
- HAMA search TheTVDB by default if your series have multiple seasons
