### ISSUE TITLE
Error starting framework core for /config/Plex Media Server/Plug-ins/Hama.bundle.

### ISSUE THREAD

**Issue by sassyass** [ZeroQI/Hama.bundle#423]
Hi,

Hama was working great but apparently it may have been broken a while back and I never noticed until recently? I updated both Hama and ASS, manually downloaded anime-titles.xml, and even fixed the thing where somehow I had ended up not using the raw version of __init__.py, and I'm still ending up with this:

> 2020-09-25 16:59:04,934 INFO success: plexmediaserver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
>2020-09-25 16:59:08,908 DEBG 'plexmediaserver' stderr output:
>Error starting framework core for /config/Plex Media Server/Plug-ins/Hama.bundle.

And the hama.log ends up with this:

>2020-09-25 16:59:08,908 (14e746f1af80) :  CRITICAL (core:615) - Exception starting plug-in (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c91f25744/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 608, in start
    self.sandbox.execute(self.init_code)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c91f25744/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 256, in execute
    exec(code) in self.environment
  File "/config/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 16, in <module>
    import tvdb4             # Functions: GetMetadata                                                Variables: None
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c91f25744/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 345, in __import__
    raise e

I think I've reached the limits of my Google-fu, so hopefully you can make sense of it?

Thanks so much in advance!

[Plex Media Server.log](https://github.com/ZeroQI/Hama.bundle/files/5285892/Plex.Media.Server.log)
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/5285893/com.plexapp.agents.hama.log)

**Comment by ZeroQI** [comment]
ImportError: No module named tvdb4
Do you have a file called tvdb4.py?
If not your are updating wrongly...

**Comment by sassyass** [comment]
hmmm this is what i did to update:

```
cd '/mnt/user/appdata/binhex-plexpass/Plex Media Server/Plug-ins/Hama.bundle'
git reset && git pull
chmod 775 -R '/mnt/user/appdata/binhex-plexpass/Plex Media Server/Plug-ins/Hama.bundle'
 
wget -O '/mnt/user/appdata/binhex-plexpass/Plex Media Server/Scanners/Series/Absolute Series Scanner.py' https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/Scanners/Series/Absolute%20Series%20Scanner.py
chmod 775 -R '/mnt/user/appdata/binhex-plexpass/Plex Media Server/Scanners'
```

maybe i will delete everything and just reinstall fresh i guess

**Comment by ZeroQI** [comment]
Please do

**Comment by sassyass** [comment]
ok, i reinstalled fresh and it does seem like it cleared up most of it. i still do have one series One Piece where none of the new episodes are getting metadata. when i do try a refresh on one of the uncooperative episodes, i see this in the log:

> 2020-09-26 15:29:50,318 (151f04449640) :  ERROR (model:205) - Cannot read model from /config/Plex Media Server/Metadata/TV Shows/1/9973dffa60352836b0b61ab0b88ccca067d00ff.bundle/Contents/com.plexapp.agents.hama
