### ISSUE TITLE
FreeNAS install location is out of date

### ISSUE THREAD

**Issue by skmagiik** [ZeroQI/Hama.bundle#426]
The new FreeNAS jail location seems to be in the 'jail root/Plex Media Server/Plug-ins'. 

~~However copying the Hama.bundle folders to there doesn't allow it to be picked up by my Plex install. 
EDIT: Absolute Series Scanner is working fine when installed but not Hama.bundle.~~
EDIT: Other issues were a lack of CHMOD on my part. Please disregard.

**Comment by skmagiik** [comment]
Checking the main server log (Plex Media Server/Logs/Plex Media Server.log) Hama.bundle says there is an error reading the Info.plist:

Oct 15, 2020 10:50:15.202 [0x80c5d0100] ERROR - Error reading file ["/Plex Media Server/Plug-ins/Hama.bundle/Contents/Info.plist"].
Oct 15, 2020 10:50:15.202 [0x80c5d0100] ERROR - Unable to scan bundle /Plex Media Server/Plug-ins/Hama.bundle: Empty or non-existant file.

I'm able to cat the file out in the freenas plex jail shell and see the plist file.

**Comment by ZeroQI** [comment]
The agent code is not loaded yet, these are the agent declaration issues, it seems like your Plex install/OS doesn't load third party agent, please check. ALso check rights

**Comment by ZeroQI** [comment]
"other issues" preclude the main issue, hence my confusion...

The agent is OS agnostic but since you now list the FreeNAS version so I amended the Readme
