### ISSUE TITLE
Porn thumbnail for El Melloi Case Files

### ISSUE THREAD

**Issue by reconman** [ZeroQI/Hama.bundle#429]
I added https://www.thetvdb.com/series/lord-el-melloi-iis-case-files-rail-zeppelin-grace-note to my library via the anidb ID and the following poster was shown:
![Screenshot_20201022-225949](https://user-images.githubusercontent.com/12360257/96930210-a3887100-14bb-11eb-9dd9-5a0be3689d37.jpg)

Where does it come from?

**Comment by ZeroQI** [comment]
Where did the HAMA series logs said it came from?
It is clearly indicated in logs which source provided it, located in agent data folders

**Comment by reconman** [comment]
Here's the log: https://pastebin.pl/view/raw/07aff6dc

The series is associated with the porn movie via TheMovieDB via the AniDB mapping. It's linked to TMDB ID 85368. But there are 2 entries with that ID, one is https://www.themoviedb.org/movie/85368-lesbian-legal-4 and the other one is https://www.themoviedb.org/tv/85368.

**Comment by ZeroQI** [comment]
[x] posters                  ( 1)  Sources: tvdb4, (TheMovieDb), TheTVDB, AniList, FanartTV, AniDB        Inside: '['FanartTV', 'TheTVDB', 'AniDB', 'TheMovieDb', 'AniList']'  Value: '{'https://image.tmdb.org/t/p/original/f3UVCBf4czRuBX77o0VsiZd1VLU.jpg': ('TheMovieDb/poster/f3UVCBf4czRuBX77o0VsiZd1VLU.jpg', 17, None)}'

So in short, the MovieDB meta for movies instead of series is picked up...

**Comment by reconman** [comment]
So, is there anything you can do to influence which one gets picked? For example, if the anidb entry is a series, look for the series with that ID?

**Comment by ZeroQI** [comment]
TheMovieDb API url need to be found for movies and series and Hama code to load the relevant one depending if a movie or series. Am on my phone so taking notes for later, but if I had url pulling the series and movies with the same ID, it would be basically solved

**Comment by EndOfLine369** [comment]
There is nothing we can do here. Scudlee mapping is incorrect. They put a series # when it should be a movie # and Scudlee mapping has now current way to differentiate what is a series or movie #.
Feel free to open up a new ticket or add to https://github.com/ScudLee/anime-lists/issues/342 .
