### ISSUE TITLE
Switch anime lists

### ISSUE THREAD

**Issue by mweber03** [ZeroQI/Hama.bundle#433]
Recommend switching to https://github.com/Anime-Lists/anime-lists since it'll be better maintained by @sven-7.

**Comment by ZeroQI** [comment]
Already discussed in https://github.com/ZeroQI/Absolute-Series-Scanner/issues/315#issuecomment-733890450

If somebody do a pull request, will approve straight away

**Comment by sven-7** [comment]
This can close now. I can’t close on HAMA.
