### ISSUE TITLE
Overseerr HAMA AniDB Support (through AniDBTVDBMap)

### ISSUE THREAD

**Issue by DJScias** [ZeroQI/Hama.bundle#436]
Hello there,

Lately there's a new promising "request management" system on the block available for Plex and it's called [Overseerr](https://github.com/sct/overseerr) (it's basically like Ombi).

They've recently (today) added support for animes added with HAMA that follow the TVDB standard: https://github.com/sct/overseerr/commit/ffe9e19c3b99de6af1185900e292da641ff44320

However, I've noticed (after using HAMA for a while now) that HAMA has a `AniDBTVDBMap` function that makes AniDB connect to TVDB and vica versa. As shown for example with this example:
```
=== Update() ================================================================================================================================================
id: anidb-13643, title: None, lang: en, force: True, movie: False
start: 2020-11-12 01:51:42,121400
=== AnimeLists.GetMetadata() ================================================================================================================================
tvdb_numbering: False
Local custom mapping file not present: anime-list-custom.xml
--- AniDBTVDBMap --------------------------------------------------------------------------------------------------------------------------------------------
[+] AniDBid: 13643, TVDBid: 353666, defaulttvdbseason:    0, offset:   1, TMDBid:  495907, IMDBid:           , name: Fate/Grand Order: Moonlight/Lostroom
             -----          ------
             13643          353666
[ ] collection: TVDBid '353666' is part of collection: '['Fate/Grand Order: Zettai Majuu Sensen Babylonia Collection']', related_anime_list: ['12519', '13643', '13644', '14238', '14239', '14579']
[ ] studio: 
--- return --------------------------------------------------------------------------------------------------------------------------------------------------
AniDB_id: '13643', AniDB_id2: '13643', AniDBid: '13643', TVDB_id: '', TVDB_id2: '353666', TVDBid: '353666'
```
Info: We started with AniDB 13643 and eventually we got TVDB (and TVDB_id2) 353666.

I spoke to the people at Overseerr and they told me that they'd have no issue in supporting more ways of HAMA but the issue is that there's no anidb support (right now?).

However, they did mention that they can support more of HAMA if the TVDB (and AniDB perhaps future-wise) are exposed by having it written in the XML somewhere.

I can probably ask them what that entails if that makes no sense (in its current form), but once it's exposed in XML then the program (and others) can pick this up and then even HAMA items with AniDB (that get mapped/linked with TVDB entries) can work like the TVDB additions in HAMA with Overseerr.

**Comment by ZeroQI** [comment]
https://github.com/mmozeiko/overseerr/commit/cab03fdafbe873e43ab90280c516e758dc68386c
https://github.com/mmozeiko/overseerr/commit/521e53f297fdc3eca3bd7e301e130c943bd9a8d0
Seem like a commit 5 days and also 13 hours ago was done "feat: map AniDB IDs from Hama agent to tvdb/tmdb/imdb IDs "
https://github.com/sct/overseerr/pull/538

**Comment by ZeroQI** [comment]
Clear sing as nothing expected agent side.
Please reply if I can assist in any wat
