### ISSUE TITLE
Disable collection for series/minimal threshold to create them

### ISSUE THREAD

**Issue by Hakujou** [ZeroQI/Hama.bundle#437]
Hello,

I currently have an issue with HamaTV: it creates collections for a lot of animes I got, which have only one season.
I don't want collections containing single items, and a lot of collections are having Japanese (kanjis) names, while I want x-jat names.

I tried deleting them, but then refreshing all metadata recreates them.

I tried to set Collections parameter to "Local" only in Hama settings, but it looks like the setting is only for movies (T--M).
Is there a way to disable HamaTV collections for series ?
An option that would be nice for users wanting them is also threshold (which is available on official Plex Movie agent), which means collections won't be created for single items.

I don't think logs are needed as this doesn't look like a bug, but please let me know if they are necessary.

Thanks!

**Comment by ZeroQI** [comment]
Set it to 'None'
If it still sets it, please confirm as the code may need to be corrected, but I believe this is not the case

'Local' is for using grouping folders (folder at root with series folder inside) as collection, which is the most versatile way to set it up...

Since the collection is set per series, I cannot know in advance the number of items in a collection, so the above allow you to group series in collections simply...

**Comment by sven-7** [comment]
If you want collection metadata and do not want it to reset after you cleaned it up, you need to do this next time you clean...

1. Open the series and go to Tags.
2. Delete your collection from it.
3. Click the lock button on the side (see below). This will prevent the metadata repopulating when you refresh your library. 
4. You'll need to Open collections and delete the empty collection folder.

<img width="701" alt="Screen Shot 2021-01-03 at 1 32 42 PM" src="https://user-images.githubusercontent.com/18091557/103485976-547f8600-4df2-11eb-8cec-29dc9a388510.png">

**Comment by Hakujou** [comment]
> Set it to 'None'
> If it still sets it, please confirm as the code may need to be corrected, but I believe this is not the case
> 
> 'Local' is for using grouping folders (folder at root with series folder inside) as collection, which is the most versatile way to set it up...
> 
> Since the collection is set per series, I cannot know in advance the number of items in a collection, so the above allow you to group series in collections simply...

I also tried None, it's still getting updated.
Is that unexpected ? I thought the "Collection" settings was only for movies (as it's T--M and not TS-M). Or my understanding of letter code is wrong ?



> If you want collection metadata and do not want it to reset after you cleaned it up, you need to do this next time you clean...
> 
> 1. Open the series and go to Tags.
> 2. Delete your collection from it.
> 3. Click the lock button on the side (see below). This will prevent the metadata repopulating when you refresh your library.
> 4. You'll need to Open collections and delete the empty collection folder.
> 
> <img alt="Screen Shot 2021-01-03 at 1 32 42 PM" width="701" src="https://user-images.githubusercontent.com/18091557/103485976-547f8600-4df2-11eb-8cec-29dc9a388510.png">

Did not thought of that.
It indeed works (but is a little tedious for large libraries such as mine).

**Comment by sven-7** [comment]
Definitely tedious, but once you do it once it's done. Then you just have to maintain going forward. Just wanted to toss that option out there.

**Comment by ZeroQI** [comment]
Collection exists for series so definitely TS-M.
As such if still updated when set to None, that means the code doesn't check the setting and needs correcting

**Comment by Hakujou** [comment]
Got it, please let me know if you need details or want me to test something

**Comment by ZeroQI** [comment]
Logs. We need to know which source provided collection fields not following the agent settings

**Comment by Hakujou** [comment]
Here you go.
[logs_hama.zip](https://github.com/ZeroQI/Hama.bundle/files/5765913/logs_hama.zip)

One example that should be available in the logs that I've seen happening in live is Accel World (it created "アクセル・ワールド Collection" and moved Animes in it).
The whole library refresh was not done but it takes days to complete so I figured it would be faster to give you current logs and an example.

**Comment by ZeroQI** [comment]
Accel World.agent-update.log
Accel World - Infinite Γê₧ Burst.agent-update.log

Hama logs show the following agent settings:
- Prefs[collections            ] = Local                                                          (Default: Local, AniDB, TheMovieDb, AnimeLists)

The source 'Local' would mean grouping folders would be used as collection, but none were (Grouping folder not found for Accel World)
A collection field is in AnimeLists ('Accel World Collection') but not the one title in Kanji you mention, and could not find the field "collections" in the table of updated fields at the end of the log...

The engine is in https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/common.py lines 666-688

Check your secondary agents (Lambda?), doesn't look like HAMA provide that field, especially if disabled in the settings...

**Comment by Hakujou** [comment]
I tried on a fresh install and set to None and I cannot reproduce the issue.
I wonder if the clean bundle would have helped, maybe there was some setting cache at some level.

Anyway, not sure of what happened, but since I can't reproduce it on a fresh install, the issue was probably on my side, closing this issue then. Thanks for the help! :)
