### ISSUE TITLE
Some metadata from tvdb instead of anidb [anidb-12014]

### ISSUE THREAD

**Issue by olehag** [ZeroQI/Hama.bundle#439]
On the Anime serie "91 Days"
Special episode "91 Days - S1 - Shoal of Time / All Our Yesterdays / Tomorrow and Tomorrow".
I get the title for S2, but the description is correct
![image](https://user-images.githubusercontent.com/26063307/104008902-6ffbdf80-51aa-11eb-9432-89ab9e17cf82.png)
Red- title from episode 2.
green- description from correct ep, from Anidb.

Hama agent title settings:
![image](https://user-images.githubusercontent.com/26063307/104009047-b18c8a80-51aa-11eb-96b3-dd74c35b5c6c.png)

Is this a ScudLee mapping issue, same as #362  ? im unsure since some metadata is correct..

[[Beatrice-Raws] 91 Days [BDRip 1920x1080 x264 FLAC][anidb-12014].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5786817/Beatrice-Raws.91.Days.BDRip.1920x1080.x264.FLAC.anidb-12014.agent-update.log)

**Comment by ZeroQI** [comment]
I spent weeks so all info needed is in the logs, but at least, you did include them to your first post so i will explain the behaviour:

metadata.seasons[ 0].episodes[  1]
[?] rank: 1, source_title:   AniDB, title: "Shoal of Time / All Our Yesterdays / Tomorrow and Tomorrow"
[?] rank: 0, source_title: TheTVDB, title: "Brief Candle"
[=] title                          Sources:  AniDB, TheTVDB| AniDB, (TheTVDB)                             Inside: '['TheTVDB', 'AniDB']'  Value: 'Brief Candle'
[=] summary                        Sources: (AniDB), TheTVDB                                              Inside: '['TheTVDB', 'AniDB']'  Value: 'Flashback stories'
[=] originally_available_at        Sources: (AniDB),TheTVDB                                               Inside: '['TheTVDB', 'AniDB']'  Value: '2017-07-05'
[=] writers                  ( 2)  Sources: AniDB,(TheTVDB)                                               Inside: '['TheTVDB']'  Value: '[u'Hiro Kaburagi', u'Taku Kishimoto']'
[=] directors                      Sources: (AniDB),TheTVDB                                               Inside: '['TheTVDB', 'AniDB']'  Value: 'Kaburagi Hiro'
[=] producers                      Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Kishimoto Taku'
[=] thumbs                   ( 1)  Sources: (TheTVDB)                                                     Inside: '['TheTVDB']'  Value: '{'https://thetvdb.plexapp.com/banners/episodes/309530/5704266.jpg': (u'TheTVDB\\episodes\\5704266.jpg', 1, None)}'
[=] duration                       Sources: (TheTVDB), AniDB, MyAnimeList, TheMovieDb, OMDb               Inside: '['TheTVDB', 'AniDB']'  Value: '1500000'
[=] content_rating                 Sources: AniDB,(TheTVDB)                                               Inside: '['TheTVDB']'  Value: 'TV-MA'
[!] 'Anidb' source not in MetaSources dict, please Check case and spelling

TheTVDB (there is a 'x' if the file is present locally)
```
TVDBid: '309530', IMDbid: '', language_series : ['en', 'ja'], language_episodes: ['en', 'ja']
common.LoadFile() - File cached locally - Filename: 'TheTVDB\json\309530\episodes_page1_en.json', Age: '0.73 days', Limit: '6 days', url: 'https://api.thetvdb.com/series/309530/episodes?page=1'
[X]    s0e1 s00e001 anidbid:   12014 air_date: 2016-08-27 abs_number: 0, title: Brief Candle
 - [1] title:   [en] Brief Candle
 - [1] summary: [en] Recap of the first seven episodes. (official Site Call Episode 7.5)
```
In your case takes AniDB before TVDB (series|episode priorities, '()' around the selected one AND it even states which sources have a field for that filed) **however** the language priority (language_episodes: ['en', 'ja']) made TVDB first

Thetvdb s00e01 is called 'Brief Candle' https://thetvdb.com/series/91-days/episodes/5704266
AniDB s00e01 is shoal of times, s01e02 is 'Brief Candle' https://anidb.net/anime/12014
Sven7's fork of ScudLee's AnimeList: https://github.com/Anime-Lists/anime-lists/blob/master/anime-list-master.xml
```
  <anime anidbid="12014" tvdbid="309530" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>91 Days</name>
  </anime>
```

Working as designed as the specials are not mapped and the first two specials are swapped between anidb and TheTVDB
```
  <anime anidbid="12014" tvdbid="309530" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>91 Days</name>
      <mapping anidbseason="0" tvdbseason="0">;1-2;2-1;3-3;4-4;5-5;6-6;7-7;8-8;9-9;</mapping>
  </anime>
```
Submitted https://github.com/Anime-Lists/anime-lists/issues/30

**Comment by olehag** [comment]
Thank you for laying it out for me like this! 👍 Seems i should've read the docs better.. rtfm tax paid.

**Comment by ZeroQI** [comment]
You attached logs on the first post and explained the issue so i gave due dilligence
The fix has been pushed by sven7 on the mapping file branch so if you delete the file cache in hama agent data folders, then plex cache (search manually for a title called 'clear-cache'), then refresh metadata, it should be good to go
