### ISSUE TITLE
Some Anime specials with air-date as the episode name

### ISSUE THREAD

**Issue by jvmunhoz** [ZeroQI/Hama.bundle#443]
I've been having lots of problems regarding the name of specials while using Hama+ASS. The anime I'm currently testing this with is [Akatsuki no Yona (2015)](https://anidb.net/anime/11143) and I can't for the life of me make the scanner recognize the proper name for the [Good Night for Today](https://anidb.net/episode/183623) special. While the [normal episodes get all the necessary metadata](https://i.imgur.com/vkMwxGx.png) without any issues, [the special has the air-date for a name](https://i.imgur.com/269CQSy.png) (the air-date is correct btw, so it should be getting the right episode). I definitely could just hardcode the name in the metadata, but I actually wanna understand what's happening.

I'm kinda new to Hama, so I may be making something wrong? That's a mapping issue?

Here are the logs:

[Akatsuki no Yona (2015) [anidb-11143].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/5876475/Akatsuki.no.Yona.2015.anidb-11143.filelist.log)
[Akatsuki no Yona (2015) [anidb-11143].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/5876476/Akatsuki.no.Yona.2015.anidb-11143.scanner.log)
[Akatsuki no Yona (2015) [anidb-11143].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5876444/Akatsuki.no.Yona.2015.anidb-11143.agent-update.log)

Anything else I should provide? 

Best regards

Edit: Fresh logs

**Comment by ZeroQI** [comment]
"Akatsuki no Yona (2015) [anidb-11143]\Specials\[UrbanTbc] Akatsuki no Yona OAD Bonus [DVDrip 848x480p][SoftSub].mkv" is mapped as S00e01 so the scanner did its job, and anidb id forced so using anidb numbering as base, so agent logs mandatory (and provided) and hold the answer as there is a clear readable output at the end

The agent find NO TITLE for it at the end though:
```
metadata.seasons[ 0]-----------------------------------------------------------------------------------------------------------------------------------------
metadata.seasons[ 0].episodes[  1]
[=] originally_available_at        Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: '2016-12-19'
[=] writers                        Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Kusanagi Mizuho'
[=] directors                      Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Yoneda Kazuhiro'
[=] duration                       Sources: TheTVDB, (AniDB), MyAnimeList, TheMovieDb, OMDb               Inside: '['AniDB']'  Value: '240000'
```

AniDB sees s01e01 without title line 196: ('X' means file present locally)
```
[X] s0e  1 => s0e  1 air_date: 2016-12-19 language_rank: 0, title: ""
 - [ ] summary: 
```

TheTVDB sees s00e01 translated as s01e01 so no metadata for s00e01: ('X' means file present locally)
```
[X]    s0e1 s01e001 anidbid:   11143 air_date: 2015-09-18 abs_number: 25, title: On That Back
 - [1] title:   [en] On That Back
 - [1] summary: [en] ona and the gang head to a hot springs hotel, where they are greeting by the owner, an old women who always dozes off. Later on, Jae-Ha wonders why Kija has not entered the men's bath, discovering that Kija has a scar on his back shaped like claw marks and coming to the conclusion that the previous white dragon warrior scarred Kija's back.
```

Mapping AniDB-TheTVDB is wrong, so let's look at the XML mapping [https://raw.githubusercontent.com/Anime-Lists/anime-lists/master/anime-list-master.xml]
```
  <anime anidbid="11143" tvdbid="283942" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Akatsuki no Yona (2015)</name>
  </anime>
```

Looking at episode mapping manually:
- tvdb https://thetvdb.com/series/yona-of-the-dawn/allseasons/official
- anidb https://anidb.net/anime/11143
- mapping: anidb s01e01-03, s00e01 =>tvdb s00e01-03, s00e04

Mapping file is wrong in mapping file, as s01e01-03 are mapped to s00e01-03 through [defaulttvdbseason="0"]
s00e01 should map to s00e04, it is missing, the mapping should be as below:
```
  <anime anidbid="11143" tvdbid="283942" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Akatsuki no Yona (2015)</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-4;</mapping>
    </mapping-list>
  </anime>
```
- defaulttvdbseason="0" so the season eps 1-3 are mapped to season 0
- mapping so anidb season 0 ep 1 (1-...) mapped to tvdb season 0 e 4 (...-4)

You will need to:
- wait for the mapping XML to be fixed
- delete the file cache for it in agent data folders
- update the metadata
- Consider donating as it is not an agent issue, but a mapping issue, which could be spoted by checking anidb and tvdb episode title which did not match the mapping file

**Comment by jvmunhoz** [comment]
Really an amazing explanation, @ZeroQI thank you!

I kinda got the gist of it after reading your explanations, not only on how to identify what mapping problem is happening, but also on how to fix it.

To test it, I created a local _anime-list-custom.xml_ with your provided fix (learned this by reading a previous issue :P) and cleared my cache. It indeed fixed the issue, [as you can see here](https://i.imgur.com/fi1OlWH.png) and by the provided [log](https://github.com/ZeroQI/Hama.bundle/files/5876931/Akatsuki.no.Yona.2015.anidb-11143.agent-update.log)

 I was also having this same problem on other animes, so I'll try to fix it by myself, and creating issues (or PRs?) on anime-lists as I go about doing it.

Thanks again! As for the donation, when I finish organizing my anime library, I probably will. You really deserve it!

PS: In mapping issues such as this, should I close the issue now or do I wait for the issue in anime-lists to be fixed?

**Comment by ZeroQI** [comment]
If the fix is confirmed to fix, then the issue is resolved from the agent perspective and queued to be added shortly

You can create the PR (better) or bug report (that's what i did, got lazy) once you tested locally, to avoid incorrect PR, but use Sven's 7 fork as we switched recently in code, due to Scudlee one seemingly no longer be maintained [https://github.com/Anime-Lists/anime-lists]
