### ISSUE TITLE
6 series out of over 300 do not load metadata correctly.

### ISSUE THREAD

**Issue by Tyestor** [ZeroQI/Hama.bundle#445]
All series are using forced AniDB IDs in the folder names. Logs attached - I deleted all previous logs and did a clean scan.

The series in question:

**Night Raid 1931** - Not detecting at all. No idea what the issue is

[Senkou no Night Raid [anidb-7278].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/5897696/Senkou.no.Night.Raid.anidb-7278.agent-search.log)
[Senkou no Night Raid [anidb-7278].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/5897697/Senkou.no.Night.Raid.anidb-7278.filelist.log)
[Senkou no Night Raid [anidb-7278].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/5897698/Senkou.no.Night.Raid.anidb-7278.scanner.log)

**Pokémon: Diamond and Pearl** - Incorrectly detecting as TheTVDB's [Pokémon](https://thetvdb.com/series/pokemon) even though I have forced the folder to use AniDB's [Pokemon: Diamond and Pearl](https://anidb.net/anime/4728) ID. All other Pokémon series detect correctly, I will include their logs.

[Pokemon - Advanced Generation Series [anidb-1041].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/5897700/Pokemon.-.Advanced.Generation.Series.anidb-1041.filelist.log)
[Pokemon - Best Wishes Series [anidb-7891].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5897701/Pokemon.-.Best.Wishes.Series.anidb-7891.agent-update.log)
[Pokemon - Best Wishes Series [anidb-7891].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/5897702/Pokemon.-.Best.Wishes.Series.anidb-7891.filelist.log)
[Pokemon - Diamond and Pearl Series [anidb-4728].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/5897703/Pokemon.-.Diamond.and.Pearl.Series.anidb-4728.filelist.log)
[Pokemon - Original Series [anidb-230].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/5897704/Pokemon.-.Original.Series.anidb-230.filelist.log)

I do not know what the issue is with these last four, however, there is an interesting pattern. All four AniDB IDs start with 0. Also, there is an error in the log file "Anime - anime-list AniDBid missing.htm" which lists all four as not having AniDB IDs.

**Fullmetal Alchemist: Brotherhood** 

[Fullmetal Alchemist - Brotherhood [anidb-06107].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/5897706/Fullmetal.Alchemist.-.Brotherhood.anidb-06107.filelist.log)
[Fullmetal Alchemist - Brotherhood [anidb-06107].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/5897707/Fullmetal.Alchemist.-.Brotherhood.anidb-06107.scanner.log)
[Fullmetal Alchemist - Brotherhood [anidb-06107].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5897708/Fullmetal.Alchemist.-.Brotherhood.anidb-06107.agent-update.log)

**Samurai Champloo**

[Samurai Champloo [anidb-01543].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5897710/Samurai.Champloo.anidb-01543.agent-update.log)

**School Rumble**

[School Rumble [anidb-02165].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5897711/School.Rumble.anidb-02165.agent-update.log)

**Serial Experiments Lain**

[Serial Experiments Lain [anidb-00099].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5897715/Serial.Experiments.Lain.anidb-00099.agent-update.log)

**Other logs**

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/5897727/com.plexapp.agents.hama.log)
[com.plexapp.system.log](https://github.com/ZeroQI/Hama.bundle/files/5897728/com.plexapp.system.log)

**Anime - anime-list AniDBid missing.htm** (can't upload .htm)
![image](https://user-images.githubusercontent.com/4704145/106353358-de334e00-62e1-11eb-9e60-f8ee28681faa.png)

Thanks for any help you can provide.

**Comment by Tyestor** [comment]
So I just fixed 

- Fullmetal Alchemist: Brotherhood
- Samurai Champloo
- School Rumble
- Serial Experiments Lain

by deleting the leading zeroes. 

Both https://anidb.net/anime/00099 and https://anidb.net/anime/99 work so it's kind of strange that leading zeroes are ignored in hama.

**Comment by Tyestor** [comment]
Alright, I also managed to fix both

- Senkou no Night Raid - Renamed the folder "Senkou no Night Raid - Specials" to just "Specials")
- Pokemon: Diamond and Pearl - Renamed all seasons so they follow TheTVDB order (Season 1-19) rather than restarting from Season 1 when changing series (Pokemon Original series (Season 1-5), Pokemon Advanced Series (Season 1-4) etc... Although for some reason Pokemon Original series and Pokemon Advanced series detected perfectly fine without changing season ordering numbers.

**Comment by ZeroQI** [comment]
Never have seen leading zeroes with Anidb IDs... Indeed they are not supported.
Season folder numbering is precise.

Sometime the XML mapping file is not up to date, but if you have multiple seasons, like pokemon, using the numbering make sense
