### ISSUE TITLE
Can't look for adult anime from anidb

### ISSUE THREAD

**Issue by LeoNg628** [ZeroQI/Hama.bundle#450]
Hi, I can't search for a15855 via HAMATV agent...anyone could help? Thanks.

**Comment by ZeroQI** [comment]
Search "xxx [anidb-15855]".
Please use forums.plex.tv for use request

**Comment by LeoNg628** [comment]
Thanks.
https://forums.plex.tv/t/rel-http-anidb-metadata-agent-hama/40470/2053
