### ISSUE TITLE
Add support for season names (new in Plex Web 4.52.1)

### ISSUE THREAD

**Issue by jgilf** [ZeroQI/Hama.bundle#452]
As Plex Web 4.52.1 has officially added the option to manually set/change season names, would it be possible for this to be implemented into ASS? This will be especially useful for tvdb4 (for story arcs) and Youtube playlist mapping.  

See below example:

![Screenshot from 2021-02-24 00-43-49](https://user-images.githubusercontent.com/5531002/108852276-81edf080-7639-11eb-80c6-c330077f3833.png)

I'm 90% sure this is a Scanner request but please advise if this is actually more relevent to the HAMA/Youtube-Agent bundles.

Thanks!

**Comment by sven-7** [comment]
Probably related to enhancement #354 too.

**Comment by ZeroQI** [comment]
Correct: https://forums.plex.tv/t/implemented-custom-names-for-seasons-anime-season-naming/123837/15
seem like it will be possible agent wise

on a side note mame on plex??? https://arstechnica.com/gaming/2021/01/plex-adds-game-streaming-as-paid-add-on-completely-botches-the-landing/

**Comment by jgilf** [comment]
> Correct: https://forums.plex.tv/t/implemented-custom-names-for-seasons-anime-season-naming/123837/15
> seem like it will be possible agent wise

I was just reading this thread, looks encouraging. Hopefully they fix those othe metadata entries while they are at it. It would be great to be able to populate season descriptions as well. 


> on a side note mame on plex??? https://arstechnica.com/gaming/2021/01/plex-adds-game-streaming-as-paid-add-on-completely-botches-the-landing/

Gotta find a way to get everyone who bought lifetime Plex Passes to couch up more dough!

**Comment by sven-7** [comment]
I'm curious where they're pulling that data from. If you look at the Ghost in the Shell example, I'm not seeing that title or season description anywhere in the JSON for GITS:SAC. So...either HAMA is not pulling everything available down or Plex has some different method of pulling data via their API?

**Comment by ZeroQI** [comment]
It doesn't matter where from. I support and and thetvdb, and we already have tvdb4 titles so as long as the agent can access the fields we can set them.

Current plex web version is one version behind so we need to wait

**Comment by sven-7** [comment]
I was just commenting that I didn't see the metadata or fields they had used in any of the JSON files.

**Comment by ZeroQI** [comment]
Closing other request https://github.com/ZeroQI/Hama.bundle/issues/354, but good notes in it for reference

**Comment by ZeroQI** [comment]
https://github.com/suparngp/plex-personal-shows-agent.bundle show how to use web API to update field
Pending official release of 4.52.1 (no longer beta access) before looking into it

**Comment by ZeroQI** [comment]
Still PlexWeb Version 4.51.3 on windows

**Comment by ZeroQI** [comment]
Plex Web Version 4.54.5 on windows
Did code change locally, not updating in GUI...
