### ISSUE TITLE
Monogatari episodes not updating after upstream fix

### ISSUE THREAD

**Issue by cure1245** [ZeroQI/Hama.bundle#453]
Encountered issue in #358 regarding Sugura Devil episode 2 and Tsukimonogatari episode 2. @EndOfLine369  mentioned that the issue is due to duplicate mappings in the Anime-list, but the issue is persisting after an upstream pull request fixed the mappings:

```
 <anime anidbid="10046" tvdbid="102261" defaulttvdbseason="0">
    <name>Hanamonogatari: Suruga Devil</name>
    <mapping-list>
      -----<mapping anidbseason="1" tvdbseason="0">;1-10;2-10;3-11;4-12;5-13;6-14;</mapping>
      +++++<mapping anidbseason="1" tvdbseason="0">;1-0;2-10;3-11;4-12;5-13;6-14;</mapping>
    </mapping-list>
  </anime>
  <anime anidbid="10049" tvdbid="284795" defaulttvdbseason="1">
-------------------------------------------------------------------------------------------------
  <anime anidbid="10891" tvdbid="102261" defaulttvdbseason="0">
    <name>Tsukimonogatari: Yotsugi Doll</name>
    <mapping-list>
      -----<mapping anidbseason="1" tvdbseason="0">;1-15;2-15;3-16;4-17;5-18;</mapping>
      +++++<mapping anidbseason="1" tvdbseason="0">;1-0;2-15;3-16;4-17;5-18;</mapping>
    </mapping-list>
  </anime>
  <anime anidbid="10892" tvdbid="279830" defaulttvdbseason="0">
```

I verified that the cached version of the master XML file was up-to-date by manually replacing it, but the issue seems to persist. Any ideas?

**Comment by cure1245** [comment]
Apparently there was something else that was cached--maybe the TVDB return info? I don't know: point is, it's working now after giving it a bit longer to stew.

**Comment by ZeroQI** [comment]
There is a Plex cache (custom match manually by searching "clear-cache") and a file cache in agent data folder
Monogatari being known as the trickiest to organise so requiring the most mappings due to the number of series
