### ISSUE TITLE
Title not present in anime-titles.xml

### ISSUE THREAD

**Issue by Columbo199X** [ZeroQI/Hama.bundle#455]
This is not an issue but rather a question. I'm trying to add Tenkuu Shinpan (anidb 15811) to my library. However it doesn't show any metadata. I noticed that Tenkuu Shinpan isn't listed  in the `anime-titles.xml`. Can this be fixed by updating the anime-titles.xml located in `Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\AniDB`?

**Comment by ZeroQI** [comment]
Anidb has the entry [https://anidb.net/anime/15811] so your xml is outdated
- check the file date, update the xml, or delete it, and restart plex and it will update
TheTVDB has the entry [https://thetvdb.com/series/high-rise-invasion]
Anime-Lists has both AniDB and TheTVDB entries [https://github.com/Anime-Lists/anime-lists]
```
<anime anidbid="15811" tvdbid="391006" defaulttvdbseason="1">
    <name>Tenkuu Shinpan</name>
  </anime>
```

**Comment by Columbo199X** [comment]
> check the file date, update the xml, or delete it, and restart plex and it will update
I've done that but the anime-titles.xml file get's deleted when I update my library.
Am I doing something wrong?
