### ISSUE TITLE
Incorrect critic rating pulled

### ISSUE THREAD

**Issue by Gumbyohson** [ZeroQI/Hama.bundle#460]
When refreshing metadata today the ratings of several anime appear to be incorrect. I updated Hama and the scanner both before starting and I have attempted to refresh and replace the data several times. My hamatv settings have T-EM 'rating' set as MyAnimeList, AniDB | MyAnimeList, AniDB. I have also tried to reset the rating to defaults with the same results: AniDB, TheTVDB, MyAnimeList, TheMovieDb, OMDb | TheTVDB, AniDB
The specific examples I have are
Vivy anidb 83/100: 15988 | tvdb 100/100: 397774
[Vivy -Fluorite Eye's Song-.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/6371398/Vivy.-Fluorite.Eye.s.Song-.agent-update.log)

One Piece  83/100: 69 (nice) | tvdb 53/100: 81797
[One Piece.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/6371397/One.Piece.agent-update.log)

I use tvdb IDs because of the Specials episodes ordering but I don't want the ratings from tvdb at all and thought removing it from the ratings option would be enough.
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/6371421/com.plexapp.agents.hama.log)
[_root_E -Matt's-Anime Shows.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/6371428/_root_E.-Matt.s-Anime.Shows.scanner.log)
[_root_E -Matt's-Anime Shows.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/6371429/_root_E.-Matt.s-Anime.Shows.filelist.log)

**Comment by Gumbyohson** [comment]
So; update to this. It appears that this mainly occurs when using plex "fix match" and then using [tvdb-XXXXX]. When using "fix match" and just accepting the default result it mainly works :\

**Comment by ZeroQI** [comment]
Vivy anidb 83/100: 15988 | tvdb 100/100: 397774
`[x] rating                         Sources: (MyAnimeList), AniDB | MyAnimeList, AniDB                     Inside: '['MyAnimeList', 'AniDB']'  Value: '8.34'`
https://myanimelist.net/anime/46095/Vivy__Fluorite_Eyes_Song?q=Vivy%20-Fluorite%20Eye%27s%20Song&cat=anime inficate 8.34 with 16687 users => correct
https://atarashii.fribbtastic.net/web/2.1/anime/46095
`"members_score":8.34,"members_count":114809`

One Piece 83/100: 69 (nice) | tvdb 53/100: 81797
`[=] rating                         Sources: (MyAnimeList), AniDB | MyAnimeList, AniDB                     Inside: '['MyAnimeList', 'TheTVDB', 'AniDB', 'TheMovieDb']'  Value: '5.29'`
https://myanimelist.net/anime/21/One_Piece indicate 8.54 with 806612 users
https://atarashii.fribbtastic.net/web/2.1/anime/36239
`members_score":5.29,"members_count":4033,"favorited_count":5`

In your logs, you selected MyAnimeList to provide the series rating first, and it did.
Look like MyAnimeList API give dodgy score, so remove it from the selection.

> I have also tried to reset the rating to defaults with the same results: AniDB, TheTVDB, MyAnimeList, TheMovieDb, OMDb | TheTVDB, AniDB

Well logs don't reflect that, so you probably didn't refresh the series metadata after that...

**Comment by ZeroQI** [comment]
> So; update to this. It appears that this mainly occurs when using plex "fix match" and then using [tvdb-XXXXX]. When using "fix match" and just accepting the default result it mainly works :\

It doesn't make any difference, the agent uses the unique id assigned by search function.
Logs will show at the end the value assigned, the order in setting and in parenthesis the oe that gave the result, and you can go search in the logs for that source why it gave the value...

**Comment by Gumbyohson** [comment]
Thanks so much. I didn't see that in the logs. The defaults reset was after I extracted the logs so that's why it didn't show.

**Comment by Gumbyohson** [comment]
BTW, how do I donate? I was hoping to chuck you some dollars.

**Comment by ZeroQI** [comment]
I put a link at the very bottom of the read-me for both ASS and HAMA...
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=S8CUKCX4CWBBG&lc=IE&item_name=ZeroQI&item_number=Absolute%20Series%20Scanner%20%2b%20Http%20AniDB%20Metadata%20Agent&currency_code=EUR&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted

**Comment by Gumbyohson** [comment]
So weird, vivy and nagatoro are both still giving results that are way too high based on anidb results. I've removed the Mal and tvdb options from the ratings section.

If I do fix match anidb-xxxxxx for each I get the right score but if I use tvdb default result it's wrong. Is it possible that it's missing the cross source db entry? I searched the original XML before for vivy and didn't see a result.

**Comment by ZeroQI** [comment]
HAMA cross references series and episodes between AniDB and TheTVDB based on the XML Anime lists database. If no mapping then it cannot indeed...

**Comment by ZeroQI** [comment]
Any issur remaining? if so paste the tvdb and anidb page link and can generate the correct mapping if you failed to do so

**Comment by Gumbyohson** [comment]
Thanks, I haven't been able to find time. You don't need to worry if it's
inconvenient. I'm sure someone will update it even if we don't.
