### ISSUE TITLE
One Piece episodes showing incorrect release dates

### ISSUE THREAD

**Issue by GodKratos** [ZeroQI/Hama.bundle#462]
A lot of the One Piece episodes are showing the incorrect release dates for the episodes.
I tried doing the Plex Dance on them to see if the metadata was wrong but they updated with the same release dates again.

This is season 1 which was released end of 1999 but release dates are all showing 2019
![image](https://user-images.githubusercontent.com/692616/116971553-daaec900-ad0d-11eb-94c9-921f7ba9dd43.png)

I'm using tvdb4 mapping and both TVDB and AniDB have the correct dates so I'm not sure where it's picking these dates up from.

**Comment by GodKratos** [comment]
This is an example of what the agent-update.log is showing for the show.

![image](https://user-images.githubusercontent.com/692616/116984446-5feea980-ad1f-11eb-87ad-1e09b343b854.png)

**Comment by ZeroQI** [comment]
Which metadata source used for each field and which provided the field is indicated in the custom series log in agent data folders, as per the readme troubleshooting section, whish you have pasted an extract from...

The picture clearly show AniDB gave the date.
I need the logs to get the anidb API url used and see if the dates are wrong indeed

**Comment by GodKratos** [comment]
This file?
[One Piece [tvdb4-81797].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/6421299/One.Piece.tvdb4-81797.agent-update.log)

**Comment by GodKratos** [comment]
I have this weird bug where the posters are not mapping correctly too, which I'm not sure if it is related or not.
![image](https://user-images.githubusercontent.com/692616/117011588-1499c280-ad42-11eb-8bc7-bf222fb40d77.png)
The log file above is showing the correct thumbs URLs and images but that is not what plex is showing.
Each episode seems to have multiple images for it, sometimes the correct one exists and I can switch to it but sometimes none of the images are the correct one.
![image](https://user-images.githubusercontent.com/692616/117011827-5f1b3f00-ad42-11eb-9a54-88b254f1fe36.png)

**Comment by ZeroQI** [comment]
**Screenshot**
If the right screenshot is indicated, it's a Plex issue (OR the season/episode number screenshot changed and it kept the old one, and will not make the latest one downloaded the active one)
you need to move the episode, empty trash and clear bundles to have an effect as part of the Plex dance

I could empty the thumbnails t keep only the latest ones, but will mean more downloads, and TVDB might stop the free API any day now so...

**Release date**
Wrong date from ANiDB int the summary table at the end, after looking at AniDB log part, the eps are mapped to wrong TVDB episode season and number
```
[X] s1e877 => s6e 98 air_date: 2019-03-24 language_rank: 1, title: "The Parting Time! Pudding's Last Wish!"
[X] s1e878 => s1e  1 air_date: 2019-03-31 language_rank: 1, title: "The World Is Stunned! The Fifth Emperor of the Sea Emerges!"
[X] s1e891 => s1e 14 air_date: 2019-06-30 language_rank: 1, title: "Climbing up a Waterfall! A Great Journey Through the Land [X] s1e892 => s1e  1 air_date: 2019-07-07 language_rank: 1, title: "The Land of Wano! To the Samurai Country Where Cherry [X] s1e905 => s1e 14 air_date: 2019-10-06 language_rank: 1, title: "Taking Back Otama! A Fierce Fight Against Holdem!"
```

tvdb4 mapping look OK: https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/tvdb4.mapping.xml

https://raw.githubusercontent.com/Anime-Lists/anime-lists/master/anime-list-master.xml
There seem to be bugs in the last two entries ONLY.
**Can you check your mapping file locally in HAMA Agent data folder cache for ANime-Lists ?**
```
  <anime anidbid="69" tvdbid="81797" defaulttvdbseason="a" episodeoffset="" tmdbid="" imdbid="">
    <name>One Piece</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-28;2-3;3-9;4-10;5-14;6-0;7-0;8-0;9-0;10-0;11-0;12-0;13-0;14-0;15-0;16-32;17-23;18-24;19-29;20-30;21-31;22-0;23-33;24-35;25-0;26-37;27-38;</mapping>
      <mapping anidbseason="1" tvdbseason="1" start="1" end="8"/>
      <mapping anidbseason="1" tvdbseason="2" start="9" end="30" offset="-8"/>
      <mapping anidbseason="1" tvdbseason="3" start="31" end="47" offset="-30"/>
      <mapping anidbseason="1" tvdbseason="4" start="48" end="60" offset="-47"/>
      <mapping anidbseason="1" tvdbseason="5" start="61" end="69" offset="-60"/>
      <mapping anidbseason="1" tvdbseason="6" start="70" end="91" offset="-69"/>
      <mapping anidbseason="1" tvdbseason="7" start="92" end="130" offset="-91"/>
      <mapping anidbseason="1" tvdbseason="8" start="131" end="143" offset="-130"/>
      <mapping anidbseason="1" tvdbseason="9" start="144" end="195" offset="-143"/>
      <mapping anidbseason="1" tvdbseason="10" start="196" end="226" offset="-195"/>
      <mapping anidbseason="1" tvdbseason="11" start="227" end="325" offset="-226"/>
      <mapping anidbseason="1" tvdbseason="12" start="326" end="381" offset="-325"/>
      <mapping anidbseason="1" tvdbseason="13" start="382" end="481" offset="-381"/>
      <mapping anidbseason="1" tvdbseason="14" start="482" end="516" offset="-481"/>
      <mapping anidbseason="1" tvdbseason="15" start="517" end="578" offset="-516"/>
      <mapping anidbseason="1" tvdbseason="16" start="579" end="628" offset="-578"/>
      <mapping anidbseason="1" tvdbseason="17" start="629" end="746" offset="-628"/>
      <mapping anidbseason="1" tvdbseason="18" start="747" end="779" offset="-746"/>
      <mapping anidbseason="1" tvdbseason="19" start="780" end="877" offset="-779"/>
      <mapping anidbseason="1" tvdbseason="20" start="878" end="891" offset="-877"/>
      <mapping anidbseason="1" tvdbseason="21" start="892" end="981" offset="-891"/>
    </mapping-list>
```

**Comment by sven-7** [comment]
I am also seeing the wrong dates for One Piece. The first 118 episodes, it looks like. Not sure if this has anything to do with the mapping that was put into https://github.com/Anime-Lists/anime-lists/ or not.

[One Piece.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/6423331/One.Piece.filelist.log)
[One Piece.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/6423332/One.Piece.scanner.log)
[One Piece.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/6423333/One.Piece.agent-update.log)

**Comment by ZeroQI** [comment]
anidb to tvdb in scanner log works great
anidb.py 276-287: calculate new season and ep number and wrong
```
          #If tvdb numbering used, save anidb episode meta using tvdb numbering
          if source.startswith("tvdb") or source.startswith("anidb") and not movie and max(map(int, media.seasons.keys()))>1:
            season, episode = AnimeLists.tvdb_ep(mappingList, season, episode, AniDBid)
            
            # Get episode number to absolute number
            if source in ('tvdb3', 'tvdb4') and season not in ['-1', '0']:
              if source=='tvdb4' or season=='1':
                ms, usl = (season, True) if source=='tvdb3' else (Dict(mappingList, 'absolute_map', 'max_season'), Dict(mappingList, 'absolute_map', 'unknown_series_length'))
                if ms and usl:  season  = Dict(mappingList, 'absolute_map', episode, default=(ms if usl else str(int(ms)+1), None))[0]
              else:
                try:     episode = list(Dict(mappingList, 'absolute_map', default={}).keys())[list(Dict(mappingList, 'absolute_map', default={}).values()).index((season, episode))]
                except:  pass
```

We need to check AnimeLists.tvdb_ep give correct season/ep numbers, it would confirm the issue is in the code below
Haven't coded this part from memor, i struggle to follow it

**Comment by GodKratos** [comment]
> 
> 
> I am also seeing the wrong dates for One Piece. The first 118 episodes, it looks like. Not sure if this has anything to do with the mapping that was put into https://github.com/Anime-Lists/anime-lists/ or not.
> 
> [One Piece.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/6423331/One.Piece.filelist.log)
> [One Piece.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/6423332/One.Piece.scanner.log)
> [One Piece.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/6423333/One.Piece.agent-update.log)

Yes, that's right it's only the first 118 episodes that have the wrong date.
It was only within the last week or more that this behaviour changed, they were all ok before then so if that's when the change you mention happened it is most likely related.

**Comment by GodKratos** [comment]
> 
> tvdb4 mapping look OK: https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/tvdb4.mapping.xml
> 
> https://raw.githubusercontent.com/Anime-Lists/anime-lists/master/anime-list-master.xml
> There seem to be bugs in the last two entries ONLY.
> **Can you check your mapping file locally in HAMA Agent data folder cache for ANime-Lists ?**
> 
> ```
>   <anime anidbid="69" tvdbid="81797" defaulttvdbseason="a" episodeoffset="" tmdbid="" imdbid="">
>     <name>One Piece</name>
>     <mapping-list>
>       <mapping anidbseason="0" tvdbseason="0">;1-28;2-3;3-9;4-10;5-14;6-0;7-0;8-0;9-0;10-0;11-0;12-0;13-0;14-0;15-0;16-32;17-23;18-24;19-29;20-30;21-31;22-0;23-33;24-35;25-0;26-37;27-38;</mapping>
>       <mapping anidbseason="1" tvdbseason="1" start="1" end="8"/>
>       <mapping anidbseason="1" tvdbseason="2" start="9" end="30" offset="-8"/>
>       <mapping anidbseason="1" tvdbseason="3" start="31" end="47" offset="-30"/>
>       <mapping anidbseason="1" tvdbseason="4" start="48" end="60" offset="-47"/>
>       <mapping anidbseason="1" tvdbseason="5" start="61" end="69" offset="-60"/>
>       <mapping anidbseason="1" tvdbseason="6" start="70" end="91" offset="-69"/>
>       <mapping anidbseason="1" tvdbseason="7" start="92" end="130" offset="-91"/>
>       <mapping anidbseason="1" tvdbseason="8" start="131" end="143" offset="-130"/>
>       <mapping anidbseason="1" tvdbseason="9" start="144" end="195" offset="-143"/>
>       <mapping anidbseason="1" tvdbseason="10" start="196" end="226" offset="-195"/>
>       <mapping anidbseason="1" tvdbseason="11" start="227" end="325" offset="-226"/>
>       <mapping anidbseason="1" tvdbseason="12" start="326" end="381" offset="-325"/>
>       <mapping anidbseason="1" tvdbseason="13" start="382" end="481" offset="-381"/>
>       <mapping anidbseason="1" tvdbseason="14" start="482" end="516" offset="-481"/>
>       <mapping anidbseason="1" tvdbseason="15" start="517" end="578" offset="-516"/>
>       <mapping anidbseason="1" tvdbseason="16" start="579" end="628" offset="-578"/>
>       <mapping anidbseason="1" tvdbseason="17" start="629" end="746" offset="-628"/>
>       <mapping anidbseason="1" tvdbseason="18" start="747" end="779" offset="-746"/>
>       <mapping anidbseason="1" tvdbseason="19" start="780" end="877" offset="-779"/>
>       <mapping anidbseason="1" tvdbseason="20" start="878" end="891" offset="-877"/>
>       <mapping anidbseason="1" tvdbseason="21" start="892" end="981" offset="-891"/>
>     </mapping-list>
> ```

My anime-list-master.xml looks the same as this one.

**Comment by ZeroQI** [comment]
One month ago one piece look like that:
```
  <anime anidbid="69" tvdbid="81797" defaulttvdbseason="a" episodeoffset="" tmdbid="" imdbid="">
    <name>One Piece</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-28;2-3;3-9;4-10;5-14;6-0;7-0;8-0;9-0;10-0;11-0;12-0;13-0;14-0;15-0;16-32;17-23;18-24;19-29;20-30;21-31;22-0;23-33;24-35;25-0;26-37;27-38;</mapping>
    </mapping-list>
  </anime>
```

@sven-7 can you try this mapping locally?
If defaulttvdbseason="a", then why map per season ??? It make no sense...

**Comment by sven-7** [comment]
I'll look at this later tonight if I can. @reconman - why did this get done?

**Comment by GodKratos** [comment]
Yep looks like this commit from 11 days ago is about the same time the problem would have occurred.
https://github.com/Anime-Lists/anime-lists/pull/63/commits

**Comment by reconman** [comment]
See https://github.com/Anime-Lists/anime-lists/pull/62 for the full discussion leading up to multiple entries being changed.

**Comment by EndOfLine369** [comment]
In AnimeLists.py, set "tvdb_ep()" line "debug   = False" to "debug   = True"
Then refresh meta and provide that log.

**Comment by ZeroQI** [comment]
Extract from https://github.com/Anime-Lists/anime-lists/

> defaulttvdbseason - The corresponding theTVDB.com season. For one-off titles it will be 1 unless associated to a multi-episode series, in which case it will be 0. Series that span multiple seasons on theTVDB.com may be marked as a if the absolute episode numbering is defined and matches AniDb.net.

Either the absolute episode numbering is defined on TheTVDB.com and matches AniDb.net, so defaulttvdbseason='a' and the mappings are useless, or mappings are kept and defaulttvdbseason='1'

**Comment by GodKratos** [comment]
@reconman if you check my log file above you can see that it restarts mapping the episodes back at s1e1 every time the season changes in the anime-list file. As @ZeroQI pointed out this doesn't appear to be working with defaulttvdbseaon=a.

Below are just the lines in the log that map to s1e1 each time the season changes and the episode ends up with the date of the last mapping it receives in plex.

```
[X] s1e  1 => s1e  1 air_date: 1999-10-20 language_rank: 1, title: "I'm Luffy! The Man Who's Gonna Be King of the Pirates!"
[X] s1e  9 => s1e  1 air_date: 2000-01-12 language_rank: 1, title: "The Honorable Liar? Captain Usopp!"
[X] s1e 31 => s1e  1 air_date: 2000-07-12 language_rank: 1, title: "The Worst Man in the Eastern Seas! Fishman Pirate Arlong!"
[X] s1e 48 => s1e  1 air_date: 2000-11-22 language_rank: 1, title: "The Town of the Beginning and the End! Landfall at Logue Town!"
[X] s1e 61 => s1e  1 air_date: 2001-03-07 language_rank: 1, title: "An Angry Showdown! Cross the Red Line!"
[X] s1e 70 => s1e  1 air_date: 2001-05-27 language_rank: 1, title: "An Ancient Island! The Shadow Hiding in Little Garden!"
[X] s1e 92 => s1e  1 air_date: 2001-12-09 language_rank: 1, title: "Alabasta's Hero and a Ballerina on the Ship!"
[X] s1e131 => s1e  1 air_date: 2002-11-03 language_rank: 1, title: "The First Patient! The Untold Story of the Rumble Ball!"
[X] s1e144 => s1e  1 air_date: 2003-02-09 language_rank: 1, title: "Caught Log! The King of Salvagers, Masira!"
[X] s1e196 => s1e  1 air_date: 2004-06-20 language_rank: 1, title: "A State of Emergency Is Issued! A Notorious Pirate Ship Has Infiltrated!"
[X] s1e227 => s1e  1 air_date: 2005-03-27 language_rank: 1, title: "Navy Headquarters Admiral Aokiji! The Ferocity of an Ultimate Powerhouse!"
[X] s1e326 => s1e  1 air_date: 2007-10-14 language_rank: 1, title: "The Mysterious Band of Pirates! Sunny and the Dangerous Trap"
[X] s1e382 => s1e  1 air_date: 2008-12-21 language_rank: 1, title: "The Slow-Slow Menace! 'Silver Fox' Foxy Returns!"
[X] s1e482 => s1e  1 air_date: 2011-01-09 language_rank: 1, title: "The Power That Can Burn Even Fire! Akainu's Ruthless Pursuit!"
[X] s1e517 => s1e  1 air_date: 2011-10-02 language_rank: 1, title: "The Beginning of The New Chapter! The Straw Hats Reunited!"
[X] s1e579 => s1e  1 air_date: 2013-01-06 language_rank: 1, title: "Arriving! A Burning Island: Punk Hazard!"
[X] s1e629 => s1e  1 air_date: 2014-01-19 language_rank: 1, title: "Startling! The Big News Shakes Up the New World!"
[X] s1e747 => s1e  1 air_date: 2016-06-26 language_rank: 1, title: "The Silver Fortress! Luffy and Barto's Great Adventure!"
[X] s1e780 => s1e  1 air_date: 2017-03-19 language_rank: 1, title: "A Hungry Front! Luffy and the Navy Rookies!"
[X] s1e878 => s1e  1 air_date: 2019-03-31 language_rank: 1, title: "The World Is Stunned! The Fifth Emperor of the Sea Emerges!"
[X] s1e892 => s1e  1 air_date: 2019-07-07 language_rank: 1, title: "The Land of Wano! To the Samurai Country Where Cherry Blossoms Flutter!"
```

**Comment by sven-7** [comment]
I can confirm that removing the below corrects the date issue. I also have no issues from season to season detecting different intros. I'm on TVDB4, but having zero issues whatsoever with the original mapping. The new mapping does mess it up. I know this is also being discussed here: https://github.com/Anime-Lists/anime-lists/commit/d56057981556094a980f9c486c65e336de1d8dfd

```
      <mapping anidbseason="1" tvdbseason="1" start="1" end="8"/>
      <mapping anidbseason="1" tvdbseason="2" start="9" end="30" offset="-8"/>
      <mapping anidbseason="1" tvdbseason="3" start="31" end="47" offset="-30"/>
      <mapping anidbseason="1" tvdbseason="4" start="48" end="60" offset="-47"/>
      <mapping anidbseason="1" tvdbseason="5" start="61" end="69" offset="-60"/>
      <mapping anidbseason="1" tvdbseason="6" start="70" end="91" offset="-69"/>
      <mapping anidbseason="1" tvdbseason="7" start="92" end="130" offset="-91"/>
      <mapping anidbseason="1" tvdbseason="8" start="131" end="143" offset="-130"/>
      <mapping anidbseason="1" tvdbseason="9" start="144" end="195" offset="-143"/>
      <mapping anidbseason="1" tvdbseason="10" start="196" end="226" offset="-195"/>
      <mapping anidbseason="1" tvdbseason="11" start="227" end="325" offset="-226"/>
      <mapping anidbseason="1" tvdbseason="12" start="326" end="381" offset="-325"/>
      <mapping anidbseason="1" tvdbseason="13" start="382" end="481" offset="-381"/>
      <mapping anidbseason="1" tvdbseason="14" start="482" end="516" offset="-481"/>
      <mapping anidbseason="1" tvdbseason="15" start="517" end="578" offset="-516"/>
      <mapping anidbseason="1" tvdbseason="16" start="579" end="628" offset="-578"/>
      <mapping anidbseason="1" tvdbseason="17" start="629" end="746" offset="-628"/>
      <mapping anidbseason="1" tvdbseason="18" start="747" end="779" offset="-746"/>
      <mapping anidbseason="1" tvdbseason="19" start="780" end="877" offset="-779"/>
      <mapping anidbseason="1" tvdbseason="20" start="878" end="891" offset="-877"/>
      <mapping anidbseason="1" tvdbseason="21" start="892" end="981" offset="-891"/>
```

**Comment by sven-7** [comment]
This can likely be closed now with the merge above. Delete your old anime-lists and refresh metadata on One Piece.
