### ISSUE TITLE
[BUG] anime-list-master.xml is not being parsed correctly in specific cases.

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#464]
Since I'm basically redoing all my library once again, I've encountered this issue that I know for a fact it was working correctly sometime ago.

Anime in question is Black Lagoon: https://anidb.net/anime/3395

I'm adding the first 4 specials which should map directly to tvdb season 0 according to the mapping xml (except special number 5):

```
  <anime anidbid="3395" tvdbid="79604" defaulttvdbseason="1">
    <name>Black Lagoon</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;5-0;</mapping>
    </mapping-list>
  </anime>
```

Hama does not make the mapping at all in every of these 4 specials. I had to create a  anime-list-custom.xml with the following:

```
<?xml version="1.0" encoding="utf-8"?>
<anime-list>
  <anime anidbid="3395" tvdbid="79604" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Black Lagoon</name>
  </anime>
</anime-list>
```

And now it works correctly. I assume the issue here is that mapping-list tag is present and there's only information about the episode 5 mapping (so basically Hama doesn't assume the other episodes should map directly like 1-1,2-2,3-3, etc.. which I know Hama used to assume this and this is the default behavior of the anime-list-master file). I'm sure of this because of this next example:

For anime Black Lagoon: The Second Barrage: https://anidb.net/anime/4597

I have the first 3 specials. Everything worked fine and we can see the mapping here does specify individually each episode (since there's no direct match like the case before)

```
  <anime anidbid="4597" tvdbid="79604" defaulttvdbseason="1" episodeoffset="12">
    <name>Black Lagoon: The Second Barrage</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-5;2-6;3-7;</mapping>
    </mapping-list>
  </anime>
```

**Comment by ZeroQI** [comment]
> Hama used to assume this
Doesn't confirm it was correct to do so

> this is the default behavior of the anime-list-master file
https://github.com/Anime-Lists/anime-lists#mapping-list
Is it a documented behaviour?

The start, end, and offset attributes are not necessary if only individual episodes are being mapped. The offset and/or episodeoffset will be ignored in favour of an individual mapping. => Implying it is necessary to have start and end to have non-individual mapping

Episodes on AniDb.net that don't match anything on theTVDB.com are mapped to 0 if and only if there's a conflict. => That is not implied, an individual mapping to 0 will be done

**Comment by KurtzPT** [comment]
You are correct that I assumed it was the correct thing to do based on previous experiences I had with Hama and AnimeList. I'm almost sure this was the default behavior when Hama used the ScudLee repo. You can check this PR where one of the maintainers mentioned the behavior: https://github.com/ScudLee/anime-lists/pull/269 

> Also the 1-1 mapping for the (2016) special is unnecessary as it already exists implicitly and should be avoided.

In my mind this makes more sense, mappings should just be written in the mapping file when the number of episode is different between anidb and tvdb.

**Comment by KurtzPT** [comment]
Bottom line, since the original creator of this mapping list disappeared (ScudLee) I think this scenario was left out for interpretation for each person who helped maintain the mapping file. Some series do have these implicitly mapping (;1-1;2-2; etc) while others don't. 

I'm not sure who is the author of the new fork, but they should decide which way we should go foward and if the implicitly mapping is decided then I can PR the changes so nothing is changed on Hama side. @sven-7

**Comment by sven-7** [comment]
I haven't looked yet. Will do so. Adding @reconman

**Comment by KurtzPT** [comment]
> Edit: it is implicit since defaulttvdbseason='0', doesn't work if set to '1'

defaulttvdbseason is not used for specials, that mapping is for the main episodes. By implicit I mean direct same episode number on specials like:
anidb s1 ---> s00e01 tvdb
anidb s2 ---> s00e02 tvdb
anidb s3 ---> s00e03 tvdb

**Comment by EndOfLine369** [comment]
From all of this, there is no logs provided. And this sounds like an ASS issue and not HAMA.
Please provide your scanner logs of where you think the mapping is not working correctly.

**Comment by KurtzPT** [comment]
I don't want to sound an asshole but I feel you didn't fully read my first post which I took some time to write. This isn't an ASS issue because:

1. anime-list-master.xml is only used by Hama and not ASS.
2. It's fixed by refreshing metadata while using anime-list-custom.xml (by removing the mapping-list elements), which once again takes ASS outside of the picture and points for Hama issues (depends on the interpretation one gives to anime-list-master.xml mapping logic).
3. I've showed another anime where Hama correctly maps specials using anime-list-master.xml, where mapping-list elements are present and each special is mapped there. 
4. If all of the above points are not enough then this last one should be enough: All specials that I mentioned in my first post were matched correctly to specials in anidb (so I had all the correct metadata from anidb) the only part that failed was the metadata from tvdb which uses the `anime-list-master.xml` to make the match between anidb->tvdb. 

Unfortunately I don't have the logs anymore, but I've given concise information to replicate and even showed a fix (via custom file, which indicates the issue lies directly to anime-list-master.xml and this specific case scenario I mentioned by excluding direct implicitly special mappings)

**Comment by ZeroQI** [comment]
1. anime-list-master.xml is used in ASS by ANiDB 2/3/4 modes (lines 53, 777-808), and HAMA.
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py line 53
`ANIDB_TVDB_MAPPING     = 'https://raw.githubusercontent.com/Anime-Lists/anime-lists/master/anime-list-master.xml'`

2. Correct. when removing the custom mapping group, it default to kep specials meta on both anidb and tvdb without translation

3. yes but explicit mapping of season 0 eps, ;anidb->tvdb: 1->5; 2->6; 3->7;

4. The direction change if assigned an AniDB id or TVDB id (if multiple seasons, will search tvdb only for matching). Here we assume you have an AniDB id assigned and follow ANiDB numbering, unsure if using anidb or tvdb modes.

Working as expected if we compare with
```
  <anime anidbid="13500" tvdbid="337020" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Beatless</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-1;2-2;3-4;4-5;5-3;</mapping>
    </mapping-list>
  </anime>
```

AniDB specials 1-4 match TheTVDB but not 5, and more specials on TheTVDB
- https://anidb.net/anime/3395
- https://thetvdb.com/series/black-lagoon/seasons/official/0
- It should be instead:
```
  <anime anidbid="3395" tvdbid="79604" defaulttvdbseason="1">
    <name>Black Lagoon</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-1;2-2;3-3;4-4;5-0;</mapping>
    </mapping-list>
  </anime>
```

**Comment by KurtzPT** [comment]
> 1. anime-list-master.xml is used in ASS by ANiDB 2/3/4 modes (lines 53, 777-808), and HAMA.
>    https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py line 53
>    `ANIDB_TVDB_MAPPING     = 'https://raw.githubusercontent.com/Anime-Lists/anime-lists/master/anime-list-master.xml'`

Seems I missed this while searching the code, I stand corrected now.

> AniDB specials 1-4 match TheTVDB but not 5, and more specials on TheTVDB
> 
> * https://anidb.net/anime/3395
> * https://thetvdb.com/series/black-lagoon/seasons/official/0
> * It should be instead:
> 
> ```
>   <anime anidbid="3395" tvdbid="79604" defaulttvdbseason="1">
>     <name>Black Lagoon</name>
>     <mapping-list>
>       <mapping anidbseason="0" tvdbseason="0">;1-1;2-2;3-3;4-4;5-0;</mapping>
>     </mapping-list>
>   </anime>
> ```

This is where we disagree and I'll try to explain why by points:

- My first point I already said above, the original repo of AnimeList was applying the logic which is not the same as the one you are saying above. It was the other way around, which was to **AVOID** explicitly define specials when number is exactly the same on tvdb/anidb (s1-->s00e01) and just explicitly define specials which either have different episode numbers between the websites (s5-->s00e07) or that have no correspondent relationship like (like that Black Lagoon case, where s5-->NO MATCH).
- Regarding the first point, most of the data on AnimeList is following the logic above and thus we have lots of anime specials not being matched correctly when there's incomplete information on the `mapping-list` elements like in this Black Lagoon case. 

Random points for AnimeList/Hama:

- If every missing special on `mapping-list` is automatically assumed to have "no episode match on tvdb" by Hama, why would we need to define episode 5 (having 5-0 or not having 5-0 would do the exactly the same) at all? It's redundancy and makes zero sense. Your suggestion would only make "sense" if it was just `;1-1;2-2;3-3;4-4;` since we are already assuming everything missing on this list has no match.
- Another inconsistency in your suggestion is: when we are missing the `mapping-list` element, why are we assuming then that all specials should be mapped directly using the special number to tvdb (s1-->s00e01) ? Your suggestion above, we are already assuming that any missing specials on `mapping-list` does not have a tvdb match! Either we assume that all missing specials (with or without `mapping-list`) have no tvdb match at all or we should directly map from anidb->tvdb. At least it should be consistent one way or another.

One last question (@sven-7 @ZeroQI, curious what you guys think of this case):

Lets say we have Anime X with 200 specials on AniDB and all are directly matches to TVDB using just their special number on AniDB (s1->s00e01, s2->s00e02...) with exception of just one specials which is missing from tvdb (lets say s200 on AniDB does not match to s00e200 on tvdb). What would make more sense:
- Either just write on `mapping-list` that s200 doesn't have a match (;200-0; on `mapping-list`) 
- Go the insane way of specify every single special including s200 (;1-1;2-2;3-3;4-4;5-5;6-6;7-7;8-8;9-9;10-10; ........ ;200-0;) ?

**Comment by reconman** [comment]
Regarding the last question, I would either map it as
```xml
<mapping-list>
  <mapping anidbseason="0" tvdbseason="0">;200-0;</mapping>
</mapping-list>
```
or
```xml
<mapping-list>
  <mapping anidbseason="0" tvdbseason="0" start="1" end="199">;200-0;</mapping>
</mapping-list>
```

Don't know if ASS/Hama expect an offset="0" attribute for the second mapping.

There are currently lots of mappings which use the same logic as the Black Lagoon, that anything not mapped manually should have the same episode number. Lots of S0 to S0 mappings map indivial specials to 0 manually.

There are also some mappings where applying this logic will be tricky. In the following example, specials 1 and 2 should be mapped to S01E16 and S01E23, while specials 3 and 4 should be mapped to S00E01 and nothing.

```xml
  <anime anidbid="171" tvdbid="75911" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Seihou Bukyou Outlaw Star</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;3-1;4-0;</mapping>
      <mapping anidbseason="0" tvdbseason="1">;1-16;2-23;</mapping>
      <mapping anidbseason="1" tvdbseason="1" start="16" end="21" offset="1">;22-24;23-25;24-26;</mapping>
    </mapping-list>
    <before>;1-16;2-22;</before>
    <supplemental-info>
      <studio>Sunrise</studio>
    </supplemental-info>
  </anime>
```

**Comment by KurtzPT** [comment]
> Regarding the last question, I would either map it as
> 
> ```
> <mapping-list>
>   <mapping anidbseason="0" tvdbseason="0">;200-0;</mapping>
> </mapping-list>
> ```

My exact thoughts too.

> There are currently lots of mappings which use the same logic as the Black Lagoon, that anything not mapped manually should have the same episode number. Lots of S0 to S0 mappings map indivial specials to 0 manually.

When I contributed to ScudLee repo, I used that logic too, this is why I raised this whole issue.

> There are also some mappings where applying this logic will be tricky. In the following example, specials 1 and 2 should be mapped to S01E16 and S01E23, while specials 3 and 4 should be mapped to S00E01 and nothing.
> 
> ```
>   <anime anidbid="171" tvdbid="75911" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
>     <name>Seihou Bukyou Outlaw Star</name>
>     <mapping-list>
>       <mapping anidbseason="0" tvdbseason="0">;3-1;4-0;</mapping>
>       <mapping anidbseason="0" tvdbseason="1">;1-16;2-23;</mapping>
>       <mapping anidbseason="1" tvdbseason="1" start="16" end="21" offset="1">;22-24;23-25;24-26;</mapping>
>     </mapping-list>
>     <before>;1-16;2-22;</before>
>     <supplemental-info>
>       <studio>Sunrise</studio>
>     </supplemental-info>
>   </anime>
> ```

That is indeed a tricky situation which I'm not sure if Hama follows it correctly, but at least on the mapping side I also agree with the way is set-up.

**Comment by ZeroQI** [comment]
We probably reached a consensus, we need to use implied mapping.
- to keep compatibility with Scudlee repo, for other tools using it
- have less entries to change in database 
- mismatches entries (rare than matching ones) will need to have animelist updated

Episode translation, 
- https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/AnimeLists.py#L336, test if replacing `  return '0', '0', 'xxxxxxx'` with `  return season, episode, 'xxxxxxx'` works
- https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/AnimeLists.py#L265 replace `  mapping = ('0', '0')` with `  mapping = (season, episode)`
- https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/AnimeLists.py#L288 remove `  mapping = ('0', '0')`

Please test and report

**Comment by ZeroQI** [comment]
@reconman @KurtzPT Did the modification from the previous post worked as expected ?

**Comment by KurtzPT** [comment]
I had no time yet to test it out. I'll give out feedback when I test it.

**Comment by ZeroQI** [comment]
Any feedback?

**Comment by KurtzPT** [comment]
@ZeroQI, I finally tried out the suggestions you made and on a quick first test the Black Lagoon issue disappeared, all specials were mapped correctly with the tvdb entry.
