### ISSUE TITLE
[BUG] Possible issue with anime that have same title as OVA followed by (Year)

### ISSUE THREAD

**Issue by noobschoolbus** [ZeroQI/Hama.bundle#465]
I'm currently using HamaTV and ASS to add Fate/Kaleid Liner Prisma Illya Zwei! - https://anidb.net/anime/10091

However, HamaTV keeps mistaking this for the OVA series Fate/Kaleid Liner Prisma Illya Zwei! (2015) - https://anidb.net/anime/10804

I'm using absolute numbering. Example episode layout:
..\Fate Kaleid Liner Prisma Illya Zwei!\Fate Kaleid Liner Prisma Illya Zwei! - 01.mkv
..\Fate Kaleid Liner Prisma Illya Zwei!\Fate Kaleid Liner Prisma Illya Zwei! - 02.mkv
..\Fate Kaleid Liner Prisma Illya Zwei!\Fate Kaleid Liner Prisma Illya Zwei! - 03.mkv
etc

As you can see in the screenshot, the 10 episode series is being mistaken for the 1 episode OVA series:
![2015](https://user-images.githubusercontent.com/76540667/117584350-6fcd0b80-b0da-11eb-8d77-eb64c99a59f4.PNG)

I've also tried naming my folder Fate Kaleid Liner Prisma Illya Zwei! [anidb-10091] to force the correct anidb ID.

This problem does not occur when using TheTVDB agent with ASS scanner, only with HamaTV. I used season 2 as an example, but it's also happening for season 1 which has the title Fate/Kaleid Liner Prisma Illya and  is being mistaken as the OVA series Fate/Kaleid Liner Prisma Illya (2014).

I also tried adding the OVA series to my anime folder along with main series, hoping HamaTV would realize they are two separate series.
Example:
..\Fate Kaleid Liner Prisma Illya Zwei!\Fate Kaleid Liner Prisma Illya Zwei! - 01.mkv
..\Fate Kaleid Liner Prisma Illya Zwei!\Fate Kaleid Liner Prisma Illya Zwei! - 02.mkv
..\Fate Kaleid Liner Prisma Illya Zwei!\Fate Kaleid Liner Prisma Illya Zwei! - 03.mkv
etc

AND

..\Fate Kaleid Liner Prisma Illya Zwei! (2015)\Fate Kaleid Liner Prisma Illya Zwei! (2015) - 01.mkv

Also tried naming the folder as Fate Kaleid Liner Prisma Illya Zwei! (2015) [anidb-10804] to force the correct anidb ID. Neither option seems to work.

**Comment by ZeroQI** [comment]
*.search.log missing since it is a matching issue
The issue on scanners with renaming the folder is that the content is not re-scanned unless the content changes, you should have done the "Plex Dance"

http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10091
```
<titles>
<title xml:lang="x-jat" type="main">Fate/Kaleid Liner Prisma Illya Zwei!</title>
<title xml:lang="ja" type="synonym">Fate/kaleid liner プリズマ☆イリヤ ツヴァイ!</title>
<title xml:lang="ko" type="synonym">Fate/Kaleid Liner 프리즈마☆이리야 2wei!</title>
<title xml:lang="x-jat" type="synonym">Fate/Kaleid Liner Prisma Illya 2wei!</title>
<title xml:lang="x-jat" type="short">F/K 2</title>
<title xml:lang="x-jat" type="short">fk 2</title>
<title xml:lang="x-jat" type="short">Prillya Zwei</title>
<title xml:lang="ja" type="official">Fate/kaleid liner プリズマ☆イリヤ 2wei!</title>
<title xml:lang="en" type="official">Fate/Kaleid Liner Prisma Illya 2wei!</title>
<title xml:lang="zh-Hans" type="official">Fate/kaleid liner 魔法少女☆伊莉雅 2wei!</title>
</titles>
```

http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10804
```
<titles>
<title xml:lang="x-jat" type="main">Fate/Kaleid Liner Prisma Illya Zwei! (2015)</title>
<title xml:lang="ja" type="synonym">Fate/kaleid liner プリズマ☆イリヤ 2wei! 魔法少女in温泉旅行</title>
<title xml:lang="en" type="synonym">Fate/Kaleid Liner Prisma Illya 2wei!: Magical Girl in Hot Springs Inn</title>
<title xml:lang="ko" type="synonym">Fate/Kaleid Liner 프리즈마☆이리야 Zwei!: 마법소녀 in 온천여관(2015)</title>
<title xml:lang="x-jat" type="synonym">Fate/Kaleid Liner Prisma Illya Zwei!: Mahou Shoujo in Onsen Ryokou</title>
<title xml:lang="x-jat" type="short">fk OVA2</title>
<title xml:lang="x-jat" type="short">F/K OVA2</title>
<title xml:lang="ja" type="official">Fate/kaleid liner プリズマ☆イリヤ 2wei! (2015)</title>
<title xml:lang="zh-Hans" type="official">Fate/kaleid liner 魔法少女☆伊莉雅 第二季 OAD</title>
</titles>
```

"Fate/Kaleid Liner Prisma Illya 2wei!" should work for the series
- since both titles are identical apart from the year in parenthesis, it could give issues, as it can't perfect match due to the forward slash so cleanup and remove the year and use last one with identical spore...

Spported naming:
- Fate Kaleid Liner Prisma Illya Zwei! [anidb-10091]/Fate Kaleid Liner Prisma Illya Zwei! - 03.mkv
- Fate Kaleid Liner Prisma Illya Zwei! (2015)\Fate Kaleid Liner Prisma Illya Zwei! (2015) - 01.mkv

**Comment by noobschoolbus** [comment]
Thank you for the reply. I do the Plex dance every time and I've deleted the library many times, but to no avail.

My current naming:
Fate Kaleid Liner Prisma Illya Zwei!/Fate Kaleid Liner Prisma Illya Zwei! - 03.mkv

I noticed when the series is loading into Plex, it temporarily appends the correct ID [anidb-10091] onto the end of the series name while scanning. However once scanning it complete, it renames the series to Fate Kaleid Liner Prisma Illya Zwei! (2015) and shows the bug in the screenshot from my OP.

Name in folder: Fate Kaleid Liner Prisma Illya Zwei!
Name in Plex (while scanning): Fate Kaleid Liner Prisma Illya Zwei! [anidb-10091]
Name in Plex (after scanning): Fate Kaleid Liner Prisma Illya Zwei! (2015)

I'm not even attempting to add the (2015) series anymore, just want to get the 10 episode one in correctly. Please let me know if you have any other suggestions.

Anyway, thanks for making this agent and scanner!

**Comment by ZeroQI** [comment]
I really need to have the search logs with the correct ID, it's in agent data folders

**Comment by noobschoolbus** [comment]
Well, it looks like I had a naming issue. I'm now able to load it correctly by forcing the ID [anidb-10091]. Thank you for your time.

However, if it helps you at all, I'm still not able to load it correctly without forcing the ID:
[Fate Kaleid Liner Prisma Illya Zwei!.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/6448394/Fate.Kaleid.Liner.Prisma.Illya.Zwei.agent-search.log)

**Comment by ZeroQI** [comment]
[-] score:  98, aid: 10091, title: "Fate/Kaleid Liner Prisma Illya Zwei!"
[-] score:  98, aid: 10804, title: "Fate/Kaleid Liner Prisma Illya Zwei! (2015)"
Due to "/" in title you cannot get perfect match and the algorithm thinks they are identical due to scrubing... 
Will leave as is, as too much risk to break something else there...
