### ISSUE TITLE
check matching with anidb

### ISSUE THREAD

**Issue by proohit** [ZeroQI/Hama.bundle#468]
Thanks for your awesome works! Most of the times, ASS+ HamaTV Agent work perfectly. 

I have one question though: I want all series to match anidb (since I need the anidb id in the episodes parent guid). Is there any quick way to check if a series has been matched with anidb?

Thanks in advance.

**Comment by ZeroQI** [comment]
As long as there is no eps in seasons 2+ it will match to AniDB first. The unique guid will contain anidb
The title.search.log would confirm that as well
