### ISSUE TITLE
Notice: Hama and ASS on Synology DSM 7 Plex Media Server

### ISSUE THREAD

**Issue by reconman** [ZeroQI/Hama.bundle#469]
I wanted to leave this info behind since the Plex devs keep repeating that Plugins were already deprecated and are no longer supported in the new Synology DSM 7 Plex Media Server.

You now have to install Hama in a location only reachable through SSH and `root`, at `/volume1/@apphome/PlexMediaServer/Plex Media Server/Plug-ins`.

More info can be found here https://forums.plex.tv/t/solved-dsmv7-how-to-update-plugins-agents-scanners/700715/12

**Comment by ScarletStar** [comment]
Hi, sorry for digging up this old issue. But can anyone confirm that this still works with DSM7.2 and Plex 1.32.4.7195-7000?
Or am I doing something wrong? This is the file structure:
![plex](https://github.com/ZeroQI/Hama.bundle/assets/2913815/05850f21-fadc-41c2-bddb-322ef9373922)

**Comment by ZeroQI** [comment]
Looks like rights and location are fine to me
