### ISSUE TITLE
Manual search for Anidb does not work

### ISSUE THREAD

**Issue by Ninelpienel** [ZeroQI/Hama.bundle#473]
Sometimes Hama can't find a match for an anime. When I try to search manually I can't find a single listening from anidb. No matter what I enter as a search term. Only entries from tvdb are found.

Here's a video: https://streamable.com/sdoxwt

**Comment by ZeroQI** [comment]
Would the series happen to have seasons? AniDB only have single seasons series so if you match on series that have season 2+ then it only searches on TVDB

Search logs needed. Readme troubleshooting with logs location not followed
