### ISSUE TITLE
Add support Shikimori

### ISSUE THREAD

**Issue by imKota** [ZeroQI/Hama.bundle#474]
Please add support [Shikimori](https://shikimori.one/)
It uses data from the animeist (the same id as in mal), but this data is translated into Russian.

https://shikimori.one/api/doc/1.0
**Anime page doc:**
https://shikimori.one/api/doc/1.0/animes/show
**Anime page sample:**
https://shikimori.one/api/animes/48488

**Related page doc:**
https://shikimori.one/api/doc/1.0/animes/related
**Related page sample:**
https://shikimori.one/api/animes/48488/related

**Screenshots page doc:**
https://shikimori.one/api/doc/1.0/animes/screenshots
**Screenshots page sample:**
https://shikimori.one/api/animes/48488/related

**Roles page doc:**
https://shikimori.one/api/doc/1.0/animes/roles
**Roles page sample:**
https://shikimori.one/api/animes/48488/roles

**Comment by ZeroQI** [comment]
There is no mapping with ANiDB nor TheTVDB, technically AniDB could provide MALid but cannot see what benefits it brings, especially if it's just ANimeList information translated...

I see no way to include that with reliable mapping into HAMA, which will stop having major functionality anytime soon when TheTVDB stops the free API access...

**Comment by imKota** [comment]
> There is no mapping with ANiDB

@ZeroQI There is a comparison with other sites(mal, ann, anidb, wa). 


**doc:**
https://shikimori.one/api/doc/1.0/animes/external_links
**sample:**
https://shikimori.one/api/animes/48488/external_links

**Comment by ZeroQI** [comment]
We can map from the MALid (if AniDB provides it) to anidb https://shikimori.one/api/animes/48488/external_links but cannot find any episode information...

What fields are provided by that, which are better than the actually already supported, and how is that support to be added more important than the impeding TVDB doom as soon as they cut the plug to the API by requiring subscription?

**Comment by imKota** [comment]
Doesn't anidb store episode information?
I remember that these data are available there.

https://wiki.anidb.net/Content:Episodes
https://anidb.net/anime/16137

1st ep
https://anidb.net/episode/241203
1st ep file info 
https://anidb.net/file/2802239

**Comment by ZeroQI** [comment]
**Why should i work on that?** 
- What fields are so badly handled by current metadata providers currently that i have to add yet another etadata source ? 
- Please document which fields are impacted by this bad metadata and how this additionnal potential metadata source solves it

**Comment by imKota** [comment]
> **Why should i work on that?**
> * Please document which fields are impacted by this bad metadata and how this additional potential metadata source solves it

Hello, @ZeroQI 
On the Shikimori, everything is translated into Russian, including descriptions, character names, seiyu, directors, etc.
It would be nice to add support for the Russian language. Since there are no translated names on mal/anidb, and everything on Shikimori.

**Comment by ZeroQI** [comment]
Hama uses mainly AniDB or TheTVDB ID as unique ID and AnimeList to do a perfect mapping of the episodes between both regardless if the series follow AniDB and TheTVDB numbering. 

This metadata source follow MaL ID so asking Meal developper to add support is more feasible as even if this metadata source has full metadata entered, MaL numbering will differ for some series with AniDB and TheTVDB so will create mismatched data. Even having AniDB or TheTVDB I'd from that source will not solve this mapping issue

TheTVDB supports Russian so ideally one would enter metadata for series there, but it will pass behind a paywall any month now...

**Comment by imKota** [comment]
> Hama uses mainly AniDB or TheTVDB ID as unique ID and AnimeList to do a perfect mapping of the episodes between both regardless if the series follow AniDB and TheTVDB numbering.
> 
> This metadata source follow MaL ID so asking Meal developper to add support is more feasible as even if this metadata source has full metadata entered, MaL numbering will differ for some series with AniDB and TheTVDB so will create mismatched data. Even having AniDB or TheTVDB I'd from that source will not solve this mapping issue
> 
> TheTVDB supports Russian so ideally one would enter metadata for series there, but it will pass behind a paywall any month now...

hmm.. but all anime no shiki have mappings with anidbhttps://shikimori.one/api/animes/48488/external_links

![image](https://user-images.githubusercontent.com/24241471/147410776-005a25ed-303f-431c-9a34-d59254de7ad3.png)

**Comment by qipparu** [comment]
Дарова, сделал поддержку, готов посмотреть?)

**Comment by imKota** [comment]
> Дарова, сделал поддержку, готов посмотреть?) 

Привет, очень даже готов;)

**Comment by ZeroQI** [comment]
You may want to create a new agent instead using this empty template and using hama anidb search() code: https://github.com/ZeroQI/Hama.bundle/releases/download/v1.0/Empty_Agent_template.bundle.7z
