### ISSUE TITLE
Hama does not show in the list of agents but is shown in settings

### ISSUE THREAD

**Issue by Nitrousoxide** [ZeroQI/Hama.bundle#475]
Hama appears to be correctly installed, and Plex sees it in the settings as an agent, but it does not populate it in the actual selection drop down when trying to match a show.

Here it fails to show it in the dropdown
![image](https://user-images.githubusercontent.com/1363931/129419932-ff84bac7-2e37-4c30-9d35-9766209e5943.png)

But it appears in my agent list.
![image](https://user-images.githubusercontent.com/1363931/129419985-184d695e-23a6-4e59-b557-a5b7de70d8c7.png)

Here's the log from Hama if that helps at all.
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/6985234/com.plexapp.agents.hama.log)

**Comment by ZeroQI** [comment]
Logs show no crash.
Did you create the new type library ? If so, it is not supported...

**Comment by Nitrousoxide** [comment]
I did just create the library a few days ago.

After switching the scanner over to the "absolute series scanner" in the advanced settings for the library it worked.
