### ISSUE TITLE
fix `FutureWarning`

### ISSUE THREAD

**Issue by ZigZagT** [ZeroQI/Hama.bundle#476]
Plex now logs the following message when Hama is running

```
common:435: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
AnimeLists:39: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
AnimeLists:62: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
AniDB:378: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
AnimeLists:100: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
AnimeLists:220: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
AniDB:315: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
AniDB:265: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
```

**Comment by ZeroQI** [comment]
Unspecified which code he was running, let's assume latest at the time
- https://github.com/ZeroQI/Hama.bundle/blob/48e36b1cfd222b5dd0ab9e82eeece3425b4c2fa6/Contents/Code/common.py#L435
`      elif file_downloaded.startswith("<error"):             Log.Error('common.LoadFile() - Error response received, file: "{}"'.format(file_downloaded));  return file_downloaded_object`
- https://github.com/ZeroQI/Hama.bundle/blob/48e36b1cfd222b5dd0ab9e82eeece3425b4c2fa6/Contents/Code/AnimeLists.py#L39
`  if not AniDBTVDBMap:  raise Exception("GetAniDBTVDBMap() - Failed to load core file '{file}'".format(url=os.path.splitext(os.path.basename(SCUDLEE_MASTER))))  #; AniDB_Movie_Set = XML.ElementFromString("<anime-set-list></anime-set-list>")  #; raise Exception("HAMA Fatal Error Hit")
`
https://github.com/ZeroQI/Hama.bundle/blob/48e36b1cfd222b5dd0ab9e82eeece3425b4c2fa6/Contents/Code/AnimeLists.py#L62
`  if not AniDBMovieSets:  raise Exception("GetAniDBMovieSets() - Failed to load core file '%s'" % os.path.basename(SCUDLEE_MOVIESET))  #;  AniDB_Movie_Set = XML.ElementFromString("<anime-set-list></anime-set-list>") 
`
- https://github.com/ZeroQI/Hama.bundle/blob/48e36b1cfd222b5dd0ab9e82eeece3425b4c2fa6/Contents/Code/AnimeLists.py#L100
`  for anime in AniDBTVDBMapFull.iter('anime') if AniDBTVDBMapFull else []:`
- https://github.com/ZeroQI/Hama.bundle/blob/48e36b1cfd222b5dd0ab9e82eeece3425b4c2fa6/Contents/Code/AnimeLists.py#L220
`  for anime in AniDBTVDBMapFull.iter('anime') if AniDBTVDBMapFull and TVDB_winner.isdigit() else []:`
- https://github.com/ZeroQI/Hama.bundle/blob/48e36b1cfd222b5dd0ab9e82eeece3425b4c2fa6/Contents/Code/AniDB.py#L265
`          title, main, language_rank = GetAniDBTitle (ep_obj.xpath('title'), [language.strip() for language in Prefs['EpisodeLanguagePriority'].split(',')])`
- https://github.com/ZeroQI/Hama.bundle/blob/48e36b1cfd222b5dd0ab9e82eeece3425b4c2fa6/Contents/Code/AniDB.py#L315
`               elif epNumType in ['1', '2']:   SaveDict([episode],   missing,         season)`
- https://github.com/ZeroQI/Hama.bundle/blob/48e36b1cfd222b5dd0ab9e82eeece3425b4c2fa6/Contents/Code/AniDB.py#L378
`  if not AniDBTitlesDB:  raise Exception("Failed to load core file '{url}'".format(url=os.path.splitext(os.path.basename(ANIDB_TITLES))[0]))`

**Comment by ZeroQI** [comment]
- https://github.com/ZeroQI/Hama.bundle/blob/48e36b1cfd222b5dd0ab9e82eeece3425b4c2fa6/Contents/Code/AniDB.py#L265
- https://github.com/ZeroQI/Hama.bundle/blob/48e36b1cfd222b5dd0ab9e82eeece3425b4c2fa6/Contents/Code/AniDB.py#L315
- https://github.com/ZeroQI/Hama.bundle/blob/48e36b1cfd222b5dd0ab9e82eeece3425b4c2fa6/Contents/Code/AniDB.py#L378
- https://github.com/ZeroQI/Hama.bundle/blob/48e36b1cfd222b5dd0ab9e82eeece3425b4c2fa6/Contents/Code/common.py#L435

**Comment by ZeroQI** [comment]
Cannot see the issue on given lines for the rest, and cannot see issues around these lines neither so a new ticket will need creating with warning like in the initial report, if possible referencing the code line affected like i did above
- https://github.com/ZeroQI/Hama.bundle/blob/48e36b1cfd222b5dd0ab9e82eeece3425b4c2fa6/Contents/Code/AniDB.py#L265
- https://github.com/ZeroQI/Hama.bundle/blob/48e36b1cfd222b5dd0ab9e82eeece3425b4c2fa6/Contents/Code/AniDB.py#L315
- https://github.com/ZeroQI/Hama.bundle/blob/48e36b1cfd222b5dd0ab9e82eeece3425b4c2fa6/Contents/Code/common.py#L435

**Comment by RoyXiang** [comment]
Tried to update to [the latest commit](https://github.com/ZeroQI/Hama.bundle/tree/9f26696971aaed394ad3430974fb5e548f5ed5d6), got these warnings:

```
common:353: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
common:386: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
common:390: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
```

Referring to:
https://github.com/ZeroQI/Hama.bundle/blob/9f26696971aaed394ad3430974fb5e548f5ed5d6/Contents/Code/common.py#L353
https://github.com/ZeroQI/Hama.bundle/blob/9f26696971aaed394ad3430974fb5e548f5ed5d6/Contents/Code/common.py#L386
https://github.com/ZeroQI/Hama.bundle/blob/9f26696971aaed394ad3430974fb5e548f5ed5d6/Contents/Code/common.py#L390

Would you mind having a look at it? @ZeroQI

**Comment by ZeroQI** [comment]
Perfect!, submitted
