### ISSUE TITLE
Certain series episodes not being names for multi season

### ISSUE THREAD

**Issue by Jaynator495** [ZeroQI/Hama.bundle#477]
For series such as Dragon Ball Z, Dragon Ball, Dragon Ball GT, and One Piece, it does not seem to like multiple seasons. The first season is named and marked correctly, but anything after the second season gets no metadata updates, aside from the season poster. 
I am using this in conjunction with ASS, and my directories are like this 
Dragon Ball Z/Season 2/[Funimation] Dragon Ball Z - 40 [1080p].mkv
Replace "40" with the episode number, and the quality with the episode quality. This behavior as far as I can tell is the same for any anime where I don't have the episode names already there and just have the numbers in separate season folders. Do I need to somehow rename the collectively nearly 2 thousand episodes to have their name in it?

**Comment by ZeroQI** [comment]
HAMA logs are not the per-series logs whose location is in HAMA readme troubleshooting section
You are not following TVDB numbering as you use TVDB season folders but absolute numbering of episodes
You didn't specify that by 'episode number' you meant 'absolute episode number'

One Piece/Season xx/[Group]One Piece - ## [quality].ext where## is the (seasonal) episode number
One Piece **[tvdb3-81797]**/Season xx/[Group]One Piece - ## [quality].ext where xx is the ABSOLUTE episode number
