### ISSUE TITLE
How to downgrade anidb when it without tvdb?

### ISSUE THREAD

**Issue by Andor233** [ZeroQI/Hama.bundle#478]
Here is the log
[Re ゼロから始める異世界生活.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/7149214/Re.agent-update.log)

[Edit] Continutation of ASS bug report https://github.com/ZeroQI/Absolute-Series-Scanner/issues/373
- https://anidb.net/anime/11370 AniDB O1 to O13 is supported, but title shows 'Other xx' and not the ANiDB title "Director`s Cut: The End of the Beginning and the Beginning of the End"
- https://thetvdb.com/series/re-zero-starting-life-in-another-world/seasons/alternate/1 alternate numbering isn't supported

**Comment by ZeroQI** [comment]
You have used season 2 folder ("Re ゼロから始める異世界生活\Season 2") episodes s2e1-25, therefore are using TVDB numbering, as AniDB do not have seasons, as confirmed by the unique ID which is 'tvdb-305089'

This is baldy named/numbered. **I did say only O1-13using AniDB numbering was supported** on the other bug report, and this is not it. The only choices are:
- Re ゼロから始める異世界生活\s00e401-413
- Re ゼロから始める異世界生活\O1 - O13
