### ISSUE TITLE
Language priority not taken into account

### ISSUE THREAD

**Issue by inter5tella** [ZeroQI/Hama.bundle#480]
I've set my preferred language priority to focus on my local language for the metadata scrapping, unfortunately, the search doesn't select the first value and is always using English.

- I set the library language to German:
![grafik](https://user-images.githubusercontent.com/12923644/133891680-fcbb7007-5cf2-45f0-aa7f-b00ea5429664.png)

- Then I selected ASS for the scanner and HamaTV as the agent and added German to the language priority:
![grafik](https://user-images.githubusercontent.com/12923644/133891723-166daf8a-a264-46ab-9e98-5938cd88b14b.png)

- Then I started a new library scan and check the serie's description:
![grafik](https://user-images.githubusercontent.com/12923644/133891920-440b780b-a779-40df-bcdd-f2b16bd5c5d4.png)

- Then I'm clicking on 'Fix match' and select the most accurate option:
![grafik](https://user-images.githubusercontent.com/12923644/133891817-d11de984-24bf-4e03-a63c-42f05622c552.png)

- After checking again the serie's description I can see that the German text has been scrapped:
![grafik](https://user-images.githubusercontent.com/12923644/133891843-5230671f-150a-4bff-bea0-4d9fcb5e4af6.png)

Checking the Search options in the 'Fix match' menu shows that German is clearly used as the default selection.
![grafik](https://user-images.githubusercontent.com/12923644/133891976-4bedc38c-8979-4a02-9348-6ceed00e0f4a.png)

So, it looks like the initial search is not using the 'de' value that I've added in the language priority line of the agent's settings.

**Comment by inter5tella** [comment]
My fault, I forgot to change language when adding a new media collection, too.

**Comment by inter5tella** [comment]
Reopened, because even if I set a language to a media collection and add my local language to the Hama prioritization, English will be used all the time. The only fix is to go through each series again and use the 'fix relation' feature. There I just need to start a new search without changing anything and the series description and episode titles are then scrapped again but in my preferred language.

**Comment by ZeroQI** [comment]
Séries specific logs missing.
Logs will show the metadata source that provided the series summary in library language.

**Comment by smoon1895** [comment]
Check you Hama Settings. I think it is using the AniDB first as source as in AniDB is no German Title and Description added. You should change the preferred options which databases are queryied from AniDB, TheTVDB to TheTVDB, AniDB ...

This should solve the problem.

**Comment by inter5tella** [comment]
I did some more testing and I think I found the issue.

@smoon1895 Settings were on default, just added 'de' to the language priorities. AniDB was working fine as the first source even if a German title is missing, as it's then using 'en'. Maybe the used series for the sample was a bad pick.

But, it looks like if you're using the Plex Windows App, add a new series library, set its main language to German, set ASS as scanner and Hama as the agent, plex is setting the library language back to English. The issue seems to be in the plex UI, because if you then change the language again to German (before starting the scan) the selection of ASS and Hama is gone. So you're inside a loop and you can only decide if for the initial scanning your preferred language should be used or a custom scanner/agent. Starting the scan then, you're allowed to change the library setting that wasn't possible for the initial scan. Then you can change the language to German and set the custom scanner/agent.

So I don't see this issue not on Hama's site but on plex and I will close this defect. Sorry for bothering.

**Comment by ZeroQI** [comment]
Thanks for the documented update
