### ISSUE TITLE
Metadata absent from shows that ive put on today even when using [anidb-####]

### ISSUE THREAD

**Issue by colelisiongaming** [ZeroQI/Hama.bundle#483]
## Platform

Operating system and version: Windows 10
Plex version: 4.63.0

## Expected Behavior
Should Give me show poster, correct title, and episode names.

## Current Behavior
Blank poster, Title with [anidb-####] at the end of title name in plex, and episodes have no names.
## Steps to Reproduce

1. Made new Plex library with ASS and Hama
2. Put shows in a metadata test folder
3. Named shows with [anidb-####] for 3 different shows
4. Bought a coffee for you

**Comment by colelisiongaming** [comment]
https://forums.plex.tv/t/rel-http-anidb-metadata-agent-hama/40470/2078 Looks like others are having this issue as of recent

**Comment by colelisiongaming** [comment]
[_root_.agent.log](https://github.com/ZeroQI/Hama.bundle/files/7231969/_root_.agent.log)
[Dr Stone [anidb-14491].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/7231970/Dr.Stone.anidb-14491.agent-search.log)
[Dr Stone [anidb-14491].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/7231971/Dr.Stone.anidb-14491.agent-update.log)
[Fire Force S01 1080p Dual Audio BDRip 10 bits DD x265-EMBER [anidb-14488].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/7231972/Fire.Force.S01.1080p.Dual.Audio.BDRip.10.bits.DD.x265-EMBER.anidb-14488.agent-search.log)
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/7231973/com.plexapp.agents.hama.log)
[com.plexapp.system.log](https://github.com/ZeroQI/Hama.bundle/files/7231974/com.plexapp.system.log)
[Fire Force S01 1080p Dual Audio BDRip 10 bits DD x265-EMBER [anidb-14488].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/7231975/Fire.Force.S01.1080p.Dual.Audio.BDRip.10.bits.DD.x265-EMBER.anidb-14488.agent-update.log)
[NANA[anidb-4143].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/7231976/NANA.anidb-4143.agent-search.log)
[NANA[anidb-4143].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/7231977/NANA.anidb-4143.agent-update.log)
[[AnimeRG] Future Diary (Mirai Nikki) Complete Series & OVAs [DUAL-AUDIO] [BD] [1080p] [x265] [pseudo].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/7231978/AnimeRG.Future.Diary.Mirai.Nikki.Complete.Series.OVAs.DUAL-AUDIO.BD.1080p.x265.pseudo.agent-search.log)

**Comment by ZeroQI** [comment]
com.plexapp.agents.hama.log
```
    for element in AniDBTitlesDB.xpath(u"/animetitles/anime/title[text()[contains(lower-case(.), '%s')]]" % orig_title.lower().replace("'", " ")):
AttributeError: 'str' object has no attribute 'xpath'
```
**That means AniDBTitlesDB is a string (str), possibly ""**. The forced ID part did work OK since it needs no database, but this is the agent base for searching title, the will not function at all like this. 

```
2021-09-26 13:58:31,081 (261c) :  DEBUG (sandbox:19) - common.LoadFile() - File cached locally - Filename: AnimeLists\anime-list-master.xml, Age: '0.01 days', Limit: '6 days', url: 'https://raw.githubusercontent.com/Anime-Lists/anime-lists/master/anime-list-master.xml'
2021-09-26 13:58:31,084 (261c) :  INFO (sandbox:19) - Entries loaded: 13712, File: https://raw.githubusercontent.com/Anime-Lists/anime-lists/master/anime-list-master.xml
```

Logs looks good but the AniDBTitlesDB should be an XML object, so please check in agent data folder "AnimeLists\anime-list-master.xml" and see the size and if a proper XML file or compressed in some way

**Comment by colelisiongaming** [comment]
I actually just did a fresh wipe of plex and the media server I will update this if the issue persists!

**Comment by ZeroQI** [comment]
all i know is that the xml didn't load as expected, so if it persists, you're not the only one impacted

**Comment by colelisiongaming** [comment]
On my new file it is 2.18 and hama seems to be functioning ok, metadata is taking awhile but moving along! I had some other questions regarding operation do you have a discord I can reach you at or do you prefer here?

**Comment by colelisiongaming** [comment]
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/7232145/com.plexapp.agents.hama.log)
Here is a updated one

**Comment by colelisiongaming** [comment]
Ive got some weirdness from kizumonogatari The 3 episodes in it are from bakemonogatari the metadata is all messed up and refresh doesnt work

**Comment by ZeroQI** [comment]
If it is a use case query, the plex forum would be more adequate to ask, as some users have passed quite some time on monogatari series which is single handledly the worst to number episode for due to its complexity

Development note: Has this API changed again? https://atarashii.fribbtastic.net/web/2.1/anime/20899

**Comment by colelisiongaming** [comment]
So basically I will have a show let's say jojos part 3 that I will force with [anidb-10206] but plex has the episode names and thumbnails of [anidb-9304] it's completely mixed up. Most shows that worked before I reset my Plex are displaying wrong even if I refresh Metadata or type fix match

**Comment by colelisiongaming** [comment]
![Screenshot_20210927-091755_Plex](https://user-images.githubusercontent.com/49499902/134916481-ffdf36b7-6422-4d5a-a879-78583badf63a.jpg)
![Screenshot_20210927-092001_Plex](https://user-images.githubusercontent.com/49499902/134916541-08a9511a-c238-4a28-b293-bfda7ade96d5.jpg)
![Screenshot_20210927-091947_Plex](https://user-images.githubusercontent.com/49499902/134916595-b9125ed9-f2f4-453b-bb40-4d44c959e043.jpg)
![Screenshot_20210927-091858_Plex](https://user-images.githubusercontent.com/49499902/134916604-b489a92d-553b-4bbb-8645-19209eb8a391.jpg)

A few photos to show what is going some episodes have correct names and thumbnails while some don't it just seems very random

**Comment by colelisiongaming** [comment]
Oh sorry the screenshots were of 3 different seasons the one I sent that goes over 27 is diamond is unbreakable. I'll go fetch the logs now

**Comment by colelisiongaming** [comment]
![image](https://user-images.githubusercontent.com/49499902/134928028-09f6fc5c-d452-4af5-ae92-b0609d69a8c5.png)
Here is one last example using kizumonogatari while I fetch you logs included pictures of the files too

**Comment by colelisiongaming** [comment]
[Kizumonogatari [anidb-8357].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/7237133/Kizumonogatari.anidb-8357.agent-update.log)
[_root_.agent.log](https://github.com/ZeroQI/Hama.bundle/files/7237134/_root_.agent.log)
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/7237135/com.plexapp.agents.hama.log)
[com.plexapp.system.log](https://github.com/ZeroQI/Hama.bundle/files/7237136/com.plexapp.system.log)
[Kizumonogatari [anidb-8357].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/7237137/Kizumonogatari.anidb-8357.agent-search.log)

**Comment by colelisiongaming** [comment]
Jojo part 3
[[inid4cFix + SFX Ver.2]  JoJo's Bizarre Adventure - Stardust Crusaders Arc 1 (Blu-Ray 1080p x265 FLAC)[anidb-10206].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/7237165/inid4cFix.%2B.SFX.Ver.2.JoJo.s.Bizarre.Adventure.-.Stardust.Crusaders.Arc.1.Blu-Ray.1080p.x265.FLAC.anidb-10206.agent-update.log)
[[inid4cFix + SFX Ver.2]  JoJo's Bizarre Adventure - Stardust Crusaders Arc 1 (Blu-Ray 1080p x265 FLAC)[anidb-10206].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/7237166/inid4cFix.%2B.SFX.Ver.2.JoJo.s.Bizarre.Adventure.-.Stardust.Crusaders.Arc.1.Blu-Ray.1080p.x265.FLAC.anidb-10206.agent-search.log)

jojo Diamond is unbreakabl
[[inid4cFix + SFX Ver.2]  JoJo's Bizarre Adventure - Diamond is Unbreakable (Blu-Ray 1080p x265 FLAC)[anidb-11734].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/7237174/inid4cFix.%2B.SFX.Ver.2.JoJo.s.Bizarre.Adventure.-.Diamond.is.Unbreakable.Blu-Ray.1080p.x265.FLAC.anidb-11734.agent-update.log)
[[inid4cFix + SFX Ver.2]  JoJo's Bizarre Adventure - Diamond is Unbreakable (Blu-Ray 1080p x265 FLAC)[anidb-11734].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/7237175/inid4cFix.%2B.SFX.Ver.2.JoJo.s.Bizarre.Adventure.-.Diamond.is.Unbreakable.Blu-Ray.1080p.x265.FLAC.anidb-11734.agent-search.log)
e

**Comment by ZeroQI** [comment]
Let's focus on jojo part 3 for the moment

Since metadata source order for ep tites is "TheTVDB, AniDB", and s01e01 from AniDB maps to TheTVDB S02e01, title will be "A Man Possessed by an Evil Spirit" , like it is for AniDB, which seem correct
```
[X]    s1e1 **s01e001** anidbid: xxxxxxx air_date: 2012-10-06 abs_number: 1, title: Dio the Invader
[X]    s2e1 **s01e001** anidbid:   10206 air_date: 2014-04-05 abs_number: 27, title: **A Man Possessed by an Evil Spirit**
```

https://www.thetvdb.com/series/jojos-bizarre-adventure-2012/seasons/official/2
https://anidb.net/anime/10206

For jojo part 3, which episodes number have wrong title according you, and what should be the title ?

**Comment by colelisiongaming** [comment]
Jojo only has incorrect thumbnails while monogatari has incorrect episode names and thumbnails
