### ISSUE TITLE
'Plex themes missing' log not being populated

### ISSUE THREAD

**Issue by EndOfLine369** [ZeroQI/Hama.bundle#49]
The log is defined but not populated in the code so that needs to be setup

**Comment by EndOfLine369** [comment]
@sven-7 open up this ticket from your comment on the pull request

**Comment by ZeroQI** [comment]
Old code had it: https://raw.githubusercontent.com/ZeroQI/Hama.bundle/60ec132c27733ca4b86ebb41f0f13b1fa14688c5/Contents/Code/__init__.py

error_log   ['Plex themes missing'      ].append("anidbid: %s, title: '%s', tvdbid: %s, title: '%s' <a href='mailto:themes@plexapp.com?cc=&subject=Missing%%20theme%%20song%%20-%%20&#39;%s%%20-%%20%s.mp3&#39;'>Upload</a>" % (metadata.id.zfill(5), orig, tvdbid.zfill(5), tvdb_title, tvdb_title, tvdbid) )

**Comment by EndOfLine369** [comment]
Looks like it has been missing for months so thanks for pulling it back in. I've corrected the invalid variables and also updated to match the required format for the entries to be maintained.

**Comment by EndOfLine369** [comment]
Looks good. Refreshed two of them and i'm getting a good log.
```
<a href='https://plexapp.zendesk.com/hc/en-us/articles/201572843' target='_blank'>Restrictions</a><br />
tvdbid: <a href='http://thetvdb.com/?tab=series&id=305074' target='_blank'>305074</a> | Title: '' | <a href='mailto:themes@plexapp.com?cc=&subject=Missing%20theme%20song%20-%20&#39;%20-%20305074.mp3&#39;' target='_blank'>Upload</a><br />
tvdbid: <a href='http://thetvdb.com/?tab=series&id=300816' target='_blank'>300816</a> | Title: '' | <a href='mailto:themes@plexapp.com?cc=&subject=Missing%20theme%20song%20-%20&#39;%20-%20300816.mp3&#39;' target='_blank'>Upload</a>
```

**Comment by ZeroQI** [comment]
@EndOfLine369: Sorry you had to correct, and thanks for fixing promptly.Good team work :D
