### ISSUE TITLE
Agent not available for shows

### ISSUE THREAD

**Issue by TheKaluwan** [ZeroQI/Hama.bundle#492]
I recently purchased a QNAP NAS and moved all my Plex Libraries on it.
As One Piece reached the 1000th episode a few weeks ago, I now observe some metadata problems for the most recent episodes.
So I decided to search the web for a solution to my problem and here I am !

I followed all the Installation instructions from the README, but the agent only appears for Movies and not for Shows.
![image](https://user-images.githubusercontent.com/42348560/146091347-daa1e4a3-a762-4398-8bde-8388d6ad4aa4.png)
![image](https://user-images.githubusercontent.com/42348560/146091379-49ac9d38-ec1e-451d-9847-61317e791721.png)

I searched in the previous issues but didn't find anything, if someone could help ...

My configuration :
- QNAP TS-251D with QTS 5.0.0.1870
- Plex Media Server 1.25.2.5319
- Absolute Series Scanner (freshly installed, no recognition problem)

**Comment by ZeroQI** [comment]
New styles libraries are NOT supported

**Comment by micr0be** [comment]
is there a workaround to this? I did a fresh install of Hama agent and ASS after some folders/files weren't getting detected and the agent kind of broke it won't use AniDB and will default to TvDB only.

**Comment by ZeroQI** [comment]
No logs.
asked to test with another series agent, didn't test.
