### ISSUE TITLE
Collections keeps being automatically created even if it's set to None

### ISSUE THREAD

**Issue by squilcon** [ZeroQI/Hama.bundle#495]
I don't know if I'm doing everything correctly, but everything I tried so far didn't work. I'm trying to disable the creation of the collections in a library with this plugin. I don't want them to be created automatically. So, I tried, on a fresh install, to set the value for `T--M 'collections'` to `None` but it did nothing and the collections are still being created automatically.

If I'm doing something wrong, I'd like to know what I'm suppose to do to make it stop creating collections. If not, could you check if there's a bug in the plugin?

I'm testing this with the Appleseed movies that are being put into Appleseed Collection.

I attached the xml for configuration I chose for Hama 
[Preferences.zip](https://github.com/ZeroQI/Hama.bundle/files/7749197/Preferences.zip)

with the logs of the plugin for the library I tested
[Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/7749212/Logs.zip)

I'm getting this 
![Wrong](https://user-images.githubusercontent.com/55063554/146863405-6e7f02cb-238a-411a-b607-01cbe46109a6.PNG)

When I want this (I manually deleted the collection here)
![Right](https://user-images.githubusercontent.com/55063554/146863418-1305a32f-9f52-4d7a-9e7c-0c1d856578f9.PNG)

If there's other log or information you need, I can get them.

Thx

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/common.py
- line 671 it will not loop if source is not in the loop
- line 688 it will not display if source set to 'None'

I don't think it is done by Hama.
What happens if you update .metadata for 1 movie or series? Does it come back
What other agents do you have active In library agent list? Lambda?

**Comment by squilcon** [comment]
When I delete the collection, the Collection field is then locked. If I unlock it and refresh the metadata, the collection is created again. For the agents, I'm not sure where I need to go to see that. I don't have Lambda for sure. If you mean the agents in the settings, I only have HamaTV and HamaMovies selected.

![hamatv](https://user-images.githubusercontent.com/55063554/146941203-ace4aea4-b72e-4c73-bc2b-8069b2c4fc0d.PNG)
![hamamovies](https://user-images.githubusercontent.com/55063554/146941216-7dc11e7b-bf62-4883-bdf8-c84687b4942b.PNG)

**Comment by squilcon** [comment]
Also, I don't know why, but when I put the 4 movies and 1 series inside a folder named "Appleseed" and by changing the collection field value in hama to `Local` and with the settings to hide items within a collection, it creates the collection with the 5 titles, but the series isn't hidden.

![collection local](https://user-images.githubusercontent.com/55063554/146967196-2a5edc83-75f6-457c-b641-bbb79e23947a.PNG)

It might not be relevant to the first problem I have but I wanted to mention it.

**Comment by ZeroQI** [comment]
You can show or hide items in collection by changing your library settings.
I would need to change the code to output the fields set to None as it doesn't make sense currently...

**Comment by squilcon** [comment]
True, I could let the collection as is and show every item, but what I wanted was to create them manually and only show the collections. If it's not possible, I'll try to do it by creating parent folder and setting the value to `Local` and hoping that only the parent folders will be created as collection. I'd prefer having every anime folder into a single parent folder though.

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/common.py
line 671 it will not loop if source is not in the loop
line 688 it will not display if source set to 'None'
there is no field 'collection' assigned at the end of the logs, it's not done by Hama, you likely have a corrupted database and it reuses old series meta
