### ISSUE TITLE
External subtitles not picking up.

### ISSUE THREAD

**Issue by Dzinsham** [ZeroQI/Hama.bundle#502]
While googling I've found this issue https://github.com/ZeroQI/Hama.bundle/issues/91
I'm having the same problem, except I have Local Media Assets enabled https://i.imgur.com/YXjATw8.png
I have tried every naming scheme possible (literally). Subs are showing like this https://i.imgur.com/SENjyc6.png but when I try to play the content using my Nvidia Shield - enabling subs and selecting them gives no result. They are shown as enabled but they simple doesn't work, player acts like they are disabled.
BUT when I manually upload the same subtitle file it shows like this https://i.imgur.com/36fRDy6.png and selecting them in the player works just fine!
Again, I have tried like 10 different naming schemes, like 5 of them from the FileBot and 5 from my head. I have refreshed the metadata, rescanned the server, rebooted it, did scheduled tasks, powercycled it like 10 times by now - same result. I also just tried deleting the whole Library and re-adding it again - no shot.

**Comment by ZeroQI** [comment]
There is no subtitle code in HAMA or ASS
This is a Plex or local media asset issue where it detects as SSA and fail but manually it loads it as ASS and it works. Are you sure the file extension was set as ASS? Closing this since not an agent issue
