### ISSUE TITLE
TVDB4 arc mapping

### ISSUE THREAD

**Issue by departet** [ZeroQI/Hama.bundle#503]
Hey there,
i'm apparently insanely stupid but i can't figure out how to order fairy tail by arc.
Searched the web and issues on github but i'm just confused. Do i need a tvdb4.mapping file or a tvdb4.mapping.xaml file? Where do i put it? What is the content of such file? Do i have to change collection/scraper settings?

Currently i have:
Anime\Fairy Tail [anidb-6662]\Fairy Tail - 01 - The Fairy Tail etc etc
Anime\Fairy Tail [anidb-6662]\tvdb4.mapping which content is

> 01|001|002|Macao Arc
> 02|003|004|Daybreak Arc
> 03|005|010|Eisenwald Arc
> 04|011|020|Sub-Zero Emperor Lyon Arc
> 05|021|029|Phantom Lord Arc
> 06|030|032|Loke Arc
> 07|033|040|Tower of Heaven Arc
> 08|041|051|The Battle of Fairy Tail Arc
> 09|052|068|Oracion Seis Arc
> 10|069|075|Daphne Arc
> 11|076|095|Edolas Arc
> 12|096|122|Tenrou Island Arc
> 13|123|124|X791 Arc
> 14|125|150|Key of the Starry Sky Arc
> 15|151|175|Grand Magic Games Arc

I have mostly the base scraper settings. I only changed the poster setting order(put anidb first).

Can anyone PLEASE explain the usage of a tvdb4 custom order (especially arcs) for me?
Thank you very much in advance!
Departet

**Comment by ZeroQI** [comment]
This is a question, Plex forum should have been used as few users could have answered

Use tvdb4 force id to use tvdb4 mode, 'Fairy Tail [anidb-6662]' is not suitable naming. It will put in season folders for you as per the online mapping file, unless you used a local file, unless you used manual season folders/numbering
