### ISSUE TITLE
Missing Studio and Miss Match Muti-Series

### ISSUE THREAD

**Issue by s683795** [ZeroQI/Hama.bundle#509]
Hamas have a problem with matching metadata for series with multiple seasons. First Season of the show, will have match metadata but after sequel after will be match with first season metadata.  Agent seems to not scrape the Studio. When checking for episode title for both first and second season, they are correctly scrape. 
![2 5](https://user-images.githubusercontent.com/104551612/165706721-78fe7e4c-cc3a-422f-a266-bb4cbb4a537b.PNG)
![3](https://user-images.githubusercontent.com/104551612/165706705-1a598ea2-2942-4334-a3d7-6751270f8c3a.PNG)
![poster](https://user-images.githubusercontent.com/104551612/165706729-42782785-5911-4ec8-8e0a-8bed759026f6.PNG)
![4](https://user-images.githubusercontent.com/104551612/165707038-b71ed849-5f32-4a4b-9e2f-3e5c12f973fd.PNG)
![5](https://user-images.githubusercontent.com/104551612/165707816-699727f8-fbe5-498b-993a-2cedbcaff3c9.PNG)
[Genjitsu Shugi Yuusha no Oukoku Saikenki (2022) [anidb-16804].agent-update.log]

Version 1.26.0.5715
Using Unraid Official Plex Media Server App

[Genjitsu Shugi Yuusha no Oukoku Saikenki (2022) [anidb-16804].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/8581329/Genjitsu.Shugi.Yuusha.no.Oukoku.Saikenki.2022.anidb-16804.agent-search.log)
[Genjitsu Shugi Yuusha no Oukoku Saikenki (2022) [anidb-16804].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/8581330/Genjitsu.Shugi.Yuusha.no.Oukoku.Saikenki.2022.anidb-16804.agent-update.log)
[Genjitsu Shugi Yuusha no Oukoku Saikenki [anidb-15505].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/8581331/Genjitsu.Shugi.Yuusha.no.Oukoku.Saikenki.anidb-15505.agent-search.log)
[Genjitsu Shugi Yuusha no Oukoku Saikenki [anidb-15505].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/8581332/Genjitsu.Shugi.Yuusha.no.Oukoku.Saikenki.anidb-15505.agent-update.log)

**Comment by ZeroQI** [comment]
Unraid > Plex 1.26.0.5715
- "Genjitsu Shugi Yuusha no Oukoku Saikenki (2022) [anidb-16804]" have the following field metadata from the first season "[Genjitsu Shugi Yuusha no Oukoku Saikenki [anidb-15505]]": N/A, "metadata" is too vague, please specify
- (https://github.com/ZeroQI/Hama.bundle/files/8581331/Genjitsu.Shugi.Yuusha.no.Oukoku.Saikenki.anidb-15505.agent-search.log)" show anidb id 16804 assigned propertly

https://raw.githubusercontent.com/Anime-Lists/anime-lists/master/anime-list-master.xml
```
 <anime anidbid="15505" tvdbid="389422" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Genjitsu Shugi Yuusha no Oukoku Saikenki</name>
  </anime>
  <anime anidbid="16804" tvdbid="389422" defaulttvdbseason="1" episodeoffset="13" tmdbid="" imdbid="">
    <name>Genjitsu Shugi Yuusha no Oukoku Saikenki (2022)</name>
  </anime>
```
mapped to same tvdb series 389422, same season 1 with 13 episode offset
tvdb logs show it detects files present as s01e14-26 so correct

AniDB_dict: {
  'Banned': **True**,
  'language_rank': 0,
  'original_title': 'Genjitsu Shugi Yuusha no Oukoku Saikenki (2022)',
  'title': 'Genjitsu Shugi Yuusha no Oukoku Saikenki (2022)'}

What did you do to get banned ???
What fields are you saying are taken from the first season (they should be taken from TVDB so yeah it could appear that way)

**Comment by s683795** [comment]
https://anidb.net/forum/thread/82649
Is it possible that I could get ban for scraping metadata too fast?

**Comment by ZeroQI** [comment]
Definitely. I did put some pause but rescanning same series multiple times could do that...
