### ISSUE TITLE
HAMA series agent missing

### ISSUE THREAD

**Issue by Toastosterone** [ZeroQI/Hama.bundle#514]
already detailed the issue here since i thought it'd be something simple and probably my mistake, but can't find an answer (https://www.reddit.com/r/PleX/comments/us702z/zeroqis_asshama_series_agent_not_showing_up/)

basically the hama/ass combo was installed (at the same time).
full server (qnap) reboot happened.
everything worked, except the series agent.
It doesn't exist.

i noticed that some folders weren't "auto created" as stated in the hama bundle page, but that's pretty much the only thing off about it that i can tell

did i miss something? really appreciate the help

here are the PMS plugin logs. there are no more since the plugin support logs folder doesn't exist

[PMS Plugin Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/8715873/PMS.Plugin.Logs.zip)

**Comment by ZeroQI** [comment]
Give me the FULL path to the __init__.py file from HAMA. I believe it is badly installed

**Comment by Toastosterone** [comment]
sure thing:
/share/CACHEDEV2_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code


![image](https://user-images.githubusercontent.com/105788879/169032643-9bfd0ae3-fa63-484b-aee9-cde7b6aab5bc.png)

**Comment by ZeroQI** [comment]
Well configured. Logs show Hama détails correct then later a crash in Plex framework...
Try to create folders manually but it shouldn't prevent the agent from being listed...
Is it seen in Plex settings, can you see agent settings?

**Comment by Toastosterone** [comment]
i'll try to create the folders now manually.

i do see the agent, but only the movies one. the series one is missing:
![image](https://user-images.githubusercontent.com/105788879/169033875-3be686d9-21a3-4882-b9c2-89d25275bcbc.png)

![image](https://user-images.githubusercontent.com/105788879/169033957-b721840b-a3f2-41f7-956f-682ea0215cbb.png)

**Comment by ZeroQI** [comment]
That is weird...
Try the version before the last one, I might have missed something in last version...

**Comment by ZeroQI** [comment]
I have no clue...
No hama agent log neither ?

**Comment by Toastosterone** [comment]
nop. in fact, even weirder, out of all the folders i created manually, the one called "Logs" (which i also made manually) just dissapeared.

only the other ones remained, plus the original 2 that already existed, "AniDB" and "AnimeLists"

![image](https://user-images.githubusercontent.com/105788879/169038884-b5b001c3-9947-4feb-ab1a-c7430571f11e.png)

**Comment by ZeroQI** [comment]
The weirdest thing is that I never had a user having the movie agent and not showing the series one...
You could temp install on a PC Plex and install the agent the same way, but if you see the movie agent, then it is installed correctly and use the same files, so it is bizarre... Seem like a Plex limitation so testing on PC the latest then older Plex version to prove if it is

**Comment by Toastosterone** [comment]
working on windows, both agents visible. looks like the issue is just on qnap

**Comment by ZeroQI** [comment]
Check if you are infected, just in cae
https://www.zdnet.com/google-amp/article/caddywiper-more-destructive-wiper-malware-strikes-ukrainian-targets/

**Comment by Toastosterone** [comment]
qnap hama series agent started appearing after i joined the windows server into the same account:
![image](https://user-images.githubusercontent.com/105788879/169285830-016b446e-7638-4233-8009-39cf400c8f2d.png)

i have no idea why, but it's suddenly fine now. i'm kinda scared of removing the windows PMS now from the account lol

**Comment by Toastosterone** [comment]
qnap and pc are on pms v1.26.1.5798

**Comment by ZeroQI** [comment]
You had a corrupted Plex database most likely:
https://support.plex.tv/articles/repair-a-corrupted-database/
