### ISSUE TITLE
AniDB "studio" in XML

### ISSUE THREAD

**Issue by ViperMagus** [ZeroQI/Hama.bundle#516]
The AniDB script uses the tags "Animation Work" and/or "Work" to fill in a show's studio. Is there a way to add the tag "Production (製作)" to the XML that gets pulled from AniDB and use it as well as a credit for a show's studio? It's easy enough to change the Python script to do that, but it doesn't do anything unless the AniDB's "Hama client" API pulls that information into the XML from http://api.anidb.net:9001/*

**Comment by ZeroQI** [comment]
I would need an anidb ID for a series with that field populated, check if the anidb http api call with that ID display it, then it is possible for HAMA to use, put please. Notice the http API do not specify the field to pull...

Here is a sample API call, just replace the anidb ID with the series with the right field present to check...
http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=11846

**Comment by ViperMagus** [comment]
Looks like the http API call doesn't display that field. Picked a random show and called the API. Looks like it's not an option at all.

Example - http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=15806
Page that has all the staff credits - https://anidb.net/anime/15806

**Comment by ZeroQI** [comment]
I am only using http api for anidb so closing this feature request
