### ISSUE TITLE
Change in data returned from FanartTV API causes exception in anidb34.py

### ISSUE THREAD

**Issue by fire332** [ZeroQI/Hama.bundle#526]
`FanartTV_dict.seasons` can now contain an `all` key in addition to the numeric keys which causes the exception, `invalid literal for int() with base 10: 'all'`, to occur in [anidb34.py#L94](https://github.com/ZeroQI/Hama.bundle/blob/c24f2e336f7891807eacef816d270d973a151826/Contents/Code/anidb34.py#L94).

Inserting
```python
FanartTV_dict.get('seasons', {}).pop('all', None)
```
before [FanartTV.py#L44](https://github.com/ZeroQI/Hama.bundle/blob/c24f2e336f7891807eacef816d270d973a151826/Contents/Code/FanartTV.py#L44) resolves this issue. However, a refactor should be considered to utilize the data in that dict.

**Comment by ZeroQI** [comment]
Thanks for the precise report, i have included as is, as i have no time to devote to using the additionnal data being returned
