### ISSUE TITLE
Using Hama.bundle just for backgrounds

### ISSUE THREAD

**Issue by Ninelpienel** [ZeroQI/Hama.bundle#529]
Hey, I really love Hama.bundle, but I want to match my Anime collection completly with AniList, so I have to use [AniList.bundle](https://github.com/scrobble-moe/AniList.bundle). Is there a way to integrate just the background search from Hama.bundle in AniList.bundle? Unfortunately AniList.bundle only uses the images from AniList and it looks like this:

![image](https://user-images.githubusercontent.com/1890524/188617888-20768ee7-c6d3-4fba-bc67-79c4103eb137.png)

**Comment by ZeroQI** [comment]
Not easilly as the guild will differ....
Find another agent for background only?
https://github.com/sander1/Fanart-TV-Agent.bundle
