### ISSUE TITLE
Incorrect Metadata for shows

### ISSUE THREAD

**Issue by markhc** [ZeroQI/Hama.bundle#530]
This is yet another Monogatari Series issue.

Forgive me if this has been asked before, I am new to Plex and Hama so it's very possible (almost guaranteed) it's something I am doing wrong. I'm trying to add the Monogatari Series to my library and it's been a mess.

The series is correctly picked up by the scanner, but when Hama tries to fetch the metadata, it seems to use Bakemonogatari metadata for every other season of the show. It looks like this:

<img src="https://user-images.githubusercontent.com/11592227/194719025-e146a91b-d895-4784-9448-fc5f86e469f3.png" width="600">

Looking through the logs it seems Hama is using TVDB to grab information about the series, and since tvdb has Monogatari under a single show, it seems to use the same information for every season.

```
AniDB_id: '8357', AniDB_id2: '8357', AniDBid: '8357', TVDB_id: '', TVDB_id2: '102261', TVDBid: '102261'
mappingList: {
  'defaulttvdbseason': '0',
  'defaulttvdbseason_a': False,
  'episodeoffset': '0',
  'imdbid': 'tt3138698,tt5084196,tt5084198',
  'name': 'Kizumonogatari',
  'possible_anidb3': False,
  's1e1_mapped': True,
  'season_map': {'8357': {'max': '0', 'min': '0'}},
  'TVDB': {'s0e2': ('1', '1', '8357'), 's0e19': ('1', '2', '8357'), 's0e20': ('1', '3', '8357'), 's-1': {'8357': '0'}},
  'tvdbcount': 1}
AnimeLists_dict: {
  'collections': ['Bakemonogatari Collection']}
=== tvdb4.GetMetadata() =====================================================================================================================================
not tvdb4 mode
=== TheTVDB.GetMetadata() ===================================================================================================================================
TVDBid: '102261', IMDbid: 'tt3138698,tt5084196,tt5084198', language_series : ['en', 'ja'], language_episodes: ['en', 'ja']
--- series --------------------------------------------------------------------------------------------------------------------------------------------------
common.LoadFile() - File cached locally - Filename: 'TheTVDB\json\102261\series_en.json', Age: '0.56 days', Limit: '6 days', url: 'https://api.thetvdb.com/series/102261?en'
[ ] language_rank: 2
[ ] title: Monogatari
[ ] original_title: Monogatari
[ ] IMDbid: tt1480925
[ ] zap2itId: 
[ ] content_rating: TV-14
[ ] originally_available_at: 2009-07-03
[ ] studio: Tokyo MX
[ ] rating: 8.9
[ ] status: Ended
[ ] genres: [u'Action', u'Animation', u'Anime', u'Comedy', u'Drama', u'Fantasy', u'Romance']
[ ] duration: 1500000
```

I'd like to know what I can do to have the series correctly listed in Plex, that is to say, each "Season" of the show is displayed on its own OR under a single Monogatari Series entry, but split into different series with correct metadata for each (which I think is not really feasible with Plex).

Full logs attached below. Thanks for any help.

This is my file structure, fyi (as you can see I tried forcing the anidb id to see if that would help - it didnt): 

F:\MEDIA\SHOWS\MONOGATARI SERIES is the root for this Library.
```
F:\MEDIA\SHOWS\MONOGATARI SERIES
├───Bakemonogatari [anidb-6327]
│       Bakemonogatari - E01 - Hitagi Crab, Part 1.mkv
│       Bakemonogatari - E02 - Hitagi Crab, Part 2.mkv
│       .... remaining episodes
│
├───Hanamonogatari [anidb-10046]
│       Hanamonogatari Suruga Devil - E01 - Part 1 of 5.mkv
│       Hanamonogatari Suruga Devil - E02 - Part 2 of 5.mkv
│       .... remaining episodes
│
├───Kizumonogatari [anidb-8357]
│       Kizumonogatari - E01 - Iron-Blooded Arc.mkv
│       Kizumonogatari - E02 - Hot-Blooded Arc.mkv
│       Kizumonogatari - E03 - Cold-Blooded Arc.mkv
│
├───Koyomimonogatari [anidb-11827]
│       Koyomimonogatari - E01 - Koyomi Stone.mkv
│       Koyomimonogatari - E02 - Koyomi Flower.mkv
│       .... remaining episodes
│
├───Monogatari Series Second Season [anidb-9183]
│       Monogatari Series Second Season - E01 - Tsubasa Tiger, Part 1.mkv
│       Monogatari Series Second Season - E02 - Tsubasa Tiger, Part 2.mkv
│       Monogatari Series Second Season - E03 - Tsubasa Tiger, Part 3.mkv
│       .... remaining episodes
│
├───Nekomonogatari Kuro [anidb-9453]
│       Nekomonogatari (Black) Tsubasa Family - E01 - Part 1 of 4.mkv
│       Nekomonogatari (Black) Tsubasa Family - E02 - Part 2 of 4.mkv
│       .... remaining episodes
│
├───Nisemonogatari [anidb-8658]
│       Nisemonogatari - E01 - Karen Bee, Part 1.mkv
│       Nisemonogatari - E02 - Karen Bee, Part 2.mkv
│       Nisemonogatari - E03 - Karen Bee, Part 3.mkv
│       .... remaining episodes
│
├───Owarimonogatari [anidb-11350]
│       Owarimonogatari - E01 - Ougi Formula, Part 1.mkv
│       Owarimonogatari - E02 - Ougi Formula, Part 2.mkv
│       Owarimonogatari - E03 - Sodachi Riddle, Part 1.mkv
│       .... remaining episodes
│
├───Tsukimonogatari [anidb-10891]
│       Tsukimonogatari Yotsugi Doll - E01 - Part 01 of 4.mkv
│       Tsukimonogatari Yotsugi Doll - E02 - Part 02 of 4.mkv
│       .... remaining episodes
│
└───Zoku Owarimonogatari [anidb-13691]
        Zoku Owarimonogatari - E01 - Part 1 of 6.mkv
        Zoku Owarimonogatari - E02 - Part 2 of 6.mkv
        .... remaining episodes
```

Agent logs: 
[_Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/9739865/_Logs.zip)
[PMS Plugin Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/9739867/PMS.Plugin.Logs.zip)
Scanner logs:
[Scanner Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/9739871/Scanner.Logs.zip)

**Comment by ZeroQI** [comment]
Monogatary is the worst ever anime to sort. 
There was posts on Plex forums
https://forums.plex.tv/t/how-do-i-separate-mistakenly-matched-versions-of-a-tv-show/160249/9
All these series being grouped in TheTVDB they will share posters and metadata but I had an offset generator to avoid duplicate posters
You may want to remove tvdb from metadata sources at your own risk or manually set anidb agent for these few series...

**Comment by markhc** [comment]
Thanks. I just used another agent (the MAL agent) for the series and that seems to have sorted it out. Good to know it might happen to other series grouped on TVDB as well. Now i'm prepared :)

**Comment by ZeroQI** [comment]
You can edit per field the tetadata source order. Tvdb has better posters. You can have proper collections using grouping folders and using Local metadata source only
