### ISSUE TITLE
Wrong meta data source for Cast

### ISSUE THREAD

**Issue by noobschoolbus** [ZeroQI/Hama.bundle#531]
After downloading the latest Hama code last night, scanning newly added series to my collection grabs the Cast meta data from (I believe) thetvdb instead of anidb. This same problem happened to me while ago, but oddly went away on its own after some time.

Note: I re-scanned my entire Plex library's meta data last night. Only shows added after the massive re-scan have been affected. Could this have anything to do with making too many requests to anidb.net? If I wait long enough and re-scan, could the meta data fix itself?

How my usual meta data looks:
![image](https://user-images.githubusercontent.com/76540667/195994547-cf9ae2d4-9dbc-4804-85d8-8d091ec76b2b.png)

How it looks now...
![image](https://user-images.githubusercontent.com/76540667/195994551-248c3692-7082-4177-a504-26332f31d97e.png)

**Comment by ZeroQI** [comment]
HAMA is not an Anidb only agent. Each field has its own separate agent setting, for 'roles' it is anidb, tvdb by default... 
Custom per series log do show the source for any field and would show what metadata source was used, and which source also had data available for each field at the end of the log.

You are not giving the series, logs, or even show anidb and tvdb metadata sources to show there is actually an issue... You haven't check setting or logs...

**Comment by noobschoolbus** [comment]
Ok I see the roles field with anidb,tvdb. I didn't realize that field is used for cast metadata, thank you.

I attached agent-search and agent-update logs.
[[GJM] Kaguya-sama wa Kokurasetai Ultra Romantic (WEB 1080p HEVC AAC) [anidb-15806].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/9792630/GJM.Kaguya-sama.wa.Kokurasetai.Ultra.Romantic.WEB.1080p.HEVC.AAC.anidb-15806.agent-update.log)
[[GJM] Kaguya-sama wa Kokurasetai Ultra Romantic (WEB 1080p HEVC AAC) [anidb-15806].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/9792631/GJM.Kaguya-sama.wa.Kokurasetai.Ultra.Romantic.WEB.1080p.HEVC.AAC.anidb-15806.agent-search.log)

**Comment by ZeroQI** [comment]
`[=] roles                    (11)  Sources: AniDB,(TheTVDB)                                               Inside: '['TheTVDB']'  Value: '[{'photo': 'https://thetvdb.plexapp.com/banners/v4/actor/7897330/photo/6250eb1f2e563.jpg', 'role': 'Kaguya Shinomiya', 'name': 'Aoi Koga'}, {'photo': 'https://thetvdb.plexapp.com/banners/v4/actor/7869890/photo/6250eb80428e2.jpg', 'role': 'Miyuki Shirogane', 'name': 'Makoto Furukawa'}, {'photo': 'https://thetvdb.plexapp.com/banners/v4/actor/7891685/photo/6250ec1d80320.jpg', 'role': 'Chika Fujiwara', 'name': 'Konomi Kohara'}, {'photo': 'https://thetvdb.plexapp.com/banners/v4/actor/7866045/photo/6250ec70cc495.jpg', 'role': 'Yuu Ishigami', 'name': 'Ryouta Suzuki'}, {'photo': 'https://thetvdb.plexapp.com/banners/v4/actor/303148/photo/6250ecced5fd7.jpg', 'role': 'Ai Hayasaka', 'name': 'Yumiri Hanamori'}, {'photo': 'https://thetvdb.plexapp.com/banners/v4/actor/464899/photo/6250f02265ddf.jpg', 'role': 'Miko Iino', 'name': 'Miyu Tomita'}, {'photo': 'https://thetvdb.plexapp.com/banners/v4/actor/7937849/photo/6250ed5978a69.jpg', 'role': 'Kei Shirogane', 'name': 'Sayumi Suzushiro'}, {'photo': 'https://thetvdb.plexapp.com/banners/v4/actor/8051705/photo/6250edcd9e891.jpg', 'role': 'Nagisa Kashiwagi', 'name': 'Momo Asakura'}, {'photo': 'https://thetvdb.plexapp.com/banners/v4/actor/460206/photo/6250ee4658e1e.jpg', 'role': 'Tanuma Tsubasa', 'name': 'Taku Yashiro'}, {'photo': 'https://thetvdb.plexapp.com/banners/v4/actor/8143505/photo/6250f084c5e20.jpg', 'role': 'Kobachi Osaragi', 'name': 'Rina Hidaka'}, {'photo': 'https://thetvdb.plexapp.com/banners/v4/actor/277098/photo/62645ffc62857.jpg', 'role': 'Shirogane no Chichi', 'name': 'Takehito Koyasu'}]'`

HAMA found no roles in anidb so used tvdb.
You are banned on anidb

AniDBid: 15806, IsPrimary: True, url: http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=15806
--- 15806.series --------------------------------------------------------------------------------------------------------------------------------------------
ERROR: common.LoadFile() - Error response received, file: "<error code="500">banned</error>"

Working as designed
