### ISSUE TITLE
Shows getting stuck as xxx [tvdb-####] 

### ISSUE THREAD

**Issue by kanjieater** [ZeroQI/Hama.bundle#532]
When trying to add series that did not match automatically, I put in the id of the series to match it, in the Fix Match -> Search Options. So for  https://anidb.net/anime/16054, it would be 16054. Hama then finds xxx [tvdb-16054] (it used to get the actual name?). Now it is stuck as xxx with no metadata. How can I resolve this?

![image](https://user-images.githubusercontent.com/32607317/199700120-b0802c46-59a2-49bb-803d-d60fc704b307.png)
![image](https://user-images.githubusercontent.com/32607317/199700149-7a3277f4-6d79-49f8-b7e6-ebbad21b13e2.png)

**Comment by ZeroQI** [comment]
No series specific search logs attached... 

Just the bare ID is for tvdb only
'Whatever [anidb-16054]' would work
