### ISSUE TITLE
get metadata for cast from TheMovieDB

### ISSUE THREAD

**Issue by vorteex** [ZeroQI/Hama.bundle#533]
Comparing to TheTVDB and AniDB, TheMovieDB has the largest database when it comes to cast, so it would be great if you could give support to TMDB.

**Comment by ZeroQI** [comment]
TheMovieDb movies and series are supported with tmdb/tsdb ID, but not for
'roles'...

One could edit
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/TheMovieDb.py
to
include roles in tmdb dict from the JSON and add to agent settings the
'TheMovieDb'
metadata source for the base functionality but there is a caveat...

Knowing TheMovieDb ID is not always included in the AnimeLists, results
with tmdb ID will be scarce and inconsistent, so it is not actually
meaningful I believe as a result. Don't forget we search and match to one
database and cross reference the IDs, and tmbd is not documented enough but
anidb to tvdb IDs work well, so not workable in my own opinion...

**Comment by vorteex** [comment]
Oh, I see. Thanks for the answer.
