### ISSUE TITLE
Local assets (poster.jpg) missing from movies 

### ISSUE THREAD

**Issue by brandonhowlett** [ZeroQI/Hama.bundle#535]
Recently implemented RPDB in Plex to add ratings to all posters.

Local asset posters showed up alongside those pulled by Hama for all anime series. However, no local assets appear for anime movies (e.g., Akira - Complete Movie (1988) [imdb-tt0094625].mkv). I've confirmed that the poster.jpg and background.jpg files exist, were updated by RPDB, and mirror series directories. Neither refreshing metadata nor scanning library files load the local assets in edit > posters.

Using the most recent versions of Hama and ASS.

**Comment by ZeroQI** [comment]
https://support.plex.tv/articles/200220677-local-media-assets-movies/

https://support.plex.tv/articles/200220717-local-media-assets-tv-shows/

Local media assets agent managing the import is Plex agent and code, so not an Hama issue, closing it.
