### ISSUE TITLE
HAMA not picking up Title Cards as Local Media Assets

### ISSUE THREAD

**Issue by thealexmay** [ZeroQI/Hama.bundle#537]
Fairly simple issue here. I use ASS/HAMA for my anime library but use local media for posters. I have the scanners set up as the wiki says with Local Media Assets placed above HAMA. It works great for posters, never had an issue. Recently, I've started adding title cards for my series, and they don't get picked up for anything in my anime library. I'm naming them according to Plex specifications, and made sure to check the wiki to see if they should be named differently but did not see anything. So as an example, I have:

```
Dragon Ball (1986) [tvdb4-76666]/
  Season 01 - Emperor Pilaf Saga/
    Dragon Ball - 001 - Secret of the Dragon Balls.mkv
    Dragon Ball - 001 - Secret of the Dragon Balls.png   <---   title card image file
```

But when named/stored this way, it is not picked up as a local media file. Even if I go to change the image for the episode manually through Plex's interface, my local file does not populate in the images to select from. Does Hama not support title cards as local media assets?

**Comment by ZeroQI** [comment]
Local media assets is a Plex agent, no local file functionality is implemented in Hama apart from the agent cache in agent data folders. Selecting file manually not working is a Plex issue. Sounds like a corrupted Plex database to me
