### ISSUE TITLE
How to investigate wrong matching for a season?

### ISSUE THREAD

**Issue by Moreasan** [ZeroQI/Hama.bundle#540]
Some of my seasons (24, 25, 27, 28) of Detective Conan were not matched, and I would like to know how to fix, or at least find out why? 
![Screenshot 2023-01-17 at 08-22-52 Plex](https://user-images.githubusercontent.com/121057007/212835063-2524bfd6-d589-4ad4-8c86-27f1053cfb02.png)

Also, how should I name specials episodes (OVA and else)? I have got some that were incorrectly matched.

**Comment by ZeroQI** [comment]
You match à série or movie not season... 
Do you mean it pulled the poster for another season number instead? 

Well one should go into the series specific agent logs and check the metadata source for the poster and check that source xml or JSON for errors. Path is in the readme troubleshooting section

Please ask the numbering on the Plex forum some would have solved that and give proper example.

**Comment by ZeroQI** [comment]
Not an Hama issue then...
As you probably saw the logs at the end allow to pinpoint the source and link to the poster, I did put some effort into this to curb the metadata source issues, and am glad they were of use here, and thanks for updating, that spares me some time
