### ISSUE TITLE
Metadata will not populate for Anime movies.

### ISSUE THREAD

**Issue by DevineAfterNine** [ZeroQI/Hama.bundle#541]
Good morning,

I have installed HAMA and ASS.
Most of the anime in my library has been categorised and metadata has populated correctly.
When in comes to a few of the movies, it initially pulled metadata for a different title.
I have renamed the files, it shows them as their own individual items without any metadata.
I've reviewed the instructions and it mentions the AniDB ID and as far as I understand adding this to the file name should point it to the entry on AniDB to pull metadata from.
This did not work.
I admit I may have done this part incorrectly or misunderstood and missed a step.
Please advise.
Also, I'm somewhat new to this and new to GitHub.
Please bear with me and be as concise as possible for an information needed.
Thanks.

**Comment by ZeroQI** [comment]
You are new to read the readme troubleshooting section too? 
- It list the location of all the logs
- it gives the breakdown of which medium to use to raise the issue...  Support thread for agent:

https://github.com/ZeroQI/Hama.bundle/issues (proven or confident enough it's a bug. Include the library name, the symptoms, the logs mentionned above)

https://forums.plex.tv/discussion/77636/release-http-anidb-metadata-agent-hama#latest (not sure if bug, if bug will create a gihub issue ticket)

Seems like you naming for the folder is sub-par and did not reach 80% similarity to one of anidb's titles, unless naming made it so you have a season 2 or more and would have used TheTVDB instead to match. 

You could rename the folder the same as Anidb. 
You could review the *.search.log file in agent data folders to check why it didn't assign a unique ID if all metadata is missing
