### ISSUE TITLE
Movies agent not confident enough to match without intervention

### ISSUE THREAD

**Issue by sgtsquiggs** [ZeroQI/Hama.bundle#544]
My movie:
```
/data/anime_movies/Evangelion 3.0+1.0 Thrice Upon a Time (2021) {tmdb-283566}/Evangelion 3.0+1.0 Thrice Upon a Time (2021) {imdb-tt2458948} [AMZN][WEBDL-1080p Proper][EAC3 5.1][x264]-RMB.mkv
```

(I also tried with the imdb in the folder/file names)

![image](https://user-images.githubusercontent.com/3420325/222925750-4a9114e5-c054-44da-bf18-4bdf64edd68e.png)

If there is a way to get the anidb IDs into the folder/file names via sonarr I'd _love_ to know how!

Disclaimer: Obviously I'm using a zeroed file to test this feature and I didn't actually download this video. 🙄

**Comment by ZeroQI** [comment]
That's a use case question, for the Plex forum thus as outlined in the readme in the troubleshooting section.. . 
Readme states to use [tmdb-283566] in folder name in the readme forced ID section...
Remove - rmb at the end and proper square brackets
Why are you using these brackets?
Please search exhibit 1 in the readme
