### ISSUE TITLE
i want to have two Hama agents

### ISSUE THREAD

**Issue by iEusKid** [ZeroQI/Hama.bundle#545]
as in the title, how i do that? i tried to duplicate it in the plugins folder but didn't really duplicate

**Comment by ZeroQI** [comment]
You have to change the unique identifier stringsCFBundleIdentifier by hama2 and label the folder the same. Keeping the same identifier would fail

https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Info.plist

**Comment by iEusKid** [comment]
"Your changes could not be saved." when trying to set the plex Library to it

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/__init__.py#L162
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/__init__.py#L168

Class must change to Hama2 as well
