### ISSUE TITLE
Trakt scrobbler not working

### ISSUE THREAD

**Issue by Thomiehawk** [ZeroQI/Hama.bundle#549]
I am using the Plex scrobbler webhook  but when watching an anime, it does not show up in now watching in trakt. With regular tv shows not using the hamatv agent it does work.

If there's more info I need to provide I'll gladly do so

**Comment by Thomiehawk** [comment]
Does this perhaps only work with tvdb guid's and not anidb guid's?

**Comment by ZeroQI** [comment]
There is no official trakt support. It would work only with tvdb ID and not even the tvdb I'd format I use for the internal guid
