### ISSUE TITLE
Missing Genre entries

### ISSUE THREAD

**Issue by jobe102282** [ZeroQI/Hama.bundle#550]
I am using the AnidbGenresMainOnly option to pull only the genre that is listed on the Anidb page. Except I'm not seeing all the genre data being pulled in.  

Example: Anime https://anidb.net/anime/618 Ikkitousen ([a618](https://anidb.net/a618))

has: action, ecchi, manga, martial arts, pantsu, seinen, violence
But Hana is only shows: Super Power,Action,Ecchi  <--Not sure Why Super Power is pulling. 

Is there something im doing wrong?

**Comment by ZeroQI** [comment]
Besides not attaching logs you mean?
Genres have weight but without the anidb http API link cannot confirm which for this anime...
Tried lowering genre weight in agent setting to 100 or 50?

**Comment by ZeroQI** [comment]
http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=618[Anidb 618 json](http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=618)h81i

Superpower weight is 200 pants 600, manga 0, martial arts 600, seinen 0, violence 400

https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/AniDB.py Line 199 onwards
