### ISSUE TITLE
Adding to TrueNAS SCALE containers

### ISSUE THREAD

**Issue by Sawtaytoes** [ZeroQI/Hama.bundle#552]
TrueNAS SCALE uses a Docker volume to store configuration data. I'm not actually sure how I'm supposed to add plugins. Honestly, it'd be nice if Plex let me configure that directory, but that's not possible right now.

**Comment by ZeroQI** [comment]
How is that my agent specific issue if you can't add any agents/Plugins? That seem clearly a Plex issue on a questionably supported os..

**Comment by Sawtaytoes** [comment]
You documented ways of adding it to different clients, but you're missing the one for TrueNAS SCALE.

I figured you might know how and could add it to the existing documentation.

**Comment by ZeroQI** [comment]
The agent is OS agnostic. 
I documented when client fed back information details to spare people time... 
I do not reproduce bugs and rely on users following decorum and providing logs

The readme clearly states the medium to use to raise issues and the forum would have been the one to use as you may already have a user using it. This seem like a spécialisés OS not really user oriented. You use docker on top. Semm like a docker plex query on how to install Any user agents...

**Comment by Sawtaytoes** [comment]
It seems like the way to do it in TrueNAS SCALE (via the TrueCharts image) is to:
1. Enable a Code Server.
2. Drag 'n drop into the `config/Library/Application Support/Plex media Server/` dir.

![image](https://github.com/ZeroQI/Hama.bundle/assets/3948069/212768a3-d24a-49ca-891b-25c14ee22924)

![image](https://github.com/ZeroQI/Hama.bundle/assets/3948069/c0cc39ec-87b1-41d1-a4ca-3b9c7acddaaa)
