### ISSUE TITLE
Japanese Summaries

### ISSUE THREAD

**Issue by buckeyez** [ZeroQI/Hama.bundle#553]
I am getting Japanese summaries in some cases. Should I just remove `main` and `ja` from these seetings to ensure everything is in `en`?

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/16466948/963dbeb0-b11e-4a9a-b8e5-dc8c77f4d70b)

**Comment by ZeroQI** [comment]
Are you posting Agent usage issues as scanner bug???
- Summaries are using Plex library language setting, so i guess you used 'Japanese' when creating the library or there is only a japanese summary
- If you want to force a metadata refresh Plex call it exactly that
- Most questions are HAMA agent user questions that an experience user could answer, so Plex forum was better suited

Per series agent logs would show the summary used and why, but not attached, series folder name and files exemple missing, use case issue...
