### ISSUE TITLE
Make Discover Credits functionality compatible with HAMA

### ISSUE THREAD

**Issue by xtremecold** [ZeroQI/Hama.bundle#554]
Would it be possible to make Discover Credits functionality work while using HAMA agent?

According to Plex support article - https://support.plex.tv/articles/discover-credits/ - the following are reasons to go to a filtered library grid instead:

- “Include adult content” is enabled for the library
- The library uses a legacy metadata agent (not our current, recommended agent).

**Comment by ZeroQI** [comment]
No. Because it is a new type library type functionality, as new t'y libraries are incompatible with python based legacy agent

> The library uses a legacy metadata agent (not our current, recommended agent).
> 
> You can fix that by upgrading the library to use the newer metadata agent, doing a library scan, and then refreshing all items in the library.
>
