### ISSUE TITLE
Locked (edited) fields are overwritten when applying anidb mapping

### ISSUE THREAD

**Issue by efalsken** [ZeroQI/Hama.bundle#555]
As discussed in this [Absolute-Series-Scanner thread](https://github.com/ZeroQI/Absolute-Series-Scanner/issues/441#issuecomment-1722318815):

- Given: a folder with an `[anidb-xxxx]` tag `Twin Star Exorcists [anidb-11785]`
- Given: in Plex metadata, edit the title from `Sousei no Onmyouji` to `Twin Stars Exorcists` and verify that the "lock" icon is lit.
- Given: Mark one episode as watched.
- Rename the folder in an inconsequential manner: `Twin Star Exorcists (2016) [anidb-11785]` -> `Twin Star Exorcists [anidb-11785]`
- Scan Anime
- Witness: The series is now renamed back to `Sousei no Onmyouji`. 
- Witness: The watch status is still the same.

The previously-locked metadata has been overwritten with fresh data from Anidb.... ignoring the "locked" flag on the field and my previous edits. This does not match the expected behavior:
![image](https://github.com/ZeroQI/Hama.bundle/assets/253640/207c268c-b568-4e14-9717-49877640f18f)

**Comment by ZeroQI** [comment]
So Plex ignore the lock icon, and somehow it's the agent problem? I don't get it...

**Comment by efalsken** [comment]
I was looking at the responsibilities documented here: https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/README.md#plex-agent-responsibilities

I'm not sure if it's Plex, the Scanner, or the Agent which is responsible for honoring the Lock. The lock works when using "refresh metadata" but not when matching. It works as intended if I do something similar with a Plex-Scanner folder. Or if I use "fix match", but not when using Absolute-Series-Scanner and Hama.

**Comment by ZeroQI** [comment]
The agent provide an array of metadata to plex.
It does not handle locks, that's a Plex decision.
Now if you change the folder and it gets a different unique ID I would understand it lose the lock information, but that's not the case here... I can safely say the lock is a Plex behaviour and not in scanner or agent responsability...

**Comment by efalsken** [comment]
Can you help me report this as a bug then to Plex? I don't think I have enough detail since this involves plugins.

**Comment by ZeroQI** [comment]
I have no contact or relations or even a Plex pass...

It does NOT involve an agent though... You lock a field, and plex update it when it shouldn't since it Was locked... The metadata field provided by the agent is irrelevant since The agent is unaware of field locked, it return the metadata structure identically regardless....
