### ISSUE TITLE
"Refresh Metadata" removes customizations

### ISSUE THREAD

**Issue by Sawtaytoes** [ZeroQI/Hama.bundle#556]
## Platform

Operating system and version: Linux Docker container `14.0.5`
Plex version: `1.32.6.755`

## Expected Behavior

When clicking "Refresh Metadata", it should leave my customizations alone once a show has been added.

Plex default scanners also do auto-collections, but once that media has been added, it stops creating auto-collections and messing with items inside even if I click "Refresh Metadata". They must have some sort of caching involved like an "already added" flag.

## Current Behavior

I clicked "Refresh Metadata" on my entire anime library, and Absolute Series Scanner moved everything out of the places I put them and out of the order I used.

Now I have a situation where I have all these Collections with nothing in them. This wouldn't be an issue if all the automatic-collections were correct, but they're not.

There are other situations where auto-collections are wrong:
1. **Patlabor** OVAs in the wrong collection. They should be in the same collection as the movies, not the TV show as they're part of the movie canon.
2. **Broken Blade** (Break Blade) has the TV show and movies in the same collection, but they're separate universes.
3. **Vision of Escaflowne** and the movie are unrelated universes, but they're in the same collection.
4. The **Gintama** collection doesn't include the TV series, only the movies. The movies are canon and need to be slotted between seasons. Absolute Series Scanner doesn't have seasons for Gintama in collections though.
5. The ordering in **Armored Troopers Votoms** is wrong, and it's supposed to be chronological.
6. The 6 OVA compilations of the original **Armored Troopers Votoms** show are out of order with Vol. II happening first, then 4 other ones in random order, and then Vol. 1 last.
7. The **Fullmetal Alchemist: Brotherhood movie** is in the Fullmetal Alchemist (2003) collection, but it's part of the Brotherhood universe and should be watched after that series completes, not the 2003 version.
8. The **Mobile Suit Gundam** collection only includes 3 of the UC series and leaves 5 of the rest outside of a collection.
9. **Legend of the Galactic Heroes: Die Neue These** is not in a collection, yet I have 3 seasons of the show.

## Steps to Reproduce

1. Customize shows by moving them around to different collections and rename collections.
2. Click "Refresh Metadata" on the anime library using Absolute Series Scanner.
3. All customizations will be reset back to the original auto-collection values from Absolute Series Scanner.

## Additional information

Screenshots of some of the situations I talked about:
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/a494db71-f1cf-465e-8bc1-b168e3b01d44)
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/054a64eb-9502-44ab-a851-719c9ce0e19c)
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/63c58d3e-ca25-4d19-aaf3-c031b473703c)
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/dd5004c6-cf64-435b-878c-cba1b2138f3f)

**Comment by Sawtaytoes** [comment]
I tried creating a local collection. I created a folder in `Anime/` called `Overlord Collection`. Then I put all 3 Overlord shows in there with their proper `anidb` IDs:
![image](https://github.com/ZeroQI/Hama.bundle/assets/3948069/204fd986-6c18-4760-a994-da6b98fa3bd7)

But I'm seeing 3 versions of the show combined into 1 Overlord show for Season 1 somehow:
![image](https://github.com/ZeroQI/Hama.bundle/assets/3948069/9191cb47-7422-46eb-b8c3-65ffe2a453e2)

How am I supposed to setup local collections?

**Comment by ZeroQI** [comment]
You have used what I called a grouping folder.
The library root should be Anime
ASS scanner will not use cache and scan the full content at every Plex scan
Plex series scanner would use the folder at root as single series. 
If using ASS Scanner, you should split the series 
You should use 'Local' only for the collection field metadata source order, and it will use grouping folder as collection.
Again grouping folders are super slow to scan as plex do not rescan if the folder content hasn't changed, but the function is nice so...

**Comment by Sawtaytoes** [comment]
Ok, I went back to putting episodes in the `Anime/` root directory. 👍

**Comment by ZeroQI** [comment]
Not sure I understand
Episodes should be in their series folder inside the library root
Multiple eps with same season and ep number in same folder should result in scanning issues

**Comment by Sawtaytoes** [comment]
I went back to this method:

![image](https://github.com/ZeroQI/Hama.bundle/assets/3948069/bad04875-446c-4cff-a8bc-664b510f2bb9)

![image](https://github.com/ZeroQI/Hama.bundle/assets/3948069/9c81ba04-97be-465b-a94d-78793ed5e316)

![image](https://github.com/ZeroQI/Hama.bundle/assets/3948069/ea39d8fd-7c99-4b92-9c3c-8a6630ddd964)
