### ISSUE TITLE
Not finding the newer series

### ISSUE THREAD

**Issue by pietchaki** [ZeroQI/Hama.bundle#557]
I'm having an issue where animes from the current season are not matched, and some can match only to tvdb.
Older series are found and matched to AniDB without any issue. 
As example, Goblin Slayer Season 2 and Shield's Hero season 3 doesn't match anything, but Sousou no Frieren matched to AniDB automaticaly. older seasons seem to be working fine, just the newer are having problems.

I had updated the hama.bundle folder and deleting com.plexapp.agents.hama folder, but same problem

I went looking for in the logs, and noticed that some files seem to only try tvdb, others only AniDB, and a few were searched on both... not sure if this

**Comment by ZeroQI** [comment]
Multiple seasons series will be matched to TheTVDB as AniDB consider seasons of a show different series so everything is season 1...

Custom series search log located in agent data folder missing.
- If 'season' is in the title ASS might scan with a season and match to tvdb, and if series title does not include season normally then it won't match...

**Comment by pietchaki** [comment]
Oh, sorry, forgot to append the logs.
[Plex Media Server Logs_2023-10-13_14-23-11.zip](https://github.com/ZeroQI/Hama.bundle/files/12896482/Plex.Media.Server.Logs_2023-10-13_14-23-11.zip)
[PluginSupport_Data_com.plexapp.agents.hama_logs.zip](https://github.com/ZeroQI/Hama.bundle/files/12896483/PluginSupport_Data_com.plexapp.agents.hama_logs.zip)

I understand how seasons are handled by AniDB, and I like it that way. 
I try to use AniDB titles where possible, and when manually matching I always use AniDB title.
The shows I'm having trouble don't have the word "season" on them but have the correct season name from AniDB, example is "Goblin Slayer" for season 1 and "Goblin Slayer II" for season 2, or "Selector Infected WIXOSS" for Season 1 and "Selector Spread WIXOSS" for season 2.
My folders are usually named as the AniDB title for that season, as mentioned above.
My files are usually named as AniDB title with the season, and some are using "S#E#" pattern.
Does the file naming also affect manual matching?

**Comment by ZeroQI** [comment]
Citrus: anidb-12545 score 98% matching
season 2 thus tvdb matching:
- "E:\Vuze_Animus_RSS\Goblin Slayer II\[DKB] Goblin Slayer - S02E01 [1080p][HEVC x265 10bit][Multi-Subs].mkv"
- "E:\Vuze_Animus_RSS\Kanojo mo Kanojo II\[DKB] Kanojo mo Kanojo - S02E01 [1080p][HEVC x265 10bit][Multi-Subs].mkv" 
- Kenkei Zumi missing space: [-] score:  74, aid: 17616, title: "Keiken Zumi na Kimi to, Keiken Zero na Ore ga, Otsukiai Suru Hanashi."
- Sousou no Frieren score 100%
- shield hero 3 logs missing

Please tell me what you do not understand in this phrase:

> Multiple seasons series will be matched to TheTVDB as AniDB consider seasons of a show different series so everything is season 1...

Since you use s02exx you do Not follow AniDB numbering and TheTVDB is used not finding anidb only title. Again, AniDB is season 1 only, so working as designed and you cannot have anidb matching with season 2 episides

**Comment by pietchaki** [comment]
So, the whole problem in my case was that I use AniDB title in the folder name, and my filenames have a season tag. Then Plex use the folder name to search for the show, but tries to match to a specific season in that show that AniDB don't have, and instead of proceeding with the match and displaying as an "unknown" season of that show, it completely discards that AniDB match. 

> Please tell me what you do not understand in this phrase:
> 
> > Multiple seasons series will be matched to TheTVDB as AniDB consider seasons of a show different series so everything is season 1...

I thought Hama would try matching to tvdb, not prevent me from using AniDB. I didn't understand that if I have a season in the file name, it becomes impossible for hama to match that show to an AniDB entry. 

>     * shield hero 3 logs missing

Shield Hero 3 is basically the same as Goblin Slayer and Kanojo mo Kanojo: not matched to anything, anidb or tvdb.

I now understand that if any kind of season number is present in the file name, Hama will not allow me to match that content to a AniDB entry. I understand that it works that way on the Auto matching phase, but if I use the manual matching function in Plex, I want to force it to match to a specific show using the name I entered in the "Fix Match" > "Search Options". Also, if I enter the correct AniDB title in the manual search, I'd assume it would ignore any kind of automatically gathered data, so if I say that the "Goblin Slayer - S02E01" should be matched to "Dragon Ball GT" on AniDB, then Hama should just accept that, use episode number as is and any other issue is users fault. 
Maybe if the show name we are searching is a good match to an aniDB entry, you could ignore the season number in the filename, pick only the episode number and match it to the episode in AniDB. It seems quite simple to do, but I do understand that many tasks that seems to be simple, are actually really hard to implement. I hope you can think about this idea, and if possible implement it as an improvement. There would be problems if multiple seasons are in the same folder, all the episode1 would be joined, but then it is the users fault of putting multiple episode 1s inside the AniDB folder.

**Comment by ZeroQI** [comment]
Anidb is season 1 only. If filename are season 2, they use tvdb numbering. No negociation...
You can use search with forced id's, but the file being the wrong season would get wrong or no metadata...

**Comment by pietchaki** [comment]
> You can use search with forced id's, but the file being the wrong season would get wrong or no metadata...

Not sure if I understood this part.
I have a separate folder for each season following AniDB titles (for example "animes/Goblin Slayer" and "animes/Goblin Slayer II"), you mean that if I force matching the second season to a specific AniDB ID, it won't get the correct metadata for the second season I specifically set? Or that it will get the metadata for the show, but episode name and description may not be set?
If it is this second option, wouldn't be possible to ignore the season for matching in this case? Then "RandomAnime II [anidb-00000]/RandomAnime s02e10.mkv" would be matched to AniDB's "Random Anime Second Season" (second season of RandomAnime, matched by the AniDB ID), episode 10.

**Comment by ZeroQI** [comment]
Anidb = season 1 max
How can you expect metadata on s02e0e when anidb only has so1e01?

You pick pick your metadata source then respect the numbering. You are doing it backwards. You are posting a bug report for a use case when readme states which medium to use depending the case...

I give up...

**Comment by pietchaki** [comment]
Man... seriously... I understand how AniDB handles seasons. I said I understand that concept in my second reply. And the third. And the fourth... 

I opened this as Bug Report because at the time, from my point of view, it just didn't work for some of my shows. Now I know that the issue is my new file source using a different naming pattern, and I know it's not a bug.
I understood what was the real issue from your second answer in this tread, and after that I asked if it would be possible to add an improvement, which you didn't answer. You just kept talking about "AniDB has no season".

Your plugin has all the information it needs for the improvement: It knows if the search is automatic or manual, from where it has a match (AniDB/tvDB), and it knows the filename. With that, its as simple as
```
SearchTvDB(...)
IF manual_search OR NOT filenameHasSeason THEN
    SearchAniDB(...)
ENDIF

...

# after matching
episodeName = filename
IF manual_search && matched_to_AniDB THEN
    episodeName = RemoveSeason(episodeName )
ENDIF
```
Using RegEx for the "RemoveSeason()" method, could be matched with `/((s00)|(s?[\d]{1,2}))[._xe]+([\d]{1,2})([ -]*[._xe]+([\d]{1,2}))*` (case insensitive and global search), and for replacing `${2:+s}$4${5:+-$6:}` (IF 2nd group matched, add an 's'; add content of the 4th group; if 5th group matched, add '-' and the 6th group).

.
> 
> It is awfully complex to map EVERY EPISODE between Anidb and TheTVDB?

YES! It IS!
Well... technically not, but I have a ton of files using one scheme, and newer will use another.
You know how I get my files, and you know that renaming such files lead to a lot of issues for the source app ( at least to those that stay as an active peer after the download is complete, which is my case ).
I also use RSS feeds to automate file downloads, it will get the file, place in the correct folder and keep track of file version, updating as needed, and that software needs the files with their original names to work.
As I said, filename may have a season, but folders are separate as in AniDB scheme. So the only problem is Hama not allowing me to force matching to whatever I want. Everything else already working.

Now my time to ask: It is awfully complex to ignore the season tag in a file name if currently performing a manual search?

**Comment by ZeroQI** [comment]
Seasons are chosen by the scanner, so you want to leave season 2 but have Hama disregard it to display episode metadata correctly? Reverse mapping of episode metadata from tvdb to anidb through the xml would get broken...

Most people would leave torrents in a temp download folder and number properly the folder used for Plex library...

Hama so allow forced ID in a file or search so you could overwrite the season without renaming files... "series [anidb-12345-s1]" would make the misnamed anidb series season 1, that is what I meant by season one, as per ASS readme, for Ed I'd section, advanced mode subsection...

It is utterly pointless to code it as mapping through xml must work both ways between anidb and tvdb and your suggestion break that I believe. Without renaming folder or files this can be fixed, so why would I complexify the code further needlessly?
