### ISSUE TITLE
Naruto Arcs not being correctly named, I think my tvdb4.mapping file is being ignored and is using the online xml file?

### ISSUE THREAD

**Issue by AdamZane** [ZeroQI/Hama.bundle#562]
I put this issue in ASS, and because my files are actually in the right spot, I think it may be a hama issue, I won't rewrite all the details though: https://github.com/ZeroQI/Absolute-Series-Scanner/issues/484

Here are all the logs I think:
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/14305816/com.plexapp.agents.hama.log)
[com.plexapp.system.log](https://github.com/ZeroQI/Hama.bundle/files/14305817/com.plexapp.system.log)
[Naruto [tvdb4-78857].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/14305839/Naruto.tvdb4-78857.agent-update.log)
[Naruto [tvdb4-78857].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/14305842/Naruto.tvdb4-78857.agent-search.log)
[_root_.agent.log](https://github.com/ZeroQI/Hama.bundle/files/14305861/_root_.agent.log)

**Comment by ZeroQI** [comment]
What metadata do you have that is wrong, and what did you expect it to be?

**Comment by AdamZane** [comment]
This is what I would like my Arcs to be:
![image](https://github.com/ZeroQI/Hama.bundle/assets/119836760/d183dea8-1959-4ea5-bc39-ea09c66a2e3b)

This is the Metadata for season 2 I have received in plex:
![image](https://github.com/ZeroQI/Hama.bundle/assets/119836760/3a0a97c8-abd3-4ddb-8bb0-c4f6fac4183a)

As you can see in that picture, say episode 13, 
it should be getting this metadata: "https://thetvdb.com/series/naruto/episodes/296987" 
but instead it gets this metadata: "https://thetvdb.com/series/naruto/episodes/297022"

I think it is pulling from the tvdb4.mapping.xml file rather than matching to my tvdb4.mapping file. 

Let me know if further elaboration is needed

**Comment by AdamZane** [comment]
I am going to move these comments to the other thread and keep everything there so this does not get confusing

**Comment by ZeroQI** [comment]
Ep s01e13 abs number 13 "Haku's Secret Jutsu: Demonic Mirroring Ice Crystals" getting s02e13 abs number 48 metadata "Gaara vs. Rock Lee: The Power of Youth Explodes!" metadata... Clearly a metadata hence agent issue mapping file is to put eps in the right season

**Comment by AdamZane** [comment]
So I was right, it is an agent issue, thus everything should be within this thread? Dang it?

**Comment by ZeroQI** [comment]
Pure agent issue since eps at right season and episode number, closing this one

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/tvdb4.py
absolute_map: {'1': ('1', '1'), '2': ('1', '2'), '3': ('1', '3'), '4': ('1', '4'), '5': ('2', '5'), '6': ('2', '6'), '7': ('2', '7'), '8': ('2', '8'), '9': ('2', '9'), '10': ('2', '10'), '11': ('2', '11'), '12': ('2', '12'), '13': ('2', '13'), '14': ('2', '14'), '15': ('2', '15'), '16': ('2', '16'), '17': ('2', '17'), '18': ('2', '18'), '19': ('2', '19'), '20': ('3', '20'), 'max_season': '3', 'unknown_series_length': True}
TVDB4_dict: {}
Tvdb4 s02e13 (real s01e13) got data from real s02e13. Need to locate where the mistage is. Seem like it can only happen if first saga folder have less episodes than the real folder and absolutely numbered eps overlaps real episode in subsequent seasons

**Comment by AdamZane** [comment]
I ended up just using the anidb ordering, I realized I don't really care much for arcs in Naruto.
On another note, you said that 0.5 arcs wouldn't work, but I actually did some clever renaming and got it to work!
![image](https://github.com/ZeroQI/Hama.bundle/assets/119836760/56fce36e-2446-4fd1-9cff-dd509e202f3f)
![image](https://github.com/ZeroQI/Hama.bundle/assets/119836760/9b6510f8-51d8-4029-9647-19f0ccdf0f46)
