### ISSUE TITLE
ASS + Hama not correctly identifying Show

### ISSUE THREAD

**Issue by alejakun** [ZeroQI/Hama.bundle#563]
## Platform
Linux Docker

Operating system and version: Linux, Docker (lscr.io/linuxserver/plex)
Plex version: 4.125.1

## Current Behavior

First of all thanks for the great work, I have a rather big library and everything seems to work great most of the time, and when it doesn't most of the time an update solves the problem. However lately I've been facing problems with a particular show and while trying to fix those issues I updated ASS and HAMA (I think I broke something in the process), let me explain:

Now ASS + Hama are not automatically "Identifying" a new show, meaning it shows in the list of shows but with the Directory Name used to store ie. "Show Name [tvdb-XXXXXX]", so I try to manually Identify the show, however something curious is happening, ASS is not showing in the list of options to search the show:

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/72576153/58a50b51-32a3-422e-a77c-9c0340854927)

I'm sure the Scanner is correctly installed since it shows as an option in the library settings, it just is not showing in this other place (the logs also seem healthy):

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/72576153/02f62e32-5267-41c1-83cf-1f963880937c)

Another funny thing is that there are no logs created per Library/Show (I deleted all the logs to have a clean test):

[Logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14729561/Logs.zip)

Hope this helps.

Best Regards

**Comment by alejakun** [comment]
Sorry for the late reply, here you go!

[com.plexapp.system.log](https://github.com/ZeroQI/Hama.bundle/files/14733081/com.plexapp.system.log)

**Comment by ZeroQI** [comment]
two errors but not linked to Hama
ASS is listed so pure agent issue
Please show content folder and folde name for HAMA agent in plugins folder

**Comment by alejakun** [comment]
Hope this helps

<img width="375" alt="image" src="https://github.com/ZeroQI/Hama.bundle/assets/72576153/91013f6d-ebbf-4a00-be20-b9ee6a7437ac">

(I changed the folder name to show the contents, but it's usually set to Hama.bundle

<img width="380" alt="image" src="https://github.com/ZeroQI/Hama.bundle/assets/72576153/8215022b-9066-4d0c-a784-f60d20c73601">

**Comment by ZeroQI** [comment]
Looks good to me.
Must be a local rights issue

**Comment by alejakun** [comment]
Hi,

Thanks for the input, do you think most likely of ASS+Hama files permissions or the media files? Should I move this to Hama github?

Best Regards

**Comment by alejakun** [comment]
After a series of tests I discovered that yesterday while trying to solve another issue the library configuration reset the Agent, just had to update and try again, now I know it's a different issue but would like your help here, the behavior is as follows:

- If I have files from season 1 it correctly identifies the files as season 1
- If I have files from season 2 it correctly identifies the files as season 2
- If I have files from season 1 and 2 it just recognizes the files from season 2 (shows season 2 but not season 1)

Is this a ASS or HAMA issue?

Best Regards!

**Comment by ZeroQI** [comment]
Hama file permissions

Answer is in the first lines of ASS readme.
Wrong season or ep number are scanner issues

**Comment by alejakun** [comment]
Thanks for the support, I'll create a new issue to follow up the new symptoms.
