### ISSUE TITLE
Hama Parsing Errors degrading server performance

### ISSUE THREAD

**Issue by AbstractUmbra** [ZeroQI/Hama.bundle#565]
Apologies for the vague title, allow me to try and explain the issue!

I use both Hama and ASS to resolve anime shows.

Recently I had to remove my anime library and optimize the plex database and prune bundles as some cleanup. When I attempted to re-add the anime library with both ASS and Hama, I noticed that matching and then metadata resolution was much slower, if it worked at all.

Currently only around 70% of my library has matched and updated metadata. I use the ASS method of adding a `anidb.id` file in the roots of the respective directories so I know the matching should be O(1) rather than O(n).

The issue now is that Plex/Hama is constantly trying to gather metadata and failing (see below image)
![image](https://github.com/ZeroQI/Hama.bundle/assets/16031716/83300142-5529-4366-8eb8-7dbfd0b37fbb)
The errors in red and the warnings in yellow only appear when the anime library is present, I have tested by removing it several times.

This is actively killing my Plex server performance and having an effect on the host OS' performance too, which strangely enough cannot be reflected within `htop`.

I can provide whatever logs are needed to help diagnose the issue, if you could please let me know which are necessary, thanks!

### Additional context:

I run Plex in a docker container using the [linuxserver.io image](https://docs.linuxserver.io/images/docker-plex/), I use their [mod](https://github.com/linuxserver/docker-mods/tree/plex-absolute-hama) to add Hama and ASS to the container.

I have an example show here, whose name correctly updated to the anidb entry but will not match/pull metadata
![image](https://github.com/ZeroQI/Hama.bundle/assets/16031716/1e863aa4-f426-44ad-a812-c79665acf550)
I have several more if needed.

**Comment by ZeroQI** [comment]
You are proving plex have an issue, but seeminly neither search nor update fonctions of the agent  completed

You need to provide ASS custom scanner logs and hama per series logs for one series to focalise on

You may have created grouping folders by setting the root folder wrong, you could have created new type libraries not supporting legacy agents like hama, you haven't shown other agent works and could be a corrupted plex database, etc...

**Comment by AbstractUmbra** [comment]
Apologies for the delay in responding - I am currently trying to access the host whilst the app is running to gather the most up to date logs to post. I will update within a few hours!

**Comment by AbstractUmbra** [comment]
[logs.tar.gz](https://github.com/ZeroQI/Hama.bundle/files/15215524/logs.tar.gz)

Relevant [VirusTotal](https://www.virustotal.com/gui/file/ad79966af64c39f428deefcbc26b9aa404eeced39facacee7f6b74fdb40a6f52?nocache=1) link for the above attachment.

I've uploaded the relevant log files from the [Troubleshooting]() section of Hama's readme. I removed all of the anime entries aside from Mushoku Tensei as I used this in the earlier comment to showcase my issue, and that GitHub would not allow 50mb of log files.
If more logs are needed please let me know and I will provide them.

```sh
- _Logs/ # this is "[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/"

- com.plexapp.* # these are from "[...]/Plex Media Server/Logs/PMS Plugin Logs/"

- mushoku_tensei.*.log # these are from ASS logs
```

**Comment by ZeroQI** [comment]
ASS filelist is empty when i decompress it...

You don't have the rights to create the folder, so likely a file or folder right issue in agent data folder, location exemple below:
\\nas\PlexMediaServer\AppData\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems

```
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c67dce28e/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/storage.py", line 128, in make_dirs
    os.makedirs(path)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 5] I/O error: '/config/Library/Application Support/Plex Media Server/Media/localhost/4/bc1645605e430ca62f1b9a6db0611f6d861d515.bundle'
```

**Comment by AbstractUmbra** [comment]
Hey, thanks for highlighting that error - it allowed me to figure out there was a corruption of some kind in my file system which I have now mitigated, sorry for the trouble and thank you again!
