### ISSUE TITLE
Multiple threads optimization

### ISSUE THREAD

**Issue by ZeroQI** [ZeroQI/Hama.bundle#57]
We should optimise to make the agent faster and key functions separate in logging if possible by using the following two directives
@parallelize
@task

From the framework.bundle:

The @parallelize and @task decorators are designed to be used in conjunction with each other -
@parallelize decorates a function that defines one or more @task functions. A ThreadKit-specific
lock is maintained so only one parallelizer can be created at any time. When the parallelizer
has run, the tasks are queued for dispatch to the runtime's task pool, and the calling thread is
blocked until all tasks have completed.

TVB Source: https://github.com/plexinc-agents/TheTVDB.bundle/blob/master/Contents/Code/__init__.py

However it look like the @task precede a "def function (var)" type of declaration so we might have to create "def UpdateEpisodes()" or similar to manage the multi threaded task and another definition inside the loop for the task part... will need beginning and end logged line for parallelize and single line for tasks to keep logging accurate

**Comment by ZeroQI** [comment]
From the framework.bundle:

The @parallelize and @task decorators are designed to be used in conjunction with each other -
@parallelize decorates a function that defines one or more @task functions. A ThreadKit-specific
lock is maintained so only one parallelizer can be created at any time. When the parallelizer
has run, the tasks are queued for dispatch to the runtime's task pool, and the calling thread is
blocked until all tasks have completed.

**Comment by EndOfLine369** [comment]
I'm seeing points to Not do thid.
This could possibly cause sources to see things as a dos attack or ban (AniDB) through multiple requests all at the same time. Or even cause as user's network to be slammed at throughput max causing issues in their home network. 
There are only two scenarios I see this being beneficial of a (1) "Refresh All" or (2) the creation of new Library. 
Plex also already does two parallel loads of series' metadata in both of those scenarios which helps if one leg is delayed due to series size (One Piece) or a delay in a url pull.

**Comment by ZeroQI** [comment]
I have seen 2 concurrently and this made things weird for logging at times, i wanted a lock to allow 1 only, but the way it is now is fine i guess.
Thanks for another meaningful discussion

**Comment by EndOfLine369** [comment]
Btw, i'm not saying we shouldn't do this. I just usually point out the bad possibilities as better to think about them now instead of later. And we start causing issues and/or end up throwing away our time spent on trying to do it when we only think about the bad possibilities after the fact.

**Comment by ZeroQI** [comment]
I take pride in what i coded so far but your argument was compelling. I cannot locate a function to loop and it is stable..

**Comment by EndOfLine369** [comment]
I think in the search section this might actually be fine if we enable the other sources. Thus we could enable a parallel search of all 4 tasks AniDB/TVDB/TMDB/TSDB then analyize all 4 output when they are done.

**Comment by EndOfLine369** [comment]
Trying to think of how we could potentially minimize any impact in the update section, we might be able to  parallel it out by seasons? That could potentially limit the impact of doing too many things at once...

**Comment by ZeroQI** [comment]
Updated https://github.com/ZeroQI/Hama.bundle/blob/master/Metadata.md to show all metadata fields per data type and info provided by all metadata sourced used

Humm if working that could be cool. was thinking searching all if anidb failed since anidb is local...

**Comment by ZeroQI** [comment]
Good for file download, not sure about search thread. retiring for now
