### ISSUE TITLE
Anime named with year (Trash Guide) causing metadata to not be found

### ISSUE THREAD

**Issue by Renatochaz** [ZeroQI/Hama.bundle#570]
## Summary
Metadata search for "Jujutsu Kaisen" Season 2 fails when using year in the search query with Hama bundle and ASS scanner in Plex.

## Platform

Operating system and version: Windows 11
Plex version: 1.40

## Expected Behavior
The search should return the correct metadata for "Jujutsu Kaisen" Season 2 regardless of whether the year is included in the search query.

## Current Behavior
When episodes are renamed following the TRASH guides naming recommendation and include the year in the anime title, the metadata search for "Jujutsu Kaisen" fails. This is due to the search function in [`TheTVDBv2.py`] appending the year to the search query, which results in an empty response from TheTVDB.

## Steps to Reproduce
1. Rename episodes of "Jujutsu Kaisen" season 2 (to replicate exactly) to include the year in the title following the TRASH guides naming recommendation.
2. Use Hama bundle with ASS scanner in Plex to fetch metadata.
3. Observe that the metadata for "Jujutsu Kaisen" Season  is not found.

## Additional information
This issue seems to be related to how the search query is constructed in [`TheTVDBv2.py`].
Specifically, appending the year to the anime title when performing the search causes the query to fail. A successful search can be performed without including the year in the title, as demonstrated by the provided URLs:
- Failing search: https://thetvdb.com/api/GetSeries.php?seriesname=Jujutsu%20Kaisen%20%282020%29
- Successful search: https://thetvdb.com/api/GetSeries.php?seriesname=Jujutsu%20Kaisen

It may be beneficial to modify the search function to handle cases where including the year in the search query results in a failed search, or put that as a restriction/best practice

**Comment by ZeroQI** [comment]
Thetvdb search is only used if a season number bigger than 1 is found, otherwise it uses anidb for the unique id and search, unless a forced id is used... 

I need the *.search.log to know why search failed

**Comment by Renatochaz** [comment]
I thought that would be the case, which is way it seems to be a niche interaction (I started downloading Season 2, because I already watched S1 =).)

The logs don't show much, because the XML returned is empty, but here it is:

```
=============================================================================================================================================================
common.PlexLog(file="C:\Users\Dell\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\TV - Animes\Jujutsu Kaisen (2020).agent-search.log", movie=False)
[!] file:       "C:\Users\Dell\Documents\Media\Animes\Jujutsu Kaisen (2020)\Season 02\Jujutsu Kaisen - S02E05 - Premature Death WEBDL-1080p.mkv"
[ ] library:    "TV - Animes"
[ ] root:       "C:\Users\Dell\Documents\Media\Animes"
[ ] path:       "Jujutsu Kaisen (2020)\Season 02"
[ ] Plex root:  "C:\Users\Dell\AppData\Local\Plex Media Server"
[ ] Log folder: "Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\TV - Animes"
[ ] Log file:   "Jujutsu Kaisen (2020).agent-search.log"
[ ] Logger:     "0x1a44"
[ ] mode:       "w"
=== Search() ================================================================================================================================================
title: 'Jujutsu Kaisen (2020)', name: 'Premature Death', filename: 'C%3A%5CUsers%5CDell%5CDocuments%5CMedia%5CAnimes%5CJujutsu%20Kaisen%20%282020%29%5CSeason%2002%5CJujutsu%20Kaisen%20-%20S02E05%20-%20Premature%20Death%20WEBDL-1080p%2Emkv', manual: 'False', year: 'None'
start: 2024-06-26 13:19:39,498000
=============================================================================================================================================================
--- force id ------------------------------------------------------------------------------------------------------------------------------------------------
--- source searches -----------------------------------------------------------------------------------------------------------------------------------------
=== TheTVDB.Search() ==========================================================================================================================================
=============================================================================================================================================================
end: 2024-06-26 13:19:39,534000, False

```

**Comment by ZeroQI** [comment]
https://thetvdb.com/series/jujutsu-kaisen#seasons

**Comment by Renatochaz** [comment]
Yeah it does get the series even in thetvdb, but the function in the code did not work because the series is named following that convention which is: {Series TitleYear}. (https://trash-guides.info/Sonarr/Sonarr-recommended-naming-scheme/)

This results in the following query from the function: https://thetvdb.com/api/GetSeries.php?seriesname=Jujutsu%20Kaisen%20%282020%29

After changing the namming schema to {Series Title}, it correctly found the metadata using: https://thetvdb.com/api/GetSeries.php?seriesname=Jujutsu%20Kaisen

Not sure what would be the best way to deal with this from the bundle perspective (changing the namming convention solved my issue and I will keep it this way (: )

**Comment by ZeroQI** [comment]
The year is very useful for Movies, wouldn't use it for series.. You can force the id with a file to avoid renaming the folder or simply change the convention

Any metadata agent expect the exact title used in the database. I gave a lot of freedom, but this is hardly actionable due to the potential of breaking something else for a title at the end of the day that is incorrect.

One can custom match the title by hand without renaming the folder too...

**Comment by Renatochaz** [comment]
@ZeroQI At [Loc366](https://github.com/ZeroQI/Hama.bundle/blob/bb684a2299d06b1377b4d3e1c81dff417ce4e9de/Contents/Code/TheTVDBv2.py#L366) would a if statement for checking if `TVDBsearchXml.xpath('Series')` returned empty and logging that the search (url) didn't find anything be acceptable to help debugging? I could open a simple PR if you think that could prove useful.

Anyway, thanks for the help and for maintaining the project.

**Comment by ZeroQI** [comment]
If return empty only, doing another request with the year would prove safe and i would import such PR

**Comment by Renatochaz** [comment]
Do you mean without the year? Stripping it with a regex match?

**Comment by ZeroQI** [comment]
Tired, yes without the year, retry if no results with the year stripped with regex,

**Comment by Renatochaz** [comment]
It's fine. =)
Just tried the second failover request with the title cleansed, and it found the match in TVDB, but it didnt get the 80% match, even though the titles match perfectly. Maybe I'm missing something?

Change
```
...
  try:
    TVDBsearchXml = XML.ElementFromURL( TVDB_SERIE_SEARCH + quote(orig_title), headers=common.COMMON_HEADERS, cacheTime=CACHE_1HOUR * 24)
    if not TVDBsearchXml.xpath('Series'):
      # Do a second try with the year removed from the title, if any
      title_cleansed = re.sub(r'\s*\(\d{4}\)$', '', orig_title)
      Log.Info("===== Temporary DEBUG ===== title_cleansed: {}".format(title_cleansed))
      TVDBsearchXml = XML.ElementFromURL( TVDB_SERIE_SEARCH + quote(title_cleansed), headers=common.COMMON_HEADERS, cacheTime=CACHE_1HOUR * 24)
  except Exception as e:
...
```

*search.log
```
=============================================================================================================================================================
common.PlexLog(file="C:\Users\Dell\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Animes\Jujutsu Kaisen (2020).agent-search.log", movie=False)
[!] file:       "C:\Users\Dell\Documents\Media\Animes\Jujutsu Kaisen (2020)\Season 02\Jujutsu Kaisen - S02E05 - Premature Death WEBDL-1080p.mkv"
[ ] library:    "Animes"
[ ] root:       "C:\Users\Dell\Documents\Media\Animes"
[ ] path:       "Jujutsu Kaisen (2020)\Season 02"
[ ] Plex root:  "C:\Users\Dell\AppData\Local\Plex Media Server"
[ ] Log folder: "Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Animes"
[ ] Log file:   "Jujutsu Kaisen (2020).agent-search.log"
[ ] Logger:     "0x3b98"
[ ] mode:       "w"
=== Search() ================================================================================================================================================
title: 'Jujutsu Kaisen (2020)', name: 'Premature Death', filename: 'C%3A%5CUsers%5CDell%5CDocuments%5CMedia%5CAnimes%5CJujutsu%20Kaisen%20%282020%29%5CSeason%2002%5CJujutsu%20Kaisen%20-%20S02E05%20-%20Premature%20Death%20WEBDL-1080p%2Emkv', manual: 'False', year: 'None'
start: 2024-06-26 16:06:21,584000
=============================================================================================================================================================
=== TheTVDB.Search() ========================================================================================================================================
===== Temporary DEBUG ===== title_cleansed: Jujutsu Kaisen
TVDB  - score: ' 77', id: '377543', title: 'Jujutsu Kaisen'
=============================================================================================================================================================
end: 2024-06-26 16:06:21,688000, False

```

**Comment by ZeroQI** [comment]
My advice is to put quotes, pretty sure a space is remaining, but could be wrong

**Comment by Renatochaz** [comment]
Just found the issue: It uses the orig_title at https://github.com/ZeroQI/Hama.bundle/blob/bb684a2299d06b1377b4d3e1c81dff417ce4e9de/Contents/Code/TheTVDBv2.py#L367 and the calculates the score based on it. (the orig title now deviates from the cleansed title).

If I change the code to rename the orig_title, it matches with 100% and correctly populates the metadata:
```
    if not TVDBsearchXml.xpath('Series'):
      # Do a second try with the year removed from the title, if any
      orig_title = re.sub(r'\s*\(\d{4}\)$', '', orig_title)
      Log.Info("===== Temporary DEBUG ===== title: {}".format(orig_title))
      TVDBsearchXml = XML.ElementFromURL( TVDB_SERIE_SEARCH + quote(orig_title), headers=common.COMMON_HEADERS, cacheTime=CACHE_1HOUR * 24)
```

I can raise a PR if its OK to change the orig_title in this case (no idea if this can break something).

**Comment by ZeroQI** [comment]
Call it orig_title_cleansed maybe to avoid confusion but no issue in any case since it doesn't modify the metadata itself.
Please do the PR
