### ISSUE TITLE
Support new style of subtitle metadata hi, sdh, cc

### ISSUE THREAD

**Issue by kanjieater** [ZeroQI/Hama.bundle#572]
I've been using bazarr to automatically fetch subtitles. Bazarr forces all subtitles to use the new formats documented here.
https://support.plex.tv/articles/200471133-adding-local-subtitles-to-your-media/
![image](https://github.com/ZeroQI/Hama.bundle/assets/32607317/6bae9739-89ad-4e77-a82c-1576381be045)

Unfortunately that breaks the language code detection
![image](https://github.com/ZeroQI/Hama.bundle/assets/32607317/9ae04e4a-0662-4d10-a65e-61a8e3b61f11)

My request would be to support the naming convention to read the sub language in properly

**Comment by ZeroQI** [comment]
Plex support subtitles...
The HAMA agent doesn't support any subtitles...
Please create feature request to Plex
