### ISSUE TITLE
Dr. Stone: Ryuusui keeps getting a high score with other Dr. Stone Titles

### ISSUE THREAD

**Issue by Hidara1904** [ZeroQI/Hama.bundle#574]
### LOGS
Here are the logs:
**Dr. Stone:**
[Dr.Stone.agent-search.log](https://github.com/user-attachments/files/16487134/Dr.Stone.agent-search.log)
[Dr.Stone.agent-update.log](https://github.com/user-attachments/files/16487135/Dr.Stone.agent-update.log)
[Dr.Stone.filelist.log](https://github.com/user-attachments/files/16487137/Dr.Stone.filelist.log)
[Dr.Stone.scanner.log](https://github.com/user-attachments/files/16487138/Dr.Stone.scanner.log)
**Dr. Stone: Stone Wars:**
[Dr.Stone.agent-search.log](https://github.com/user-attachments/files/16487117/Dr.Stone.agent-search.log)
[Dr.Stone.agent-update.log](https://github.com/user-attachments/files/16487118/Dr.Stone.agent-update.log)
[Dr.Stone.filelist.log](https://github.com/user-attachments/files/16487146/Dr.Stone.filelist.log)
[Dr.Stone.scanner.log](https://github.com/user-attachments/files/16487147/Dr.Stone.scanner.log)

### Summary:
Dr. Stone: Ryuusui has conflicts with other Dr.Stone Titles. It manages to get a high score despite having Kanji with it. This does not happen with the main Ryuusui title but with the official Japanese title "Dr.STONE 龍水".

### Reason:
As much as I can tell, it is happening because of the String.stripDiacritics function used in cleanse_title function in common.py
the original title gets cleansed to "Dr Stone " and obviously that is going to give a high match.

Also, I have no idea why Dr. Stone: Stone Wars isn't getting a 90+ score with my naming scheme. My folder name is "Dr.Stone - Stone Wars". This gets cleansed to "dr stone stone wars". This should get a really high score with the cleansed main title on AniDB database.

**Comment by ZeroQI** [comment]
orig_title: 'Dr Stone - Stone Wars', orig_title_cleansed: 'dr stone stone wars'
[-] score:  80, aid:   660, title: "Charmstone"
[-] score:  80, aid:  1661, title: "Powerstone"
[-] score:  83, aid: 15305, title: "Dr.STONE STONE WARS"
[-] score:  86, aid: 16164, title: "Dr.STONE 龍水"
[-] score:  86, aid: 14491, title: "Dr.STONE"

You are missing the dot with no space that makes Dr.STONE one word and change the behaviour and the length based calculations, also no hyphen, you should have named it "Dr. Stone Stone Wars" like in `<title xml:lang="en" type="official">Dr. Stone: Stone Wars</title>`
http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=15305
