### ISSUE TITLE
HamaTV Settings Are Tied Together Not Independent.

### ISSUE THREAD

**Issue by randomdice101** [ZeroQI/Hama.bundle#579]
Hello, I have another odd issue, I made a second library to have english title due to "popular" request from my friends. Unfortunately the HamaTV settings seem to be global and as such all new shows (or any metadata refresh) will switch my original library's data to english or my friend's library to japanese depending on what I have my series language set to. Is it not possible to have independent hamTV agent settings?

![image](https://github.com/user-attachments/assets/c9903ca5-4737-4096-bdf7-240dfaea5f1b)

Or if there was a way to force a library to use a certain language... it would help a lot with friends who can't read Japanese but I don't want to deal with English titles myself...

**Comment by ZeroQI** [comment]
Correct, Hama settings are global
One could Edit in Info.plist the identifying strings to create a different copy: <string>com.plexapp.agents.hama2</string> and use Hama2.bundle folder to create a valid hama duplicate with its own settings
