### ISSUE TITLE
Check for best episode name

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#60]
Not sure what exactly to title or call this.

Due to a difference in how AniDB and TVDB operate, AniDB will often go days without the real episode title populating.  This is due to AniDB's admin/mod approval system.  TVDB, on the other-hand, can be updated instantly by it's community.  

Not sure if it's necessary, but could be neat.  There could be a check for "If AniDB's title = 'Episode #' then use TVDB Episode #" until the next metadata pull.  That way, people using AniDB for their mappings will still get an updated title as soon as possible.  It's definitely possible that both aren't updated, but here is an example for the show 91 Days:

AniDB:
<img width="859" alt="screen shot 2016-07-08 at 10 55 17 pm" src="https://cloud.githubusercontent.com/assets/18091557/16705682/1d2171dc-455f-11e6-8d8b-60ac6f38bc66.png">

TVDB: 
<img width="832" alt="screen shot 2016-07-08 at 10 55 29 pm" src="https://cloud.githubusercontent.com/assets/18091557/16705684/2960adf0-455f-11e6-8324-e07cafe031e2.png">

Just a thought I had as I've been adding some things today.

**Comment by sven-7** [comment]
Please label this as en Enhancement when someone gets the chance.  I can't for the HAMA issues.  Thanks.

**Comment by EndOfLine369** [comment]
@sven-7 This is already exiting in the code (I added a while back) for when AniDB does not have a title yet but TVDB does. https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/__init__.py#L569

**Comment by EndOfLine369** [comment]
EX:
![image](https://cloud.githubusercontent.com/assets/16750699/16705843/8b784a8c-455c-11e6-8f4e-f4fa3a652c8e.png)

![image](https://cloud.githubusercontent.com/assets/16750699/16705845/981ebff0-455c-11e6-9193-bf866ac1c848.png)

![image](https://cloud.githubusercontent.com/assets/16750699/16705849/a537c286-455c-11e6-9e40-19337e38918e.png)

**Comment by sven-7** [comment]
Ah, perfect.  It didn't seem like it was working earlier, but when I look at the TVDB metadata, it wasn't picked up on the download, so it must have been changed relatively recently from when I put it into Plex.  Didn't catch this enhancement earlier -- good work!!
