### ISSUE TITLE
No matches found for any series on the latest commit

### ISSUE THREAD

**Issue by localh0st-** [ZeroQI/Hama.bundle#64]
the logs simply say that no match was found, despite finding a match using the older code

**Comment by localh0st-** [comment]
in the plex system log, I found the following entry pertaining to the attempted match:

> ERROR` (networking:217) - Error opening URL http://127.0.0.1:32400/:/plugins/com.plexapp.agents.hama/messaging/function/[a bunch of random characters, i'll spare you the full URL]

**Comment by localh0st-** [comment]
Another update: ValidatePrefs() is throwing an error on line 49, triggered by the if[] block on line 48. I believe the problem is with the `.count[True] > 0` component

**Comment by EndOfLine369** [comment]
Already being dealt with in https://github.com/ZeroQI/Hama.bundle/issues/62
