### ISSUE TITLE
AniDB links showing in summaries

### ISSUE THREAD

**Issue by EndOfLine369** [ZeroQI/Hama.bundle#66]
Looks like we are only filtering out character links. We need to just get rid of all seen links in the expected API format.
![image](https://cloud.githubusercontent.com/assets/16750699/17169891/4b5ba2f8-53af-11e6-8dcd-ad11c45f70f2.png)

**Comment by ZeroQI** [comment]
```
### AniDB Serie/Movie description ###
        try:                    description = re.sub(r'http://anidb\.net/[a-z]{2}[0-9]+ \[(.+?)\]', r'\1', getElementText(anime, 'description')).replace("`", "'") # Remove wiki-style links to staff, characters etc
        except Exception as e:  description = ""; Log.Error("Exception: %s" % e)
        if description == "":
          error_log['AniDB summaries missing'].append("anidbid: %s" % (WEB_LINK % (ANIDB_SERIE_URL % metadata_id_number, metadata_id_number) + " | Title: '%s'" % metadata.title))
          if tvdbOverview:  description = tvdbOverview;  Log.Warn("AniDB series summary is missing but TVDB has one availabe so using it.")
        if metadata.summary != description and description:  metadata.summary = description.replace("`", "'")
```
URL not removed: http://anidb.net/a715[Gundam], regex expect two letters, changed range from 1 to 2

 try:                    description = re.sub(r'http://anidb\.net/[a-z]{1,2}[0-9]+ \[(.+?)\]', r'\1', getElementText(anime, 'description')).replace("`", "'") # Remove wiki-style links to staff, characters etc

**Comment by EndOfLine369** [comment]
Awwww, put it in as a placeholder for me to fix. :cry:
You broke the indent though btw.

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Hama.bundle/issues/66
thanks for spotting.
