### ISSUE TITLE
[Enhancement] "Load Local Metadata" Option

### ISSUE THREAD

**Issue by EndOfLine369** [ZeroQI/Hama.bundle#67]
Lets see if we want to do this.

Could include loading of locally seen jpg files in the parent series folder.
EX from JMM:
```
2016-07-25 00:18:51 file: 'D:\Videos\Animehama\Gekijouban Bleach Fade to Black Kimi no Na o Yobu [tvdb3-74796-s0e5]\fanart.jpg', ext: 'jpg' not in video_ext
2016-07-25 00:18:51 file: 'D:\Videos\Animehama\Gekijouban Bleach Fade to Black Kimi no Na o Yobu [tvdb3-74796-s0e5]\poster.jpg', ext: 'jpg' not in video_ext
2016-07-25 00:18:51 file: 'D:\Videos\Animehama\Gekijouban Bleach Fade to Black Kimi no Na o Yobu [tvdb3-74796-s0e5]\season01-poster.jpg', ext: 'jpg' not in video_ext
```

~~And even see about loading support [media stubs](http://kodi.wiki/view/Media_stubs) with this option as well.~~

Local images would also be loaded at top priority even if tvdb/tmdb/anidb images are loaded.

**Comment by ZeroQI** [comment]
https://support.plex.tv/hc/en-us/articles/200220717-Local-Media-Assets-TV-Shows
If we use local media assets and put it before HAMA, it should load local meta first.
We can test, and if works , then using that would make more sense i believe

Media stubs are loaded in scanner and generate dummy entries, like multi episode files

**Comment by EndOfLine369** [comment]
Ok, misunderstood media stubs so ignore that.

It already has that agent as second in the agent listing.

![image](https://cloud.githubusercontent.com/assets/16750699/17170696/ef299a9a-53b2-11e6-8b57-12f2debd65b6.png)

So your saying move it to be first?

**Comment by ZeroQI** [comment]
yes. that will load meta locally if it works as it should, which it should

**Comment by EndOfLine369** [comment]
Is there any way or do we want to have it automatically put the LMA agent above HAMA? I would think there should be some way as TMDB/TVDB in Plex have multiple agents in their listings.

![image](https://cloud.githubusercontent.com/assets/16750699/17198947/e3fc4078-543e-11e6-802c-b89f2e1c9e78.png)

**Comment by ZeroQI** [comment]
maybe we can put local media agent first in the code below.
The agents need to share the guid in mentionned secondary agents but in that case it's irrelevant. users can disable and change priority on that very window.
```
class HamaTVAgent(Agent.TV_Shows, HamaCommonAgent):
  name, primary_provider, fallback_agent, contributes_to, languages, accepts_from = ('HamaTV', True, False, None, [Locale.Language.English,], ['com.plexapp.agents.localmedia'] ) #, 'com.plexapp.agents.opensubtitles'
```
I believe you are right in implying local media take precedence. if they don't want a poster in hte folder as main poster, they should delete/move it to Extras

On a separate note, theme songs, I believe the metadata id changes need small change (tvdbid for metadata.id):
self.metadata_download (metadata.themes, THEME_URL % tvdbid, 1, "Plex/"+metadata.id+".mp3")
```
### Plex - Plex Theme song - https://plexapp.zendesk.com/hc/en-us/articles/201178657-Current-TV-Themes ###
      if THEME_URL % tvdbid in metadata.themes:  Log.Info("Theme song - already added")
      elif Prefs['GetPlexThemes']:
        self.metadata_download (metadata.themes, THEME_URL % tvdbid, 1, "Plex/%s.mp3" % tvdbid)
        if not THEME_URL % tvdbid in metadata.themes:  error_log['Plex themes missing'].append("tvdbid: %s | Title: '%s' | %s" % (WEB_LINK % (TVDB_SERIE_URL % tvdbid, tvdbid), tvdbtitle, WEB_LINK % ("mailto:themes@plexapp.com?cc=&subject=Missing%%20theme%%20song%%20-%%20&#39;%s%%20-%%20%s.mp3&#39;" % (tvdbtitle, tvdbid), 'Upload')))
```

**Comment by EndOfLine369** [comment]
Just a random thought that came to mind as I don't know how multiple agents work with each other. Would putting the 'localmedia' agent first cause issues in meatdata id assignment? as 'localmedia' would put an id and skip HAMA search for id assignment? 

Re theme songs, makes sense. As Plex has for tvdbid which means we actually have duplicate mp3 files based on the 'metadata.id' named files for Anidb series under the same tvdb id. So good call on the change.

**Comment by ZeroQI** [comment]
We need a mechanism for anidb as there is a song per season. Wanted a 30s
theme song archive...

The primary agent give the id
The secondary agent other stuff. Putting it first in the list should make
it favor local files as metadata

Sorry fir the many errors. Am surprised at times i managed to do the
scanner for so long alone... i learnt few things so thanks.

I saw you forked the rom browser...
Did some coding but nothing actionable with mane offline flat files...

**Comment by EndOfLine369** [comment]
ok, so no matter what the order, as HAMA is the primary (even if 20th in order) it still assigns the id (meaning is the search source). good to know.

forked it to mainly to bring it into view to remind myself to take a look

**Comment by ZeroQI** [comment]
I think since this exists, no need to implement ourselves...
Is it working as expected ? If so, shall we close ?

**Comment by ZeroQI** [comment]
@EndOfLine369 Is it working as expected ? If so, shall we close this issue ticket ?
