### ISSUE TITLE
Should Season summary metadata be populated?

### ISSUE THREAD

**Issue by ZeroQI** [ZeroQI/Hama.bundle#68]
Since the "media.seasons[season].summary" exist, we should use the anidb summary as season summary if there is multiple seasons, but it means multiple anidb xml pull. maybe use an option in DefaultPrefs.json and disable by default
```
{
    "id"      : "GetAnidbSeasonSummary",
    "label"   : "Fetch AniDB serie summary to use as season summary",
    "type"    : "bool",
    "default" : "false"
  },
```

**Comment by EndOfLine369** [comment]
Hmmmm.....
So your saying for example "Bakuman" (only multi season/series fresh in my mind) that if it is added into Plex with a 'tvdb*' mode id, we would work backwords using scudlee's file to find the associated anidb id to season. And then pull each of those season's summary and add it in as the season summary (leaving the series summary to be from TheTVDB)?

Do note that these season summaries are not seen in either the Roku or iPhone apps it seems.

![image](https://cloud.githubusercontent.com/assets/16750699/17171284/99f9ef86-53b5-11e6-80ee-e2e75e58ce39.png)
![image](https://cloud.githubusercontent.com/assets/16750699/17171301/b6baec1a-53b5-11e6-9e79-47aac2ec0f58.png)
![image](https://cloud.githubusercontent.com/assets/16750699/17171316/c799fac6-53b5-11e6-86e3-3f7f66cdd6c1.png)
![image](https://cloud.githubusercontent.com/assets/16750699/17171333/d85ec080-53b5-11e6-8211-edf2dff1002e.png)

**Comment by ZeroQI** [comment]
The field is in the meta declaration exist but some devices will not show the field indeed and the agent can't test which client connects...
It will generate more calls to anidb which i don't like but the functionality would be nice...

That is what i meant but i am split over whether to implement or not.
Banning from anidb seem a thing of the past, would hate for it to come back...

**Comment by EndOfLine369** [comment]
I personally would not want this info loaded.

**Comment by sven-7** [comment]
I'd like this, if possible. TVDB should be adding the capability to their site in the future.

**Comment by EndOfLine369** [comment]
Then i'd rather wait for TVDB to have that data as should automatically be included in the already pulled TVDB API info.

**Comment by ZeroQI** [comment]
After chatting with Endofline369 the cost of loading multiple anidb series
xml is not worth it but shall tvdb offer the field we would use it

**Comment by EndOfLine369** [comment]
@sven-7, can you please post a link to the statement of this TheTVDB enhancement for us to check the status.

**Comment by sven-7** [comment]
Yeah - no prob.  Let me chase that down tomorrow.

**Comment by sven-7** [comment]
Nevermind...I was the one who made the request and someone just revived my thread 😝

https://forums.thetvdb.com/viewtopic.php?f=5&t=29932

**Comment by EndOfLine369** [comment]
Hmmm......with the speed of them getting around to responding to those requests that I saw, seems like this could take months if if even ever gets their ok/response. Instead of labeling this on hold, i'm closing it. Please open up a ticket for the enhancement if they ever get around to getting it implemented.

**Comment by sven-7** [comment]
Yeah. Totally cool with that. Think this is a good option, but no sense in doing it until it's a reality.
