### ISSUE TITLE
"Download Themes from PLEX" option not being used

### ISSUE THREAD

**Issue by EndOfLine369** [ZeroQI/Hama.bundle#69]
Looks like the "Download Themes from PLEX" option is not being used in the code. It will always try to pull themes.
@ZeroQI, are you aware of why this is?

![image](https://cloud.githubusercontent.com/assets/16750699/17170384/588eef82-53b1-11e6-8a34-99f89e2a397f.png)

![image](https://cloud.githubusercontent.com/assets/16750699/17170262/dd7156e6-53b0-11e6-98b8-4e543609be81.png)

![image](https://cloud.githubusercontent.com/assets/16750699/17170308/15885ec6-53b1-11e6-96b9-3eb4d4e11d50.png)

**Comment by ZeroQI** [comment]
No i don't

**Comment by EndOfLine369** [comment]
Perfect :smile:
