### ISSUE TITLE
"GetTmdbFanart" & "GetTmdbPoster" options not being used in the code

### ISSUE THREAD

**Issue by EndOfLine369** [ZeroQI/Hama.bundle#70]
@ZeroQI, looks like another possible accidential option removal here as well?

![image](https://cloud.githubusercontent.com/assets/16750699/17171717/8b5e1ed2-53b7-11e6-9b0e-e1c6dc587484.png)

![image](https://cloud.githubusercontent.com/assets/16750699/17171804/dd856418-53b7-11e6-995d-568fbbc75613.png)

![image](https://cloud.githubusercontent.com/assets/16750699/17171855/11ef863e-53b8-11e6-9f70-9355c421517c.png)

**Comment by ZeroQI** [comment]
Yeah never noticed... OMDB should be added though
