### ISSUE TITLE
Doesn't pull down Japanese titles even if  first-choice language is Japanese

### ISSUE THREAD

**Issue by kevingriffin** [ZeroQI/Hama.bundle#74]
It seems like anidb has Japanese titles, but ends up pulling in English (or romaji) instead. Is there a way to get the Japanese titles from anidb?

**Comment by ZeroQI** [comment]
Please include logs indicated in the readme troubleshooting section
I need the hama logs, which will give me the serie name, and will need to search the anidb title xml file for it...

**Comment by ZeroQI** [comment]
hello???

**Comment by ZeroQI** [comment]
Hello ???
