### ISSUE TITLE
Wrong Name for Special Episodes

### ISSUE THREAD

**Issue by StancuFlorin** [ZeroQI/Hama.bundle#78]
Hello,

I have this files added on "Special" folder:

$ ls -l
total 226176
-r--r--r-- 1 StancuFlorin 197609 40264194 Sep 5 09:50 [Shinobi] One Piece S07 - Teatrul Pălăriilor de Paie - Chopperman [SD] [C9DF6C56].avi
-r--r--r-- 1 StancuFlorin 197609 47276404 Sep 5 09:50 [Shinobi] One Piece S08 - Teatrul Pălăriilor de Paie - Timpul Reportajului [SD] [1BECC418].avi
-r--r--r-- 1 StancuFlorin 197609 49249960 Sep 5 09:50 [Shinobi] One Piece S09 - Teatrul Pălăriilor de Paie - Obahan Time [SD] [01CB2798].avi
-r--r--r-- 1 StancuFlorin 197609 52283705 Sep 5 09:50 [Shinobi] One Piece S10 - Teatrul Pălăriilor de Paie - Fara Respect [HD] [00718C41].mp4
-r--r--r-- 1 StancuFlorin 197609 42354720 Sep 5 09:50 [Shinobi] One Piece S11 - Teatrul Pălăriilor de Paie - Timpul Monstrilor [SD] [E47AC6D6].avi

But the name and the picture of the episode on Plex is taken from episodes 7-11, not from special episodes 7-11.

Here are the logs:

[Plex Media Scanner.txt](https://github.com/ZeroQI/Hama.bundle/files/455324/Plex.Media.Scanner.txt)
[com.plexapp.agents.txt](https://github.com/ZeroQI/Hama.bundle/files/455325/com.plexapp.agents.txt)

**Comment by ZeroQI** [comment]
i can see the same screenshot is assigned. if the same name is also assigned, it is badly coded somewhere. "Plex Media Scanner (custom ASS).log" would confirm correct mapping by the scanner, but not attached. Plex Media Scanner.txt confirm scanner didn't crash

Screenshot is managed there:
Line 583                if tvdb_ep in tvdb_table and 'filename' in tvdb_table[tvdb_ep] and tvdb_table[tvdb_ep]['filename']!="":  self.metadata_download (episodeObj.thumbs, TVDB_IMAGES_URL + tvdb_table[tvdb_ep]['filename'], 1, "TVDB/episodes/"+ os.path.basename(tvdb_table[tvdb_ep]['filename']))  

I recon tvdb_ep is the same value in both instances and needs correcting. Need to look deeper into it, but i don't have your library filelist to re-create your library with zero size files.

**Comment by ZeroQI** [comment]
try https://raw.githubusercontent.com/ZeroQI/Hama.bundle/25e78bde95ded9d2829d70296733118a4fde1903/Contents/Code/__init__.py
Please follow readme t/s section and include logs.

**Comment by StancuFlorin** [comment]
Now is taking the movies names, not the one for special episodes.

[Plex Media Scanner (custom ASS) - filelist Anime.txt](https://github.com/ZeroQI/Hama.bundle/files/473126/Plex.Media.Scanner.custom.ASS.-.filelist.Anime.txt)
[Plex Media Scanner (custom ASS).txt](https://github.com/ZeroQI/Hama.bundle/files/473128/Plex.Media.Scanner.custom.ASS.txt)
[Plex Media Scanner.txt](https://github.com/ZeroQI/Hama.bundle/files/473127/Plex.Media.Scanner.txt)

**Comment by ZeroQI** [comment]
Plex Media Scanner.txt is only usefull if the scanner crash, which is not the case now
I do not know the guid (anidb or tvdb) used for example
Since it is an agent issue, the agent logs are necessary

**Comment by ZeroQI** [comment]
Please try again with code on the pull request above, once confimed it works, will push it to the master code

**Comment by ZeroQI** [comment]
Please update me with the outcome on latest code

**Comment by ZeroQI** [comment]
No answer in 22 days
