### ISSUE TITLE
Showing only one episode

### ISSUE THREAD

**Issue by guicogo** [ZeroQI/Hama.bundle#82]
The anime 11 Eyes is only showing one episode, the episode 11. The info indicates that all 12 episodes is compressed in the same one.
The naming is like this [Fubuki] 11eyes - 01 [1280x720][384630F3]

**Comment by ZeroQI** [comment]
That's a scanner issue.
Readme troubleshooting steps not followed

**Comment by ZeroQI** [comment]
Please create a scanner issue attaching the logs specified in the readme troubleshooting issue
