### ISSUE TITLE
Add movie trailers

### ISSUE THREAD

**Issue by KingJ** [ZeroQI/Hama.bundle#97]
Plex supports displaying the trailer for a movie on the movie's information page. These trailers can either be from [local media assets](https://support.plex.tv/hc/en-us/articles/200220677-Local-Media-Assets-Movies) or via a metadata agent that populates the metadata object using the `metadata.extras.add` function.

Any trailers added via a metadata agent must supply a URL from which the trailer can be streamed as a raw video. There are two sources we can use for this;

1. The Plex Pass 'Plex Movie Extras' information, aka IVA metadata, which serves up trailers hosted by Plex. 
2. An alternative 3rd party site with an API that will serve up trailer videos.

Option 1 is somewhat limited in the trailers that are listed and users can't add their own should they wish to extend the metadata. The IVA metadata API is also completely undocumented so we'd need to reverse-engineer the existing [PlexMovie metadata agent](https://github.com/plexinc-agents/PlexMovie.bundle/blob/master/Contents/Code/__init__.py). I have a feeling that queries to this metadata source would _require_ a PlexPass and Plex would also probably disapprove of us reverse engineering it and using it in Hama.

Option 2 is slightly problematic in that serving up raw trailer videos is bandwidth hungry and thus _expensive_, especially if you can't get any ad revenue! The only place i've found with an API that also serves up raw trailer videos is [Trailer Addict](http://www.traileraddict.com/trailerapi). Access to the API apparently requires emailing them, but there's an existing [3rd party TrailerAddict metadata agent](https://github.com/piplongrun/TrailerAddict.bundle) that _doesn't_ appear to use any API keys or such despite Trailer Addict's documentation saying to email for an API key.

I did originally write a bunch of code that retrieved YouTube trailer URLs from TMDB before realising that trying to get the actual mp4 for a YouTube video is really difficult and the mp4 URL also constantly changes.

The only downside of Trailer Addict is that the number of trailers on there seems to be somewhat limited - it looks to mostly be films that have had a medium/big Western release, so Ghibli movies are on there, along with things like Summer Wars, Wolf Children, Evangelion 3.0 etc. Still, better than nothing! I'll work on getting API access and integrating it into Hama. Open to discussion on alternatives though if anyone knows an alternative source.

**Comment by ZeroQI** [comment]
I already recognise anidb trailers with scanner/agent s00e201-299, so ep
number could be used to test easilly if present. Could we use that local
file?

**Comment by KingJ** [comment]
Today, so long as you enable "Local Media Assets (Movies)" in the HamaMovies agent list, any files you name as MovieName-Trailer.ext or place in a 'Trailers' folder inside the movie's folder are picked up by Plex as trailers. I've done this for a few things where I have the trailer as file, but I agree - it'd be even better if we can get Hama to add any S0E2xx as a 'trailer' extra too.

Plex's trailer feature also supports displaying trailers from a URL - the metadata agent just needs to add the relevant URL at which Plex can reach the trailer. If we added support for this, it'd mean that user who don't have the trailer as a file can also benefit from having the trailer available.

**Comment by ZeroQI** [comment]
Thanks for that, and thanks to that, i updated HAMA's readme with a nice "Local Media Assets" section with all supported mediums and naming convention.

**Comment by KingJ** [comment]
Series trailers would be good to have too, but I don't see Plex adding that any time soon - but we can still keep them as a 'special' for now. The trailer shown on the movie's page is for that specific show. However, some Plex clients have an option of playing a number of random trailers before a film plays, but is is only a random selection from things that are in your library, not every film out there. There's normally an option to turn that off though and I normally do that.

**Comment by ZeroQI** [comment]
tried using the URL from source below: http://api.traileraddict.com/?imdb=5311514
`TrailerAddict API requires a working API Key. Don't have one? Please contact TrailerAddict at contact@traileraddict.com`

searched for escqflowne, ghost in the shell, your name, naruto, nothing...
```
API_URL        = 'http://api.traileraddict.com/?imdb=%s'            # %s = imdb id
MOVIE_URL      = 'http://www.traileraddict.com/%s'                  # %s = slug or relative url
POST_URL       = 'http://www.traileraddict.com/ajax/film_all.php'
POST_BODY      = 'page=%d&filmid=%s'                                # %d = page, %s = traileraddict movie id
RE_TA_MOVIE_ID = Regex('filmpop\(\d+,(\d+)\)')
TYPE_ORDER     = ['trailer', 'feature_trailer', 'theatrical_trailer', 'behind_the_scenes', 'interview', 'music_video', 'deleted_scene']
TYPE_MAP       = { 
  'trailer':            TrailerObject, 
  'feature_trailer':    TrailerObject,
  'theatrical_trailer': TrailerObject,
  'behind_the_scenes':  BehindTheScenesObject,
  'interview':          InterviewObject,
  'music_video':        SceneOrSampleObject,     # 'music_video':        MusicVideoObject,
  'deleted_scene':      DeletedSceneObject
}

def Start():
  HTTP.CacheTime = CACHE_1WEEK
  if not 'movies' in Dict:
    Dict['movies'] = {}
    Dict.Save()

class TrailerAddictAgent(Agent.Movies):
  name             = 'Trailer Addict'
  languages        = [Locale.Language.English]
  primary_provider = False
  contributes_to = [
    'com.plexapp.agents.imdb',
    'com.plexapp.agents.themoviedb'
  ]
  def search(self, results, media, lang):
    if media.primary_agent == 'com.plexapp.agents.imdb':          imdb_id = media.primary_metadata.id
    elif media.primary_agent == 'com.plexapp.agents.themoviedb':  # Get the IMDb id from the Movie Database Agent
      imdb_id = Core.messaging.call_external_function('com.plexapp.agents.themoviedb', 'MessageKit:GetImdbId', kwargs = dict(tmdb_id = media.primary_metadata.id))
      if not imdb_id:
        Log("*** Could not find IMDb id for movie with The Movie Database id: %s ***" % (media.primary_metadata.id))
        return None

    
    if imdb_id in Dict['movies']:  # If we already have the required traileraddict movie id
      Log("*** We've already got a Trailer Addict id: %s ***" % (Dict['movies'][imdb_id]['ta_movie_id']))
      results.Append(MetadataSearchResult(id = imdb_id, score = 100))    
    else:# If not, lookup the traileraddict movie id
      try:     xml = XML.ElementFromURL(API_URL % (imdb_id.strip('t')), sleep=2.0)
      except:  return None
      link = xml.xpath('//link/text()')
      if len(link) < 1:  return None
      slug = link[0].split('/')[3]
      try:     html = HTML.ElementFromURL(MOVIE_URL % (slug), sleep=2.0)
      except:  return None
      script = html.xpath('//script[contains(., "filmpop(")]/text()')
      if len(script) < 1:  return None
      
      ta_movie_id = RE_TA_MOVIE_ID.search(script[0])
      if not ta_movie_id:  return None

      poster = html.xpath('//meta[@property="og:image"]/@content')
      if len(poster) < 1:  poster = None
      else:                poster = 'http://%s' % (poster[0].split('//')[-1])

      # Store the traileraddict movie id and poster
      Dict['movies'][imdb_id] = {}
      Dict['movies'][imdb_id]['ta_movie_id'] = ta_movie_id.group(1)
      Dict['movies'][imdb_id]['poster'] = poster
      Dict.Save()
      results.Append(MetadataSearchResult(id = imdb_id, score = 100))

  def update(self, metadata, media, lang):
    ta_movie_id = Dict['movies'][metadata.id]['ta_movie_id']
    extras = []
    for page in range(1,6):
      try:     page = HTTP.Request(POST_URL, data=POST_BODY % (page, ta_movie_id), sleep=2.0).content # Only HTTP.Request supports a POST body
      except:  break
      html = HTML.ElementFromString(page)
      if len(html.xpath('//a')) < 1:  break
      for video in html.xpath('//a'):
        title = video.text
        url   = video.get('href')

        if title.lower() == 'trailer':                                              extra_type = 'trailer'
        elif title.lower() == 'feature trailer':                                    extra_type = 'feature_trailer'
        elif title.lower() == 'theatrical trailer':                                 extra_type = 'theatrical_trailer'
        elif 'behind the scenes' in title.lower() or 'featurette' in title.lower(): extra_type = 'behind_the_scenes'
        elif 'music video' in title.lower():                                        extra_type = 'music_video'
        elif 'deleted scene' in title.lower():                                      extra_type = 'deleted_scene'
        elif 'interview' in title.lower():
          extra_type = 'interview'
          if title.lower().startswith('interview') or title.lower().startswith('generic interview'):
            title = title.split('nterview - ')[-1].split('nterview- ')[-1]
        else:                                                                       continue
        extras.append({'type': extra_type, 'extra': TYPE_MAP[extra_type](url = 'ta://%s' % (url.lstrip('/')), title = title, thumb = Dict['movies'][metadata.id]['poster'])})
    extras.sort(key=lambda e: TYPE_ORDER.index(e['type']))
    for extra in extras:   metadata.extras.add(extra['extra'])
```
TMDB API support trailers according https://www.themoviedb.org/documentation/api
That should be the way to go

**Comment by ZeroQI** [comment]
can we delete https://github.com/ZeroQI/Hama.bundle/tree/ZeroQI-patch-1 ?
Added code for themovieDB trailers. should output youtube url. if that is ok, uncomment the meta line and it should add trailer, let me know the outcome.
Didn't find an example with quicktime trailer, if you have one post it please. i output the list structure in hama log, would be enough

**Comment by KingJ** [comment]
I originally tried this with TMDB trailer links. Most (all?) of the trailers linked by TMDB are on YouTube. However, the Plex video player used for the trailer expects a direct mp4 URL - passing `https://www.youtube.com/watch?v=ID` to the player as a source won't work (if you add a trailer object with that URL it'll show up as a trailer on the movie's page in Plex, but will give you a playback error if you try and watch it). It is possible to convert a YouTube video ID to a direct MP4, but the URLs for those change frequently and wouldn't be a good source for Hama to use.

Quicktime/Apple Movies trailers are more stable and easy to fetch a direct mp4, but their anime coverage was even lower than TrailerAddict when I was looking earlier in the month.

**Comment by ZeroQI** [comment]
Do you know what plex uses as source for normal movie trailers ?
Am kinda out of ideas now...

**Comment by KingJ** [comment]
Plex uses the [Internet Video Archive](http://www.internetvideoarchive.com/), their API costs which is presumably why it's limited to Plex Pass users only. We might be able to use this for Plex Pass users. I'm having a think about ways to achieve this still, i'll update here if anything comes of it.

**Comment by ZeroQI** [comment]
https://github.com/piplongrun/TrailerAddict.bundle/blob/master/Contents/Code/__init__.py
for extra in extras:  metadata.extras.add( TYPE_MAP[extra_type](	url = 'ta://%s' % (url.lstrip('/')), title = title, thumb = Dict['movies'][metadata.id]['poster']) )
why the "ta://"? can you try that ?

btw found that: https://github.com/aquilax1/Plex-IMDb-Extras-Downloader

**Comment by KingJ** [comment]
It looks like TrailerAddict.bundle bundles their own [custom-coded Video Service](https://github.com/piplongrun/TrailerAddict.bundle/blob/master/Contents/Services/URL/Trailer%20Addict/ServiceCode.pys). This handles any calls to ta:// URLs and returns an URL to a mp4.

The YouTube Video Service i'm using that's bundled with Plex itself should also do this for any http://youtube.com/* URLs but fails. However, it's interesting that TrailerAddict.bundle have written their own Video Service. Normally the Video Service plugins are used by Channels, so i'm wondering if Metadata Agents have to bundle their own Video Service agents in order to work? I will try a few things and see if it works...

The Plex IMDb Extras Downloader just places the files into the media folders so that the Local Metadata Scanner picks them up by the looks of things.

**Comment by KingJ** [comment]
I've spent a few hours looking at this but have ultimately drawn a blank - having the service as part of the metadata agent makes no difference. I've updated the ticket on Plex's Video Service repository with a few bits of information i've found - it looks like a MediaContainer object with the correct video URL is passed to Plex Web, but that URL isn't then loaded by Plex Web.

**Comment by ZeroQI** [comment]
something useful in https://github.com/kolsys/YouTubeTV.bundle/blob/master/Contents/Services/URL/YouTubeTV/ServiceCode.pys maybe?

**Comment by KingJ** [comment]
I did try the YouTubeTV.bundle as an alternative Video Service to Plex's own video bundle, unfortunately I ran in to the same problem. The Video Service passed a MediaContainer object to the player that contains the correct video URL but it doesn't seem to be used. There's nothing much in the server logs or client logs so i'm a little stuck - i'm hoping someone from Plex can reply to my thread on the forums or the issue I opened up.

**Comment by ZeroQI** [comment]
Closing for now, but would have liked the functionality. wil lreopen if i see such functionalities in other agents

**Comment by KingJ** [comment]
Yeah, it would definitely have been nice to have but it makes sense to close for now. I did log [an issue](https://github.com/plexinc-plugins/Services.bundle/issues/943) with Plex back in January, but nothing much has happened with it since I logged it. I'll let you know if they update/fix it.

**Comment by ZeroQI** [comment]
Please do. have coded this morning different meta source for sereis and episodes by separating priorities with "|", have a look

**Comment by ReenigneArcher** [comment]
I have created a working YouTube URL service that allows playback of YouTube extras.  https://github.com/LizardByte/PlexyGlass
